### ISSUE TITLE
[Question] starward从0.12.1更新到0.12.2之后就打不开了

### ISSUE THREAD

**Issue by my282946** [Scighost/Starward#1001]
### Checklist

- [X] I have already read [docs/Tips.md](https://github.com/Scighost/Starward/blob/main/docs/Tips.md), but my question is not solved.
- [X] My question was not mentioned by others, and it is not a duplicate question.

### Description

打开starward之后顺手点了更新，更新之后软件就打不开，点了之后也没反应，本以为是电脑问题，但重启之后还是打不开

### Starward Version

0.12.2

### Windows Version

22631.3880

**Comment by SSB-ARFCN** [comment]
我的更新後正常
![螢幕擷取畫面 (218)](https://github.com/user-attachments/assets/818525a8-8b82-4fe9-9795-a117a350acd0)


試試重新下載 然後解壓縮 覆蓋檔案

![螢幕擷取畫面 (219)](https://github.com/user-attachments/assets/1426dc50-a1da-49c9-bed4-b673ca504035)

**Comment by my282946** [comment]
> 我的更新後正常 ![螢幕擷取畫面 (218)](https://private-user-images.githubusercontent.com/107019852/353732336-818525a8-8b82-4fe9-9795-a117a350acd0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI0MTM1NjYsIm5iZiI6MTcyMjQxMzI2NiwicGF0aCI6Ii8xMDcwMTk4NTIvMzUzNzMyMzM2LTgxODUyNWE4LThiODItNGZlOS05Nzk1LWExMTdhMzUwYWNkMC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzMxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDczMVQwODA3NDZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yM2NmOTY3M2RhMGRlNDIzNDMzYjQxNzU2ZDMyYjVkY2RjNWEyYWQ4ZDY1NzdhZmQ4YTNiYjMzNThlYTEyMWNkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.B_0aQlQpXP1MgEQdbhqMI10wydWeeFluQq471SqZBwo)
> 
> 試試重新下載 然後解壓縮 覆蓋檔案
> 
> ![螢幕擷取畫面 (219)](https://private-user-images.githubusercontent.com/107019852/353733393-1426dc50-a1da-49c9-bed4-b673ca504035.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI0MTM1NjYsIm5iZiI6MTcyMjQxMzI2NiwicGF0aCI6Ii8xMDcwMTk4NTIvMzUzNzMzMzkzLTE0MjZkYzUwLWExZGEtNDljOS1iZWQ0LWI2NzNjYTUwNDAzNS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzMxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDczMVQwODA3NDZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wYTVhZWMwNDE1NGY1NzZiYTdmZjczMTlmMzY5NGYzYmM5ZTE1ZmY5YmUzMmNlYTMwNjc1NDBiYzdmN2UxZjk3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.sKZbkOfvS9XfcrjGnSZNRc3u7oCPBO8ipCmfLVGgG1w)

覆盖的话抽卡记录会保存吗

**Comment by Eric-Joker** [comment]
> 覆盖的话抽卡记录会保存吗

不去动数据库文件就不会消失，下载的压缩包中不存在数据库文件。
