### ISSUE TITLE
[Question] 求助，我重新选择数据文件夹后，数据文件丢失，请问我如何使用之前保存的备份文件恢复数据

### ISSUE THREAD

**Issue by xxbhpan** [Scighost/Starward#1007]
### Checklist

- [X] I have already read [docs/Tips.md](https://github.com/Scighost/Starward/blob/main/docs/Tips.md), but my question is not solved.
- [X] My question was not mentioned by others, and it is not a duplicate question.

### Description

求助，我重新选择数据文件夹后，数据文件丢失，请问我如何使用之前保存的备份文件恢复数据
![image](https://github.com/user-attachments/assets/bf63151d-b82a-4fd4-90e6-f154c931f14a)
谢谢！

### Starward Version

0.12.2 Preview 1

### Windows Version

19044.4651

**Comment by xxbhpan** [comment]
当然，之所以我能恢复备份数据可能是作者的贴心小功能。例如下图中，原本data文件夹下面放的是相关文件，现已全部都在上级的文件夹中，还贴心了留下了我重新选择数据文件夹时的当时的备份记录。
![image](https://github.com/user-attachments/assets/7cb5c4a5-591d-4a87-ad2c-8dfb0b94efd8)
.

**Comment by stz1222** [comment]
把你备份的恢复数据改名成StarwardDatabase.db覆盖到你的新数据文件夹中。

**Comment by xxbhpan** [comment]
> 把你备份的恢复数据改名成StarwardDatabase.db覆盖到你的新数据文件夹中。

感谢，数据已恢复
