### ISSUE TITLE
[Question] 請問選擇下載語言包的選項在哪挑整?

### ISSUE THREAD

**Issue by SSB-ARFCN** [Scighost/Starward#1012]
### Checklist

- [X] I have already read [docs/Tips.md](https://github.com/Scighost/Starward/blob/main/docs/Tips.md), but my question is not solved.
- [X] My question was not mentioned by others, and it is not a duplicate question.

### Description

印象中 舊版本有個選擇語言包的勾選方塊 用於選擇要下載那些語言
![螢幕擷取畫面 (258)](https://github.com/user-attachments/assets/f903004b-b534-4ca1-9f02-7cdb5a7c65b6)
新版點安裝就開始下載了

### Starward Version

0.12.2 Preview 1

### Windows Version

19045.2965(WIN10 22H2)

**Comment by Scighost** [comment]
<img width="131" alt="image" src="https://github.com/user-attachments/assets/3df0394e-01ed-40af-acfa-c865a7fe0fde">

**Comment by SSB-ARFCN** [comment]
感謝大佬
