### ISSUE TITLE
[Question] the json value could not be converted to system

### ISSUE THREAD

**Issue by linkwang233** [Scighost/Starward#1015]
### Checklist

- [X] I have already read [docs/Tips.md](https://github.com/Scighost/Starward/blob/main/docs/Tips.md), but my question is not solved.
- [X] My question was not mentioned by others, and it is not a duplicate question.

### Description

昨天没事 ，今天一打开就这样了，尝试过清除缓存，重装软件（从0.12.2预览版到0.12.1）
![屏幕截图(1)](https://github.com/user-attachments/assets/54339e1d-8454-4944-9f49-11716f2669df)
大佬帮帮我。

### Starward Version

0.12.1

### Windows Version

Windows 10 企业版 LTSC    21H2     19044.4651

**Comment by cokebar** [comment]
same issue

**Comment by Eric-Joker** [comment]
96d94931a3f0ab2aed8b25679b5eadc6d7273350
