### ISSUE TITLE
能否加个一键切换账号

### ISSUE THREAD

**Issue by axwg020226** [Scighost/Starward#102]
关闭当前账号的程序，打开新账号的程序，不然每次切号还要关游戏

**Comment by Scighost** [comment]
请更详细地说明一下你的需求。

**Comment by axwg020226** [comment]
就现在想要切换账号的话需要先关闭当前账号的游戏，然后打开新游戏这个步骤
能否一键完成这个操作，就 关游戏 切账号 开游戏这个过程

**Comment by axwg020226** [comment]
应该加一个 关闭正在运行的游戏 这个功能就能实现了吧

**Comment by Scighost** [comment]
游戏正在运行的时候，你不能点击切换账号吗？

<img width="115" alt="image" src="https://github.com/Scighost/Starward/assets/61003590/f731cd7f-1de1-4ab7-bd72-f80656952965">

**Comment by axwg020226** [comment]
可是我需要关闭A账号的原神才能启动B账号的原神
忽略正在进行的游戏原神也不能启动

**Comment by axwg020226** [comment]
铁道好像能多开，但是我同样希望我打开B账号铁道时 不需要我手动去关闭A账号的铁道

**Comment by axwg020226** [comment]
> 铁道好像能多开，但是我同样希望我打开B账号铁道时 不需要我手动去关闭A账号的铁道

铁道多开可能会有人需要，但我估计我带不动双开（）

**Comment by axwg020226** [comment]
> 应该加一个 关闭正在运行的游戏 这个功能就能实现了吧

所以可能需要实现这个功能？

**Comment by Scighost** [comment]
其实不需要退出游戏，切换账号后直接返回登录界面就是使用新的账号了。

**Comment by axwg020226** [comment]
密钥的保存和上机环境有关吗，我换了个地点之后，密码好像失效了，进去是登录界面

**Comment by axwg020226** [comment]
然后我把之前保存的全删了，重新存了账号。切换账号后直接返回登录界面仍然是原账号。

**Comment by axwg020226** [comment]
我在双开的情况下返回登录界面都是各自自己的账号

**Comment by zhangchi1997** [comment]
1.登录A账号，做完任务
2.启动器切换B账号
3.点击【启动游戏】 杀死当前A账号的原神进程  用B账号的信息重新启动新原神
我觉得他是要这样的  不过感觉可以在设置里添加一个选项 【是否强制杀死当前进程】
类似这样的https://github.com/babalae/genshin-account

**Comment by Scighost** [comment]
我需要在测试后再回答你的疑问

**Comment by Jiuly-H** [comment]
请问一下如何添加其他账号

**Comment by Scighost** [comment]
经过我的测试，游戏返回到登录界面的时候，不会再读取注册表，而是会把当前账号的信息再次写入注册表。所以想要通过 Starward 切换账号，必须重新启动游戏。
