### ISSUE TITLE
[Bug] S-rank/5* doesn't reset A-rank/4* pity

### ISSUE THREAD

**Issue by Flyingbacen** [Scighost/Starward#1028]
### Checklist

- [X] My issue was not mentioned by others, and it is not a duplicate issue.

### Description

In the off-chance that you get an S-rank, and then an A-rank after, and the S-rank has reset the A-rank pity, the pity value shown can go above 10

### Reproduction Steps

<ul><li>Pull an A-rank</li><li>Pull an S-rank</li><li>Get unlucky, and pull an A-rank more than 10 pulls since your last A-rank</li></ul>

### Expected Behavior

The S-rank to reset the A-rank pity, so that the displayed pity value is not above 10.

### Screenshots

![image](https://github.com/user-attachments/assets/b6316790-a2f5-4a27-ac4a-e20f712eb8a0)
![image](https://github.com/user-attachments/assets/b1a38c4c-6586-4695-a189-c39f354ac2b9)

### Starward Version

0.12.1

### Windows Version

22H2 - 19045.4170

### Log

```shell
Not relevant - N/A
```

### Additional Context

Worst case, `if ARANKPITY > 10: ARANKPITY = 10`

**Comment by Scighost** [comment]
> Within 10 Signal Searches, at least one **A-Rank or higher Signal** is guaranteed.

Such as `A B B B B  B B B B S  A`. S-Rank item does make A-Rank item appears one place later, but the number here refers to the count of pulls after the previous A-Rank item.
