### ISSUE TITLE
更新到0.8.0后，如果将数据文件夹路径设置为非程序所在路径，则每次启动都是初始化界面

### ISSUE THREAD

**Issue by windskyxb** [Scighost/Starward#103]
在0.8.0版本之前，我的数据文件夹路径为C:\Users\winds\Documents\Starward、程序所在目录为D:\Tools\Starward；更新到0.8.0后，我仍将数据文件夹设置为C:\Users\winds\Documents\Starward。但关闭Starward后再次打开为如下界面
![image](https://github.com/Scighost/Starward/assets/60282327/cddf10d6-4237-4cd4-a16b-ea8d99e433f8)
但如果将数据文件夹设置为D:\Tools\Starward则不会出现以上问题

**Comment by Scighost** [comment]
感谢反馈，因为我的疏忽，现在用户数据文件夹无法使用绝对路径。

**Comment by Scighost** [comment]
已解决
