### ISSUE TITLE
[Feature] 希望可以通过创建软链接（Junction链接或符号链接）安装游戏

### ISSUE THREAD

**Issue by z-w-h-m-x** [Scighost/Starward#1030]
### Checklist

- [X] I have already read [docs/Tips.md](https://github.com/Scighost/Starward/blob/main/docs/Tips.md), but my feature is not implemented.
- [X] My suggested feature was not mentioned by others, and it is not a duplicate feature.

## 写在前面

符号链接创建的弊端是目标文件（文件夹）被删除后会导致找不到目标
翻译：不能卸载作为符号链接目标的游戏

## 正文

安装游戏的选项已经有创建硬链接的功能，但是硬链接的目标只能在同一分区下。遇到链接目标的游戏文件处于不同分区的情况下，虽然安装程序提示成功但游戏无法正常运行。希望可以考虑提供创建符号链接安装游戏的功能。

举个人的例子，将游戏的AB包放在固态硬盘的一个分区下，其余文件处于机械硬盘的分区下，这样做以缩短游戏校验和加载的时间。但在使用硬链接创建同个游戏的其他服务器本体时，遇到使用软链接创建的文件夹会导致硬链接创建失败，但是游戏依旧安装成功（启动游戏后处于黑屏），用软链接补上AB包的文件夹也无法启动（可能有其他问题，待排除）（这么做的玩家应该不多（没了解过））

### Solution or Design

通过符号连接创建游戏，符号链接对应的文件或文件夹
或使用软连接

**Comment by Scighost** [comment]
这里解释了为什么不使用符号链接 https://github.com/Scighost/Starward/issues/749#issuecomment-2258226089

我还有一个疑问，安装游戏的时候你是怎么链接到其它分区的，理论上会碰到如下的错误：

![image](https://github.com/user-attachments/assets/dfdda61a-adeb-46d3-b673-0113d3872273)

**Comment by z-w-h-m-x** [comment]
@Scighost 谢谢回答

我是在游戏安装成功后把整个文件夹复制Asb并符号链接文件夹（StreamingAssets\Asb）,并非是单独链接文件

至于为什么没有遇到错误，是因为设定安装目录和目标目录是同一分区（可能是我描述有问题造成误解）

![ae67f911-2c00-4ad6-9495-8e3223276f12](https://github.com/user-attachments/assets/4f8497b2-23b0-47c7-af51-f1f1ba4ba2e3)

刚刚才发现碰到了点问题（指Asb/windows中的文件被删除，可能和我昨晚多次操作与其他行为有关）
我会再尝试下

**Comment by z-w-h-m-x** [comment]
结论是 符号链接文件确实无法通过校验
至于为什么我在链接AB包后（[正文](https://github.com/Scighost/Starward/issues/1030#issue-2462364475)中）铁启动后黑屏，没有结论，但是好消息是多尝试安装几次后就正常了（也可以在用一键修复试试）

如果真要用软连接（Junction 链接），只能链接文件夹，还必须判断文件夹下有差异否，这样做复用率肯定是没硬链接高
以铁的文件为例（CN和Global对比，只看StreamingAssets文件夹）（差异确实很散
![image](https://github.com/user-attachments/assets/bd53719e-bc29-4b96-a7af-0f23bd374793)
文件夹为单位，复用率就很低，但是以储存占用空间的角度看，就差了约21MB（图中StreamingAssets下标黄的差异文件和文件夹）
但是也不能排除后续更新其他文件夹中的文件会有差异的可能性（但是这个可能性很小
而且Junction链接会受盘符的影响（绝对路径问题），不过一般是不会更改
