### ISSUE TITLE
[Bug] 硬链接异常和卸载异常

### ISSUE THREAD

**Issue by devil233-ui** [Scighost/Starward#1031]
### Checklist

- [X] My issue was not mentioned by others, and it is not a duplicate issue.

### Description

本地存在【原神国服客户端】通过下载差异文件方式获得的【原神全球服客户端】，二者均可正常使用。sw升级至0.12.2-preview.1后，使用硬链接将全球服链至国服，出现了以下问题
![image](https://github.com/user-attachments/assets/c392d56a-8e75-4009-becc-a057e43c0f81)
使用sw启动器的卸载功能清除全球服的临时文件重新启动，仍然存在以上报错。继续使用卸载功能清理全球服注册表和删除全球服游戏资源后，国服数据文件被一同清理了，与以下描述出现矛盾情况。
![image](https://github.com/user-attachments/assets/bd9a4b81-4296-41eb-ac67-43cf295de7c8)

### Reproduction Steps

另，备份截图文件功能似乎备份并不完全，和我自己手动备份的数量存在差异。
![image](https://github.com/user-attachments/assets/4668f8f8-15a9-4dba-a8bf-fa76abfd7ceb)

### Starward Version

0.12.2-preview.1

### Windows Version

22631.3958

### Log
https://drive.google.com/drive/folders/14UU722XBLRLxMo_TZclwiRdxOBVM7gcU?usp=sharing
```shell
[Starward_240813_015913.log](https://github.com/user-attachments/files/16595916/Starward_240813_015913.log)
[Starward_240813_144701.log](https://github.com/user-attachments/files/16595918/Starward_240813_144701.log)
[Starward_240813_145853.log](https://github.com/user-attachments/files/16595920/Starward_240813_145853.log)
[Starward_240813_145911.log](https://github.com/user-attachments/files/16595921/Starward_240813_145911.log)
[Starward_240813_145918.log](https://github.com/user-attachments/files/16595923/Starward_240813_145918.log)
[Starward_240813_150031.log](https://github.com/user-attachments/files/16595924/Starward_240813_150031.log)

```

**Comment by InTka** [comment]
![114514](https://github.com/user-attachments/assets/44a2818a-2db2-4343-b7c1-20fec0cd26b5)
居然遇到了同一个问题，有缘粪，撒泡尿

**Comment by devil233-ui** [comment]
> > 31-4302
> 
> 游戏安装文件夹内只能有一个 exe 文件，安装游戏的时候请选择不同的文件夹。
> 
> 截图备份功能只会复制游戏安装文件夹内的截图，左图中存在于桌面的文件夹不会被检测到。

看来是理解错了意思...以为和【定位游戏】一样
左图就是我说的手动备份的图，右图是系统功能备份的，当然问题可能真就出在了上一步塞同个文件夹了...

**Comment by devil233-ui** [comment]
已通过正确操作分别打开了国际服和国服

**Comment by devil233-ui** [comment]
> 已通过正确操作分别打开了国际服和国服，截图功能下次卸载时验证（）

**Comment by devil233-ui** [comment]
已通过正确操作分别打开了国际服和国服，截图备份功能下次卸载时验证（）
