### ISSUE TITLE
启动崩溃

### ISSUE THREAD

**Issue by MiaoLingF** [Scighost/Starward#104]
0.8.0启动后崩溃，从github下载的0.8.0没有config.ini，打开后崩溃，从0.7.1中更新得到的0.8.0中有config.ini,其中写着
app_folder=app-0.7.1
exe_name=Starward.exe
启动后仍然崩溃

**Comment by forchannot** [comment]
需要更改config.ini
```ini
EnableConsole=False
UserDataFolder=.
```
