### ISSUE TITLE
[Question] 选b服的时候左下角活动框不见了，切换账号功能也不见了

### ISSUE THREAD

**Issue by InTka** [Scighost/Starward#1041]
### Checklist

- [X] I have already read [docs/Tips.md](https://github.com/Scighost/Starward/blob/main/docs/Tips.md), but my question is not solved.
- [X] My question was not mentioned by others, and it is not a duplicate question.

### Description

![QQ截图20240820072919](https://github.com/user-attachments/assets/4bb740a8-94c9-4621-bbdf-64419054581e)
![QQ截图20240820072944](https://github.com/user-attachments/assets/9d8d9dd1-7253-44b7-bbd9-5898230e5b01)

### Starward Version

0.12.2

### Windows Version

22631.4037

**Comment by Scighost** [comment]
B服没有左下角的公告
B服的账号通过IE组件登录，无法适配账号切换功能
