### ISSUE TITLE
[Question] ESC键退出Starward，但没完全退出

### ISSUE THREAD

**Issue by InTka** [Scighost/Starward#1044]
### Checklist

- [X] I have already read [docs/Tips.md](https://github.com/Scighost/Starward/blob/main/docs/Tips.md), but my question is not solved.
- [X] My question was not mentioned by others, and it is not a duplicate question.

### Description

<img width="891" alt="QQ截图20240824212342" src="https://github.com/user-attachments/assets/02be18ff-d440-45d8-949e-90ffbc032c52">
如图，即使我在《关闭窗口选项》里选择了“完全退出”，但我通过ESC键关闭Starward的时候，依然被隐藏在托盘。
我个人感觉这算是个bug，我想you也是这样想的

### Starward Version

0.12.2-preview.2

### Windows Version

22631.4037

**Comment by Scighost** [comment]
esc是隐藏窗口键，退出要点右上角的X

**Comment by InTka** [comment]
> esc是隐藏窗口键，退出要点右上角的X

可是选择“完全退出”就是不想让应用在托盘驻留，以保持托盘干净。但有这个功能存在的话，如果误触ESC但不知道按下了ESC，就不知道到底是关闭了还是没关闭，然后还得去托盘检查一遍
![思考](https://github.com/user-attachments/assets/c31abc5b-8eb6-44bf-91a1-0d268ab8f8e9)
或者考虑加个开关？
