### ISSUE TITLE
更换（增加）镜像代理链接

### ISSUE THREAD

**Issue by forchannot** [Scighost/Starward#105]
在国内部分地区，`cdn.jsdelivr.net`已经无法访问或者延迟极高，推荐几个镜像代理链接
- 对`raw.githubusercontent.com`可采用`ghproxy.com`代理，如`https://raw.githubusercontent.com/Scighost/Starward/metadata/test/test_10kb`可更改为`https://ghproxy.com/https://raw.githubusercontent.com/Scighost/Starward/metadata/test/test_10kb`,即直接在链接前加上`https://ghproxy.com/`即可
- 对`jsdelivr`可考虑使用`cdn.staticaly.com`直接代替`cdn.jsdelivr.net`不用更改其他的地方
- 尝试将文件镜像一份到gitee上，虽然gitee不怎么讨喜，但是国内的延迟和速度勉强能用

**Comment by Scighost** [comment]
感谢你的建议，除了 Gitee 以外，其他的内容我会考虑。

**Comment by forchannot** [comment]
我忽略了一个，用`jsd.cdn.zzko.cn`代替`cdn.jsdelivr.net`也可以，不过未测试过超大文件是否允许下载

**Comment by Scighost** [comment]
虽然但是，更换镜像代理链接仅适用于此分支中的内容 https://github.com/Scighost/Starward/tree/metadata，并不能代理更新时需要下载的文件。

**Comment by forchannot** [comment]
代理时所需要下载的文件是哪里的呢，是github release嘛，如果是的话`ghproxy.com`是支持release的

**Comment by forchannot** [comment]
此外，我查看了jsd的issue，可以采用新建分支用action自动将release文件同步到新分支内，然后jsd等一系列替代应该都可以下载

**Comment by Scighost** [comment]
现在下载文件分两部分，一个是完整压缩包，这个在 GitHub Relase 中，还有就是自动更新的零散文件，使用的是 cloudfalre 的代理。

jsDelivr 限制的文件大小是 20MB，statically 的限制是 30MB，而最新版本的压缩包已经超过 40MB 了，我也不确定以后会不会出现单文件超过 20MB 的情况，所以这部分功能不可能使用 jsd 或 static。

**Comment by Scighost** [comment]
没有计划实现此功能
