### ISSUE TITLE
[Question] 这里或许可以添加一个绝区零

### ISSUE THREAD

**Issue by wen20919** [Scighost/Starward#1050]
### Checklist

- [X] I have already read [docs/Tips.md](https://github.com/Scighost/Starward/blob/main/docs/Tips.md), but my question is not solved.
- [X] My question was not mentioned by others, and it is not a duplicate question.

### Description

![屏幕截图 2024-08-26 133151](https://github.com/user-attachments/assets/11438e04-874a-4401-8877-d0cfa2b427bc)
如题

### Starward Version

0.12.2-preview.3

### Windows Version

22631.3880

**Comment by Scighost** [comment]
是的，但是因为加了后所有语言中的这段文本需要重新翻译，所以还没加。
