### ISSUE TITLE
[Question] 无法建立国际服硬链接

### ISSUE THREAD

**Issue by beastseapai114** [Scighost/Starward#1058]
### Checklist

- [X] I have already read [docs/Tips.md](https://github.com/Scighost/Starward/blob/main/docs/Tips.md), but my question is not solved.
- [X] My question was not mentioned by others, and it is not a duplicate question.

### Description

原神国际服无法建立硬链接
![微信图片_20240830105244](https://github.com/user-attachments/assets/746c04e5-ba3f-4a12-8840-7ef0c489551b)

### Starward Version

0.13.0

### Windows Version

19045.4780

**Comment by Scighost** [comment]
因为没有检测到已安装的其他区服客户端
