### ISSUE TITLE
[Bug] Starward无法启动

### ISSUE THREAD

**Issue by MeiVinEight** [Scighost/Starward#1059]
### Checklist

- [X] My issue was not mentioned by others, and it is not a duplicate issue.

### Description

Starward在Windows 11 Version 24H2 Build 26120.1542下打不开，双击后在任务管理器里可以看到创建了进程，但等待之后进程自动关闭，似乎是崩溃了。

### Reproduction Steps

如上

### Starward Version

0.13.0

### Windows Version

26120.1542

### Log

```shell
// 崩溃报告
Microsoft.UI.Xaml.Markup.XamlParseException: The text associated with this error code could not be found.

Failed to assign to property 'Microsoft.UI.Xaml.Media.AcrylicBrush.TintColor'. [Line: 0 Position: 0]
```

**Comment by Scighost** [comment]
重新下载过 Release 中的完整包吗？

**Comment by coden478** [comment]
淡定，我用WIN10也是经常性的启动失败

**Comment by MeiVinEight** [comment]
重新下载后解决问题
