### ISSUE TITLE
[Feature] 求添加一个符号链接

### ISSUE THREAD

**Issue by cutelittlekitahime** [Scighost/Starward#1060]
### Checklist

- [X] I have already read [docs/Tips.md](https://github.com/Scighost/Starward/blob/main/docs/Tips.md), but my feature is not implemented.
- [X] My suggested feature was not mentioned by others, and it is not a duplicate feature.

### Summary

求大佬再添加一个符号链接的功能这样，更新的时候一并更新了。
我使用命令行自己搞了一个符号链接可以用，但是手动搞的话也很麻烦，需要命令行创建
大佬，我已经赞助了一下下，求满足

### Solution or Design

求大佬再添加一个符号链接的功能

**Comment by Scighost** [comment]
感谢支持，但是 https://github.com/Scighost/Starward/issues/749#issuecomment-2258226089
