### ISSUE TITLE
[Bug] 更新抽卡记录失败

### ISSUE THREAD

**Issue by Nekoosu** [Scighost/Starward#1063]
### Checklist

- [X] My issue was not mentioned by others, and it is not a duplicate issue.

### Description

原神更新抽卡记录失败，清除缓存无法解决，请求指导

### Reproduction Steps

原神更新抽卡记录失败，清除缓存无法解决，请求指导

### Screenshots

![image](https://github.com/user-attachments/assets/68e31b95-99bb-429a-ac9f-9e1c9af518d7)

### Starward Version

0.13.0

### Windows Version

19044.3086

### Log

```shell
SqliteException SQLite Error 8: 'attempt to write a readonly database'
```

**Comment by Scighost** [comment]
管理员权限启动

**Comment by Nekoosu** [comment]
已解决
