### ISSUE TITLE
[Question] 账号切换器相关问题

### ISSUE THREAD

**Issue by Wubufei** [Scighost/Starward#1065]
### Checklist

- [X] I have already read [docs/Tips.md](https://github.com/Scighost/Starward/blob/main/docs/Tips.md), but my question is not solved.
- [X] My question was not mentioned by others, and it is not a duplicate question.

### Description

使用账号切换器的时候，已储存的账号都会登出，并且再次储存也没有用，每款游戏都会发生这种情况。我在某次登入之后发现每个游戏都需要重新登入一次之后就这样了，这是可以修复的吗？

### Starward Version

0.13.0

### Windows Version

19045.4170

**Comment by XPRAMT** [comment]
我有相同問題 經常被登出

**Comment by Haku821** [comment]
我也是 電腦也沒關機昨天晚上可以今天早上又被登出了
