### ISSUE TITLE
[Question] 最新版本的starward没有切换服务器的功能了吗？

### ISSUE THREAD

**Issue by APushingBoy** [Scighost/Starward#1066]
### Checklist

- [X] I have already read [docs/Tips.md](https://github.com/Scighost/Starward/blob/main/docs/Tips.md), but my question is not solved.
- [X] My question was not mentioned by others, and it is not a duplicate question.

### Description

如题
我一直在用starward来切换服务器，但是更新了新版本之后发现原本位于“一键修复”按钮右边的切换服务器小倒三角消失了。我仔细找了其他位置，都没找到换服务器的按钮。
按照说明文档，切换服务器的按钮在这里：
![image](https://github.com/user-attachments/assets/e5afb628-96ad-4e8c-be52-e342b5752c94)
但我starward中，是这样的：
![image](https://github.com/user-attachments/assets/bff6ed94-d50a-42ee-88b1-c3d122790c76)
![image](https://github.com/user-attachments/assets/1ce17926-87f0-4f56-8347-093cae46816f)
![image](https://github.com/user-attachments/assets/23bc9388-d298-41fc-8734-77badade10c1)
点击”一键修复“的话，确实是和字面意思一样开始检测游戏资源文件完整性，修复完后也不会出现切换服务器的选项。
有和我一样问题的小伙伴吗？

### Starward Version

0.13.1

### Windows Version

22631.4037

**Comment by Happylifezzq** [comment]
现在应该是用硬链接方式替换掉了原来的切服功能，这样以后不需要修改文件，后续使用也更方便一些。
大致操作步骤（只需每个游戏首次切换到另一服务器时操作，图片仅供参考）：
- 了解当前游戏所属的服务器（打开游戏后是哪个服）
- 清除其他服的游戏文件定位（若有）
![屏幕截图 2024-09-01 114544.png](https://github.com/user-attachments/assets/096d3cb6-3f9f-4e67-b507-5f20b0159865)
- 安装游戏，在弹出的窗口勾选“创建硬链接”
![屏幕截图 2024-09-01 114833.png](https://github.com/user-attachments/assets/31055b00-95a9-4f34-b197-b45ca406fea1)
- 点击安装，此时会直接进入文件校验阶段，等待安装完成（仅需下载少量资源）
- 安装完成后即可直接切换不同服务器

**Comment by APushingBoy** [comment]
> 现在应该是用硬链接方式替换掉了原来的切服功能，这样以后不需要修改文件，后续使用也更方便一些。 大致操作步骤（只需每个游戏首次切换到另一服务器时操作，图片仅供参考）：
> 
> * 了解当前游戏所属的服务器（打开游戏后是哪个服）
> * 清除其他服的游戏文件定位（若有）
>   ![屏幕截图 2024-09-01 114544.png](https://private-user-images.githubusercontent.com/63694797/363456438-096d3cb6-3f9f-4e67-b507-5f20b0159865.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjUxNjQxNDUsIm5iZiI6MTcyNTE2Mzg0NSwicGF0aCI6Ii82MzY5NDc5Ny8zNjM0NTY0MzgtMDk2ZDNjYjYtM2Y5Zi00ZTY3LWI1MDctNWYyMGIwMTU5ODY1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTAxVDA0MTA0NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWZjYzg0OGVjMmRkY2I2NDJkMmM1ZTg2M2NhNDQ2NDY3Mzc4YzhjMjJmMDM4N2I0OGJhYTQxMjJjZWRkOTc1ODQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.bY6G1S_dJuS-CQe4dy2H-_fsRRJEsksZHrZ1FEYUNqo)
> * 安装游戏，在弹出的窗口勾选“创建硬链接”
>   ![屏幕截图 2024-09-01 114833.png](https://private-user-images.githubusercontent.com/63694797/363456460-31055b00-95a9-4f34-b197-b45ca406fea1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjUxNjQxNDUsIm5iZiI6MTcyNTE2Mzg0NSwicGF0aCI6Ii82MzY5NDc5Ny8zNjM0NTY0NjAtMzEwNTViMDAtOTVhOS00ZjM0LWIxOTctYjQ1Y2E0MDZmZWExLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTAxVDA0MTA0NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTM2NjdmNTVkNTExNzczN2YxMzkzZDNiMGZlMTE0M2QwOTAwMjk2MzhkNDU2ZTZkM2ZjYjg3ODkxOWNkOTMzNGImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.fNoFmieBzkiChudo68Jy6b3wu1ffvlPekO-1YsZNwd8)
> * 点击安装，此时会直接进入文件校验阶段，等待安装完成（仅需下载少量资源）
> * 安装完成后即可直接切换不同服务器

打开starward看了一下，确实是这样！非常感谢！
