### ISSUE TITLE
[Question] 每次更新都会导致原快捷方式失效

### ISSUE THREAD

**Issue by RenzudadiZZA** [Scighost/Starward#1068]
### Checklist

- [X] I have already read [docs/Tips.md](https://github.com/Scighost/Starward/blob/main/docs/Tips.md), but my question is not solved.
- [X] My question was not mentioned by others, and it is not a duplicate question.

### Description

每次更新后，任务栏图标都会失效，必须重新手动添加

### Starward Version

0.13.1

### Windows Version

22631.4037

**Comment by Scighost** [comment]
固定 `app-` 文件夹外的 `Starward.exe` 到任务栏

**Comment by square-235** [comment]
> 固定 `app-` 文件夹外的 `Starward.exe` 到任务栏

文件夹外的Starward.exe不能与主程序合并，点开后任务栏会有两个图标，这是许多用版本号文件夹的软件的通病了
