### ISSUE TITLE
[Bug] 原神战绩中旅行者札记由于米游社功能更改导致无法识别到今日数目

### ISSUE THREAD

**Issue by xxbhpan** [Scighost/Starward#1071]
### Checklist

- [X] My issue was not mentioned by others, and it is not a duplicate issue.

### Description

在原神5.0版本更新后，由于米游社功能更改，导致旅行者札记中今日数据无法获得。
米游社旅行者札记
<img width="212" alt="20240901182920" src="https://github.com/user-attachments/assets/f02c5edb-c4cf-4573-ad4b-bda9107be35d">
starward相关界面数据
<img width="562" alt="20240901182930" src="https://github.com/user-attachments/assets/0a065cc5-d54d-4aaa-88aa-fad471234e99">

### Reproduction Steps

在原神 → 米游社工具箱 → 旅行者札记 → 刷新 → 实时数据中无今日数据 → 获取明细并选择当前月份 → 在每日数据一栏可以显示当天的数据

### Expected Behavior

建议，可以直接将每日数据中的内容复制到实时数据中的当日数据里；或者干脆删除此选项，仅保留当月数据。

### Starward Version

0.13.1

### Windows Version

19044.4780

### Log

```shell
[18:33:38.696] [INFO] 
Welcome to Starward v0.13.1
System: Microsoft Windows NT 10.0.19044.0
Command Line: D:\miHoYo\Tools\Starward\app-0.13.1\Starward.dll

[18:33:38.723] [INFO] Starward.Services.DatabaseService
Database path is 'D:\miHoYo\Tools\Starward'

[18:33:38.741] [INFO] Starward.Services.DatabaseService
Database version is 10, target version is 10.

[18:33:38.856] [INFO] Starward.Pages.MainPage
Last game region is hk4e_cn

[18:33:38.907] [INFO] Starward.Pages.MainPage
Navigate to "GameLauncherPage" with param hk4e_cn

[18:33:39.627] [INFO] Starward.Pages.GameLauncherPage
Game install path of hk4e_cn: "C:\ProgramMy\Genshin Impact\Genshin Impact Game"

[18:33:39.643] [INFO] Starward.Pages.GameLauncherPage
Acutal version and gamebiz of hk4e_cn is "5.0.0".

[18:33:40.571] [INFO] Starward.Services.UpdateService
Start to check update (Preview: True, Arch: X64)

[18:33:41.399] [INFO] Starward.Pages.MainPage
Navigate to "HoyolabToolboxPage" with param hk4e_cn

[18:33:41.411] [INFO] Starward.Services.GameRecordService
Change region to China.

[18:33:41.571] [INFO] Starward.Services.UpdateService
Current version: "0.13.1", latest version: "0.13.1", ignore version: null

[18:33:59.816] [WARN] Starward.Pages.Setting.FileSettingPage
Last backup database file not found: "D:\miHoYo\Tools\Starward\DatabaseBackup\StarwardDatabase_20240901_150321.db"
```

**Comment by xxbhpan** [comment]
背刺我，今天，9月2日米游社的旅行者札记页面开始显示今日数据了，奇怪的米游社
<img width="205" alt="20240902151615" src="https://github.com/user-attachments/assets/2b4f1225-8e19-40c6-8808-eb61072efcef">
再观察观察

**Comment by Scighost** [comment]
当天没有原石摩拉收入的时候，就是这句话。
