### ISSUE TITLE
[Feature] 希望能添加体力显示

### ISSUE THREAD

**Issue by Rechalliberalexmoll** [Scighost/Starward#1074]
### Checklist

- [X] I have already read [docs/Tips.md](https://github.com/Scighost/Starward/blob/main/docs/Tips.md), but my feature is not implemented.
- [X] My suggested feature was not mentioned by others, and it is not a duplicate feature.

### Summary

想在PC上也有体力恢复显示的功能

### Solution or Design

安卓手机米游社桌面小组件就是调用的米游社的实时便笺的，可行的话希望上面的数据都整合过来，方便不用在看手机了

**Comment by Eric-Joker** [comment]
duplicate #333
