### ISSUE TITLE
[Feature] 尝试保留已设定的游戏路径

### ISSUE THREAD

**Issue by 1235789gzy1** [Scighost/Starward#1075]
### Checklist

- [X] I have already read [docs/Tips.md](https://github.com/Scighost/Starward/blob/main/docs/Tips.md), but my feature is not implemented.
- [X] My suggested feature was not mentioned by others, and it is not a duplicate feature.

### Summary

我有部分游戏存放于移动存储设备中,而另一部分则保留在我设备内置的硬盘里. 
例如绝区零放在移动硬盘里,星穹铁道放在设备硬盘中,我只有偶尔启动绝区零的时候才会连接移动硬盘,但是因为我经常启动星穹铁道,导致每次我想启动绝区零需要重新设定游戏路径

### Solution or Design

保留先前设定的游戏路径,当检测到新的存储设备接入或者重新启动Starward时重新访问设定的路径

**Comment by Scighost** [comment]
很有意思也很有用的想法

**Comment by Scighost** [comment]
相关功能由 #1081 追踪
