### ISSUE TITLE
[Bug] `InstallGameService.cs`中部分代码线程安全问题（竞争执行Bug）

### ISSUE THREAD

**Issue by iamscottxu** [Scighost/Starward#1082]
### Checklist

- [X] My issue was not mentioned by others, and it is not a duplicate issue.

### Description

InstallGameService.cs：

<img width="662" alt="image" src="https://github.com/user-attachments/assets/6c069e33-50f5-4220-a517-f02eec7f84a5">
<img width="599" alt="image" src="https://github.com/user-attachments/assets/be54e365-0885-4cf3-a6f4-aed1994a760c">

红框框起来的代码有线程安全问题（竞争执行Bug）。具体来说是这样写的话读取与自增或自减不是原子操作，在特定条件下会造成判断条件在多个线程中多次触发，可能会造程序行为异常。

建议改为以下代码：
```C#
var concurrentExecuteThreadCount = Interlocked.Increment(ref _concurrentExecuteThreadCount);
if (concurrentExecuteThreadCount > Environment.ProcessorCount)
{
    return;
}
```
```C#
var concurrentExecuteThreadCount = Interlocked.Decrement(ref _concurrentExecuteThreadCount);
if (concurrentExecuteThreadCount == 0)
{
    CurrentTaskFinished();
}
```

且与 #1083 问题一起修改后，这些代码将会变为冗余代码。

### Starward Version

main分支：37253b8

### Windows Version

与操作系统版本无关

### Additional Context

已经提pr #1084 修复。

**Comment by iamscottxu** [comment]
#1084

**Comment by Scighost** [comment]
我觉得这个办法不行，假设在 `Interlocked.Increment` 和 `if (concurrentExecuteThreadCount > Environment.ProcessorCount)` 之间有其他线程修改了 `_concurrentExecuteThreadCount` 的值，那么临时变量 `concurrentExecuteThreadCount` 的值就不等于真实值。

**Comment by iamscottxu** [comment]
这里本身就不需要知道其在判断逻辑执行时的真实值，而是要得到自增自减原子操作后的值，也就是说自增自减取值必须是一个完整的原子操作，否则会导致本来不该多次执行的代码被多次执行了。简单做了一个复现例子来说明这个问题。

期望：只输出一次11。
![image](https://github.com/user-attachments/assets/b21ab96f-fbdf-475d-805c-19d10d700419)
![image](https://github.com/user-attachments/assets/500639b9-47bc-47b9-9681-bce02e6fabb0)

```C#
var _taskCount = 0;

async Task Test()
{
    Interlocked.Increment(ref _taskCount);
    await Task.Delay(500);
    if (_taskCount > 10)
    {
        Console.WriteLine(_taskCount);
    }
    await Task.Delay(1000);
}


_taskCount = 0;
var tasks = new Task[11];
for (var i = 0; i < 11; i++)
{
    tasks[i] = Test();
}
await Task.WhenAll(tasks);
Console.WriteLine("Finish");

```

**Comment by Scighost** [comment]
谢谢你指出我的错误
