### ISSUE TITLE
[Bug] 安装游戏完成后，偶发性按钮不变成`开始游戏`等奇怪问题

### ISSUE THREAD

**Issue by iamscottxu** [Scighost/Starward#1083]
### Checklist

- [X] My issue was not mentioned by others, and it is not a duplicate issue.

### Description
InstallGameService.cs：

除#1082，可能会造成此问题外，`protected void StartTask(InstallGameState state)`方法中`ExecuteTaskItemAsync`调用时不等待，而直接返回，且`protected async Task ExecuteTaskItemAsync(CancellationToken cancellationToken = default)`方法中在finally中使用判断`_concurrentExecuteThreadCount`是否等于0的机制也会造成本该执行一次的`private void CurrentTaskFinished()`方法被反复执行。而`CurrentTaskFinished`方法的代码逻辑线程不安全，造成”安装游戏完成后，偶发性按钮不变成`开始游戏`等奇怪问题“。

会反复执行的原因在于，**C#中的异步方法如果不进行特殊处理，调用后就会被立即执行**，即在`StartTask`中循环还没有执行完成，前面启动的`ExecuteTaskItemAsync`异步任务已经在执行当中了，**这会导致当任务执行速度较快时，启动异步任务的循环还没有结束**，这样线程计数器`_concurrentExecuteThreadCount`会**多次等于0**，造成`CurrentTaskFinished`方法被反复执行。

解决方法是，使用`Task.WhenAll`方法等待所有任务执行完成后，再调用`CurrentTaskFinished`方法。

```C#
_ = RunTasksAsync(); //不需要ConfigureAwait，因为返回值丢弃，且无需调用“.GetAwaiter().OnCompleted()”
return;

async Task RunTasksAsync()
{
    _cancellationTokenSource = new CancellationTokenSource();
    var tasks = new Task[Environment.ProcessorCount];
    for (int i = 0; i < Environment.ProcessorCount; i++)
    {
        tasks[i] = ExecuteTaskItemAsync(_cancellationTokenSource.Token);
    }
    try
    {
        await Task.WhenAll(tasks).ConfigureAwait(false);
    }
    finally
    {
        CurrentTaskFinished();
    }
}
```

### Reproduction Steps

将`protected async Task ExecuteTaskItemAsync(CancellationToken cancellationToken = default)`中的带有`await`调用的代码清空，让其快速执行完成，即可相对稳定地复现此问题。

### Starward Version

main分支：37253b8

### Windows Version

与操作系统版本无关

### Additional Context

已经提pr #1084 修复。

**Comment by iamscottxu** [comment]
#1084

**Comment by Scighost** [comment]
很可惜，修改后的代码没能通过测试，一键修复过程完成校验后，无法进入到下载流程。

**Comment by iamscottxu** [comment]
抱歉，无法进入下载流程的原因是没有考虑到StartTask会被多次执行，加了一行State == None的判断逻辑导致的，修改后使用_concurrentExecuteThreadCount > 0进行判断，达到同样的效果，解决此问题。
