### ISSUE TITLE
[Bug] 星铁的120帧无法正常使用，现在会自动把游戏调成30帧

### ISSUE THREAD

**Issue by Xiao-Ma-cookiemx** [Scighost/Starward#1085]
### Checklist

- [X] My issue was not mentioned by others, and it is not a duplicate issue.

### Description

星铁的120帧无法正常使用，现在会自动把游戏调成30帧

### Reproduction Steps

在启动选项里选120帧，进入游戏会发现游戏变成30帧了

### Expected Behavior

游戏120帧启动

### Starward Version

0.13.1

### Windows Version

19045.4780

### Log

```shell
N/A
```

### Additional Context

N/A

**Comment by fuuunyfun** [comment]
游戏只是显示三十帧 实际还是120帧
![image](https://github.com/user-attachments/assets/bc4a3956-b7d1-48ed-b48a-cd0dc54cc3a7)

**Comment by SSB-ARFCN** [comment]
目前遇過掉30FPS只有躍遷詳情紀錄網頁 靜態頁面FPS幾乎無感 
![螢幕擷取畫面 (335)](https://github.com/user-attachments/assets/90645313-1809-435b-a63c-48a7e1d1240d)

**Comment by Xiao-Ma-cookiemx** [comment]
我这边的状况稍微有些不一样，显示30帧后掉帧严重，基本上幻灯片了【

**Comment by SSB-ARFCN** [comment]
試試驗證starward檔案完整性 若檔案有缺少會自動下載

之前這台PC有成功啟用120FPS？ 顯示卡型號？

**Comment by Xiao-Ma-cookiemx** [comment]
验证过了，貌似没有缺少。

之前有成功启动过120FPS，显卡Geforce RTX 3080

**Comment by Xiao-Ma-cookiemx** [comment]
嗯，没事了，之前用渲染精度2.0的时候也能120帧，现在把渲染精度调低就好了。
