### ISSUE TITLE
[Feature] Honkai Star Railway Mixed pool gacha records 崩铁混池抽卡记录

### ISSUE THREAD

**Issue by cangerjun** [Scighost/Starward#1090]
### Checklist

- [X] I have already read [docs/Tips.md](https://github.com/Scighost/Starward/blob/main/docs/Tips.md), but my feature is not implemented.
- [X] My suggested feature was not mentioned by others, and it is not a duplicate feature.

### Summary

获取崩铁混池抽卡记录

### Solution or Design

N/A

**Comment by SSB-ARFCN** [comment]
混池屬於活動UP池的一部分 可直接在活動池紀錄查看
![螢幕擷取畫面 (357)](https://github.com/user-attachments/assets/9b5faff0-1a4d-49b1-9071-f27aa2111fab)
