### ISSUE TITLE
[Feature] 能否添加对 Steam 版崩坏三的支持

### ISSUE THREAD

**Issue by CLydq** [Scighost/Starward#1093]
### Checklist

- [X] I have already read [docs/Tips.md](https://github.com/Scighost/Starward/blob/main/docs/Tips.md), but my feature is not implemented.
- [X] My suggested feature was not mentioned by others, and it is not a duplicate feature.

### Summary

~~第二条处理的时候我就搜了关键字 Steam，不过貌似没有~~

大致想法就是题目那样。

~~我是大怨种~~

### Solution or Design

大致想法就是调用 Steam 启动 Steam 版崩坏三，启动参数 steam://rungameid/1668940。

然后支持一下抽卡记录什么的。

文件校验这个就留给 Steam 吧。如果能直接调用 Steam 获得信息就更好了。

绑定米游社账号的话大部分功能应该能用吧。

**Comment by Scighost** [comment]
如果你需要 Steam 版的崩坏三支持，建议你使用 https://github.com/CollapseLauncher/Collapse

**Comment by CLydq** [comment]
今天我本来计划下个中国版玩玩的。

不过下完我发现，自定义启动的 exe 文件选择 Steam 版崩坏三是可以启动的……

所以能否在识别的时候支持一下对 Steam 版崩坏三的支持或者说在设置里加上“允许不进行文件校验启动游戏”（就是可以直接启动可执行文件而不是要求下载）

而且这么启动的话 Steam 那里是可以识别的……

然后这时候自行添加一个账号就行了……或者直接把换号那个位置隐藏一下……

eee

**Comment by CLydq** [comment]
而且您推荐那个好像也没法启动 Steam 版崩坏三……
