### ISSUE TITLE
[Bug] Unable to select folder during first launch

### ISSUE THREAD

**Issue by HongyuS** [Scighost/Starward#11]
![image](https://github.com/Scighost/Starward/assets/44023928/e3faa33c-39fe-44ae-b746-b4a72a11e71c)

Error: Built-in COM has been disabled via a feature switch.

Reference link suggested by Microsoft: [link](https://learn.microsoft.com/en-us/dotnet/standard/native-interop/cominterop)

**Comment by Scighost** [comment]
刚发布的 0.2.2 版本修复了这个问题

**Comment by HongyuS** [comment]
确认已修复，谢谢！
