### ISSUE TITLE
对于祈愿记录的信息展示

### ISSUE THREAD

**Issue by chen274** [Scighost/Starward#110]
目前看到了作者大大的计划  “Starward 不会加入需要开发者持续更新游戏数据和资源的功能，比如给抽卡记录加上物品图片”
希望可以添加：①改变祈愿记录的纵向排列，改为寻空类似的横向竖排，因为我也导入了原神的数据，有很多了，在记录多起来之后，看信息就想对很不直观了，也需要滑动。
② 希望可以添加角色 / 光锥 / 武器 一览展示列在记录的下方

**Comment by Scighost** [comment]
感谢建议，可以用设计图简单地展示一下你的想法吗？
