### ISSUE TITLE
[Feature] 绝区零绳网月报

### ISSUE THREAD

**Issue by wen20919** [Scighost/Starward#1105]
### Checklist

- [X] I have already read [docs/Tips.md](https://github.com/Scighost/Starward/blob/main/docs/Tips.md), but my feature is not implemented.
- [X] My suggested feature was not mentioned by others, and it is not a duplicate feature.

### Summary

米游社绝区零战绩绳网月报

### Solution or Design

在绝区零1.2版本更新后，米游社绝区零战绩中新增了绳网月报的版块（类似于原神的旅行者札记和崩铁的开拓月历），但只能查询最近三月，是否可以加入相关功能

**Comment by Scighost** [comment]
不要急
