### ISSUE TITLE
修改游戏资源位置后无法读取uid

### ISSUE THREAD

**Issue by axwg020226** [Scighost/Starward#111]
https://github.com/Scighost/Starward/issues/57#issuecomment-1587739166
RT
![image](https://github.com/Scighost/Starward/assets/74946471/3454f065-5095-4935-8f9e-4a446b8c71a9)

**Comment by Scighost** [comment]
原神没有在注册表中保存uid，自然也读不到。

**Comment by axwg020226** [comment]
ok

**Comment by axwg020226** [comment]
@axwg020226
