### ISSUE TITLE
登录环境改变后，账号失效

### ISSUE THREAD

**Issue by axwg020226** [Scighost/Starward#112]
密钥的保存和上机环境有关吗，我换了个地点之后，密码好像失效了，进去是登录界面

_Originally posted  in https://github.com/Scighost/Starward/issues/102#issuecomment-1614524054_

**Comment by axwg020226** [comment]
有线换热点之后，复现了此问题，有解决方案吗

**Comment by axwg020226** [comment]
官方保存的登录信息好像是可以不受影响

**Comment by Scighost** [comment]
你的描述有点模糊，请详细地说明一下出问题时的操作流程。

**Comment by axwg020226** [comment]
就是网络环境改变之后 之前保存的账号信息失效

使用A网络（有线），登录之后保存账号
切换网络（手机流量热点）
使用保存的信息启动游戏，账号会失效
![image](https://github.com/Scighost/Starward/assets/74946471/85637cda-b87d-49ee-bf9c-cfb3d895eee3)

**Comment by axwg020226** [comment]
切回A网络，账号信息有效，也就是说他这个登录信息和网络环境也有关？

**Comment by LIHAQI** [comment]
同碰到这个问题

**Comment by PropitiousSun** [comment]
我是把WiFi里的随机硬件地址关掉就好了

**Comment by Lightczx** [comment]
通常是连接到服务器的任何一个中继设备的MAC地址变更引起的
当然也有其他因素
