### ISSUE TITLE
更新0.8.0后原神和铁道的抽卡记录全部消失了

### ISSUE THREAD

**Issue by L3Rui** [Scighost/Starward#113]
目前不知道是什么原因造成的，姑且先想办法导出来备份了。铁道记录不多还没事，原神那边的记录是我从寻空那边导出Js之后导到启动器里面的，然后今天更新后记录全部消失了，幸好寻空这边还有云备份，不然原神这边的记录真就全没了。。。

**Comment by a285292107s** [comment]
我也是，不过这次更新重新选择数据存档位置了，估计和我上次选的不一样。

**Comment by Scighost** [comment]
请问更新前后的用户数据文件夹是不是同一个文件夹，还有 0.8.0 现有的 bug 是无法使用绝对路径，应用内之外的文件夹都会失效。
