### ISSUE TITLE
[Bug] Can't Open the Program after upgrading to 3.13.4

### ISSUE THREAD

**Issue by 111inhistory** [Scighost/Starward#1138]
### Checklist

- [X] My issue was not mentioned by others, and it is not a duplicate issue.

### Description

I can't open it. I upgrade the launcher by itself, and then the launcher can't be opened. When I look at the taskmgr, the program was in the list, then disappear, and then another starward.exe emerged, and after a few second, it disappeared. 

Then I tried the version in Github Action, also failed with the same behaviour. 

**Note: the log below are the log before upgrading, after upgrading it doesn't generate any log at all.** 

### Reproduction Steps

null

### Starward Version

3.13.4

### Windows Version

Windows 11 26120.2130, Insider Program 24H2

### Log

```shell
[12:42:15.960] [INFO] 
Welcome to Starward v0.13.3
System: Microsoft Windows NT 10.0.26120.0
Command Line: D:\Games\Starward_miHoYo_starter\app-0.13.3\Starward.dll

[12:42:15.990] [INFO] Starward.Services.DatabaseService
Database path is 'D:\Games\Starward_miHoYo_starter'

[12:42:16.021] [INFO] Starward.Services.DatabaseService
Database version is 11, target version is 11.

[12:42:16.153] [INFO] Starward.Pages.MainPage
Last game region is hk4e_global

[12:42:16.179] [INFO] Starward.Pages.MainPage
Navigate to "GameLauncherPage" with param hk4e_global

[12:42:16.913] [INFO] Starward.Pages.GameLauncherPage
Game install path of hk4e_global: "D:\Games\miHoYo\Genshin_Impact\Genshin Impact game"

[12:42:16.941] [INFO] Starward.Pages.GameLauncherPage
Acutal version and gamebiz of hk4e_global is "5.0.0".

[12:42:17.846] [INFO] Starward.Services.UpdateService
Start to check update (Preview: True, Arch: X64)

[12:42:18.655] [INFO] Starward.Services.UpdateService
Current version: "0.13.3", latest version: "0.13.4", ignore version: null
```

**Comment by Scighost** [comment]
I have also noticed this problem and have deleted the update and am looking for the cause of the problem.
