### ISSUE TITLE
[Bug] Windows11 24H2 LTSC 打开启动器无法正常加载对应游戏LOGO以及背景页

### ISSUE THREAD

**Issue by Leienjoy** [Scighost/Starward#1143]
### Checklist

- [X] My issue was not mentioned by others, and it is not a duplicate issue.

### Description

 Windows11 24H2 LTSC26100.2033 打开启动器无法正常加载对应游戏LOGO以及背景页

### Reproduction Steps

1.启动客户端
2.发现无法正常加载对应游戏LOGO以及背景页

### Expected Behavior

打开客户端正常显示对应游戏LOGO以及背景页面

### Screenshots

<img width="918" alt="Snipaste_2024-10-23_15-11-58" src="https://github.com/user-attachments/assets/01dcc6c1-6ce7-415e-b6a2-093bc0ddbc2b">

### Starward Version

0.13.4

### Windows Version

26100.2033

### Log

```shell
并没有产生任何日志，进行排查和诊断网络后发现依旧如此
```

**Comment by Eric-Joker** [comment]
duplicate #1120
这标题关键词这么多你是一点也不搜啊

**Comment by Leienjoy** [comment]
> duplicate #1120 这标题关键词这么多你是一点也不搜啊

？没听明白我是脑瘫

**Comment by sakana164** [comment]
> > duplicate #1120 这标题关键词这么多你是一点也不搜啊
> 
> ？没听明白我是脑瘫

意思是提issue之前，先搜搜有无类似的issue，大概率别人之前已经遇到过了，已经提过issue了
翻翻就能得到解答：去微软应用商店安装webp扩展

**Comment by Leienjoy** [comment]
> > > duplicate #1120 这标题关键词这么多你是一点也不搜啊
> > 
> > 
> > ？没听明白我是脑瘫
> 
> 意思是提issue之前，先搜搜有无类似的issue，大概率别人之前已经遇到过了，已经提过issue了 翻翻就能得到解答：去微软应用商店安装webp扩展

好的，抱歉，我看还开着的issues没人提就发了
