### ISSUE TITLE
使用一键修复后崩铁旧资源依旧没有删除

### ISSUE THREAD

**Issue by Shiroha1768** [Scighost/Starward#1144]
![image](https://github.com/user-attachments/assets/df19e41b-3aac-4240-bd30-8066d9809526)
![image](https://github.com/user-attachments/assets/8fb024af-c4e0-413c-84f0-62f521f24760)
[Starward_241023_160239.log](https://github.com/user-attachments/files/17487674/Starward_241023_160239.log)

**Comment by devil233-ui** [comment]
是的，甚至多下了2g文件……
不知道是不是要等到下次2.7版更才会执行diff比对删除

**Comment by Mirror1934** [comment]
如果是在他修复这个bug前就更新的话应该是不会删除的。
有个办法是删除 游戏目录\StarRail_Data\StreamingAssets\Asb\Windows 文件夹，然后使用一键修复重新下载缺失资源，应该可以解决这个问题。
或者继续等待作者添加删除冗余资源的功能。

**Comment by devil233-ui** [comment]
> 如果是在他修复这个bug前就更新的话应该是不会删除的。 有个办法是删除 游戏目录\StarRail_Data\StreamingAssets\Asb\Windows 文件夹，然后使用一键修复重新下载缺失资源，应该可以解决这个问题。 或者继续等待作者添加删除冗余资源的功能。

修复bug的版本就是13.4啊，上面有图

**Comment by Mirror1934** [comment]
13.4版本的修复应该是只修复了更新游戏时没有删除冗余资源的问题，如果你使用13.3更新了游戏，产生了冗余资源，那么即使你将Starward更新后再点一键修复也不会删除冗余资源，因为更新游戏的操作已经在13.3完成了，而一键修复只是比对游戏文件有没有缺失，并不会对多余的文件进行删除。
我的意思是等他在后续版本中增加“删除冗余资源”的功能（也许不会加）

**Comment by devil233-ui** [comment]
> 13.4版本的修复应该是只修复了更新游戏时没有删除冗余资源的问题，如果你使用13.3更新了游戏，产生了冗余资源，那么即使你将Starward更新后再点一键修复也不会删除冗余资源，因为更新游戏的操作已经在13.3完成了，而一键修复只是比对游戏文件有没有缺失，并不会对多余的文件进行删除。 我的意思是等他在后续版本中增加“删除冗余资源”的功能（也许不会加）

那，13.4我们多下的2g是干啥的

**Comment by ExtermanetX** [comment]
> > 13.4版本的修复应该是只修复了更新游戏时没有删除冗余资源的问题，如果你使用13.3更新了游戏，产生了冗余资源，那么即使你将Starward更新后再点一键修复也不会删除冗余资源，因为更新游戏的操作已经在13.3完成了，而一键修复只是比对游戏文件有没有缺失，并不会对多余的文件进行删除。 我的意思是等他在后续版本中增加“删除冗余资源”的功能（也许不会加）
> 
> 那，13.4我们多下的2g是干啥的

强迫症已经删除重下了😂
