### ISSUE TITLE
给用0.13.3版更新星穹铁道2.6导致过时文件未删除的玩家的解决方法

### ISSUE THREAD

**Issue by pbxs666** [Scighost/Starward#1149]
这个issue不是反馈问题，仅仅提供一个解决问题的方法，也就_2.6_更新手快的人能用得到，过几天就关掉这个issue。

如果你用**0.13.3**更新星穹铁道_2.6_，导致旧文件未删除，这时即便用**0.13.4**来**一键修复**也没用。
接下来按照如下步骤即可解决：
1.更新starward至**0.13.4**或更新版（截止发帖最新版为**0.13.4**）；
2.打开星穹铁道游戏根目录的_config.ini_文件，修改里面的game_version=2.6.0这一行，2.6改成2.5，保存；
3.启动starward，发现开始按钮变成更新游戏了，重新更一次吧，也就15GB的数据包，总比你删掉data文件夹用**一键修复**重下那几十GB快多了吧。

原理是欺骗starward让它以为游戏还是旧版重新更新一次，starward版本最低要到**0.13.4**，这很重要，**0.13.4**适配了游戏新的更新方式。

**Comment by devil233-ui** [comment]
感谢，到家试试。
~~但其实不是手快才会中招，只要预下载就会，多数人只是没注意到异常大小~~

**Comment by HeroTch** [comment]
之后 Closed 掉就可以了，留个解决方案（）

**Comment by devil233-ui** [comment]
试了下，这个欺诈对官方启动器也一样适用。其实我刚突然想到是不是能做文件比对然后批量删来着？
