### ISSUE TITLE
8.0版本更新后闪退，修改 config.ini 文件无效

### ISSUE THREAD

**Issue by axwg020226** [Scighost/Starward#116]
8.0 Release 无 config.ini文件 手动添加后仍然无效

**Comment by axwg020226** [comment]
删除注释后解决，但release里面好像确实没有 config.ini文件

**Comment by Scighost** [comment]
正常流程是在软件中选择好文件夹后会自动创建 config.ini

**Comment by axwg020226** [comment]
![image](https://github.com/Scighost/Starward/assets/74946471/8279d3cd-7081-4907-9c83-fb230de793f8)

**Comment by axwg020226** [comment]
这里说的下载的文件必定满足此条件 QAQ
