### ISSUE TITLE
因版本问题或兼容性导致无法运行

### ISSUE THREAD

**Issue by star287** [Scighost/Starward#1171]
### Checklist

- [X] I have already read [docs/Tips.md](https://github.com/Scighost/Starward/blob/main/docs/Tips.md), but my question is not solved.
- [X] My question was not mentioned by others, and it is not a duplicate question.

### Description

为什么解压后的安装程序显示<此应用无法在你的电脑上运行>

### Starward Version

0.13.4

### Windows Version

24H2

### Additional Context

![Uploading 569be377eab5b034ae623d9e659f752.png…]()

**Comment by star287** [comment]
![7185e7f84af3b7fffeb5005d4549b9a](https://github.com/user-attachments/assets/a4ea12d4-9e40-4814-a981-50b1c30636e0)

**Comment by Scighost** [comment]
如果你使用的是英特尔或AMD的CPU，下载带 `x64` 的压缩包；如果使用的是高通的CPU，下载带 `arm64` 的压缩包。

**Comment by S-t-e-v-e-e** [comment]
> ![7185e7f84af3b7fffeb5005d4549b9a](https://private-user-images.githubusercontent.com/189837725/390338684-a4ea12d4-9e40-4814-a981-50b1c30636e0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzMzMjAyODAsIm5iZiI6MTczMzMxOTk4MCwicGF0aCI6Ii8xODk4Mzc3MjUvMzkwMzM4Njg0LWE0ZWExMmQ0LTllNDAtNDgxNC1hOTgxLTUwYjFjMzA2MzZlMC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjA0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIwNFQxMzQ2MjBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wYTU1NmUzMmY4ZDRlNmIyZWZlMGZlYzBkOTZkY2FiYTU5ZDRiYTA3ZDAwNWM2MTViZmU5ZWE1MTliNTI2YTZmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.f0onQKWzYY_rydzF2esTRxXmMMKlDQajH0xB1TQJJ3s)

什么cpu
