### ISSUE TITLE
0.8闪退

### ISSUE THREAD

**Issue by accelerator148** [Scighost/Starward#118]

**Comment by issligang** [comment]
可以尝试，修改config.ini文件，如下如所示（若是复制说明文档中的，需要将#号注解内容去除，否则还是会闪退）
![image](https://github.com/Scighost/Starward/assets/48896199/28a9f3ff-ef74-4c3a-b46a-26c7ac85dedb)

**Comment by Scighost** [comment]
就是这个解决办法
