### ISSUE TITLE
[Bug] 五星平均抽数计算错误

### ISSUE THREAD

**Issue by HongyuS** [Scighost/Starward#12]
![image](https://github.com/Scighost/Starward/assets/44023928/49f4fbac-6a67-49e7-b757-5699d5292641)

如图所示，现有算法得到的平均数可能大于理论值
建议计算总数时减去自上一个五星以来已垫的抽数

**Comment by Scighost** [comment]
感谢反馈，是我疏忽了

**Comment by Scighost** [comment]
修了，但没修完，当最后一抽为5星时仍会出现计算错误。
