### ISSUE TITLE
希望可以添加繁体中文 便于港港的伙伴们使用

### ISSUE THREAD

**Issue by yelan2067** [Scighost/Starward#121]
希望可以添加繁体中文 便于港港的伙伴们使用（zh-tw）

**Comment by yelan2067** [comment]
找到繁体中文啦 谢谢

**Comment by toonwiz28** [comment]
不好意思繁體中文在哪裡設定，沒看到的樣子？

**Comment by Scighost** [comment]
@toonwiz28 因为确实没有繁体中文，我也不知道他找到的是什么

**Comment by XPRAMT** [comment]
繁中希望+1

**Comment by Scighost** [comment]
如果想要贡献新的本地化语言，请参考这一部分。
https://github.com/Scighost/Starward/blob/main/docs/README.zh-CN.md#%E6%9C%AC%E5%9C%B0%E5%8C%96
