### ISSUE TITLE
你好，请问米游社工具箱账号登录用网页登录无法使用？

### ISSUE THREAD

**Issue by QiFenQAQ** [Scighost/Starward#122]
RT，手动也无法输入网页
![截图20230701143343](https://github.com/Scighost/Starward/assets/137874785/5ba2bee5-ab85-4758-bf66-a2c73315eaa3)

**Comment by Scighost** [comment]
你安装 WebView2 了吗？
https://developer.microsoft.com/microsoft-edge/webview2/

**Comment by QiFenQAQ** [comment]
安装过的寻空的可以打开

**Comment by Scighost** [comment]
请提供发生此问题时的日志文件

**Comment by QiFenQAQ** [comment]
[Starward_230705_121643.log](https://github.com/Scighost/Starward/files/11953855/Starward_230705_121643.log)

**Comment by Scighost** [comment]
抱歉，久等了。根据你提供的日志，可以判断是初始化 WebView2 失败，建议你重装 WebView2 或安装 Edge 的预览版。
