### ISSUE TITLE
win11更新8.0版本后无法打开启动器

### ISSUE THREAD

**Issue by snfd3** [Scighost/Starward#125]
启动程序之后，会弹出黑屏窗口然后过几秒就自动关闭了

**Comment by axwg020226** [comment]
![image](https://github.com/Scighost/Starward/assets/74946471/77c869b8-c035-4085-aac8-ec4a31ddd910)

**Comment by axwg020226** [comment]
详见README

**Comment by axwg020226** [comment]
部分设备上可能出现运行后崩溃的问题，如果遇到了此问题，请在 Starward 文件夹中创建 config.ini 文件，并把以下内容粘贴到此文件中。有关 config.ini 的更多信息请参考 [docs/Configuration.md](https://github.com/Scighost/Starward/blob/main/docs/Configuration.zh-CN.md) 。

EnableConsole=False
UserDataFolder=.
