### ISSUE TITLE
界面逻辑优化

### ISSUE THREAD

**Issue by ahshy1996** [Scighost/Starward#128]
既然是合并登录器，何必要点一下就自动最小化呢？
我觉得应该分两种：
1、点击启动，无反应。
2、点击启动直接最小化到右下角。

另外，界面能否添加快捷键？
既然是选项卡形式，就应该有切换标签的快捷键。如ctrl tab/ctrl shift tab之类，这样就不需要手点了。

**Comment by Scighost** [comment]
抱歉，我不接受您的建议。
