### ISSUE TITLE
Update Content (0.8.1 - Seele)

### ISSUE THREAD

**Issue by Scighost** [Scighost/Starward#129]
This issue is about todo list and update content for version [0.8.1 - Seele](https://github.com/Scighost/Starward/releases/tag/0.8.1). Welcome to help us translate it.

Previous version and commit: [0.8.0 - Dan Heng](https://github.com/Scighost/Starward/releases/tag/0.8.0) d1a9dba9ccae8620cfb374efae36972fa2760f3a

The latest commit of current version: 083896a30d633c16ead2a2ba16a92fda228145ff

**Comment by Scighost** [comment]
# Todo list

(This section does not require translation)

**Comment by Scighost** [comment]
# 简体中文

（翻译未完成）

- 修复了无法在 `config.ini` 中设置绝对路径的问题 #103 9a22a8adaa8fadaeba0b9d456f7290971098c11a

**Comment by Scighost** [comment]
# English

(Translation unfinished)

- Fix the error that cannot set full path in `config.ini` #103 9a22a8adaa8fadaeba0b9d456f7290971098c11a

**Comment by phucho0237** [comment]
# Tiếng Việt

(Bản dịch chưa hoàn thành)

- Sửa lỗi không thể đặt đường dẫn đầy đủ trong `config.ini` #103 9a22a8adaa8fadaeba0b9d456f7290971098c11a
