### ISSUE TITLE
一些功能建议

### ISSUE THREAD

**Issue by PIut02** [Scighost/Starward#13]
1.加入类似Collapse上的小窗口模式，现在的窗口有些过大了
2.加入祈愿记录的导入与导出功能，或者能直接用寻空的用户数据再好不过了
3.顶部游戏切换能否自定屏蔽部分和排序，比如国际服和云原神
4.游戏切换能否用浏览器标签页的方式一字排开的话，这样只用点一下效率会高一些
5.能否加入Collapse上的预下载以及游戏修复及缓存功能，有了这些就能完全抛弃官方启动器了
6.能否加入窗口模式的修改（全屏、无边框、窗口化）以及窗口大小的设置
7.能否加入b服切换功能，非uwp应该没有权限问题了
8.是否有计划加入对崩坏3的支持，三个官方启动器实在太多了（
以上仅为建议，一直期待能有一个美观的全功能启动器，不知道实现起来容不容易

**Comment by PIut02** [comment]
关于4就像图片中这样，最右侧的×可以改成下拉切换同游戏的不同地区
![6LVLG{MLL)FZBN%18`{1A%O](https://github.com/Scighost/Starward/assets/39442130/3b9ceb68-97d1-4f6d-8dff-8a6ce9c2df65)

**Comment by Scighost** [comment]
你的建议很有建设性，其中1258条在开发计划中。

4 能否给出更详细的描述？

6 窗口模式的修改是关于启动器的，还是关于游戏窗口的？

7 我暂时还不知道怎么切换官B服，得去搜一搜方法。

如果仅需要启动器的功能，Collapse 已经做得非常好了，Starward 现在也只是对前者的拙劣模仿

**Comment by PIut02** [comment]
4 我预想的是游戏按浏览器标签页的形式在顶部居中一字排开，取代现在的切换方式，把不同地区服务器放在标签页的展开里面，点击标签页即可切换游戏，类似图片这种
![2](https://github.com/Scighost/Starward/assets/39442130/c8ce43a3-0022-459d-92cc-37c2385709c9)
6 是关于游戏窗口的
7 b服切换的方法可以参考这个(https://www.bilibili.com/read/cv12173130)

**Comment by Scighost** [comment]
相关功能的完成情况

- [x] 小窗模式
- [x] 抽卡记录的导入导出
- [x] 更好的服务器切换方式
- [ ] 下载修复游戏文件
- [ ] 游戏图形设置
- [ ] 官B服切换
- [ ] 支持崩坏三

**Comment by Scighost** [comment]
大部分功能已实现，此 issue 关闭，剩余内容由 #76 追踪
