### ISSUE TITLE
[Feature] 需要一个最小化到托盘的功能，同时希望能加入图标

### ISSUE THREAD

**Issue by MephistoSatanDevil** [Scighost/Starward#130]
### Summary

最小化需要一个最小化到系统托盘的功能
另外，至少在任务栏显示时，有一个图标比较好。

### Solution or Design

最小化到系统托盘功能最好类似原版启动器有这样的设置
![QQ截图20230702222939](https://github.com/Scighost/Starward/assets/1319061/576f5dd5-15c3-4f46-b801-f52d9d322e00)

启动器图标个人认为用米游姬头像，就如附图这样，会与米哈游游戏一贯启动图标的“二次元图标”风格较为统一。
![logo](https://github.com/Scighost/Starward/assets/1319061/29922a01-389d-4326-8af4-829cb5cd0c40)

**Comment by meng-ru-nan-fa** [comment]
最小化托盘我提过，被拒了（倒）

**Comment by MephistoSatanDevil** [comment]
> 

拒绝需求挺正常

**Comment by MephistoSatanDevil** [comment]
> 最小化托盘我提过，被拒了（倒）

拒绝需求挺正常。比如无法实现，实现意义不大之类。

**Comment by Eric-Joker** [comment]
> > 最小化托盘我提过，被拒了（倒）
> 
> 拒绝需求挺正常。比如无法实现，实现意义不大之类。

拒绝的理由是不符合“使用后即关闭”的设计原则，但是现在实际只是最小化窗口。而且作为米家游戏同时支持的启动器使用后即关闭貌似是个反人类的使用习惯，最小化置托盘或者最小化窗口才是应该的。 @Scighost

**Comment by goldenapple1** [comment]
> > > 最小化托盘我提过，被拒了（倒）
> > 
> > 
> > 拒绝需求挺正常。比如无法实现，实现意义不大之类。
> 
> 拒绝的理由是不符合“使用后即关闭”的设计原则，但是现在实际只是最小化窗口。而且作为米家游戏同时支持的启动器使用后即关闭貌似是个反人类的使用习惯，最小化置托盘或者最小化窗口才是应该的。 @Scighost

同意

**Comment by YIMUYONG** [comment]
还是先来个图标比较舒服，什么样子的图标都行，至于最小化托盘，可能会有些麻烦

**Comment by Eric-Joker** [comment]
> 还是先来个图标比较舒服，什么样子的图标都行，至于最小化托盘，可能会有些麻烦

https://github.com/Scighost/Starward/issues/96#issue-1781643235这个图标真的好好看

**Comment by shoah7** [comment]
启动后保持开启状态也好一点.. 开完原神立刻最小化然后还得再点开开崩铁emmm
