### ISSUE TITLE
[Feature] 使用体验

### ISSUE THREAD

**Issue by shoah7** [Scighost/Starward#132]
### Summary

我觉得启动游戏边上那个设置按钮 如果是游戏就好了 每次点了之后才发现不是调整分辨率然后点菜单里去设置... 

### Solution or Design

游戏路径设置和游戏设置应该对调一下

**Comment by Scighost** [comment]
已经聊过一轮了.jpg
https://github.com/Scighost/Starward/issues/79#issuecomment-1604059100
