### ISSUE TITLE
[Bug] 崩铁启动Bug

### ISSUE THREAD

**Issue by shoah7** [Scighost/Starward#133]
### Description

![QQ截图20230703060032](https://github.com/Scighost/Starward/assets/138249024/4e7811f2-0de2-4b70-98ac-78ba28896112)

### Reproduction Steps

启动器设置分辨率后开启120帧-monitor x启动在副屏后分辨率出现问题

### Starward Version

0.8.0

### Windows Version

19045.2251

**Comment by phucho0237** [comment]
您是否尝试过使用官方启动器启动?

**Comment by Scighost** [comment]
很遗憾，我没有多个显示器，无法测试你的问题。
