### ISSUE TITLE
预下载功能的一些疑问

### ISSUE THREAD

**Issue by meng-ru-nan-fa** [Scighost/Starward#137]
### Description

1.在成功预下载之后再点击starward还会跳出下载界面（但是在我翻issue时突然正常了）（应该没啥问题）
2.下载结束后仅在starward显示已预下载，那游戏正式更新后是否必须用starward启动游戏资源？官方启动器是否会到时候不能用？
![image](https://github.com/Scighost/Starward/assets/72238162/7fa29d22-e2a9-4bb2-9eae-7bd19f1e32df)
![image](https://github.com/Scighost/Starward/assets/72238162/fd9a5ec5-1310-44dd-9e53-c2aad790a720)

### Starward Version

0.8.0

### Windows Version

22H2 19045.3086

### Log

```shell
（应该不需要吧）
```

**Comment by Scighost** [comment]
更新的时候还需要使用 Starward，因为使用了多线程下载，但是为了避免额外的磁盘写入量，下载完成后没有合并文件切片，官方启动器无法正确识别。

文件夹中应该是一大堆这样的东西。

<img width="280" alt="image" src="https://github.com/Scighost/Starward/assets/61003590/c11ecf30-82a6-4e76-9f78-fb998bdbc616">
