### ISSUE TITLE
[Question] 为什么崩坏3没有游戏时长统计呢？

### ISSUE THREAD

**Issue by baijinqvan007** [Scighost/Starward#138]
### Description

我想看看自己平时凹分花了多久。。

### Starward Version

0.8.0

### Windows Version

22621.1848

**Comment by Scighost** [comment]
崩坏3 的启动过程有些复杂，第一次启动的崩坏3**进程A**会先检查系统环境，然后**进程A**再启动**两个进程BC**，此时**进程A**退出。现有的记录游戏时间的方法还不能应付这种情况，以后可能会优化，但是优先级不高。

**Comment by Scighost** [comment]
已加入此功能
