### ISSUE TITLE
关于帧数解锁问题。

### ISSUE THREAD

**Issue by Meterstream** [Scighost/Starward#14]
不知道你们使用的方法是否就是修改注册表信息。我设置帧数是120帧，但是进入游戏之后使用xbox gamebar检测帧数仍旧是锁60

**Comment by Scighost** [comment]
我测试可以成功解锁帧数

![image](https://github.com/Scighost/Starward/assets/61003590/f1056964-3cfa-482c-9692-c132a1b368e2)

使用的方法是修改注册表项 `HKEY_CURRENT_USER\Software\miHoYo\崩坏：星穹铁道\GraphicsSettings_Model_h2986158309` 中 `FPS` 的值

**Comment by Meterstream** [comment]
![image](https://github.com/Scighost/Starward/assets/129191100/3bc0ab3c-a0f9-4f3a-928b-936a77235bb8)
![image](https://github.com/Scighost/Starward/assets/129191100/a89c4999-ea54-4ef2-9ba3-2ae7bcbda748)
那不清楚诶，难道是我的问题？之前我自己直接修改注册表也不行，游戏里面画质不能设置就应该是修改好了的呀

**Comment by Scighost** [comment]
你在游戏中把画质预设跳到最低，关闭垂直同步，关闭游戏进程后修改注册表项，再尝试一下？

**Comment by Meterstream** [comment]
![image](https://github.com/Scighost/Starward/assets/129191100/eef24c4b-4380-429e-95b2-b7a83b6ffc7f)
![image](https://github.com/Scighost/Starward/assets/129191100/b57a4a92-2995-4c42-866b-d90470287988)
![image](https://github.com/Scighost/Starward/assets/129191100/c13f2080-2b6c-4d70-8e39-7130d6233e77)
![image](https://github.com/Scighost/Starward/assets/129191100/9b423f3b-51da-4072-ac76-f39a8b839ea9)
还是不行捏应该是我的问题吧

**Comment by Meterstream** [comment]
改为false吗？

**Comment by Meterstream** [comment]
哦哦哦这是垂直同步知道了

**Comment by Scighost** [comment]
![image](https://github.com/Scighost/Starward/assets/61003590/83f24752-9382-4239-ae42-f325ba2a33ef)
