### ISSUE TITLE
寻空 -> Starward 的数据迁移工具

### ISSUE THREAD

**Issue by Scighost** [Scighost/Starward#141]
此工具适用于 Starward 0.8.0 及以上版本。

[Xunkong2Starward_arm64.zip](https://github.com/Scighost/Starward/files/11952910/Xunkong2Starward_arm64.zip)
[Xunkong2Starward_x64.zip](https://github.com/Scighost/Starward/files/11952911/Xunkong2Starward_x64.zip)

启动后按照提示输入或拖入 Starward 的数据库文件 StarwardDatabase.db 即可。

**Comment by HyBoxwood** [comment]
这玩意还有用吗（
![QQ截图20230902111308](https://github.com/Scighost/Starward/assets/87700780/0686d90a-c793-4186-b76c-edb39ec4e838)
