### ISSUE TITLE
[Feature] 希望增加复制(预)下载包体链接的功能

### ISSUE THREAD

**Issue by CRZZA** [Scighost/Starward#142]
### Summary

如题
方便用户获取下载链接
以便用户可以自行使用第三方下载器下载

### Solution or Design

可以为下载/预下载功能设计一个右键菜单
用户右键点击按钮时，出现复制(预)下载链接的选项

**Comment by Scighost** [comment]
是一个很小众的功能呢，不考虑支持，你可以在[胡桃](https://github.com/DGP-Studio/Snap.Hutao)中找到这个功能。

你也可以通过下面的 api 中获取资源包的下载链接。
https://github.com/Scighost/Starward/blob/825f79bf130f09d600251e3bc3aa046bd851df03/Starward.Core/Launcher/LauncherClient.cs#L85-L94
