### ISSUE TITLE
[Question]祈愿记录无法正常获取

### ISSUE THREAD

**Issue by yejihui** [Scighost/Starward#144]
### Description

3.8版本更改了cache的位置 
3.8 版本把原来的 Genshin Impact\Genshin Impact Game\YuanShen_Data\webCaches\Cache\Cache_Data
改成了 Genshin Impact\Genshin Impact Game\YuanShen_Data\webCaches\2.13.0.1\Cache\Cache_Data

把2.13.0.1目录下的cache复制到原目录就能获取记录了

### Starward Version

0.8.1

### Windows Version

19044.2965

### Log

```shell
[12:16:11.827] [WARN]
Request mihoyo api error: "authkey timeout (-101)"
```

**Comment by Scighost** [comment]
感谢反馈

**Comment by Scighost** [comment]
已修复
