### ISSUE TITLE
没法正常更新

### ISSUE THREAD

**Issue by SakuraYukiMF** [Scighost/Starward#145]
### Description

从上个版本就不能正常更新，0.8.0还是我重新下载的，这个版本也不能更新一直说我SSL错误
![image](https://github.com/Scighost/Starward/assets/138652720/a33b314b-03ec-424a-a508-8af1dbd20594)

### Starward Version

0.8.0

### Windows Version

19045.3155

**Comment by Scighost** [comment]
你的网络环境的问题，我无能为力。

**Comment by SakuraYukiMF** [comment]
> 你的网络环境的问题，我无能为力。

可是我都测了一下没问题啊，访问网址都正常，网络配置协议都勾上了

**Comment by SakuraYukiMF** [comment]
> 防火墙的能力超乎你我的想象 
感谢指导，还真是防火墙，允许通关里面没有，添加进去就行了
