### ISSUE TITLE
[Question] 看详情

### ISSUE THREAD

**Issue by goldenapple1** [Scighost/Starward#147]
### Description

1.启动器菜单的启动器栏和应用设置栏图标变成了汉字？这是因为目前没有设计好图标吗？
2.为啥在原神祈愿记录为空的时候图标仍然是星铁帕姆的图标？
3.考不考虑开个赞赏什么的，我觉得作者还是比较用心的，已经star了

### Starward Version

0.8.2

### Windows Version

win10专业版 19045.3155

### Additional Context

![image](https://github.com/Scighost/Starward/assets/56142186/d75d64e9-cb00-4d4d-a498-e29c334a9a92)
![image](https://github.com/Scighost/Starward/assets/56142186/d2bc6c54-b3af-480e-b76b-5d0c9a9cf663)

**Comment by Scighost** [comment]
- 请问其他界面十分也有这种图标乱码的错误，如果有的话请截个图，我需要核对一下。
- 帕姆不可爱吗？
- 好意我心领了，等我想开赞赏的时候会加上的

**Comment by goldenapple1** [comment]
> * 请问其他界面十分也有这种图标乱码的错误，如果有的话请截个图，我需要核对一下。
> * 帕姆不可爱吗？
> * 好意我心领了，等我想开赞赏的时候会加上的

- 图标乱码暂时没有在其他地方出现
- 帕姆可爱，但是原神对应派蒙，星铁对应帕姆，从UI设计的角度来说我觉得这样更清晰直观。我刚发现这个设计的时候以为是bug，直到我看到对应的文字也改变了才发现这两个抽卡记录界面的图标是一样的。另一种解决方案是，当抽卡记录空白的时候，让居中图标和启动器logo保持一致，这个也比较能接受。
- 顺便刚发现还有个bug，原神的UID貌似没有正常抓取，显示的还是0

接下来我想探讨一个UI设计方面的问题，就是我觉得应用设置栏目的界面不太合理
![image](https://github.com/Scighost/Starward/assets/56142186/7da0c27f-6d23-47b7-9071-eee0ed3f68d4)

上图中，我觉得“打开日志文件夹”和“网络测试”这种按钮比设置副标题“日志”和“CDN”更加显眼。我的建议是让所有的设置副标题都变成按钮这种UI，然后按钮的UI变成一个圆角淡色UI，这样会让副标题更明显，方便用户更快找到自己需要的设置在哪里。

**Comment by Scighost** [comment]
麻烦再确认一下，米游社工具箱页面的这两个图标是否正常，这两个图标和上图中乱码的图标属于同一编码段，看看是否能印证我的猜测。

<img width="161" alt="image" src="https://github.com/Scighost/Starward/assets/61003590/5c42dd62-ec5a-460a-b1d9-c71c96858ff3">

**Comment by goldenapple1** [comment]
> 

你是正确的，这两个图标也出现了同样的情况

![image](https://github.com/Scighost/Starward/assets/56142186/5c605cb1-9fa6-453d-8e0e-f7c84aa50555)

**Comment by Scighost** [comment]
感谢反馈，短时间内可能不会有新版本，但是你可以通过安装 Segoe Fluent Icons 字体解决这个问题，下载链接如下：
https://aka.ms/SegoeFluentIcons

此外，我会考虑你的关于派蒙的建议。

**Comment by zhuhansan666** [comment]
所以 icon 是 UTF-8 字符?
