### ISSUE TITLE
[Bug] Icon in Launcher not show in the right way

### ISSUE THREAD

**Issue by phucho0237** [Scighost/Starward#148]
### Description

Just reinstall Starward and the error happen. I think the problem caused by system font

### Reproduction Steps

Reinstall Starward

### Screenshots

![Capture](https://github.com/Scighost/Starward/assets/88989555/effbe698-c62b-4ef5-8391-079af8ca7cdc)
![Capture2](https://github.com/Scighost/Starward/assets/88989555/6643453a-b17e-41cd-8ec0-70b3b0d9eba4)
![Capture3](https://github.com/Scighost/Starward/assets/88989555/c4bd14a2-b1bb-4233-9a9a-704155e0aaaa)

### Starward Version

0.8.2

### Windows Version

Windows 10 22H2 (OS Build 19045.2965)

**Comment by phucho0237** [comment]
Nevermind, I upgraded from Win 10 to Win 11 and the problem is fixed now.

**Comment by Scighost** [comment]
I found why the download icon displays error. Segoe MDL2 Assets on Windows 10 is version 1.79 by default, whose `\xEBD3` doesn't exist. The latest version is 1.86.

**Segoe MDL2 Assets 1.79**
<img width="116" alt="image" src="https://github.com/Scighost/Starward/assets/61003590/fbda2bae-fb80-4175-a6a9-739ae2d9c388">

**Segoe MDL2 Assets 1.86**
<img width="180" alt="image" src="https://github.com/Scighost/Starward/assets/61003590/fea583ca-8756-4ebf-bab3-95c19f1d6d90">

**Comment by phucho0237** [comment]
I tested with my other computer with Windows 10 installed, have the same error but when install [Segoe Fluent Icons](https://aka.ms/SegoeFluentIcons), the error go away. I think you should make something like automatic download & install SegoeFluentIcons when the installer come out.
