### ISSUE TITLE
[Bug] 原神更新后获取抽卡链接貌似寄了

### ISSUE THREAD

**Issue by Eric-Joker** [Scighost/Starward#149]
### Description

RT

### Reproduction Steps

- 清除URL缓存文件
- 打开原神进入抽卡历史界面
- 点击更新记录按钮

### Expected Behavior

正常读取抽卡历史

### Screenshots

![ed87351bdd6dd92ec4b55fa7e032c8a](https://github.com/Scighost/Starward/assets/60310368/c8240b77-f7d9-4325-a004-9e4440df38bb)

### Starward Version

0.8.1

### Windows Version

22621.1848

### Log

```shell
没有找到相关log，没开控制台
```

### Additional Context

嘶，要不做个通过抓包获取的备用方案？（

**Comment by Scighost** [comment]
已经聊过一轮了.jpg
https://github.com/Scighost/Starward/releases/tag/0.8.2
