### ISSUE TITLE
下载安装后，启动应用-选择语言-点击选择文件夹，未弹出文件目录至无法后续操作

### ISSUE THREAD

**Issue by animalsBeef** [Scighost/Starward#15]
下载安装后，启动应用-选择语言-点击选择文件夹，未弹出文件目录至无法后续操作
/
![图片](https://github.com/Scighost/Starward/assets/12947893/abda7ab6-c2df-427d-94ee-03f6dd124803)

**Comment by Scighost** [comment]
似乎出现了未知的错误，需要启动日志功能。

请在注册表路径 `HKEY_CURRENT_USER\Software\Starward` 中添加 DWORD 值 `EnableConsole`，将值设置为 `1`，然后重启软件，观察控制台的输出内容。

你也可以在注册表中设置数据文件夹，在上述相同的路径中添加字符串值 `ConfigDirectory`，内容设置为想要选择的文件夹。

**Comment by cqdzhengduo** [comment]
> 似乎出现了未知的错误，需要启动日志功能。
> 
> 请在注册表路径 `HKEY_CURRENT_USER\Software\Starward` 中添加 DWORD 值 `EnableConsole`，将值设置为 `1`，然后重启软件，观察控制台的输出内容。
> 
> 你也可以在注册表中设置数据文件夹，在上述相同的路径中添加字符串值 `ConfigDirectory`，内容设置为想要选择的文件夹。

刚刚在使用最新版（0.3.0）时同样出现了此问题。选择添加ConfigDirectory后能正常打开启动器，但是在设置游戏安装路径时依然发生闪退。重启后ConfigDirectory值丢失。
控制台输出内容如图
![](https://upload.cc/i1/2023/05/26/GIm9qQ.png
)
输出完上述内容后即闪退

**Comment by cqdzhengduo** [comment]
PS：在issues/8 中下载了您提供的0.2.2版本后可以正常运行和使用了……更喜欢新版的切换UI但是不敢更新

**Comment by Scighost** [comment]
似乎找到了问题，请下载这个链接的文件测试一下：
https://starward.scighost.com/release/package/dev/Starward_Portable_0.3.1-Dev.1_x64.7z

**Comment by PIut02** [comment]
试了下新的测试文件已经没问题了

**Comment by cqdzhengduo** [comment]
同样没问题了

**Comment by Viel0320** [comment]
Welcome to Starward v0.3.1-Dev.1
2023-05-30 00:26:00.372
D:\Starward\app-0.3.1-Dev.1\Starward.dll

Config Directory is NULL


win11 25375.1

**Comment by Scighost** [comment]
已修复，此 issue 关闭
