### ISSUE TITLE
[Bug] 原神设置启动器分辨率失效问题

### ISSUE THREAD

**Issue by TanVane** [Scighost/Starward#152]
### Description

![QQ截图20230707152943](https://github.com/Scighost/Starward/assets/41543274/7039b016-2c45-4c41-9471-af95d1e513d5)

![QQ截图20230707152924](https://github.com/Scighost/Starward/assets/41543274/9ca065c4-aeb2-4eff-a96b-b8b5405178ef)

### Reproduction Steps

原神设置启动器分辨率，进游戏自动还原默认分辨率

### Starward Version

0.8.2

### Windows Version

19042.508

**Comment by Scighost** [comment]
根据你的说明，我也遇到了相同的情况。同时我发现，在游戏内调整分辨率为 800x600 后，再重新启动游戏，窗口的分辨率还是 1024x768。这证明原神的窗口初始分辨率有一个最低大小，小于此值的分辨率将不会生效。
但是你可以通过把启动参数设置为 `-screen-width 800 -screen-height 600` 解决这个问题。

**Comment by Xzhao233** [comment]
原神都这样 ;D
