### ISSUE TITLE
[Feature] Additional executable

### ISSUE THREAD

**Issue by Small-Ku** [Scighost/Starward#154]
### Summary

Instead of custom start executable, launch other executable along side the game started by Starward. Keep the game timer working and able to play with something like [SRMI](https://github.com/SilentNightSound/SR-Model-Importer/) injected.

### Solution or Design

Start other executable after start the game itself

**Comment by Scighost** [comment]
Thanks for the suggestion, but I can't implement it.
Starting game is the most important feature of Starward and it should be kept as brief and stable as possible. And starting additional executable is obviously not necessary for normal gameplay. 
With the existing functionality you can define your startup process in a batch file `.bat` and then set it as the startup target.

**Comment by Small-Ku** [comment]
Thank you for explanation.
