### ISSUE TITLE
[Feature] Add Japanese translation

### ISSUE THREAD

**Issue by reindex-ot** [Scighost/Starward#155]
### Summary

Please add me to Crowdin as I will do the Japanese translation.

### Solution or Design

Japanese support

**Comment by Scighost** [comment]
Hi, @reindex-ot 
Welcome to participate in our localization group! I've added Japanese as target translation, and it would be merged into main branch once completed.

**Comment by Scighost** [comment]
Japanese translation is going to be merged into the main branch (#162). Before that, you could download artifact from [GitHub Actions](https://github.com/Scighost/Starward/actions/workflows/l10n.yml) and replace existing files of Starward. Then switch to Japanese in the setting page and check translation and layout.
