### ISSUE TITLE
[Bug] Houkai3rd cannot be executed

### ISSUE THREAD

**Issue by reindex-ot** [Scighost/Starward#158]
### Description

The game does not start due to a DLL error.

### Reproduction Steps

1. Install
2. cannot be executed (dll error)

### Starward Version

0.8.2

### Windows Version

Windows 11 (22H2) build 22621.1928

**Comment by Scighost** [comment]
Sorry, you didn't provide any useful information, so I couldn't help you.

**Comment by phucho0237** [comment]
Have you installed DirectX yet? Some DLL errors are usually caused by not having DirectX installed.

**Comment by Scighost** [comment]
I think I have fixed this issue bdb67f763f83bc7f6d0a0af9e87afde74305717f, and you could test it in the next game update.

**Comment by reindex-ot** [comment]
thx
