### ISSUE TITLE
[Bug] 原神总是出现一个“0”账号

### ISSUE THREAD

**Issue by yaxuan97** [Scighost/Starward#159]
### Description

每次启动都会出现一个'0'账号，并且被选中，必须手动切换为自己的账号。删掉也会在下次启动重新出现。

### Reproduction Steps

启动就会这样。

### Screenshots

![image](https://github.com/Scighost/Starward/assets/11773871/7e6cdf53-8b4a-498d-9e20-3b43c105f7fa)

### Starward Version

0.8.2

### Windows Version

windows 11 22H2 (22621.1928)

**Comment by XPRAMT** [comment]
我也有相同問題
![螢幕擷取畫面 2023-07-11 122439](https://github.com/Scighost/Starward/assets/34093551/e9ca536d-bec1-4ae8-9491-d62e07e24194)

**Comment by meng-ru-nan-fa** [comment]
意思是原神无法自动获取uid么，新账号都仅显示0 ？

**Comment by yaxuan97** [comment]
我尝试移除了所有账号，然后重新保存了当前帐号。
下次启动后，又会重新多一个'0'出来。

**Comment by Scighost** [comment]
@yaxuan97 如果你不想看到这个 `0`，只需要
<img width="355" alt="image" src="https://github.com/Scighost/Starward/assets/61003590/09a71bce-0b20-4190-8b43-e5e613e5a32b">

**Comment by MephistoSatanDevil** [comment]
> > 意思是原神无法自动获取uid么，新账号都仅显示0 ？
> 
> 新账号的uid都显示为0，但是**新账号**的判断依据不是uid，而是是否保存过相同的登录密钥。
> 
> 经常会出现游戏中登录的是同样的账号，但是Starward中出现了两行的情况，因为该账号的登录密钥变了。
> 
> 如果你只有一个游戏账号，不需要过多地关注切换账号的功能。

在启动器中切换账号登录似乎并不能切换游戏中登录的账号，那么这里的切换账号功能似乎没有存在的必要？

**Comment by meng-ru-nan-fa** [comment]
> > > 意思是原神无法自动获取uid么，新账号都仅显示0 ？
> > 
> > 
> > 新账号的uid都显示为0，但是**新账号**的判断依据不是uid，而是是否保存过相同的登录密钥。
> > 经常会出现游戏中登录的是同样的账号，但是Starward中出现了两行的情况，因为该账号的登录密钥变了。
> > 如果你只有一个游戏账号，不需要过多地关注切换账号的功能。
> 
> 在启动器中切换账号登录似乎并不能切换游戏中登录的账号，那么这里的切换账号功能似乎没有存在的必要？

关于原神切换账号，当我保存了2个账号A和B时，如果最后一次上号是A账号，在下次启动starward会出现账号0，则该账号0就是A账号，切换B账号正常，若再次登录A账号，则应选择账号0而非账号A，若选择账号A，登录游戏会显示未登录。
总结：最后一次登陆的账号在下次启动starward后应用账号0代替，这样可以稳定登陆。
以上均仅为我这一段时间经验总结。

**Comment by bee10301** [comment]
> 在启动器中切换账号登录似乎并不能切换游戏中登录的账号，那么这里的切换账号功能似乎没有存在的必要？

可以的，只是不能遊戲中實時切換帳號，必須重啟遊戲，主要是省略了重新輸入帳號密碼的麻煩。
基於安全設計，帳號並不是以帳號密碼的方式儲存，而是一組key存在你電腦註冊表裡，而且這組key會過期。

整個事情的流程就是：
- 啟動時、或切換頁面時（例如從崩壞切到原神）檢查當前註冊表中的key是否有存在starward中。
- 如果沒有，則添加一組「0」（因為無法獲得uid），且因為獲得的就是當前的帳號，故附上（v）
- 當你的帳號的key被米哈由更新之後，對starward來說就是新的（因為無法獲得uid）所以就會多一組「0」
- 你再硬切回原本記錄的key，當然就會顯示登出，因為那組key已經過期了，無法登入遊戲
- 所以請把原本的刪了，然後把新的那組0編輯成你想要的名字（這功能雖然很基本但真的很棒）

為何作者會說不想要0請卸了原神，那是因為只要原神記錄方式不是帳號密碼而是key，那麼就不可能得知當前key是屬於哪個帳號，而key是會過期的，也就是說當前機制中，不存在可以永久登錄一個帳號的方法，既然無法辨別uid，也就無法自動替換掉原本你打好的帳號標籤。

如果真的要一勞永逸，那麼還可以把你的密碼放在鍵盤的巨集裡，這樣不用重啟遊戲，也不用管key過不過期，花費時間應該也跟重啟遊戲差不多

**Comment by Scighost** [comment]
@bee10301 谢谢你帮忙解释清楚 (｡･ω･｡)ﾉ♡

**Comment by MephistoSatanDevil** [comment]
> > 在启动器中切换账号登录似乎并不能切换游戏中登录的账号，那么这里的切换账号功能似乎没有存在的必要？
> 
> 可以的，只是不能遊戲中實時切換帳號，必須重啟遊戲，主要是省略了重新輸入帳號密碼的麻煩。 基於安全設計，帳號並不是以帳號密碼的方式儲存，而是一組key存在你電腦註冊表裡，而且這組key會過期。
> 
> 整個事情的流程就是：
> 
> * 啟動時、或切換頁面時（例如從崩壞切到原神）檢查當前註冊表中的key是否有存在starward中。
> * 如果沒有，則添加一組「0」（因為無法獲得uid），且因為獲得的就是當前的帳號，故附上（v）
> * 當你的帳號的key被米哈由更新之後，對starward來說就是新的（因為無法獲得uid）所以就會多一組「0」
> * 你再硬切回原本記錄的key，當然就會顯示登出，因為那組key已經過期了，無法登入遊戲
> * 所以請把原本的刪了，然後把新的那組0編輯成你想要的名字（這功能雖然很基本但真的很棒）
> 
> 為何作者會說不想要0請卸了原神，那是因為只要原神記錄方式不是帳號密碼而是key，那麼就不可能得知當前key是屬於哪個帳號，而key是會過期的，也就是說當前機制中，不存在可以永久登錄一個帳號的方法，既然無法辨別uid，也就無法自動替換掉原本你打好的帳號標籤。
> 
> 如果真的要一勞永逸，那麼還可以把你的密碼放在鍵盤的巨集裡，這樣不用重啟遊戲，也不用管key過不過期，花費時間應該也跟重啟遊戲差不多
> 
> 要說這功能沒用我認為不太正確，米刷新key也不致於天天刷新，有玩兩組帳號的我就是starward這功能的受益者。

流程逻辑很明白，出现问题的原因也很明白。但是从用户的操作体验上存在问题。
我自己也同时玩着两组账号，有时时不时还会登录朋友的账号。
刷新key的问题不至于天天刷新，但是会两三天就出现这么一次。而且根据你的描述，我明白了为什么很多次登录后，它登陆进去的账号并非我选择的账号从而使我误以为“切换账号没有用”，同时，由于经常会在游戏启动后再去切换账号，会出现一个问题是，不知道当前出现的“0”账号到底是游戏过程中切换的哪个账号，也就是说出现这个问题后我应该删除哪个过期账号并把新出现的0账号改为正确的账号都不知道。

另外，根据实测，你所述
>* 當你的帳號的key被米哈由更新之後，對starward來說就是新的（因為無法獲得uid）所以就會多一組「0」
>* 你再硬切回原本記錄的key，當然就會顯示登出，因為那組key已經過期了，無法登入遊戲
是不符合实际情况的，我这边实测结果是如果硬切回原本记录的key，启动游戏后，登录的是上次启动游戏最后一次切换到的账号，而非无法登入游戏。

最关键的问题是：绝大部分玩家在实际玩游戏的过程中，玩多个米家游戏的时候，登陆原神，会在游戏中把需要登录的账号在游戏中分别切换，把该做的事情一次性做完而非退出游戏，再启动下个游戏。在启动器内进行切换，需要退出游戏再切换，费时费力，不如在游戏中切换，速度要更快一点。
所以才说“似乎没有存在的必要”。

**Comment by bee10301** [comment]
> 我这边实测结果是如果硬切回原本记录的key，启动游戏后，登录的是上次启动游戏最后一次切换到的账号，而非无法登入游戏。

我剛開始使用starard的時候切回原本帳號是會顯示登出的，不過我是切了才啟動遊戲。
如果能確認原神讀取註冊表的時機，應該是可能做到遊戲內切換的。
我之前比較懶都是直接重啟遊戲解決（因為我的密碼是用產生的隨機碼，不是用記憶的，所以對我來說直接切回starward強關原神切換帳號重啟是更快的），如果之後試了有結論再來回覆
