### ISSUE TITLE
想请教一下获取跃迁记录所需的URL链接怎么获取……

### ISSUE THREAD

**Issue by BTTLimit** [Scighost/Starward#16]
如题

**Comment by Scighost** [comment]
如果是软件的使用问题，在游戏中打开抽卡记录页面就行。

如果是开发的问题，在这个文件 `StarRail_Data\webCaches\Cache\Cache_Data\data_2` 中，找到以 `https://webstatic.mihoyo.com/hkrpg/event/e20211215gacha-v2/index.html` 开头的字符串。

**Comment by zhaoxuyang13** [comment]
请问想获取url拿去其他软件上面做抽卡分析怎么做呢。
`StarRail_Data\webCaches\Cache\Cache_Data\data_2` 这个路径的应该去哪里找？

**Comment by BTTLimit** [comment]
直接打开抽卡界面似乎不行，我最后用 Fiddler 获取了URL链接，并开了梯子才获取到跃迁数据……原因不明

**Comment by Scighost** [comment]
0.3.0 版本支持复制 URL，此 issue 关闭。
