### ISSUE TITLE
mydockerfinder中显示的两个按钮是什么东西

### ISSUE THREAD

**Issue by meng-ru-nan-fa** [Scighost/Starward#160]
### Description

按经验mydockfinder会显示一些快捷按钮，在starword为最前端程序时出现2个莫名其妙的按钮，点击之后公告界面会在活动和公告来回切换（三游均如此）。请问是什么原因？

https://github.com/Scighost/Starward/assets/72238162/5781c6b5-8a1f-4198-89d2-e7f02dd4ac62

### Starward Version

0.8.2

### Windows Version

22H2 19045.3086

**Comment by Scighost** [comment]
如你所见，这两个按键是切换游戏公告的。至于为什么会出现，我不知道，你需要去问 [MyDockFinder](https://github.com/mydockfinder/mydockfinder-for-Win10-Win11) 的开发者。
