### ISSUE TITLE
Starward会有寻空的全部功能吗？[Feature] 

### ISSUE THREAD

**Issue by yige-yigeren** [Scighost/Starward#163]
### Summary

更细致的查询，以及云上传记录的功能

### Solution or Design

祈愿记录-添加备份
旅行札记-显示图表
深渊显示所用的角色
以及成就，图鉴等功能

**Comment by Scighost** [comment]
你提到的抽卡记录备份需要提供服务端，成就、图鉴需要每个版本定期更新数据，这些功能不会加入到 Starward；
旅行札记的图表和深境螺旋的角色显示会在后续版本完成。

**Comment by yige-yigeren** [comment]
> 你提到的抽卡记录备份需要提供服务端，成就、图鉴需要每个版本定期更新数据，这些功能不会加入到 Starward； 旅行札记的图表和深境螺旋的角色显示会在后续版本完成。

也就是说Starward不会添加任何需要定期维护和需要服务端的功能？

**Comment by Scighost** [comment]
是的，我在readme中有提到这一点

<img width="535" alt="image" src="https://github.com/Scighost/Starward/assets/61003590/f17555a9-6540-48d6-9578-8589802d4a0d">
