### ISSUE TITLE
[Bug] 原神账号里总是会添加一个UID为0的账号

### ISSUE THREAD

**Issue by MephistoSatanDevil** [Scighost/Starward#170]
### Description

![QQ截图20230715100926](https://github.com/Scighost/Starward/assets/1319061/d91ae69a-9bec-4331-9b93-fb99b9b7d751)
如图所示
在启动游戏后，登录的账号都是启动器中已经保存过的账号，但是在游戏结束后退出后，在这里总是会加入一个UID为0的帐号。

### Reproduction Steps

用Starward登陆原神后，在游戏中切换过不同的账号（这些账号在Starward中都有保存）。
星铁也出现过这样的问题，但是不知道触发条件为何。

### Starward Version

0.8.3

### Windows Version

25393

### Log

[Starward_230715_074642.log](https://github.com/Scighost/Starward/files/12060097/Starward_230715_074642.log)

**Comment by Scighost** [comment]
已经聊过一轮了.jpg #159

**Comment by meng-ru-nan-fa** [comment]
> > > 意思是原神无法自动获取uid么，新账号都仅显示0 ？
> > 
> > 
> > 新账号的uid都显示为0，但是**新账号**的判断依据不是uid，而是是否保存过相同的登录密钥。
> > 经常会出现游戏中登录的是同样的账号，但是Starward中出现了两行的情况，因为该账号的登录密钥变了。
> > 如果你只有一个游戏账号，不需要过多地关注切换账号的功能。
> 
> 在启动器中切换账号登录似乎并不能切换游戏中登录的账号，那么这里的切换账号功能似乎没有存在的必要？

关于原神切换账号，当我保存了2个账号A和B时，如果最后一次上号是A账号，在下次启动starward会出现账号0，则该账号0就是A账号，切换B账号正常，若再次登录A账号，则应选择账号0而非账号A，若选择账号A，登录游戏会显示未登录。
总结：最后一次登陆的账号在下次启动starward后应用账号0代替，这样可以稳定登陆。
以上均仅为我这一段时间经验总结。

_Originally posted by @meng-ru-nan-fa in https://github.com/Scighost/Starward/issues/159#issuecomment-1637644297_
            
sir, this way.
