### ISSUE TITLE
[Bug] "Open Folder" button not working

### ISSUE THREAD

**Issue by phucho0237** [Scighost/Starward#171]
### Description

When I try to open my screenshot folder from Starward, it's not working

### Reproduction Steps

- Open "Screenshot"
- Click on "Open Folder"

### Starward Version

0.8.3-preview.1

### Windows Version

19045.3208

**Comment by Scighost** [comment]
Is there any log like this?

<img width="512" alt="image" src="https://github.com/Scighost/Starward/assets/61003590/249856c1-03d7-41a8-be2b-0ca2fc18f96d">

**Comment by phucho0237** [comment]
No, the log is: 

[21:19:13.991] [INFO] 
Welcome to Starward v0.8.3-preview.1
System: Microsoft Windows NT 10.0.19045.0
Command Line: "C:\Program Files\Starward\app-0.8.3-preview.1\Starward.dll"

[21:19:14.081] [INFO] Starward.Services.DatabaseService
Database path is 'C:\Program Files\Starward\StarwardDatabase.db'

[21:19:14.130] [INFO] Starward.Services.DatabaseService
Database version is 4, target version is 4.

[21:19:14.460] [INFO] Starward.Pages.MainPage
Select game region is hkrpg_global

[21:19:14.460] [INFO] Starward.Pages.MainPage
Navigate to "LauncherPage" with param null

[21:19:14.821] [INFO] Starward.Pages.LauncherPage
Game install path hkrpg_global: "C:\Program Files\Star Rail\Games"

[21:19:15.398] [INFO] Starward.Services.UpdateService
Start to check update (Preview: True, Arch: X64)

[21:19:15.550] [INFO] Starward.Services.UpdateService
Current version: "0.8.3-preview.1", latest version: "0.8.3-preview.1", ignore version: null

[21:19:17.753] [INFO] Starward.Pages.MainPage
Navigate to "ScreenshotPage" with param null

[21:19:17.868] [WARN] Starward.Pages.ScreenshotPage
Cannot find screenshot folder

**Comment by Scighost** [comment]
Please check whether screenshot folder `{StarRailInstallPath}\StarRail_Data\ScreenShots` exists.

**Comment by phucho0237** [comment]
I already checked, and there is no log like that

**Comment by phucho0237** [comment]
I need to manually create the "ScreenShots" folder, and the problem is fixed now
