### ISSUE TITLE
[Feature] 退出游戏时弹出

### ISSUE THREAD

**Issue by WilliamPeterMatthew** [Scighost/Starward#172]
### Summary

希望和官方启动器一样，退出游戏后可以将最小化的启动器重新弹出。

### Solution or Design

在设置中添加一个“退出游戏时弹出”选项，检测到游戏进程结束后执行还原窗口操作。

**Comment by Scighost** [comment]
好奇怪的需求，官方启动器这个弹出功能这么多人不喜欢，你却想要加进来。

**Comment by WilliamPeterMatthew** [comment]
官方启动器因为只能启动一个游戏所以我也不喜欢这个功能，但是一次性上三个游戏的班的时候退出时弹出还是会方便一点儿。

**Comment by Scighost** [comment]
弹出的功能应该不会做，这个太具有侵入性了，我会考虑使用其他的更快捷的启动游戏的方法。

**Comment by Ikeltis** [comment]
在未来mhy推出更多游戏的时候，也不会考虑这个功能吗？毕竟玩全家桶的话，一个个游戏清体力确实感觉确实挺有用的。
