### ISSUE TITLE
关于原神部分暂时无法解锁高帧率的建议

### ISSUE THREAD

**Issue by XHLiang0** [Scighost/Starward#18]
关于原神的部分启动设置项，Starward目前还不支持解锁120fps，对于我这个需要高帧原神打本、深渊的用户目前还是只能暂时只有胡桃启动器启动部分的精简版也就是之前的原神启动器plus，但是功能过于简陋，如果后续能支持那就太好了。
我看了下寻空和Starward的原神部分，理论上如果代码可复用的话，Starward可以直接使用寻空已经弄好的帧率解锁功能，而且效果也会非常好，当然了，在Starward这边，参量质变仪和洞天宝钱的检测选项就不需要留着了，可以直接精简掉，仅保留相关的帧率解锁选项就可以了。
![Snipaste_2023-05-23_23-58-27](https://github.com/Scighost/Starward/assets/90927576/9a274c1b-dde6-421c-8050-c3870abc4100)
![Snipaste_2023-05-23_23-59-41](https://github.com/Scighost/Starward/assets/90927576/0a7543fe-7031-4b4d-8a79-0de9c3da7a3d)
这是两个软件的对比，我不是很懂代码部分，但是我感觉这俩是可以相通的

**Comment by Scighost** [comment]
解锁原神的高帧率限制需要用到第三方软件，原神的版本更新可能导致第三方软件失效（比如刚刚更新的 3.7 版本），所以我不打算内置解锁帧率的功能。
但是你可以通过间接启动的方式使用第三方软件，有关间接启动参考 #17 。
