### ISSUE TITLE
Update Content (0.8.3 - Tartaglia)

### ISSUE THREAD

**Issue by Scighost** [Scighost/Starward#181]
This is update content for version [0.8.3 - Tartaglia](https://github.com/Scighost/Starward/releases/tag/0.8.3), welcome to help us translate it.

Previous version and commit: [0.8.2 - Seele](https://github.com/Scighost/Starward/releases/tag/0.8.2) 74fd4177197f947c93b52a9d2fa611aee92e8bb4

The latest commit of current version: 9df06b61ef8ebc438bdc7e8070974dce1c234e9a

**Comment by Scighost** [comment]
# 简体中文

这个版本主要改善了米游社工具箱的使用体验，还修复了崩坏三下载和更新中的一些问题，至此 Starward 已基本实现了代替米哈游官方启动器的目标。


## 功能：米游社工具箱

### 模拟宇宙

<img width="951" alt="image" src="https://github.com/Scighost/Starward/assets/61003590/81976069-80b7-4aed-9e0d-7b8ee44d5057">

### 深境螺旋的战斗记录

<img width="789" alt="image" src="https://github.com/Scighost/Starward/assets/61003590/77136d9f-8df7-4193-8922-99fbadc72880">

### 旅行者札记和开拓月历的每日数据图

<img width="789" alt="image" src="https://github.com/Scighost/Starward/assets/61003590/7fa19d23-21ed-40be-b2a9-5d07a91ccf50">


## 本地化：繁体中文 & 日语

新增繁体中文和日语的选项，感谢以下人员的贡献：

- 繁体中文： @XPRAMT @Small-Ku @MongWu-NeiTherHwoGer-Long @stevened7246
- 日语： @reindex-ot @Vermilion-Sinsha


## 其他内容

### UI/UX 相关

- 修复在部分 Windows 10 设备上出现图标乱码的问题 #61 6c38383796f324ad07022e45c56c704e09ae2e10
- 优化主页轮播图的显示效果 8ef26400620250b95df6d7df3caf23bcb397bbf3
- 米游社工具箱页面的头像增加了可点击的动画提示 a73fd3877d52cd8774286569d653eedfa237f09e
- 移除忘却之庭战斗记录卡片的背景图 7360f9a5f29e4f0c7577bafbd260b4277d6f3645
- 修复标题栏可拖动区域覆盖住下拉框的问题 3ee1eee562b27c4af529cac53980ca3dd480c203
- 新增派蒙和爱酱的表情包 acb795eb25d31244c86cf2a1b8d77afcd96c0b76
- 切换到其他页面时始终暂停播放背景视频 f9d2be4303f1412cfe6d494676596e38770d9658
- 下载和更新游戏完成后可点击已完成按钮退出 741ea75b495e31e6625f481ea345070e77952a3b

### 功能相关

- 优化切换语言时的内部方法 1122ed90f2c3ee57b4b53574fe35961c01835c12
- 支持 JEPG XL 格式的图片作为背景图（需自行安装解码组件 [jxl-winthumb](https://github.com/saschanaz/jxl-winthumb)） 73b46050365b59d44228946595b8bb3770d22aaf
- 优化计算游戏时间的过程 8f1bd14880412b56a5dd04e024d26fb7eb3bd7f8
- 修复删除最后一个抽卡记录账号时出现的绑定错误的问题 fcf47015d5c53e8035ac845cb885c3cba5b20ee7
- 修复崩坏三下载和更新的问题 bdb67f763f83bc7f6d0a0af9e87afde74305717f
- 崩坏三支持切换账号功能 5affa5f573a52f03e4143c2af72d441b6717bb70

**Comment by Scighost** [comment]
# English

This version mainly improves the experience of HoYoLAB Toolbox, and also fixes some the problem in the download and update of Honkai 3rd. Now Starward has basically reached the goal of replacing the HoYoverse official launcher .


## Feature: HoYoLAB Toolbox

### Simulated Universe

<img width="951" alt="image" src="https://github.com/Scighost/Starward/assets/61003590/81976069-80b7-4aed-9e0d-7b8ee44d5057">

### Battle Records for Spiral Abyss

<img width="789" alt="image" src="https://github.com/Scighost/Starward/assets/61003590/77136d9f-8df7-4193-8922-99fbadc72880">

### Daily Data Charts for Traveler's Diary and Trailblaze Calendar

<img width="789" alt="image" src="https://github.com/Scighost/Starward/assets/61003590/7fa19d23-21ed-40be-b2a9-5d07a91ccf50">


## Localization: Traditional Chinese & Japanese

Thanks to the following members for their contributions:

- Traditional Chinese: @XPRAMT @Small-Ku @MongWu-NeiTherHwoGer-Long @stevened7246
- Japanese: @reindex-ot @Vermilion-Sinsha


## Other content

### UI/UX

- Fixed messy icons on some Windows 10 devices #61 6c38383796f324ad07022e45c56c704e09ae2e10
- Optimize the display of the homepage rotating image 8ef26400620250b95df6d7df3caf23bcb397bbf3
- Added clickable animated tips to the avatars on the HoYoLAB Toolbox page a73fd3877d52cd8774286569d653eedfa237f09e
- Removed the background image of the Forgotten Hall battle records card 7360f9a5f29e4f0c7577bafbd260b4277d6f3645
- Fix the problem that the draggable area of the title bar covers the dropdown box 3ee1eee562b27c4af529cac53980ca3dd480c203
- Add new emotions for Paimon and Ai Hyperion acb795eb25d31244c86cf2a1b8d77afcd96c0b76
- Always pause the background video when switch to other pages f9d2be4303f1412cfe6d494676596e38770d9658
- You can click the Finished button to exit after downloading or updating the game 741ea75b495e31e6625f481ea345070e77952a3b
- Automatically fallback to the previous background image when the network is abnormal 93178a0cbf8a9b37e98f205450b1112c2fae4b4b

### Feature

- Optimize the internal method when switch languages 1122ed90f2c3ee57b4b53574fe35961c01835c12
- Support JEPG XL format image as background (Need to install codec component [jxl-winthumb](https://github.com/saschanaz/jxl-winthumb)) 73b46050365b59d44228946595b8bb3770d22aaf
- Optimize the procedure of calculating game time 8f1bd14880412b56a5dd04e024d26fb7eb3bd7f8
- Fix the binding error when deleting the last gacha records account fcf47015d5c53e8035ac845cb885c3cba5b20ee7
- Fix the problem when download and update Honkai 3rd bdb67f763f83bc7f6d0a0af9e87afde74305717f
- Switching account supports Honkai 3rd 5affa5f573a52f03e4143c2af72d441b6717bb70

**Comment by prpjzz** [comment]
**Tiếng Việt**
---
Phiên bản này chủ yếu cải thiện trải nghiệm của Hộp Công cụ HoYoLAB, đồng thời khắc phục một số sự cố trong quá trình tải xuống và cập nhật Honkai Impact 3rd. Hiện Starward về cơ bản đã đạt được mục tiêu thay thế launcher chính thức của HoYoverse.

### **Tính năng mới: Hộp công cụ HoYoLAB**
---
### **Vũ Trụ Mô Phỏng**
![image](https://github.com/Scighost/Starward/assets/89702898/4f546649-18ca-402f-a66c-ac5d49794da9)

### **Chiến Tích La Hoàn Thâm Cảnh**
![image](https://github.com/Scighost/Starward/assets/89702898/0fa1417b-cb80-4669-a3ba-b57c0141161d)

### **Nhật Kí Nhà Lữ Hành và Lịch Tháng Khai Phá**
![image](https://github.com/Scighost/Starward/assets/89702898/ab67074d-48f3-4ba9-8a9e-200733eb6e64)

![image](https://github.com/Scighost/Starward/assets/89702898/e8784517-6676-4bc9-a110-91492accfd4a)

### Bản dịch cho các ngôn ngữ: Trung Quốc Phồn Thể & Tiếng Nhật

- Tiếng Trung Phồn Thể: @XPRAMT @Small-Ku @MongWu-NeiTherHwoGer-Long @stevened7246
- Tiếng Nhật: @reindex-ot @Vermilion-Sinsha

### Thay đổi khác
---

### Giao diện và trải nghiệm của người dùng

- Giải quyết vấn đề vỡ biểu tượng trên một số thiết bị Windows 10 #61 
- 
- Bạn có thể bấm vào nút Đã hoàn thành để thoát sau khi tải hoặc cập nhật trò chơi
- Tự động chuyển về hình nền trước đó khi mạng bất thường #

 

### Tính năng

**Comment by Vermilion-Sinsha** [comment]
# 日本語
このバージョンでは、主にHoYoLABツールボックスの使用体験が向上し、崩壊3rdのダウンロードとインストールの際に起こる複数の問題も修正されました。これにて、StarwardはmiHoYo公式ランチャーを置き換える目標を基本的に達成しました。

## HoYoLABツールボックス
### 模擬宇宙
<img src="https://user-images.githubusercontent.com/61003590/254209590-81976069-80b7-4aed-9e0d-7b8ee44d5057.png" >

### 深境螺旋戦績
<img src="https://user-images.githubusercontent.com/61003590/254207782-77136d9f-8df7-4193-8922-99fbadc72880.png" >

### 旅人日記と開拓カレンダーのデイリーグラフ
<img src="https://user-images.githubusercontent.com/61003590/254208988-7fa19d23-21ed-40be-b2a9-5d07a91ccf50.png" >

## ローカライズ：繁体字中国語＆日本語
繁体字中国語と日本語を追加しました。貢献してくれた以下のメンバーに感謝します。
- 繁体字中国語：@XPRAMT @Small-Ku @MongWu-NeiTherHwoGer-Long @stevened7246
- 日本語：@reindex-ot @Vermilion-Sinsha

## その他
### UI/UX関連
- 一部Windowsデバイスでアイコンが文字化けする問題を修正 #61 https://github.com/Scighost/Starward/commit/6c38383796f324ad07022e45c56c704e09ae2e10
-  メインページのバナーカルーセルの表示を最適化 https://github.com/Scighost/Starward/commit/8ef26400620250b95df6d7df3caf23bcb397bbf3
- HoYoLABツールボックスページでアバターアイコンをクリックしたときのアニメーションを追加 https://github.com/Scighost/Starward/commit/a73fd3877d52cd8774286569d653eedfa237f09e
- 忘却の庭戦績カードの背景を削除 https://github.com/Scighost/Starward/commit/7360f9a5f29e4f0c7577bafbd260b4277d6f3645
- タイトルバーのドラッグ領域がドロップダウンメニューを隠す問題を修正 https://github.com/Scighost/Starward/commit/3ee1eee562b27c4af529cac53980ca3dd480c203
- パイモンとAIちゃんのスタンプを追加 https://github.com/Scighost/Starward/commit/acb795eb25d31244c86cf2a1b8d77afcd96c0b76
- 背景に動画を使用している場合、ページ移動時は必ず動画を一時停止するように変更 https://github.com/Scighost/Starward/commit/f9d2be4303f1412cfe6d494676596e38770d9658
- ゲームをダウンロードまたは更新した際、「完了」ボタンをクリックして終了する https://github.com/Scighost/Starward/commit/741ea75b495e31e6625f481ea345070e77952a3b
- ネットワーク接続に異常が発生した際、自動的に以前の背景画像に戻す https://github.com/Scighost/Starward/commit/93178a0cbf8a9b37e98f205450b1112c2fae4b4b

### 機能関連
- 言語変更時の内部メカニズムを最適化 https://github.com/Scighost/Starward/commit/1122ed90f2c3ee57b4b53574fe35961c01835c12
- 背景画像にJPEG XLフォーマットをサポート（[jxl-winthumb](https://github.com/saschanaz/jxl-winthumb)プラグインをインストールする必要があります）https://github.com/Scighost/Starward/commit/73b46050365b59d44228946595b8bb3770d22aaf
- プレイ時間の計算プロセスを最適化 https://github.com/Scighost/Starward/commit/8f1bd14880412b56a5dd04e024d26fb7eb3bd7f8
- 最新のガチャ記録を削除した際のバインドエラーを修正 https://github.com/Scighost/Starward/commit/fcf47015d5c53e8035ac845cb885c3cba5b20ee7
- 崩壊3rdをダウンロード・アップデートする際の問題を修正 https://github.com/Scighost/Starward/commit/bdb67f763f83bc7f6d0a0af9e87afde74305717f
- 崩壊3rdのアカウント切り替えをサポート https://github.com/Scighost/Starward/commit/5affa5f573a52f03e4143c2af72d441b6717bb70
