### ISSUE TITLE
[Question] 关于抽卡记录导入

### ISSUE THREAD

**Issue by mlrsyz** [Scighost/Starward#182]
### Description

我将其他工具的JSON记录文件按照启动器备份格式转换后导入  出现了意料外的情况
![image](https://github.com/Scighost/Starward/assets/44489042/61421c6c-7802-4e9c-a355-d9c1410d285d)

original.json是Genshin-Wish-Export插件的原始记录数据
export.json是转换后需要导入的json数据
[jsonFile.zip](https://github.com/Scighost/Starward/files/12084144/jsonFile.zip)

### Starward Version

0.8.3-preview.3

### Windows Version

19045.3086

**Comment by Scighost** [comment]
你说的意料之外的情况是指这个导入成功吗？

**Comment by mlrsyz** [comment]
> 你说的意料之外的情况是指这个导入成功吗？

是的  导入提示成功    但是启动器面板并没有统计信息显示    我不知道是为什么   这个可以提供一份json格式说明么    还是有什么特殊限制

**Comment by Scighost** [comment]
看了你提供的数据，问题原因是格式不正确，可参考 https://uigf.org/zh/standards/SRGF.html

**Comment by mlrsyz** [comment]
> 看了你提供的数据，问题原因是格式不正确，可参考 https://uigf.org/zh/standards/SRGF.html

ok  我解决了  是因为记录内部 ID 字段  由于Genshin-Wish-Export初始没记录  我设置了模拟id搞定了   thanks~
