### ISSUE TITLE
[Feature] 米游社工具箱问题和侧边栏的建议

### ISSUE THREAD

**Issue by meng-ru-nan-fa** [Scighost/Starward#186]
### Summary

1.当没有忘却之庭数据时，starward显示账号异常（账号cookie刚更新，非登录问题）；
![image](https://github.com/Scighost/Starward/assets/72238162/a72a02c1-ecd4-49f2-94a4-cbbd3a5d6e54)
2.希望可以和寻空一样保留侧边栏，方便切换。

### Solution or Design

1.我觉得应该改为“无数据”更为直观；
2.虽然作为启动器主界面需要简洁，但仍希望添加一个类似固定的按钮。
![image](https://github.com/Scighost/Starward/assets/72238162/950a3cdc-c220-4e72-a566-1eaee054a838)

**Comment by Scighost** [comment]
1、出现了**校验账号**的按键必然是有用的，你为什么不点一下试试看呢
2、不予接受
