### ISSUE TITLE
[Question] HoYoKProtect.sys会影响吗

### ISSUE THREAD

**Issue by yige-yigeren** [Scighost/Starward#189]
### Description

C:\Windows\System32\HoYoKProtect.sys
原神最近有新的反作弊，会有影响吗？
游戏时长记录功能是怎么实现的？
（其实好像直接不允许创建这个文件也没问题）

### Starward Version

0.8.3

### Windows Version

22642.1000.0

**Comment by Scighost** [comment]
没什么特别的方法，只是每秒检测进程是否退出。

**Comment by yige-yigeren** [comment]
> 没什么特别的方法，只是每秒检测进程是否退出。

草
