### ISSUE TITLE
以后会有installer或者商店版本么

### ISSUE THREAD

**Issue by Fachep** [Scighost/Starward#19]
感觉现在的版本有点像牛杂的发行方式，总有点不知道放在哪的感觉（）姑且扔program files了

**Comment by TechOtakupoi233** [comment]
追加：有无考虑支持scoop/winget/chocolately等不需要考虑放在哪的安装方式（

**Comment by Scighost** [comment]
等图标做出来后会出一个安装版（install/setup），暂时还没想好是放在 Program Files 中还是 AppData 中。

安装版出来以后也不需要考虑放在哪儿了

**Comment by PangYanze** [comment]
不喜欢便携版的软件，要么就不知道放哪去了（开始菜单也搜不到），要么就像是牛杂那样卸载都很麻烦。我还是喜欢安装版本的，可以用geek uninstaller等软件直接管理，反而方便一些。还有，催一下图标。

**Comment by CharliePu** [comment]
> 等图标做出来后会出一个安装版（install/setup），暂时还没想好是放在 Program Files 中还是 AppData 中。
> 
> 安装版出来以后也不需要考虑放在哪儿了
> 
> 补充：不会上架微软商店

请问安装版还会考虑吗？

**Comment by InTka** [comment]
> 等图标做出来后会出一个安装版（install/setup），暂时还没想好是放在 Program Files 中还是 AppData 中。
> 
> 安装版出来以后也不需要考虑放在哪儿了
> 
> 补充：不会上架微软商店

2025了安装版会出吗
毕竟这Starward会在AppData\Local留东西
某种意义上来讲其实不够绿色，要是删除的时候忘了删除%LocalAppData%\Starward里的东西就永远留在那里了~
而且AppData还是默认隐藏的文件夹，平常也不会翻看
![Image](https://github.com/user-attachments/assets/e66c88f9-00c9-477b-a4eb-2c39faa3844b)

**Comment by RealHeart** [comment]
已PR到scoop games bucket https://github.com/Calinou/scoop-games/pull/1508
可以使用Scoop安装了
```
scoop bucket add games
scoop install starward
```

**Comment by ANTIQUE91** [comment]
> 已PR到scoop games bucket [Calinou/scoop-games#1508](https://github.com/Calinou/scoop-games/pull/1508) 可以使用Scoop安装了
> 
> ```
> scoop bucket add games
> scoop install starward
> ```


@RealHeart 这个log文件好像还在老家呆着
<img width="1208" height="1085" alt="Image" src="https://github.com/user-attachments/assets/7c4099ad-f2e8-4445-8443-16a728fad7af" />

<img width="128" height="128" alt="Image" src="https://github.com/user-attachments/assets/14ecc11c-d822-4ed8-accc-c52952e946d1" />

**Comment by RealHeart** [comment]
AppData的目录无法持久化，也没有对应设置可以修改路径

> > 已PR到scoop games bucket [Calinou/scoop-games#1508](https://github.com/Calinou/scoop-games/pull/1508) 可以使用Scoop安装了
> > 
> > ```
> > scoop bucket add games
> > scoop install starward
> > ```
> 
> 
> @RealHeart 这个log文件好像还在老家呆着
> <img width="1208" height="1085" alt="Image" src="https://github.com/user-attachments/assets/7c4099ad-f2e8-4445-8443-16a728fad7af" />
> 
> <img width="128" height="128" alt="Image" src="https://github.com/user-attachments/assets/14ecc11c-d822-4ed8-accc-c52952e946d1" />
