### ISSUE TITLE
[Bug] 开拓月历异常

### ISSUE THREAD

**Issue by legxd** [Scighost/Starward#193]
### Description

开拓月历显示账号异常，请先登录，没有按钮，其他的都可以

### Reproduction Steps

![开拓月历](https://github.com/Scighost/Starward/assets/39611681/e9878a23-fd3d-4422-9f18-ecaee20a81d0)

### Expected Behavior

开拓月历异常

### Screenshots

开拓月历异常

### Starward Version

0.8.3

### Windows Version

0.8.3

### Log

```shell
开拓月历异常
```

### Additional Context

开拓月历异常

**Comment by Scighost** [comment]
<img width="207" alt="image" src="https://github.com/Scighost/Starward/assets/61003590/c0ac8bfb-7517-4dc4-9692-fdc1e7ca706b">

**Comment by legxd** [comment]
点击登录/输入cookie挑战mihayou主界面没有问题，一点开拓月历或者开拓月历的刷新/获取明细按钮就会报错
![image](https://github.com/Scighost/Starward/assets/39611681/00387bab-0562-4d5b-a0c8-854f5770a1ab)

**Comment by Scighost** [comment]
如果你是重新登录后仍然出现了账号异常的错误，建议你多多使用米游社消除账号被风控的问题。
