### ISSUE TITLE
[Feature] 可提供国内速度较快的下载

### ISSUE THREAD

**Issue by qianxinwanjiu** [Scighost/Starward#194]
### Summary

考虑到软件之后可能会面向小白群体，国内下载可能受影响
可以联系我这边有几个方案
邮箱yang761847613@outlook.com

### Solution or Design

国内下载增强

**Comment by Scighost** [comment]
谢谢你对本项目的关注，如果有什么好的解决方案，不妨就发在这里。

**Comment by qianxinwanjiu** [comment]
建议添加国内速度较快的源，例如微软存储等，可提供稳定A1P账号存储

**Comment by Scighost** [comment]
OneDrive 只是一个网盘，并不专门用于分发文件大规模使用必然有一定的限制。请问你提供的账号

- 是世纪互联运营的还是微软运营的
- 是否有权限使用 OneDrive API
- 每日可使用的下载次数和流量是多少

**Comment by qianxinwanjiu** [comment]
账号存储由微软运营，有权限使用OneDrive API，可用下载次数和流量暂不清楚
或者尝试一下cloudreve所建网盘，已被许可使用，此方案仅供尝试，可行后可实装
![IMG_20230722_230110](https://github.com/Scighost/Starward/assets/111267078/268153ab-e8bb-4354-8da9-03ce5f22a9d1)

**Comment by Scighost** [comment]
微软运营的 OneDrive 在中国大陆地区没有服务器，各省的网络体验不一致，不适合用作文件分发服务。
