### ISSUE TITLE
[Feature] Genshin Impact Convert Client

### ISSUE THREAD

**Issue by prpjzz** [Scighost/Starward#195]
### Summary

According to my research, Genshin Impact Global and Chinese versions don't have much difference, especially in the StreamingAsset folder, game data of the two versions can be shared, so hopefully you can support this feature in the future.

### Solution or Design

As some of the tools I used to know, like "Snap Hutao", you could use some way to back up old Genshin Impact Global files to some directory (e.g. Starward's folder) and then copy the files from the Chinese version. then interfere with the pkg_version file to change the MD5 code of the specified files or download a Chinese version of pkg_version file and copy it directly to the directory containing Genshin.

**Comment by Scighost** [comment]
Thanks for your suggestion. As you said, Genshin's files verification method does make switching between China and Global servers very easy. But I wouldn't use the backup file method because I can't be sure when a backed up file should be deleted. The exact implementation should be merged with the existing feature of repairing the game.

**Comment by prpjzz** [comment]
This is the file that I extracted from two versions of the game. You can take a look.
I am not sure whether the Audio_Chinese_pkg_version, Audio_Japanese_pkg_version and Audio_Korean_pkg_version files are correct in both versions, because I did not install this language pack in the device.

https://z3lkb-my.sharepoint.com/:u:/g/personal/prpjzz_z3lkb_onmicrosoft_com/EZLYbR1mSSRBs4C5ifYBcxgB5iEvwc91t-BQ8_keI6tkhA?e=wnEaDk

You can check it out. However in the next version (V4.0), there may be some more different files in both versions, I will try to update as soon as possible.
