### ISSUE TITLE
[Feature] 跃迁记录中添加常驻/限定五星单位区分

### ISSUE THREAD

**Issue by TremblingMoeNew** [Scighost/Starward#198]
### Summary

方便在大多数情况下识别大小保底（确信

UP常驻单位的情况就摆烂吧（

### Solution or Design

可以从官方的跃迁详情数据页获取常驻单位列表（

国服这边的是`https://webstatic.mihoyo.com/hkrpg/gacha_info/prod_gf_cn/{gacha_id}/{lang}.json`，常驻池子的id似乎一直没变一直是`ad9815cdf2308104c377aac42c7f0cdd8d`

**Comment by Scighost** [comment]
容我拒绝。
如果要准确的展示大小保底，唯一的办法是定期维护卡池数据，这个定期可能是每次扩充常驻池时维护一次。即使很长时间才需要维护一次，但我还是觉得麻烦。
另外，不同游戏的抽卡功能共用的是一个页面模板，如果星铁支持了大小保底原神也要支持，再考虑到绝区零，后续的工作更多了。
