### ISSUE TITLE
[Feature] Installer for launcher

### ISSUE THREAD

**Issue by ItsukaHiro** [Scighost/Starward#202]
### Summary

Uh... I just want to simplify how to install launcher.

### Solution or Design

[None]

**Comment by Scighost** [comment]
You should download package from release page and unzip it, then run `Starward.exe`.

**Comment by ItsukaHiro** [comment]
> You should download package from release page and unzip it, then run `Starward.exe`.

I know, but I'd like to use installer, much ezer for most of people (and way faster for some who just reinstall their entire system :V)

**Comment by ChuotBuhhh** [comment]
where's the "Starward.exe" file? 

> Bạn nên tải xuống gói từ trang phát hành và giải nén nó, sau đó chạy `Starward.exe`.

**Comment by phucho0237** [comment]
> where's the "Starward.exe" file?
> 
> > Bạn nên tải xuống gói từ trang phát hành và giải nén nó, sau đó chạy `Starward.exe`.

Download it from Release

**Comment by ChuotBuhhh** [comment]
![image](https://github.com/Scighost/Starward/assets/144521542/24194db6-76af-41b8-b68a-6477676df71a)
I don't see it

**Comment by ItsukaHiro** [comment]
> ![image](https://github.com/Scighost/Starward/assets/144521542/24194db6-76af-41b8-b68a-6477676df71a)
> I don't see it 
> 

Not the source code.

**Comment by ChuotBuhhh** [comment]
> > ![image](https://user-images.githubusercontent.com/144521542/270154977-24194db6-76af-41b8-b68a-6477676df71a.png)
> > I don't see it
> 
> Not the source code.

but all zip is source

**Comment by ItsukaHiro** [comment]
Download 7z file. Choose the right 7z based on your cpu architecture.
7z is also a kind of zip file.

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by Scighost** [comment]
Installer feature will continue to be tracked in #204.

**Comment by ChuotBuhhh** [comment]
thanks
