### ISSUE TITLE
[Bug] Cannot update Warp Record [Honkai: Star Rail]

### ISSUE THREAD

**Issue by phucho0237** [Scighost/Starward#205]
### Description

I'm already opened Star Rail gacha records history page in game, but it's keep saying "Cannot find URL, please open the gacha records history page in game."

### Reproduction Steps

- Open "Warp Records" function in the launcher
- Open "Gacha History" in game
- Click on "Update Records" in the launcher, then the error happened

### Screenshots

![image](https://github.com/Scighost/Starward/assets/88989555/46653c8f-d20d-4e73-aa98-f8e18ac25881)

### Starward Version

0.8.4-preview.1

### Windows Version

Windows 10 22H2 (Build 19045.3208)

**Comment by prpjzz** [comment]
Exit the game, then see if this path exists? (StarRail_Data\webCaches\2.14.0.0\Cache\Cache_Data\data_2)

Is there an additional folder named 2.14.0.0 in the WebCaches folder?

If so, try opening the data_2 file with notepad, and then look for the word "gacha" to get the link to the gacha history web that you need.

**Comment by phucho0237** [comment]
> Exit the game, then see if this path exists? (StarRail_Data\webCaches\2.14.0.0\Cache\Cache_Data\data_2)
> 
> Is there an additional folder named 2.14.0.0 in the WebCaches folder?
> 
> If so, try opening the data_2 file with notepad, and then look for the word "gacha" to get the link to the gacha history web that you need.

Thank you for your response. I tried it and it works. But I think the Starward app have a problem.
