### ISSUE TITLE
[Bug] File zf_cef.dll is corrupted

### ISSUE THREAD

**Issue by GaotingNaiye1** [Scighost/Starward#208]
### Description

![6565](https://github.com/Scighost/Starward/assets/107612106/6baa3142-b2c0-4833-b5b5-e1cb23f4ad06)

### Reproduction Steps

用启动器打开星穹铁道就会出现这种情况，之前0.8.3这样，这次更新到了开发版也是这样，我是win11系统，重复过好多次，在两台不同的电脑上都出现过，不知道为啥。

### Screenshots

![6565](https://github.com/Scighost/Starward/assets/107612106/19f34063-a5bc-4491-9ef8-b77ca7495f34)

### Starward Version

0.8.4

### Windows Version

22621.1992

**Comment by KomoriDev** [comment]
我下载时也遇到了这个情况，使用官方下载器解决了

**Comment by GaotingNaiye1** [comment]
> 我下载时也遇到过这种情况，使用官方下载器解决了

但是使用官方下载器没法获取抽卡记录这些

**Comment by Scighost** [comment]
已知的原因是解压过程中发生了文件损坏，但是考虑到之前版本没有这个问题，并且相关代码没有变动，我怀疑是 .NET 最近引入的 Bug，这个猜测需要进一步验证。

此外，请补上 issue 标题。

**Comment by KomoriDev** [comment]
> > 我下载时也遇到过这种情况，使用官方下载器解决了
> 
> 但是使用官方下载器没法获取抽卡记录这些

不会。使用官方下载器下载后，将其中的 `Game` 文件夹复制，放于 Starward 同级，命名为 `StarRail`（事实上，`Game` 文件夹就是 星铁 的本体，其他的都是下载器需要的文件），然后打开 Starward ，将安装位置改为 `StarRail` ，直接用 Starward 打开。

**Comment by GaotingNaiye1** [comment]
> 

感谢，这个方法是可行的

**Comment by Scighost** [comment]
> 已知的原因是解压过程中发生了文件损坏，但是考虑到之前版本没有这个问题，并且相关代码没有变动，我怀疑是 .NET 最近引入的 Bug，这个猜测需要进一步验证。

经验证，是我的代码的问题，而不是 .NET Runtime 的问题，已在 [0.8.4 Preview 2](https://github.com/Scighost/Starward/releases/tag/0.8.4-preview.2) 中修复。
