### ISSUE TITLE
[Feature] 添加半透明背景

### ISSUE THREAD

**Issue by Xzhao233** [Scighost/Starward#209]
### Summary

我认为应该添加一个类似Windows Vista和Windows 7中的Aero的半透明的背景

### Solution or Design

我认为应该添加一个类似Windows Vista和Windows 7中的Aero的半透明的背景
开启的选项应该放在设置中的使用另一个背景选项的附近（好像是叫这个吧）
开启的效果应该是半透明半纯白的色调（类似于磨砂材质？）
当然，如果实现难的化就当我没说吧 :D

**Comment by Scighost** [comment]
不难，但是不好看

<img width="789" alt="image" src="https://github.com/Scighost/Starward/assets/61003590/166ad247-2c58-418a-94a4-346f931287a6">
