### ISSUE TITLE
似乎是bug还是什么

### ISSUE THREAD

**Issue by lacunes** [Scighost/Starward#21]
设置页面非常卡且选项不全
![image](https://github.com/Scighost/Starward/assets/52728445/570dfa74-3630-44b1-9f40-bf846a10d52f)

**Comment by Fachep** [comment]
改帧率的正常现象

**Comment by Scighost** [comment]
修改帧率后的正常现象

**Comment by lacunes** [comment]
> 修改帧率后的正常现象
后面会修复的吗QAQ

**Comment by Fachep** [comment]
这是游戏的问题。。。你得看m打不打算开放pc端的120帧了

**Comment by lacunes** [comment]
> 这是游戏的问题。。。你得看m打不打算开放pc端的120帧了
az
