### ISSUE TITLE
[Feature] 抽卡记录界面希望可以优化一下

### ISSUE THREAD

**Issue by GaotingNaiye1** [Scighost/Starward#211]
### Summary

在抽卡记录很多的情况下，当前的抽卡记录没法在同一页显示，查看起来很不方便，如图
![3333355555](https://github.com/Scighost/Starward/assets/107612106/44242137-545c-4831-9cac-88b348edc344)

### Solution or Design

建议参考其它抽卡导出工具的排列样式来优化。

![image](https://github.com/Scighost/Starward/assets/107612106/dd74ea62-945e-4cf8-aba1-0126e4ed99c0)

类似于红框里面这种就比较紧凑，或者用寻空的样式也可以

![image](https://github.com/Scighost/Starward/assets/107612106/90121fb8-567b-47b3-a73a-cc0caabc272f)

**Comment by Scighost** [comment]
大概率就是这个界面，不会再变了。

**Comment by prpjzz** [comment]
I think just add a scrollbar in each area if there are more characters or weapons displayed on the screen.
