### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by PropitiousSun** [Scighost/Starward#214]
### Description

崩铁忘却之庭 账号异常1034

### Reproduction Steps

崩铁忘却之庭刷新不出来

### Screenshots

[](url)
![QQ截图20230728103230](https://github.com/Scighost/Starward/assets/120573583/37a69a7f-c7c3-4bbc-b93b-692a31c9cb45)

### Starward Version

0.8.4

### Windows Version

win10 22H2

**Comment by Scighost** [comment]
Closed for no title or content.
