### ISSUE TITLE
[Feature] 祈愿记录可以加入对非小酋导出的excel数据的导入支持吗？

### ISSUE THREAD

**Issue by g1fts** [Scighost/Starward#219]
### Summary

[非小酋](https://feixiaoqiu.com/index/)
默认只有json的导入，非小酋到处的excel转json对应的键值对跟这边的也有很大区别。

### Solution or Design

有没有对应的转换工具啥的？

**Comment by Scighost** [comment]
Excel 不适合作为在应用程序间交换数据的格式，不会考虑支持。

**Comment by AlbertWen-AW** [comment]
不如建议非小酋改用UIGF的json的格式来导出导入：https://uigf.org/zh/   。 目前七八个第三方工具都支持了，还有成就的UIAF也是，接入已有规范不是还能更好推广么
