### ISSUE TITLE
Update Content (0.9.0 - Kafka)

### ISSUE THREAD

**Issue by Scighost** [Scighost/Starward#220]
This is update content for the next version, welcome to help us translate it.

Previous version and commit: [0.8.3 - Tartaglia](https://github.com/Scighost/Starward/releases/tag/0.8.3) https://github.com/Scighost/Starward/commit/9df06b61ef8ebc438bdc7e8070974dce1c234e9a

(This comment doesn't need to translate)

## Roadmap

- Logo
- System tray

**Comment by goldenapple1** [comment]
好耶，终于有logo了

**Comment by studiobuttermedia** [comment]
** Lộ Trình
- Logo
- Chạy dưới thanh công cụ

**Comment by Scighost** [comment]
# 简体中文

**祝开拓者们都能顺利抽到卡芙卡！**

很高兴地宣布这一版本给大家带来了非常大的使用体验的改善，下面由我一一道来。

## Starward Logo (待定)

历经三个多月，我终于做出来了一个简单的 Logo（又不是不能用）。在此期间，有许多人分享了他们的设计方案，我把这些建议全部汇总到了 #242，感谢你们的贡献。如果以后有了更好的设计，这个 Logo 将会被替代。

<img src="https://user-images.githubusercontent.com/61003590/258953393-beabf661-e905-4184-a6ed-73c61a499cfa.png" width="400px" />


## 系统托盘

有了 Logo 之后，就可以实现系统托盘功能了。首先你需要在设置页面开启**系统托盘图标**。

<img width="174" alt="image" src="https://github.com/Scighost/Starward/assets/61003590/8ef5e796-feb7-48a0-a0f2-a4507bc8d719">

之后你会在桌面右下角发现一个新图标（因为系统限制，首次开启时这个图标会被隐藏到左边的箭头中），右键点击可以看到快速启动游戏的选项。托盘存在时 Starward 将会以单例模式运行，此时运行新的进程将会被重定向到已存在的进程。上面那个橙色的 Logo 是下载器进程的图标，用不同的颜色和主进程区分开。

<img width="165" alt="image" src="https://github.com/Scighost/Starward/assets/61003590/e91d91f5-6b22-4c43-b904-bb03f1f16ba2">

<img width="169" alt="image" src="https://github.com/Scighost/Starward/assets/61003590/1b65644d-f3ef-4fd3-a14c-aa378c6627af">


## 抽卡记录

抽卡记录页面做出了如下改进：

- 加入了物品图片
- 为五星物品新增更直观的保底进度条
- 加入了四星物品的出货记录
- 加入了每个物品的出货次数统计
- 支持修改现有记录的语言

下面用一个视频简单展示一下这些功能

https://github.com/Scighost/Starward/assets/61003590/c2ffa2dc-d626-443a-95d4-d2b60ede229b


## 游戏时间

新版本重新设计了启动游戏的流程，现在**崩坏3**和**自定义启动程序**都支持记录游戏时间。但是仍有一些限制，崩坏3需要在启动后 20s 内出现游戏窗口，否则不会记录此次游戏的时间；自定义启动程序需要在 10s 内启动游戏本体进程。


## 小技巧

Starward 中存在一些正常使用过程中很难发现的隐藏功能，比如转换游戏客户端，为此我加入了小技巧这一主题。
[链接在此](https://github.com/Scighost/Starward/blob/main/docs/Tips.zh-CN.md)，也可以在 Starward 中点击相关按键跳转。


## 其他

- 修复安装游戏时的解压缩问题 #208
- 提前适配后续版本的抽卡记录缓存变动
- 新增隐私策略
- 新增游戏截图和个人数据库的备份操作
- 其他的文本和 UI 改进

**Comment by phucho0237** [comment]
## Tiếng Việt

**Chúc các Nhà khai phá may mắn trong công cuộc roll Kafka ❤**

Tôi vui mừng thông báo rằng bản phát hành này mang lại những cải tiến đáng kể cho trải nghiệm của bạn.

## Biểu tượng Starward (đang chờ)

Sau hơn ba tháng, cuối cùng tôi cũng đã tạo ra một biểu tượng đơn giản (không phải là không sử dụng được). Trong giai đoạn này, rất nhiều người đã chia sẻ các đề xuất thiết kế của họ và tôi đã tóm tắt tất cả các đề xuất này trong #242. Cảm ơn những đóng góp của bạn. Nếu có một thiết kế tốt hơn trong tương lai, biểu tượng này sẽ được thay thế.

<img src="https://user-images.githubusercontent.com/61003590/258953393-beabf661-e905-4184-a6ed-73c61a499cfa.png" width="400px" />


## Khay hệ thống

Với logo, tính năng khay hệ thống đã có thể thực hiện. Trước tiên, bạn cần bật **Biểu tượng khay hệ thống** trong trang cài đặt.

![image](https://github.com/Scighost/Starward/assets/88989555/ccb031af-da5f-4a2b-b0f0-9c2f3bf744ce)

Sau đó, bạn sẽ tìm thấy một biểu tượng mới ở góc dưới cùng bên phải của màn hình nền (do hạn chế của hệ thống, biểu tượng này sẽ bị ẩn trong mũi tên bên trái khi bật lần đầu) và nhấp chuột phải để xem tùy chọn nhanh để bắt đầu trò chơi. Khi khay tồn tại, Starward sẽ chạy ở chế độ đơn lẻ và việc chạy một tiến trình mới sẽ được chuyển hướng đến một tiến trình hiện có. Biểu tượng màu cam ở trên là biểu tượng của tiến trình tải xuống, được phân biệt với tiến trình chính bằng màu khác nhau.

![image](https://github.com/Scighost/Starward/assets/88989555/8c1328bf-9886-4ba8-9d54-4c93cee0354a)

![image](https://github.com/Scighost/Starward/assets/88989555/296688bd-d73f-4e1c-a70b-d0f3515234b2)


## Bản ghi gacha

Trang bản ghi gacha đã được cải thiện:

- Thêm hình ảnh vật phẩm
- Thêm thanh tiến trình trực quan cho vật phẩm 5 sao
- Hiển thị bản ghi đã thu thập được về vật phẩm 4 sao
- Thêm số liệu thống kê về số lượng đã đạt được cho từng vật phẩm
- Hỗ trợ chuyển đổi ngôn ngữ của các bản ghi hiện có

Dưới đây là một video để chứng minh ngắn gọn các tính năng này:

https://github.com/Scighost/Starward/assets/61003590/ecfc3732-724f-4f77-b532-4d1fd586a6b6


## Thời gian chơi

Phiên bản mới đã thiết kế lại quy trình khởi chạy trò chơi và hiện tại **Honkai Impact 3rd** và **Chương trình thực thi tùy chỉnh** đều hỗ trợ ghi lại thời gian chơi. Tuy nhiên, vẫn còn một số hạn chế: cửa sổ chính của Honkai Impact 3 sẽ xuất hiện trong vòng 20 giây sau khi khởi động, nếu không thời gian chơi sẽ không được ghi lại; quá trình trò chơi sẽ bắt đầu trong vòng 10 giây sau khi khởi động chương trình thực thi tùy chỉnh.


## Mẹo
Có một số tính năng ẩn trong Starward khó tìm thấy trong quá trình sử dụng thông thường, chẳng hạn như chuyển đổi ứng dụng khách trò chơi, vì vậy tôi đã thêm một tài liệu có tên Mẹo.
[Link ở đây](https://github.com/Scighost/Starward/blob/main/docs/Tips.vi-VN.md), hoặc bạn có thể nhấn vào nút Mẹo ở Starward.


## Thay đổi khác

- Sửa lỗi giải nén khi cài đặt trò chơi #208
- Thích ứng với thay đổi bộ đệm ghi lại lịch sử gacha trong tương lai
- Thêm [chính sách bảo mật](https://github.com/Scighost/Starward/blob/main/docs/Privacy.vi-VN.md)
- Thêm thao tác sao lưu ảnh chụp màn hình và cơ sở dữ liệu cá nhân
- Các cải tiến về văn bản và giao diện người dùng khác
