### ISSUE TITLE
[Feature] Genshin Impact Game Config

### ISSUE THREAD

**Issue by prpjzz** [Scighost/Starward#221]
### Summary

I hope you bring this feature into Starward Launcher.

### Solution or Design

Because Genshin Impact saves application settings through Registry, specifically at HKCU\Software\miHoYo\Genshin Impact (Global version), and HKCU\Software\miHoYo\原神 (CN Ver), all settings are stored at the "GENERAL_DATA_h2389025596" key.

**Comment by Scighost** [comment]
Genshin's settings are indeed saved in the registry, but its data model is very complex. I have no energy to implement this feature.
