### ISSUE TITLE
[Bug] 游戏更新时将页面放在后台会有卡住的情况

### ISSUE THREAD

**Issue by Jasumin** [Scighost/Starward#224]
### Description

更新星穹铁道时把更新页面放在后台过一段时间下载大小、下载速率和剩余时间不动，但进度条仍有特效且整个更新界面可以拖动

### Reproduction Steps

打开Starward-选择更新游戏-放置在后台-稍等一会-卡住

### Screenshots

https://github.com/Scighost/Starward/assets/25867464/5c270213-c58a-43ff-95d5-03391790b412

### Starward Version

0.8.4-preview.2

### Windows Version

22621.1992

**Comment by Scighost** [comment]
从日志中看不出来问题在哪。问一下，你遇到这个卡住的情况后，点击暂停键是否有反应，点击关闭键是否弹出提示。

**Comment by Jasumin** [comment]
> 从日志中看不出来问题在哪。问一下，你遇到这个卡住的情况后，点击暂停键是否有反应，点击关闭键是否弹出提示。

都有的，而且点击暂停再点继续（还是开始来着）就会又继续下载一段时间。

**Comment by Scighost** [comment]
新版本中重写了下载功能，此 issue 将关闭，如果仍存在问题，请重新提 issue 。
