### ISSUE TITLE
[Question] Blur or Transparent

### ISSUE THREAD

**Issue by prpjzz** [Scighost/Starward#225]
### Description

I'm not sure if this is a mistake, so I'm just asking here the question.

Instead of blurting out other menus like settings, Starward on my device is transparent on other menus. For example, in the photo.

![image](https://github.com/Scighost/Starward/assets/89702898/f5e7f335-42d4-4607-9ab8-2202f32bafc4)

### Starward Version

0.8.4-preview.2

### Windows Version

19044.3086

**Comment by Scighost** [comment]
Hi, you should enable `Transparency effects` in system settings.

<img width="392" alt="image" src="https://github.com/Scighost/Starward/assets/61003590/e156b9de-e94b-4889-a5c9-cac9913a2142">

**Comment by prpjzz** [comment]
Okay, I Fixed.


On Windows 10: Settings -> Personalization -> Colors -> Transparency effects
