### ISSUE TITLE
[Feature] One instance of Starward only

### ISSUE THREAD

**Issue by phucho0237** [Scighost/Starward#229]
### Summary

I think Starward should only have 1 window and there will be a message like: "Starward is now running, press yes to return to the window or press no to restart the app" if you open Starward while it's running

### Solution or Design

- If Starward already runnning, show a dialog box like I mentioned

**Comment by Scighost** [comment]
Thanks for your suggestion.
Starting from 0.9.0-preview.1, when you enable `System Tray Icon`, it would only exists one instance of Starward. However, according my test, if I start a game and then run Starward, the redirection operation failed. I need time to resolve the bug.

**Comment by Scighost** [comment]
The bug is traced in #235, this issue will be closed.
