### ISSUE TITLE
关于抽卡记录

### ISSUE THREAD

**Issue by xingmen** [Scighost/Starward#23]
感觉抽卡界面不好看，已经抽了多少发都看不出来，寻空的直观

**Comment by Iwax12458** [comment]
我也想要类似寻空的那种，可以看自己垫了多少发四星

**Comment by Scighost** [comment]
<img width="221" alt="image" src="https://github.com/Scighost/Starward/assets/61003590/a9067d2e-91f7-4cd2-8939-fef76e9fb860">

来来来，跟着我看，从上到下分别是：

- 池子总共多少抽
- 四星垫了多少抽
- 五星垫了多少抽
- 五星平均多少抽

**Comment by Iwax12458** [comment]
我的，没看懂抱歉

**Comment by xingmen** [comment]
好吧是我没看懂
