### ISSUE TITLE
[Bug] Screenshot index number overlapped with window title in the screenshot viewing screen

### ISSUE THREAD

**Issue by TinLite** [Scighost/Starward#230]
### Description

As the title says, screenshot index text overlapped with window title.  
I'm able to reproduce this on both the preview version and stable version. Behaviours are slightly different between stable and preview version, see the screenshots section for comparison.  
Not sure if this problem exists on HI3rd or GI. I only have HSR installed.

### Reproduction Steps

1. Open Starward.
2. Open the navigation menu, navigate to Screenshots screen.
3. Open any screenshot.

### Expected Behavior

Everything is clear.

### Screenshots

Above is stable version, below is preview version. Behaviours are slightly different: stable version's title text a little bit darker than the preview version.
![image](https://github.com/Scighost/Starward/assets/37470201/6da85db8-d326-4cb9-9d33-20c4e1ba37e1)

### Starward Version

Stable 0.8.3 and 0.9.1 Preview 1

### Windows Version

Windows 11 23H2 (Build 22631.2129)

### Additional Context

My device enrolled in Windows Insider program, and Microsoft introduced a bunch of UI redesigns recently so hopefully they're not the cause of this.

**Comment by Scighost** [comment]
Thanks for your feedback. It occurs because the logo is above all other UI elements. I will fix it latter.
