### ISSUE TITLE
[Question] 

### ISSUE THREAD

**Issue by I-love-Nahida** [Scighost/Starward#236]
### Description

![{1B962FD0-713F-4c65-9F73-7673F2B066B6}](https://github.com/Scighost/Starward/assets/120999873/cd6aaa22-699c-4bd9-9d1d-55ab6fb52370)
![{230AD7B4-ACC6-4597-9818-323FCD339C5D}](https://github.com/Scighost/Starward/assets/120999873/aab6682d-cef4-4785-8e35-4403cbfde081)
[QQ202387-134242.zip](https://github.com/Scighost/Starward/files/12272557/QQ202387-134242.zip)

### Starward Version

0.9.0

### Windows Version

22621.2070

**Comment by Scighost** [comment]
Closed for no title or content.
