### ISSUE TITLE
[Feature] 建议新增关闭主界面程序在任务栏运行

### ISSUE THREAD

**Issue by jerryjoejj** [Scighost/Starward#237]
### Summary

点击右上角×号关闭程序后，提醒用户程序是否最小化到右下角任务栏或者直接关闭程序，并且可以选择下次关闭是否继续提醒。如果选择了最小化到任务栏，则点击×号后最小化到右下角任务栏，点击应用图标可以唤起。

### Solution or Design

点击右上角×号关闭程序后，提醒用户程序是否最小化到右下角任务栏或者直接关闭程序，并且可以选择下次关闭是否继续提醒。如果选择了最小化到任务栏，则点击×号后最小化到右下角任务栏，点击应用图标可以唤起。

**Comment by Scighost** [comment]
在最新版的程序逻辑中，系统托盘功能需要在设置页面手动开启。用户启用这个功能后，自然能理解点击关闭按键后，程序会最小化到系统托盘，不再需要你建议的提醒步骤。
