### ISSUE TITLE
[Improvement] 图标改进

### ISSUE THREAD

**Issue by PanSongyang** [Scighost/Starward#238]
### Summary

![image](https://github.com/Scighost/Starward/assets/79133624/138b893a-b302-4589-91c0-45f217b3eea5)
图标外层有一圈白边，图标内蓝色主体边缘似乎也有白边；图标只有一种大小

### Solution or Design

修一下白边，适配更多大小的图标

**Comment by Scighost** [comment]
现在图标的分辨率是 64x64，下图左侧是 64x64，右侧是 128x128，可以看出图标大小没有变化（系统缩放率150%）。但是右侧图标的白边更不明显，我猜测是分辨率提高后边缘显示效果更好。我会在下个版本发布前让图标文件包含更多的分辨率。

<img width="183" alt="image" src="https://github.com/Scighost/Starward/assets/61003590/db851740-3da1-4014-929f-6159ac7f3b0f">
