### ISSUE TITLE
[Feature] 国内更新源

### ISSUE THREAD

**Issue by weold957** [Scighost/Starward#239]
### Summary

有考虑使用国内更新源吗

### Solution or Design

如果可以的话，我手里有闲置的服务器可以提供使用

**Comment by Scighost** [comment]
谢谢你的建议，但是我不想备案正在使用的域名，所以不能解析到大陆境内的 IP。

**Comment by weold957** [comment]
> 谢谢你的建议，但是我不想备案正在使用的域名，所以不能解析到大陆境内的 IP。

如果需要也有已备案的域名提供使用

**Comment by Scighost** [comment]
抱歉，我没有在中国大陆地区使用 CDN 的计划。
