### ISSUE TITLE
星铁未运行却依旧提示运行中

### ISSUE THREAD

**Issue by Iwax12458** [Scighost/Starward#24]
这是不是bug啊

**Comment by Iwax12458** [comment]
![Uploading image.png…]()

**Comment by Iwax12458** [comment]
![image](https://github.com/Scighost/Starward/assets/134679716/40201df5-ae69-40ee-aa3a-111feb90746f)

**Comment by Scighost** [comment]
下次遇到这种情况请在任务管理器中检查是否有名为 `StarRail.exe` 的进程正在运行。
