### ISSUE TITLE
[Feature] 可以相对或者个性化增强米友社工具么?

### ISSUE THREAD

**Issue by mlrsyz** [Scighost/Starward#241]
### Summary

可以增强米友社工具么 例如体力,素材等固定资源展示

### Solution or Design

关于游戏工具的支持我知道是比较麻烦的   如果大佬有这方面的想法    有可能针对设计一套插件模板么?
让有能力的人对接[Starward]插件模板去个性化增强功能 这一点能极大的扩展生态
很多云崽机器人的核心玩法就是插件 如果最终能制定一套插件系统 会变的有趣丰富
当然这个需求会比较复杂 希望大佬能考虑一下

**Comment by Scighost** [comment]
谢谢你的建议，但是我本人没有开发插件系统的经验，这个需求可能不会被实现。
