### ISSUE TITLE
[Feature] 窗口左侧常驻菜单小图标

### ISSUE THREAD

**Issue by Xuan0cheng** [Scighost/Starward#243]
### Summary

类似这样的？
![QQ截图20230808102503](https://github.com/Scighost/Starward/assets/40588325/5f7f2203-1a17-4c61-9d1e-f035baa46afd)
或许可以增加一些操作上的便捷性

### Solution or Design

平常的时候就仅展示小图标，点击即可切换到对应页面，点左上角菜单按钮的时候就展开显示详细信息

**Comment by Scighost** [comment]
[Collapse 的最新预览版](https://github.com/neon-nyan/Collapse/releases/tag/CL-v1.71.5-pre) 使用的就是这种设计，我个人认为这种菜单占据窗口侧边的设计不是很好，整个启动器界面缺少了沉浸感。
