### ISSUE TITLE
Some images in Tips.md

### ISSUE THREAD

**Issue by Scighost** [Scighost/Starward#244]
Please unsubscribe this issue!

**Comment by Scighost** [comment]
<img width="789" alt="image" src="https://github.com/Scighost/Starward/assets/61003590/8ae65395-58a3-48b0-a1e8-8e2cf6e351f7">

<img width="789" alt="image" src="https://github.com/Scighost/Starward/assets/61003590/3b7bab3c-4d94-4450-ada6-7b9aaad9e92e">

**Comment by Scighost** [comment]
<img width="186" alt="image" src="https://github.com/Scighost/Starward/assets/61003590/9fffe2ec-056f-495c-8840-1a3672e7be3c">

<img width="187" alt="image" src="https://github.com/Scighost/Starward/assets/61003590/7d67e320-6e7e-469e-b404-58669f42491f">

**Comment by phucho0237** [comment]
![image](https://github.com/Scighost/Starward/assets/88989555/d84e7feb-9949-454c-9c46-c9bc77c1ea3a)

**Comment by phucho0237** [comment]
> <img alt="image" width="789" src="https://user-images.githubusercontent.com/61003590/259001799-8ae65395-58a3-48b0-a1e8-8e2cf6e351f7.png"> <img alt="image" width="789" src="https://user-images.githubusercontent.com/61003590/259002026-3b7bab3c-4d94-4450-ada6-7b9aaad9e92e.png">

@Scighost, can you help me upload this picture in Vietnamese?

**Comment by Scighost** [comment]
@phucho0237 

<img width="789" alt="image" src="https://github.com/Scighost/Starward/assets/61003590/907934e2-29fd-46ee-8e1c-83cb1daaa143">
