### ISSUE TITLE
游戏选择界面还会继续优化么

### ISSUE THREAD

**Issue by acgcc** [Scighost/Starward#25]
选择游戏的地方，选中一个另一个看着就跟遗照一样，太出戏了

**Comment by Scighost** [comment]
这不让你看得更清楚选中的是哪个游戏嘛

**Comment by TPAXcc** [comment]
> 这不让你看得更清楚选中的是哪个游戏嘛

可以把灰度调到 10%-30% 就行，纯黑白多少有点

**Comment by Scighost** [comment]
已优化，此 issue 关闭
