### ISSUE TITLE
[Bug] 更新0.9.0后程序无法启动

### ISSUE THREAD

**Issue by Apocalypse233** [Scighost/Starward#253]
### Description

Starward更新到0.9.0后就无法启动。事件查看器中记录有一个.NET Runtime错误和一个Application Error错误，以及一个Windows Error Reporting事件。每次尝试启动都会产生一次三个事件，详情分别如下：

**事件1026，.NET Runtime**
> Application: Starward.exe
CoreCLR` Version: 7.0.1023.36312
.NET Version: 7.0.10
Description: The process was terminated due to an unhandled exception.
Exception Info: System.BadImageFormatException: 试图加载格式不正确的程序。 (0x8007000B)
   at Starward.Program.Main(String[] args) in D:\a\Starward\Starward\Starward\Program.cs:line 41

**事件1000，Application Error**
> 错误应用程序名称: Starward.exe，版本: 0.9.0.0，时间戳: 0x64b07659
错误模块名称: KERNELBASE.dll，版本: 10.0.19041.3155，时间戳: 0xbf300201
异常代码: 0xe0434352
错误偏移量: 0x000000000002cf19
错误进程 ID: 0x3c18
错误应用程序启动时间: 0x01d9cad4eea54fa3
错误应用程序路径: D:\Starward\app-0.9.0\Starward.exe
错误模块路径: C:\WINDOWS\System32\KERNELBASE.dll
报告 ID: ce26271a-d158-4206-807d-961c21ce1ae2

**事件1001，Windows Error Reporting**
> 故障存储段 1993961892164807039，类型 4
事件名称: APPCRASH
响应: 不可用
Cab ID: 0
问题签名:
P1: Starward.exe
P2: 0.9.0.0
P3: 64b07659
P4: KERNELBASE.dll
P5: 10.0.19041.3155
P6: bf300201
P7: e0434352
P8: 000000000002cf19
P9: 
P10: 
附加文件:已上传
[AppCrash_Starward.exe_ebce7376bcf61a3e7f461ce64544fb6239ea8b7_08f66437_5ad1081f-7d3b.wer.txt](https://github.com/Scighost/Starward/files/12304473/AppCrash_Starward.exe_ebce7376bcf61a3e7f461ce64544fb6239ea8b7_08f66437_5ad1081f-7d3b.wer.txt)
分析符号: 
重新检查解决方案: 0
报告 ID: ce26271a-d158-4206-807d-961c21ce1ae2
报告状态: 268435456
哈希存储段: 0368f71d1e6bf5e56babf9c6c626297f
Cab GUID: 0

### Reproduction Steps

分别尝试点击\Starward\Starward.exe或\Starward\app-0.9.0\Starward.exe均没有反应。
\Starward目录下已添加过config.ini文件，删除该文件还是无法启动。

### Starward Version

0.9.0

### Windows Version

19045.3208

**Comment by Scighost** [comment]
尝试过重新下载 Release 页面的压缩包吗

**Comment by Apocalypse233** [comment]
> 尝试过重新下载 Release 页面的压缩包吗

感谢，重新下载替换后正常运行， 估计是app内热更时文件损坏了。
