### ISSUE TITLE
是否可以增加一个页面，以便在无需切换页面的情况下进入不同游戏？

### ISSUE THREAD

**Issue by CLAIRE-WAR** [Scighost/Starward#254]
### Summary

感觉可以增加一个页面，同时列出米哈游所有pc端的游戏，并可以在这个界面中进行更新以及进入游戏。
因为占据当前启动器界面极大页面的信息资讯，实际上是个使用频率颇低的功能，我想大多数人使用启动器的目的主要依旧是启动游戏本体，而目前的模式会增加操作步骤。

### Solution or Design

![58411ed949642e2e426aa25a2f8083a2](https://github.com/Scighost/Starward/assets/138675401/c9e409fe-aed1-4fcb-91dc-71916fc851bd)

类似于这样，将三个游戏同时放在一个页面中以便启动，如果用户需要查看版本资讯或者欣赏海报，再进入详情页面即可。
点击左上菜单键后，随着游戏变化而改变的功能栏。则可以通过增加点击对应游戏窗口的空白处选中对应游戏（而不切换到详细页面）的方式切换。
这一整合页面所用海报可以选用三个游戏中最近更新的游戏，或者随着用户选择而改变(或者同时）。
又或者将清晰与模糊的方式和上面例图反过来，使用最近更新的游戏的版本海报并模糊，而三个小窗口则截取对应游戏的版本海报。
只是个人的期望，如有冒犯，十分抱歉orz

顺便试着给目前选用的logo做了一个带文字的横版，不过好像也不是很好看.....如果有需要可以用orz

![starward-logo版本5](https://github.com/Scighost/Starward/assets/138675401/7a5b5905-46f4-449e-9a42-a4965d55c567)

**Comment by Scighost** [comment]
谢谢你的建议，我认为你可以通过托盘图标实现这个需求。

在设置页面开启托盘图标

<img width="188" alt="image" src="https://github.com/Scighost/Starward/assets/61003590/f05b04fd-1257-49e1-9bcd-054ee2e77e0d">

<img width="145" alt="image" src="https://github.com/Scighost/Starward/assets/61003590/115fa0ed-60c1-40a0-b99a-c501f9aa3be6">

**Comment by CLAIRE-WAR** [comment]
> 谢谢你的建议，我认为你可以通过托盘图标实现这个需求。
> 
> 在设置页面开启托盘图标
> 
> <img alt="图像" width="188" src="https://user-images.githubusercontent.com/61003590/259622748-f05b04fd-1257-49e1-9bcd-054ee2e77e0d.png"> <img alt="图像" width="145" src="https://user-images.githubusercontent.com/61003590/259622794-115fa0ed-60c1-40a0-b99a-c501f9aa3be6.png">

原来现在有个这个功能啊，那请问有没有内置的开机启动呢？如果有的话大大提升开使用验了，开机后直接右击选择，感觉会很爽

**Comment by CLAIRE-WAR** [comment]
感觉也可以在此基础上加入二级菜单，无需打开启动器本体就能直接查看抽卡记录等等

**Comment by xinyihl** [comment]
自启可以自己加
`reg add HKEY_CURRENT_USER\SOFTWARE\Microsoft\Windows\CurrentVersion\Run /v Starward /t REG_SZ /d "你的安装地址\Starward.exe" `这个会有uac
`schtasks /create /sc ONLOGON /tn Starward /tr "你的安装地址\Starward.exe" /rl highest`这个不会报uac

**Comment by Scighost** [comment]
> 那请问有没有内置的开机启动呢？

托盘功能依赖于主窗口实现，启动时必定会出现一个窗口，放在开机启动项中体验不是很好，不会内置此设置项。

> 感觉也可以在此基础上加入二级菜单，无需打开启动器本体就能直接查看抽卡记录等等

托盘右键菜单那点地方放不下其他的功能，加入其他的功能也会拖慢菜单的显示速度。
