### ISSUE TITLE
[Bug] 星穹铁道跃迁记录无法导出excel

### ISSUE THREAD

**Issue by meng-ru-nan-fa** [Scighost/Starward#255]
### Description

![image](https://github.com/Scighost/Starward/assets/72238162/be5114be-3858-429d-9516-f40cd5e6cec0)
如图，并且json导出正常

### Reproduction Steps

设置→导出为Excel

### Starward Version

0.9.0

### Windows Version

22H2 19045.3086

**Comment by Scighost** [comment]
谢谢反馈，下个版本修复。
