### ISSUE TITLE
[Feature] 自定义背景支持显示游戏 Logo

### ISSUE THREAD

**Issue by 1625423178** [Scighost/Starward#258]
### Summary

在开启【自定义背景】功能后，支持在启动器主页左上角显示当前选中游戏的 Logo。
After the [Custom Background] function is enabled, the logo of the currently selected game is displayed in the upper left corner of the launcher home page.

### Solution or Design

（效果如下图）
(The effect is shown below)
![1691829804481](https://github.com/Scighost/Starward/assets/115442729/fc35be83-38a0-4dd4-ba92-447f8606010c)

**Comment by Scighost** [comment]
谢谢你的建议，我看了半天竟然没发现左上角的游戏 logo 有什么问题，像是本来就在这儿一样。

**Comment by Scighost** [comment]
很遗憾地告诉你，因为各游戏 Logo 的分辨率和长宽比不同的原因，在自定义图片上展示游戏 Logo 的显示效果不理想，很难做到在同一个位置上显示相同大小的 Logo。所以我决定放弃实现这个需求。
