### ISSUE TITLE
[Question] 每次打开都要重新输入账号密码

### ISSUE THREAD

**Issue by FlameFires** [Scighost/Starward#259]
### Description

在更新到 0.9.0 之后，每次打开应用都需要重新输入账号密码，请问下这个问题如何解决呢？

### Starward Version

0.9.0

### Windows Version

22621.1992

**Comment by Scighost** [comment]
这个问题和 Starward 无关，和米哈游服务器的账号验证策略有关。如果你不使用账号切换功能，Starward 是不会修改你的已登录账号凭据的。
