### ISSUE TITLE
程序闪退无法运行，程序第一次使用 点击“选择文件夹”闪退。

### ISSUE THREAD

**Issue by XiaoMiaoICa** [Scighost/Starward#26]
![image](https://github.com/Scighost/Starward/assets/120804480/7ea5b24b-cfad-4844-9bc1-dfff9537d8a8)
图内点击“选择文件夹”后直接出现闪退情况

![Desktop Screenshot 2023 04 14 - 19 29 40 63](https://github.com/Scighost/Starward/assets/120804480/4b8f118e-5fd5-4eaa-905c-179400b9d006)
尝试修改注册表依然无法运行

**Comment by XiaoMiaoICa** [comment]
![image](https://github.com/Scighost/Starward/assets/120804480/d119415d-6d84-4550-b65b-cdc126141c7a)

**Comment by Scighost** [comment]
反馈的问题和这个 issue #15 很像，后续请在 #15 中讨论，此 issue 关闭。
