### ISSUE TITLE
[Feature] 可以增加个关闭游戏后自动弹出

### ISSUE THREAD

**Issue by trupure** [Scighost/Starward#261]
### Summary

可以增加个关闭游戏后自动弹出功能，在勾选后可以检测到游戏关闭后弹出窗口

### Solution or Design

可以和系统托盘的那个一样供用户选择

**Comment by Scighost** [comment]
重复的 issue #172

**Comment by trupure** [comment]
> 虽然我也觉得挺奇怪，但是确实有人因为这个放弃
![CUZZV%)9L0D@EX6(05KWC0O](https://github.com/Scighost/Starward/assets/107930791/79dce89c-2409-4515-a8ff-9b9a05d72fa3)

**Comment by XYY1411** [comment]
> > 虽然我也觉得挺奇怪，但是确实有人因为这个放弃
> > ![CUZZV%)9L0D@EX6(05KWC0O](https://user-images.githubusercontent.com/107930791/260280315-79dce89c-2409-4515-a8ff-9b9a05d72fa3.png)

完全可以做成自选功能啊

**Comment by Scighost** [comment]
只能说 Starward 与他无缘
