### ISSUE TITLE
[Feature] 抽卡记录没有显示歪没歪

### ISSUE THREAD

**Issue by lijian12345** [Scighost/Starward#263]
### Summary

现在的抽卡记录只显示了多少抽出的

### Solution or Design

可以考虑加个开关显示歪没歪，快速判断自己是不是非酋，不想看的玩家也可以关闭这个开关

**Comment by Scighost** [comment]
判断小保底歪没歪需要定期更新卡池信息，我不会选择增加自己的维护负担。

**Comment by lijian12345** [comment]
> 判断小保底歪没歪需要定期更新卡池信息，我不会选择增加自己的维护负担。

感觉只需要判断是否抽出常驻池的角色就行了吧，常驻池更新频率也不是很高

**Comment by Scighost** [comment]
> 感觉只需要判断是否抽出常驻池的角色就行了吧，常驻池更新频率也不是很高

你说得对，但是我不会选择增加自己的维护负担。
