### ISSUE TITLE
[Feature] 抽卡记录支持Excel导入以及能显示当前游戏区服

### ISSUE THREAD

**Issue by witcheng1024** [Scighost/Starward#264]
### Summary

1. 当前抽卡记录只支持json文件导入，希望可以添加Excel格式文件导入
2. 如图，当前实际客户端是国际服，但我通过标题栏改为国服，界面展示仍和国际服一致。导致我只有点击开始游戏才知道当前是什
么服。

![QQ截图20230813190947](https://github.com/Scighost/Starward/assets/109953026/f311e4d0-4b51-47c1-b9f2-a35228bc90db)

### Solution or Design

1. 添加Excel格式文件导入
2. 添加显示当前服务器
![image](https://github.com/Scighost/Starward/assets/109953026/d5253fdc-4f22-4f1d-beec-03a5fad9a258)

**Comment by Scighost** [comment]
谢谢你的建议

1. Excel 导入的功能见 #89 
2. 同样的，Starward 也无法得知当前客户端是哪个服务器
