### ISSUE TITLE
[Bug] 原神抽卡紀錄的綺良良頭像似乎不存在

### ISSUE THREAD

**Issue by dase1353** [Scighost/Starward#266]
### Description

原神抽卡紀錄的綺良良頭像似乎不存在

### Reproduction Steps

僅更新抽卡紀錄

### Expected Behavior

綺良良頭像應該要出現

### Screenshots

![image](https://github.com/Scighost/Starward/assets/46934514/4e8b673e-d7b3-41a4-80d5-0f9170e72dc1)

### Starward Version

0.9.0

### Windows Version

22621.2134

**Comment by Scighost** [comment]
换个网络重启试试

**Comment by dase1353** [comment]
好的 我這次是在我公司的電腦(請不要在意公司)
綺良良的頭像仍沒有出現
![image](https://github.com/Scighost/Starward/assets/46934514/e254f975-e67a-4d3f-83d4-c2981f94d39a)

**Comment by Scighost** [comment]
接下来的操作需要你会简单使用数据库管理工具：

- 使用数据库管理工具打开 `StarwardDatabase.db`
- 在表 `GenshinGachaItem` 中找到绮良良的抽卡记录，记下其 `ItemId` 的值
- 在表 `GenshinGachaInfo` 中找到绮良良的数据，对比其 `Id` 是否和上述 `ItemId` 一致，并把 `Icon` 中的链接在浏览器中打开

**Comment by Lightczx** [comment]
绮良良头像需要特殊处理
[UI_AvatarIcon_Momoka.png](https://github.com/DGP-Studio/Snap.Static/blob/main/AvatarIcon/UI_AvatarIcon_Momoka.png)
@Scighost

**Comment by Scighost** [comment]
> 绮良良头像需要特殊处理 [UI_AvatarIcon_Momoka.png](https://github.com/DGP-Studio/Snap.Static/blob/main/AvatarIcon/UI_AvatarIcon_Momoka.png) @Scighost

不是这个原因，我使用的是米游社的图片，不需要特殊处理

**Comment by Scighost** [comment]
Closed for long time no reply.
