### ISSUE TITLE
[Feature] Crowdin 添加韩文翻译任务吧

### ISSUE THREAD

**Issue by DE2SSE** [Scighost/Starward#268]
### Summary

Crowdin 添加韩文翻译任务吧

###

**Comment by Scighost** [comment]
谢谢，我已经添加了

**Comment by Scighost** [comment]
韩语翻译已合并到主分支，你可以在 GitHub Actions 中下载最新编译的翻译文件，替换本地文件并检查翻译和布局的问题。
https://github.com/Scighost/Starward/actions/workflows/l10n.yml
