### ISSUE TITLE
希望可以添加抽卡统计

### ISSUE THREAD

**Issue by Akizon77** [Scighost/Starward#27]

**Comment by Akizon77** [comment]
像寻空一样，统计一下五星和四星
<img width="718" alt="Snipaste_2023-05-27_12-40-10" src="https://github.com/Scighost/Starward/assets/64686663/0791470b-5a71-460c-884f-749660825914">

**Comment by Scighost** [comment]
实现这样的界面需要定期维护角色和光锥的图片数据，我不会加入增加自己维护负担的功能。
