### ISSUE TITLE
[Feature] CDN

### ISSUE THREAD

**Issue by qweasd945** [Scighost/Starward#270]
### Summary

能不能加一个中国的CDN呢，每次启动都要挂VPN。

### Solution or Design

。

**Comment by Scighost** [comment]
我负担不起在大陆地区使用 CDN 的费用

**Comment by qweasd945** [comment]
> 

没有免费的吗？

**Comment by Scighost** [comment]
如果你愿意为了 CDN 付费，那在我这儿不久免费了吗。
