### ISSUE TITLE
[Feature] Limit downloading speed/限制下载速率

### ISSUE THREAD

**Issue by Fachep** [Scighost/Starward#272]
### Summary

![${I8QWMBTTT 3CTXBJE%`3Y](https://github.com/Scighost/Starward/assets/31302548/4d100251-8073-4b1c-b482-2f7b44d84deb)
希望能添加下载速率的限制功能，现在感觉比steam都能吃，啥网页都打不开了直接

### Solution or Design

-

**Comment by Scighost** [comment]
6，也就十几分钟，忍一忍就过去了

**Comment by EdenLeaf** [comment]
但是我的家庭网速很慢，上限只有10MB，所以没有下载速率限制真的很难受

**Comment by EdenLeaf** [comment]
> 6，也就十几分钟，忍一忍就过去了

但是像我家里下载速度上限就10MB/s，没有限制下载速率的选项真的很难受，好几个小时家里啥都用不了，所以还是拿官方启动器更新的

**Comment by Scighost** [comment]
我的能力不足以做到在多线程下载时限制下载速度，你们可以借用第三方软件实现此需求。
