### ISSUE TITLE
[Feature] 软件设置快速返回

### ISSUE THREAD

**Issue by ILikeLayla** [Scighost/Starward#276]
### Summary

在设置界面可以增加一个退出设置的按钮，按下就返回到当前游戏的页面。现在需要双击游戏图标或者在菜单栏中选择启动器才能返回。

### Solution or Design

可以在应用设置界面的右下角放置一个固定的退出按钮，然后弹出是否保存的对话框

**Comment by Scighost** [comment]
冒昧地问一下，您是有什么设备或身体上的原因无法完成双击操作吗？或者您认为您的建议相比于现有的操作逻辑有什么优点？

**Comment by ILikeLayla** [comment]
> 冒昧地问一下，您是有什么设备或身体上的原因无法完成双击操作吗？或者您认为您的建议相比于现有的操作逻辑有什么优点？

我认为这样是更加符合逻辑的。当用户完成了他所有的更改后，此时他（她）的鼠标应该是靠近底部的，因此在底部增加一个返回的按钮可以为用户节省一些“路程”。此外，当用户只是修改了某个或某些设置但是没有划到页面的底部时，右下角固定的按钮也可以为用户节省“路程”。

当然，我这个提议是建立在用户修改完设置后的鼠标是停留在底部的。不排除有只修改顶部设置或者修改完后停留在顶部的可能性。

**Comment by Scighost** [comment]
抱歉，我拒绝此功能请求。
