### ISSUE TITLE
导入抽卡记录后提示条幅一直存在

### ISSUE THREAD

**Issue by MaxwellYe0815** [Scighost/Starward#28]
# 描述
提示导入抽卡记录成功的条幅不会自动关闭，切换界面也一直存在，直到手动关闭。
# 复现
## 操作
更新抽卡记录
## 复现概率
每次
# Starward版本
0.3.1-Dev.1
# 系统版本
Windows 10 22H2
# 截图
![image](https://github.com/Scighost/Starward/assets/64358442/a20e04c9-c515-4d19-87dc-ba9cfccb7d9c)
![image](https://github.com/Scighost/Starward/assets/64358442/723df26a-89bc-4e0b-b2c8-2f0ab164035f)

**Comment by Scighost** [comment]
你说得对，但是点个×就能关闭
