### ISSUE TITLE
无法下载崩三[Bug] 

### ISSUE THREAD

**Issue by 9523140211** [Scighost/Starward#280]
### Description

无法下载崩三

### Reproduction Steps

点击安装游戏
选择安装文件夹
选择后再次点击安装游戏出现以下
![屏幕截图 2023-08-17 133135](https://github.com/Scighost/Starward/assets/125105053/c3c2a1ea-cca7-429a-8413-e54efedc7935)
无法继续

### Starward Version

0.9.0

### Windows Version

22621.2134

**Comment by Scighost** [comment]
重复的问题 #278
