### ISSUE TITLE
[Feature] 祈愿记录查看不方便

### ISSUE THREAD

**Issue by GaotingNaiye1** [Scighost/Starward#282]
### Summary

![image](https://github.com/Scighost/Starward/assets/107612106/1bd24861-c7fe-42b1-8ac3-25f3af196f51)

### Solution or Design

如图，角色祈愿记录太多的话就展示不下了，建议借鉴其它工具的方式，如图，红框里面这样展示就比较直观，当然有别的方法也行，弄到一页就好。
![image](https://github.com/Scighost/Starward/assets/107612106/242d7c0a-51c6-433a-bae0-eff2ac074194)

**Comment by Scighost** [comment]
谢谢你的建议，但是我不会考虑使用上图所示的展示抽卡记录的方法。
