### ISSUE TITLE
[Feature] 一些很杂的建议。

### ISSUE THREAD

**Issue by 1625423178** [Scighost/Starward#283]
### Summary

# Chinese 简体中文

1. [[Feature] 自定义背景支持显示游戏 Logo #258](https://github.com/Scighost/Starward/issues/258)
2. 可设置当检测到游戏已退出时，唤起最小化到托盘的 Starward 主界面，类似官方启动器的“退出游戏时弹出”开关。
3. 在切换到非启动器页时，针对 [快速返回到启动器页面](https://github.com/Scighost/Starward/blob/main/docs/Tips.zh-CN.md#%E5%BF%AB%E9%80%9F%E8%BF%94%E5%9B%9E%E5%88%B0%E5%90%AF%E5%8A%A8%E5%99%A8%E9%A1%B5%E9%9D%A2) 功能在顶部标题栏给予提示。
4. 针对活动祈愿记录，支持判断祈愿结果是否为当期UP奖励，并在抽数前显示。（如针对《原神》的角色活动祈愿，当抽中的五星角色非 琴、莫娜、迪卢克 等，则在抽数前显示“UP“标识(提纳里、迪希雅等UP过的常驻池角色需稍加注意)。）
5. 禁止对 原神-旅行者札记、崩铁-开拓月历 中历史每日数据折线图的缩放操作。
6. 游戏截图页：
  (1)查看截图详情时，滚动鼠标滚轮的操作改为放大与缩小截图，而非查看上一张或下一张截图。
  (2)对于非16:9比例的截图，预览居中显示，而非居左显示。
  (3)增加快捷键支持：ESC返回游戏截图主页，方向键查看上一张或下一张截图。

（暂时就这么多叭，想到了再发issue。）
（有了Starward我都很少启动官方启动器了，动画生硬功能还少，从阿B了解到的，支持支持！）

# English

1. [[Feature] Custom background support to display game Logo #258](https://github.com/Scighost/Starward/issues/258)
2. It can be set to call up the Starward main screen minimized to the tray when it detects that the game has exited, similar to the "eject when exiting the game" switch of the official launcher.
3. When switching to a non-launcher page, prompt in the top title bar for the [Quickly return to launcher page](https://github.com/Scighost/Starward/blob/main/docs/Tips.md#quickly-return-to-launcher-page) feature.
4. For the activity wish record, it supports judging whether the wish result is the current UP reward, and displays it before number of wishes. (For example, for the character activity wish of Genshin Impact, when the five-star character drawn is not Jean, Mona, Diluc, etc., the "UP" logo is displayed before the number of wishes (The resident wish character that have been UP, such as Tighnari and Dehya, need a little attention).）
5. Prohibit for Genshin Impact and Honkai: Star Rail 's Traveler Daily data line chart's zoom.
6. Game Screenshot Page:
  (1)When viewing the screenshot details, the mouse wheel scrolling operation is changed to zoom in and out of the screenshot instead of viewing the previous or next screenshot.
  (2)For screenshots with a ratio other than 16:9, the preview is centered instead of left.
  (3)Added shortcut key support: ESC to return to the game screenshot home page, arrow keys to view the previous or next screenshot.

(That's all I can think of for the moment, I'll post another one when I think of new advise.）
(With Starward I rarely start the official launcher, animation blunt and function is still less. I found out about this program through BiliBili, thank you!）

### Solution or Design

阿巴阿巴...

none :(

**Comment by Scighost** [comment]
谢谢你的建议，如果下次仍有许多建议，每条建议请单独创建一个 issue。

> 2. 可设置当检测到游戏已退出时，唤起最小化到托盘的 Starward 主界面，类似官方启动器的“退出游戏时弹出”开关。

启动游戏后，为了减少资源占用，最小化到任务栏或托盘的 Starward 进程没有实时检测正在运行的游戏，无法得知游戏何时退出，做不到退出时弹出。

> 3. 在切换到非启动器页时，针对 [快速返回到启动器页面](https://github.com/Scighost/Starward/blob/main/docs/Tips.zh-CN.md#%E5%BF%AB%E9%80%9F%E8%BF%94%E5%9B%9E%E5%88%B0%E5%90%AF%E5%8A%A8%E5%99%A8%E9%A1%B5%E9%9D%A2) 功能在顶部标题栏给予提示。

我认为没有必要，我也不知道如何设计一个不突兀的提示，欢迎提出你的设计方案。

> 4. 针对活动祈愿记录，支持判断祈愿结果是否为当期UP奖励，并在抽数前显示。（如针对《原神》的角色活动祈愿，当抽中的五星角色非 琴、莫娜、迪卢克 等，则在抽数前显示“UP“标识(提纳里、迪希雅等UP过的常驻池角色需稍加注意)。）

判断大小保底需要定期维护卡池信息，我不会给自己增加维护负担。

> 5. 禁止对 原神-旅行者札记、崩铁-开拓月历 中历史每日数据折线图的缩放操作。

这个图标的缩放不是我能控制的。

> 6. 游戏截图页

请提供一下你说的左对齐的截图。

**Comment by 1625423178** [comment]
![image](https://github.com/Scighost/Starward/assets/115442729/edbff704-d99f-4c6a-ace5-9399d42db232)
任意一张非16:9的截图均无法居中预览，此图为19:9。
（神奇的是，这个问题已经在 Starward 0.9.1-Preview.1 版本不再出现，发布此 issue 时最新版本为 0.9.0-Kafka 。）
（鞠躬.jpg）
