### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by 954150714** [Scighost/Starward#284]
### Description

Can not use the toolbox function, neither web login nor cookies
![20230819123022](https://github.com/Scighost/Starward/assets/93700304/5fc575b0-bbf9-4156-a462-087197193ffb)

### Reproduction Steps

1：Web landing

2：
Go to Miyoushe on my browser and Login
Open Dev Tools -> Console -> type document.cookie and copy all data
Open Starward -> Set CN Server on Star Rail and go to Hyperion Toolbox
Click Login -> Input Cookie

### Screenshots

![20230819123022](https://github.com/Scighost/Starward/assets/93700304/51623766-37b8-4a46-885a-54facc177240)

### Starward Version

0.9

### Windows Version

Windows 10  22H2 19045.2965

**Comment by Scighost** [comment]
Closed for no title or content.
