### ISSUE TITLE
[Bug] Can not use the toolbox function, neither web login nor cookies

### ISSUE THREAD

**Issue by 954150714** [Scighost/Starward#285]
### Description

Both web login and cookie login prompt network error，Please help me！
![20230819123022](https://github.com/Scighost/Starward/assets/93700304/604c4c66-6ce3-423c-82c1-5881087c41a8)

### Reproduction Steps

Login via web

Go to Miyoushe on my browser and Login
Open Dev Tools -> Console -> type document.cookie and copy all data
Open Starward -> Set CN Server on Star Rail and go to Hyperion Toolbox
Click Login -> Input Cookie

### Starward Version

0.9

### Windows Version

19045.2965

**Comment by Scighost** [comment]
米游社和 HoYoLAB 本就是完全独立的两个账号系统，你用米游社的 Cookie 去登录 HoYoLAB 必然会出错。
此外，HoYoLAB 限制了中国大陆的 IP 访问。
