### ISSUE TITLE
[Feature] 通过服务自启动来避免UAC弹窗

### ISSUE THREAD

**Issue by SBBTD** [Scighost/Starward#286]
### Summary

目前启动游戏时会显示UAC提示框，Starward已经有单例和后台运行了，希望能设置Starward开机自启动，通过Windows服务方式可实现无UAC弹窗的管理员权限，这样启动游戏时就也不会弹UAC了

### Solution or Design

通过Windows服务方式自启动，可实现无UAC弹窗的管理员权限

**Comment by Eric-Joker** [comment]
https://github.com/Scighost/Starward/issues/95

**Comment by Scighost** [comment]
抱歉，我不知道如何增加服务功能。
