### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by lik1234** [Scighost/Starward#288]
### Description

躍遷紀錄 visit too frequently (-110)

### Reproduction Steps

因為我遊戲內的紀錄頁數有二百多頁 , 瀏覽次數太頻繁 , 所以更新紀錄就會出現圖片內的情況

### Screenshots

![image](https://github.com/Scighost/Starward/assets/27262709/ec7c55ac-8ff2-4355-a545-0d4ed1ea4232)

### Starward Version

0.9.0

### Windows Version

windows 10 22H2

### Log

```shell
14:55:47.437
info: Starward.Services.UpdateService[0]
      Current version: 0.9.0, latest version: 0.9.0, ignore version: (null)
14:55:52.542
info: Starward.Pages.MainPage[0]
      Navigate to GachaLogPage with param hkrpg_global
14:55:59.678
warn: Starward.Pages.GachaLogPage[0]
      Request mihoyo api error: visit too frequently (-110)
```

**Comment by Scighost** [comment]
Closed for no title or content.
