### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by x3cit** [Scighost/Starward#289]
### Description

![bug](https://github.com/Scighost/Starward/assets/142771566/91e33b65-3d89-45df-9837-efbf13d9ebb0)
来自崩坏3的弹窗，启动游戏并在窗口打开后约1秒触发，后游戏自动退出

### Reproduction Steps

来自崩坏3的弹窗，启动游戏并在窗口打开后约1秒触发，后游戏自动退出

### Starward Version

0.9.0

### Windows Version

19045.2486

**Comment by Scighost** [comment]
Closed for no title or content.
