### ISSUE TITLE
[Question] 请问如何保存多个星铁账号数据

### ISSUE THREAD

**Issue by thouwave** [Scighost/Starward#290]
### Description

启动星铁后，在登录界面切换账号，starward会把新账号直接覆盖旧账号，不再像之前那样子新创建一个账号

### Starward Version

0.9.0

### Windows Version

Windows11

**Comment by Scighost** [comment]
- 在游戏中登录账号一
- 在 Starward 中编辑完账号信息后点击保存
- 在游戏中登录账号二
- 在 Starward 中编辑完账号信息后点击保存


<img width="210" alt="image" src="https://github.com/Scighost/Starward/assets/61003590/023a4b5a-f1ec-4b3c-b46d-2037164cebf4">

**Comment by thouwave** [comment]
在第三步里，在游戏中登录账号二，starward里面没有出现新的账号，只有上一个账号的信息

**Comment by huali825** [comment]
问下 我使用这个保存的账号的功能
会出现bug, 就是之前保存的账号切换之后都用不了

**Comment by thouwave** [comment]
最新情况，我把starward整个完全关闭再启动就可以正常添加账号了

**Comment by huali825** [comment]
我这儿有个问题:  昨天凌晨3点添加了6个账号, 今天13点开机上游戏发现全部失效, 切换之后都需要重登.

**Comment by huali825** [comment]
新情况 ,电脑重启之后全都恢复正常了(奇怪的问题

**Comment by lesswhite810** [comment]
我新下载的，加不了新账号，会覆盖
