### ISSUE TITLE
[Feature] Switch back to Home page when click on the "X" button in Game Notices page

### ISSUE THREAD

**Issue by phucho0237** [Scighost/Starward#292]
### Summary

Like the title said

### Solution or Design

Like the title said

**Comment by phucho0237** [comment]
I mean this
![image](https://github.com/Scighost/Starward/assets/88989555/186e4492-19a9-47bb-a81e-901695b2ab6a)

**Comment by Scighost** [comment]
Sorry, I cannot implement it. The close event occurs in confused JavaScript, I cannot infer how it was transmitted to the browser host. So Starward cannot know whether you have clicked the close button and navigate back to the launcher page.

**Comment by Scighost** [comment]
Good news, the feature has been implemented in 0.9.1-preview.2
