### ISSUE TITLE
[Question] 启动器里原神的界面账号里始终显示“0”

### ISSUE THREAD

**Issue by Castelliann** [Scighost/Starward#296]
### Description

作者您好，首先非常感谢您开发的程序，让一切都变得方便起来。

我这里发现我启动器的原神界面不会更新我的账号UID，哪怕我手动输入了一次后，再次重启应用，又会变成“0”。我不知道这是我设置的不对还是程序的小BUG。

![interface](https://github.com/Scighost/Starward/assets/57893646/b2379147-706f-466a-bd7d-dd18f8d3bcdb)

但是在崩铁的界面上，只要登陆一次，就会一直记录我的UID。

再次感谢您！

### Starward Version

0.9.0

### Windows Version

22631.2048

**Comment by Scighost** [comment]
为了区分不同的账号，你的昵称不能为空，点击保存后出现了下图的√就说明保存成功
<img width="89" alt="image" src="https://github.com/Scighost/Starward/assets/61003590/11cb7128-23ff-4996-91f4-e3cca45c516d">

**Comment by DGCK81LNN** [comment]
请问uid需要手动输入是吗？

**Comment by gongfuture** [comment]
![image](https://github.com/Scighost/Starward/assets/60888755/e7b57d97-bda4-4ea3-9b32-2eb8e08447f2)
有同样问题，每次打开都会自动跳回到0

**Comment by Scighost** [comment]
每次在游戏中重新登录之后，账号密钥会更新，图上打勾✔的那一行才是最新的账号，之前保存的账号已过期。
