### ISSUE TITLE
原神开放了web版本云原神，大佬什么时候同步一下

### ISSUE THREAD

**Issue by rainbowwarmth** [Scighost/Starward#299]
原神开放了web版本云原神，大佬什么时候同步一下
web云原神链接：https://ys.mihoyo.com/cloud/#/
![3e389c8f31f8d51aafc623a6827f6d96_720](https://github.com/Scighost/Starward/assets/94736026/95af2e96-dad2-4b0c-8709-6b8d0ddbc4c6)

**Comment by Scighost** [comment]
网页版云原神不会把数据存储在本地计算机中，并且我也没有办法监测云原神是否在运行。Starward 的功能和网页版云原神没有任何的相关性，也不会针对此做出任何的功能修改。
