### ISSUE TITLE
[Question] 多账号切换失败的问题

### ISSUE THREAD

**Issue by huali825** [Scighost/Starward#300]
### Description

电脑刚开机时 保存的7个账号都可以正常切换。 
但是在一段时间后 会出现不明原因的 切换账号登录但需要重新登录的问题。
这时候重启电脑则会恢复正常切换功能。

### Starward Version

0.9.1 Preview 1

### Windows Version

22621.2134

**Comment by Scighost** [comment]
账号切换功能只负责保存游戏存储在注册表中的密钥，而某一账号是否需要重新登录则是由米哈游的服务器逻辑决定的，Starward 无权干涉这一过程。如果你在切换账号后遇到需要重新登录的问题，我无能为力。
