### ISSUE TITLE
[Feature] 多壁纸

### ISSUE THREAD

**Issue by Eric-Joker** [Scighost/Starward#301]
### Summary

emm，这是一个没什么卵用的功能
每次显示背景都自动切换（比如开启关闭启动器、从别的游戏标签页切换回来）

### Solution or Design

希望可以有一个列表，列表里是用于自定义背景的图片、视频、或游戏启动器默认背景
如果模式选择随机每一项都可以配置权重，用于设置这个壁纸可能被选中的概率
模式也可以为顺序播放，每一次显示壁纸都显示上次所显示的下一项

**Comment by Cai20020424** [comment]
> ### Summary
> 
> emm，这是一个没什么卵用的功能
> 每次显示背景都自动切换（比如开启关闭启动器、从别的游戏标签页切换回来）
> 
> ### Solution or Design
> 
> 希望可以有一个列表，列表里是用于自定义背景的图片、视频、或游戏启动器默认背景
> 如果模式选择随机每一项都可以配置权重，用于设置这个壁纸可能被选中的概率
> 模式也可以为顺序播放，每一次显示壁纸都显示上次所显示的下一项

意思是现在的背景图片是纯随机的吗？那确实可以优化下。

**Comment by Scighost** [comment]
你的功能请求超出了一个启动器的职责范围，我想你可能更需要一个专业的壁纸软件。
