### ISSUE TITLE
[Feature] 游戏的隐藏与显示

### ISSUE THREAD

**Issue by Ns2Kracy** [Scighost/Starward#307]
### Summary

实现游戏的隐藏以及显示

### Solution or Design

区服的修改和显示也许可以移动到其他地方，然后在区服的地方做隐藏的游戏的菜单(以拖拽的方式进行隐藏游戏或显示?)。

**Comment by Ns2Kracy** [comment]
就像Collapse那样，上面的菜单显示一个游戏，其他的隐藏

**Comment by Scighost** [comment]
你可以参考这个 issue https://github.com/neon-nyan/Collapse/issues/133 ，切换游戏的 UI 在 Collapse 那边已经讨论过很长时间了。就按照点击次数计算，Collapse 那种使用下拉框的切换方式至少需要点击 3 次鼠标，这无疑是十分低效和繁琐的。相比之下，Starward 只需要点击一次。

**Comment by Ns2Kracy** [comment]
或许给出选项隐藏游戏？对我来说只玩部分游戏，另外的就希望能够隐藏。

**Comment by Scighost** [comment]
现在只有三个游戏，暂时还没有隐藏的必要，以后游戏多了后会考虑此功能。
