### ISSUE TITLE
[Question] Translatable Game Region Name

### ISSUE THREAD

**Issue by phucho0237** [Scighost/Starward#308]
### Description

Is there a way for me to translate this?

![image](https://github.com/Scighost/Starward/assets/88989555/a7245143-7b66-467a-8a7b-72b05c2fa505)

### Starward Version

0.9.1-preview.3

### Windows Version

Windows 10 (OS Build 19045.3324)

**Comment by Scighost** [comment]
No, I have no plan to localize these texts.
