### ISSUE TITLE
游戏的启动可以自己选择程序吗

### ISSUE THREAD

**Issue by FujishiroOtone** [Scighost/Starward#31]
就是选择游戏路径的时候，具体针对到文件夹的某个程序，因为原的反和谐需要用到一个b站Ex_M的up的插件，能直接用那个启动的话会方便不少

还有一些个人想问的，这个看起来只是单纯启动器程序为主，和寻空的定位似乎不太一样，大佬有考虑出星铁版的寻空吗？在抽卡记录方面寻空的ui我觉得是用过最舒服的，所以比较希望星铁也有类似的软件

**Comment by Scighost** [comment]
与 #17 重复，此 issue 关闭。
