### ISSUE TITLE
[Feature] 添加Windows计划任务可以管理员身份开机自启且无UAC弹窗

### ISSUE THREAD

**Issue by KKatationer** [Scighost/Starward#312]
### Summary

看别的issue提到了游戏运行时的uac弹窗

### Solution or Design

nuget有封装好调用win32 api 创建计划任务的包，可静默以管理员身份启动。

![屏幕截图 2023-08-29 110706](https://github.com/Scighost/Starward/assets/35140122/382584c5-2c81-45e4-ab58-e1b09ec3975c)

[taskscheduler](https://github.com/dahall/taskscheduler)

**Comment by Eric-Joker** [comment]
#95 #157 #286 
乐

**Comment by Scighost** [comment]
谢谢你的建议，如果有开机启动的需求可以在任务计划程序中自行添加，我不会内置此功能。
