### ISSUE TITLE
[Bug] 启动器版本更新权限问题

### ISSUE THREAD

**Issue by Eric-Joker** [Scighost/Starward#313]
### Description

启动器版本更新后新版本目录的执行权限仅限于当前用户，其他用户在之后想使用需要先在父级目录覆盖权限

### Reproduction Steps

当启动器有版本更新时在用户一打开启动器并更新
切换用户二打开启动器会发现无法打开

### Expected Behavior

多用户环境下正常打开启动器

### Starward Version

app-0.9.1-preview.2

### Windows Version

22621.2134

**Comment by Scighost** [comment]
Windows 多用户的权限管理我不是很了解，没有办法帮助到你。

**Comment by Eric-Joker** [comment]
> Windows 多用户的权限管理我不是很了解，没有办法帮助到你。

嘶，那关了？

**Comment by Eric-Joker** [comment]
也许可以重新开开看看有没有大佬能解决（诶嘿）
