### ISSUE TITLE
[Feature] 希望能把logo放在父级目录

### ISSUE THREAD

**Issue by Eric-Joker** [Scighost/Starward#314]
### Summary

目前logo是放在版本目录的，但是每次更新启动器会导致其他应用读取启动器ico时文件被删除

### Solution or Design

RT

**Comment by Scighost** [comment]
抱歉，不是很明白你的意思。

**Comment by Eric-Joker** [comment]
> 抱歉，不是很明白你的意思。

emm，就是在特殊情况下，快捷方式无法读取到exe图标，需要手动选择logo.ico，但是这个文件的路径随着版本变动，我希望能把这个文件放到根目录下

**Comment by Scighost** [comment]
那你为什么不把 logo.ico 手动复制一下呢

**Comment by Eric-Joker** [comment]
> 那你为什么不把 logo.ico 手动复制一下呢

emmm，你说得对，但是万一logo以后要改的话，嗯（
