### ISSUE TITLE
[Bug] 点击启动器页的游戏公告按钮不跳转标签页

### ISSUE THREAD

**Issue by Eric-Joker** [Scighost/Starward#315]
### Description

RT，并且在启动器选项激活的时候再次点击也无法切换至启动器页

### Reproduction Steps

![ff3d45861096cf505abf4c0acaa3e1f](https://github.com/Scighost/Starward/assets/60310368/81df3b27-1a71-4efc-8388-1673cc4e14ff)

### Expected Behavior

标签页选项切换至游戏公告，取消启动器选项的激活状态

### Screenshots

![6e7184c9c051efee847315859a3160c](https://github.com/Scighost/Starward/assets/60310368/7caa4081-90b0-4678-8874-4754e58fe460)

### Starward Version

app-0.9.1-preview.3

### Windows Version

22621.2134

**Comment by Scighost** [comment]
因为代码结构的原因，在不手动点击导航栏的情况下切换到其他页面时，导航栏内的对应项不会被选中。如果要返回启动器页面，需要点击公告内容中右上角的 `X`。

**Comment by Eric-Joker** [comment]
> 因为代码结构的原因，在不手动点击导航栏的情况下切换到其他页面时，导航栏内的对应项不会被选中。如果要返回启动器页面，需要点击公告内容中右上角的 `X`。

ok，如果可能的话希望优化下，那我关了？

**Comment by Eric-Joker** [comment]
也许可以重新开开看看有没有大佬能解决（诶嘿）
