### ISSUE TITLE
[Bug] 系统托盘不显示Starward图标

### ISSUE THREAD

**Issue by LspColor** [Scighost/Starward#317]
### Description

如标题，设置中已打开“系统托盘图标”且未隐藏图标，升入0.9.1pre3发现的，并且点击关闭直接会关闭程序而非进入托盘

### Reproduction Steps

正常开关闭

### Starward Version

0.9.1Pre3

### Windows Version

19045.3271

**Comment by Scighost** [comment]
同 #251
