### ISSUE TITLE
[Bug] 在主页点公告栏后导航会失显示错

### ISSUE THREAD

**Issue by wsd114514** [Scighost/Starward#319]
### Description

在**主页**点公告后导航栏还显示主页面

### Reproduction Steps

1. 在主页点公告

### Screenshots

![image](https://github.com/Scighost/Starward/assets/116425752/3e629c3e-1f6b-42e9-8dce-99210dcb1d87)
![image](https://github.com/Scighost/Starward/assets/116425752/2b420395-e7bc-4ece-8cbd-698589fa4346)

### Starward Version

0.9.1-preview.3

### Windows Version

10-22H2

**Comment by Scighost** [comment]
同 #315
