### ISSUE TITLE
通过json导入的祈愿记录不显示

### ISSUE THREAD

**Issue by ALEXsun0** [Scighost/Starward#32]
它光跳新增，不显示不覆盖的

**Comment by Georgebillion** [comment]
用的是啥软件导出的？如果不行尝试使用寻空导出试试

**Comment by Scighost** [comment]
> 它光跳新增，不显示不覆盖的

@ALEXsun0 不是很明白你在说什么

**Comment by cqdzhengduo** [comment]
> > 它光跳新增，不显示不覆盖的
> 
> @ALEXsun0 不是很明白你在说什么

就是横幅提示正常跳出“UID XXX 成功导入祈愿记录 XXX 条”，但是实际记录并没有增加，也没有覆盖掉原本的记录。在记录界面无法看到导入的记录。
我是用 genshin wish export 导出的 json 文件。
"export_app":"genshin-wish-export","export_app_version":"v0.9.0","uigf_version":"v2.2"

**Comment by Scighost** [comment]
请问导出的文件中的 `list` 列表的数据是否还有 `uid`，最好把前几项的内容展示出来。

**Comment by cqdzhengduo** [comment]
`{"info":{"uid":"101000000","lang":"zh-cn","export_time":"2023-05-29 12:35:02","export_timestamp":1685334902520,"export_app":"genshin-wish-export","export_app_version":"v0.9.0","uigf_version":"v2.2"},"list":[{"gacha_type":"100","time":"2020-09-16 04:08:49","name":"沐浴龙血的剑","item_type":"武器","rank_type":"3","id":"1000000000000000001","uigf_gacha_type":"100"},{"gacha_type":"100","time":"2020-09-16 04:08:49","name":"鸦羽弓","item_type":"武器","rank_type":"3","id":"1000000000000000002","uigf_gacha_type":"100"},{"gacha_type":"100","time":"2020-09-16 04:08:49","name":"魔导绪论","item_type":"武器","rank_type":"3","id":"1000000000000000003","uigf_gacha_type":"100"},{"gacha_type":"100","time":"2020-09-16 04:08:49","name":"铁影阔剑","item_type":"武器","rank_type":"3","id":"1000000000000000004","uigf_gacha_type":"100"},{"gacha_type":"100","time":"2020-09-16 04:08:49","name":"鸦羽弓","item_type":"武器","rank_type":"3","id":"1000000000000000005","uigf_gacha_type":"100"},{"gacha_type":"100","time":"2020-09-16 04:08:49","name":"鸦羽弓","item_type":"武器","rank_type":"3","id":"1000000000000000006","uigf_gacha_type":"100"},{"gacha_type":"100","time":"2020-09-16 04:08:49","name":"铁影阔剑","item_type":"武器","rank_type":"3","id":"1000000000000000007","uigf_gacha_type":"100"},`

> 请问导出的文件中的 `list` 列表的数据是否还有 `uid`，最好把前几项的内容展示出来。

好像list里没有uid了，只有文件头有。（手动码了下uid，原本是正确的）

**Comment by Scighost** [comment]
已修复，此 issue 关闭
