### ISSUE TITLE
更完善的项目介绍

### ISSUE THREAD

**Issue by textGamex** [Scighost/Starward#320]
在 `README.md` 文件添加一些对开发人员有用的信息, 比如项目所用 UI 框架, 项目架构, 所使用的 `.NET` 版本

**Comment by Scighost** [comment]
我觉得没有必要，关注技术栈的看项目文件 `csproj` 自然就懂，不关注的没必要展示给他们看。

**Comment by textGamex** [comment]
主要是方便, 直观一点,打开项目就可以直接看,不用再点开`csproj`了,不过你说的也有道理.
