### ISSUE TITLE
[代码风格] 关于判断变量是否为 null 值的方法的统一

### ISSUE THREAD

**Issue by textGamex** [Scighost/Starward#323]
我在代码中看了一圈下来发现, 在项目中对 `null` 值的判断既有 `!=` | `==`, 也有 `is` | `is not`, 作者是否想过在项目中确定一个统一的写法呢? 我个人认为 `is` | `is not` 优于传统的 `!=` | `==`.

**Comment by Scighost** [comment]
谢谢你的建议。你应该能看出来，我的代码中不存在一个统一的风格，基本上是想怎么写就怎么写。我的思路也是随着时间改变的，一个项目在不同的时期可能会有两种甚至更多的风格。所以不要在意风格的不统一。

**Comment by textGamex** [comment]
> 谢谢你的建议。你应该能看出来，我的代码中不存在一个统一的风格，基本上是想怎么写就怎么写。我的思路也是随着时间改变的，一个项目在不同的时期可能会有两种甚至更多的风格。所以不要在意风格的不统一。

豪迈😂
