### ISSUE TITLE
可不可以加上渠道服

### ISSUE THREAD

**Issue by 2702073928** [Scighost/Starward#324]
### Summary

作为一名B服原神玩家，很喜欢作者的启动器，可是没有B服登录的入口，希望作者能考虑一下加入渠道服登录

### Solution or Design

希望作者加入渠道服登录，非常感谢

**Comment by Scighost** [comment]
B服应该是可以使用除了**安装更新游戏**和**切换账号**以外的功能，前面提到的两个功能我没有精力去完成。

**Comment by EdenLeaf** [comment]
> 

我就是B服，可以用这个启动器进，只不过更新游戏得用原本的启动器更新。
