### ISSUE TITLE
适应手机的长屏视频[Feature] 

### ISSUE THREAD

**Issue by xiaoan-1** [Scighost/Starward#326]
### Summary

效果如下
![image](https://github.com/Scighost/Starward/assets/63486752/60273e44-de37-47b7-a2d7-0e7f463f20a5)

### Solution or Design

修改MainPage.xaml的样式，如果可以的话，在设置界面加一个下拉框，让用户可以自定义图片和视频的填充模式
![image](https://github.com/Scighost/Starward/assets/63486752/e8e89ce2-8165-4c4c-abc8-a52da0a682d3)

**Comment by Scighost** [comment]
> 不是，你在一个横向的窗口中看纵向的视频，旁边杵着这么大两个黑框，真的看着不难受吗

我不想接受这个建议
