### ISSUE TITLE
[Feature] 在原神游戏启动界面的开始游戏按钮旁的设置里添加快捷更改输入设备选项

### ISSUE THREAD

**Issue by wzxyisme** [Scighost/Starward#327]
### Summary

希望在原神游戏启动界面的开始游戏按钮旁的设置里添加快捷更改输入设备选项

### Solution or Design

在原神游戏启动界面的开始游戏按钮旁的设置里添加快捷更改输入设备选项，且关闭启动器后恢复默认键鼠输入

**Comment by Scighost** [comment]
重复的 issue https://github.com/DGP-Studio/Snap.Hutao/issues/868

**Comment by wzxyisme** [comment]
> 重复的 issue [DGP-Studio/Snap.Hutao#868](https://github.com/DGP-Studio/Snap.Hutao/issues/868)

请问是否可以实现

**Comment by wzxyisme** [comment]
好吧，谢谢回复

**Comment by wzxyisme** [comment]
> 实现不了，因为这是原神进程内部的限制，无法从进程外改变。

我的意思是在游戏运行前更改，更改完再启动游戏也是不行的吗？

**Comment by Scighost** [comment]
如果相关的设置项保存在注册表中，那么在启动游戏前是可以更改的。即使如此，我也不会实现此功能，原神保存在注册表中的设置项太复杂了，我不想在这上面耗费精力。
