### ISSUE TITLE
[Feature] 体力显示

### ISSUE THREAD

**Issue by Eric-Joker** [Scighost/Starward#333]
### Summary

将游戏体力（源萃树脂/开拓力，崩三不玩不知道）显示在启动器页（左侧导航栏第一个标签页），选择指定游戏就能看到
或上方标题栏（选择游戏的那一排）显示，不用选择游戏就能显示所有游戏的体力

### Solution or Design

通过米游社战绩来获取，emm，应该不难吧。。
如果是放在上方标题栏显示貌似不能常驻，排版可能不好看（也可能是我想不到好看的方法），也许可以鼠标在指定游戏图标悬停然后显示
如果可以的话顺便显示下委托数量/每日积分、探索派遣/委托、周本/周本&模拟宇宙积分吧（

**Comment by Scighost** [comment]
米游社有较为严格的风控系统，第三方软件在请求其数据后会触发账号验证，我没有能力绕过或自动完成验证。
此外你的需求与 Starward 的定位不符，建议你使用 [Snap Hutao](https://github.com/DGP-Studio/Snap.Hutao)。
