### ISSUE TITLE
Shortcut Key to Switch Games [Feature] 

### ISSUE THREAD

**Issue by studiobuttermedia** [Scighost/Starward#340]
### Summary

Add a feature where pressing `CTRL + [Any Number]` or `CTRL + Tab` switch to another game (With Tab being used to Switch in Order and `CTRL + Shift + Tab` switch in reverse order).
And an Area for User to change these mapped keys.

I would suggest one for changing server of that game but I don't have any ideas for that Shortcut.

### Solution or Design

Example: 

- `CTRL + 1`: Switch to Honkai Impact 3rd
- `CTRL + 2`: Switch to Genshin Impact
- `CTRL + 3`: Switch to Honkai: Star Rail
- `CTRL + 4`: Switch to Zenless Zone Zero
- `CTRL + Tab`: Switch games from Left to Right (HI3 -> GI -> HSR -> ZZZ)
- `CTRL + Shift + Tab`: Switch games from Right to Left (ZZZ -> HSR -> GI -> HI3)

**Comment by Scighost** [comment]
Great idea, I will try to implement it.

**Comment by Scighost** [comment]
In my design, there are tow kinds of shortcut keys. `Ctrl` for switching game and `Alt` for navigate page. In app, shortcut tips display when pressing Ctrl or Alt key, then press any number key to trigger action.

**Showcase (only use keyboard)**

https://github.com/Scighost/Starward/assets/61003590/437eec5e-ef88-4016-9613-292058b0d1da


However, there are tow known issues I cannot fix:

- Shortcut keys are not triggered after clicking background image
- System beeps when using `Alt` shortcuts

Link: [Download the latest build to experience the bug](https://github.com/Scighost/Starward/actions/runs/6074968283)

**Comment by studiobuttermedia** [comment]
I have a theory tho IDK about it.  What if there's a layer between the background image and the UI so if you clicked on the background, you will still able to use shortcuts.

**Comment by Lightczx** [comment]
> * Shortcut keys are not triggered after clicking background image

[Doc](https://learn.microsoft.com/zh-cn/windows/windows-app-sdk/api/winrt/microsoft.ui.xaml.uielement.previewkeydown?view=windows-app-sdk-1.4)
当UIElement**具有焦点**时按下键盘键时发生。 点击背景图片后MainPage直接失焦了，当然不能触发快捷键

**Comment by Scighost** [comment]
I made some changes in [0.10.0 Preview 2](https://github.com/Scighost/Starward/releases/tag/0.10.0-preview.2).

- Remove shortcut key of switching game
- `Ctrl + num` shortcut key is for navigation
- Navigation panel can be clicked
- Click right/left button of mouse to show/hide navigation panel


https://github.com/Scighost/Starward/assets/61003590/419f8223-31ee-42ab-bb8a-c00798f2962f
