### ISSUE TITLE
[Question] 截图功能使用以及快捷键

### ISSUE THREAD

**Issue by Tncent** [Scighost/Starward#341]
### Description

侧边栏->游戏截图 如果为空仅仅只会显示 “截图文件夹不存在”
能否在这样的条件下增加 快捷键引导提示 引导使用这个快捷键截图
或者加入自定义热键截图

### Starward Version

0.9.1

### Windows Version

22621

**Comment by Scighost** [comment]
Starward 只有游戏内相片的浏览功能，请您使用其他工具自行截图。
