### ISSUE TITLE
[Feature] 建议增加一个看体力的组件

### ISSUE THREAD

**Issue by KZdavid** [Scighost/Starward#342]
### Summary

类似米哈游自己的手机桌面小组件，显示体力、每日、周本、模拟宇宙、委托等等的完成情况

### Solution or Design

这个功能应该各类工具都有，调用米游社的api就行，就是好像是需要用到ck的

**Comment by TMGyes** [comment]
问题是你提的这个，米哈游会在检测到之后，要求每次都要过机器人验证才能正常使用，就很麻烦

**Comment by Scighost** [comment]
参考 #333
