### ISSUE TITLE
[Feature] 建议增加自定义帧率挡位

### ISSUE THREAD

**Issue by 2103894869** [Scighost/Starward#343]
### Summary

由于噪音的影响，我不能启用风扇全速
在一开始的0.6版本，帧率可以自由设置时
我通常将游戏帧率设定在90帧，这刚好让我的GPU稳在85度
在7.0版本后
新的游戏设置将帧率改成了下拉菜单，且只提供120帧
这会跑满我的GPU,撞上温度墙掉到10帧，然后反复横跳

### Solution or Design

希望开发者考虑加回手动帧率
或者折中增加90帧下拉选项

**Comment by Scighost** [comment]
你的错觉，星穹铁道的帧率设置只有 30、60、120 这三个可用值，使用其他任意值都会在游戏开始时回退到 60 。
我是在知道这一点后移除了任意帧率的设置选项。

**Comment by 2103894869** [comment]
> 你的错觉，星穹铁道的帧率设置只有 30、60、120 这三个可用值，使用其他任意值都会在游戏开始时回退到 60 。 我是在知道这一点后移除了任意帧率的设置选项。

这么说来有相关印象，老版本设定90的时候FPS都高于95，看来得用别的方法限制显卡调度了
