### ISSUE TITLE
[Bug] 切换游戏账号后，关闭游戏，会自动生成一个当前的新账号

### ISSUE THREAD

**Issue by Mishseven** [Scighost/Starward#344]
### Description

星穹铁道，切换另一个游戏账号后，打开游戏，游玩后关闭，账号管理那里会出现一个新的当前账号

file:///C:/Users/Mishseven/%E6%A1%8C%E9%9D%A2/QQ%E6%88%AA%E5%9B%BE20230903101945.png
file:///C:/Users/Mishseven/%E6%A1%8C%E9%9D%A2/QQ%E6%88%AA%E5%9B%BE20230903101956.png

### Reproduction Steps

[file:///C:/Users/Mishseven/%E6%A1%8C%E9%9D%A2/QQ%E6%88%AA%E5%9B%BE20230903101945.png
file:///C:/Users/Mishseven/%E6%A1%8C%E9%9D%A2/QQ%E6%88%AA%E5%9B%BE20230903101956.png](url)

### Expected Behavior

[file:///C:/Users/Mishseven/%E6%A1%8C%E9%9D%A2/QQ%E6%88%AA%E5%9B%BE20230903101945.png
file:///C:/Users/Mishseven/%E6%A1%8C%E9%9D%A2/QQ%E6%88%AA%E5%9B%BE20230903101956.png](url)

### Screenshots

[file:///C:/Users/Mishseven/%E6%A1%8C%E9%9D%A2/QQ%E6%88%AA%E5%9B%BE20230903101945.png
file:///C:/Users/Mishseven/%E6%A1%8C%E9%9D%A2/QQ%E6%88%AA%E5%9B%BE20230903101956.png](url)

### Starward Version

0.9.1

### Windows Version

Windows 10

### Log

```shell
file:///C:/Users/Mishseven/%E6%A1%8C%E9%9D%A2/QQ%E6%88%AA%E5%9B%BE20230903101945.png
file:///C:/Users/Mishseven/%E6%A1%8C%E9%9D%A2/QQ%E6%88%AA%E5%9B%BE20230903101956.png
```

### Additional Context

file:///C:/Users/Mishseven/%E6%A1%8C%E9%9D%A2/QQ%E6%88%AA%E5%9B%BE20230903101945.png
file:///C:/Users/Mishseven/%E6%A1%8C%E9%9D%A2/QQ%E6%88%AA%E5%9B%BE20230903101956.png

**Comment by Scighost** [comment]
无效的 issue

**Comment by MJSummer** [comment]
传了个相对路径是什么鬼啦

**Comment by g1fts** [comment]
> 无效的 issue


我这也出现了类似的问题，上上一个版本没有，从上个版本开始有这个问题。
starward 当前版本 0.11.2
这是没退出游戏前
![image](https://github.com/Scighost/Starward/assets/20061353/85fc8e28-ecf6-4184-ac87-7edf28d62a8f)
这是退出游戏后
![image](https://github.com/Scighost/Starward/assets/20061353/a19a456f-8c7c-40e9-9e9d-724b827dffbe)

崩铁也有类似的问题
没退出游戏前
![image](https://github.com/Scighost/Starward/assets/20061353/76d353af-51b8-4423-bd0d-f6a41427bd5c)
这是退出游戏后
![image](https://github.com/Scighost/Starward/assets/20061353/8be5ded4-105d-43a6-bdb2-e3c5e410defc)

尝试过删除所有数据重新通过账号反馈添加账号，也还是会出现这个问题。
另外，原神和崩铁退出有心后新增一个账号的问题不是同一个账号，原神的是198那个账号，崩铁是177那个账号。
