### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by 11389698** [Scighost/Starward#346]
### Description

0.9.1版本更新后就显示游戏运行中，进程管理器确定星穹铁道已退出，重启电脑也无改善
![image](https://github.com/Scighost/Starward/assets/79733561/b5d7a7e8-1c60-4f0e-a995-03a374b751cd)
忽略后可以用
![image](https://github.com/Scighost/Starward/assets/79733561/0a0a3935-61a4-46aa-a1cd-80ebf45d7526)

### Reproduction Steps

未知

### Starward Version

0.9.1

### Windows Version

19045.3324

**Comment by Scighost** [comment]
Closed for no title or content.

**Comment by 11389698** [comment]
> 因无标题或内容而关闭。

？
