### ISSUE TITLE
[Feature] 建议把左上角菜单栏，展开固定，

### ISSUE THREAD

**Issue by Nonfi** [Scighost/Starward#347]
### Summary

每次看祈愿记录都得点击左上角菜单，建议把菜单栏的功能都在左边固定下来

### Solution or Design

建议把左上角菜单栏，展开并固定。

**Comment by Scighost** [comment]
你的建议会破坏首页的沉浸感，我不能接受。

**Comment by seriaati** [comment]
可以學學 collapse 的方式：
![image](https://github.com/Scighost/Starward/assets/61446626/a94bfbd4-39a1-421b-b7a3-d817e3e63f05)
