### ISSUE TITLE
[Question] 能否出一个保持最小化的功能

### ISSUE THREAD

**Issue by KurumiYYDS** [Scighost/Starward#349]
### Description

能否出一个保持最小化的功能

### Starward Version

0.9.1

### Windows Version

win10

**Comment by Scighost** [comment]
你能详细描述一下你的需求吗

**Comment by KurumiYYDS** [comment]
类似原神官方的启动器，我点击关闭就是隐藏到系统托盘，而不是直接关闭程序，想启动的话直接从托盘点击，弹出启动器。

**Comment by KurumiYYDS** [comment]
我虽然看见应用设置里面，有系统托盘这个设置，但是我无论开启还是关闭系统托盘图标，都无法在右下角win系统托盘显示。

开启了系统托盘图标，关闭程序，在任务管理器上查看，还是在后台运行的，但是就不在右下角win系统托盘显示，这个可能触发了什么bug

**Comment by Scighost** [comment]
#251

**Comment by hhelibeb** [comment]
用0.9.0
