### ISSUE TITLE
原神记录导出json格式异常

### ISSUE THREAD

**Issue by razormax007** [Scighost/Starward#35]
![屏幕截图 2023-05-30 145055](https://github.com/Scighost/Starward/assets/48665953/7b128ee2-c02a-4437-a04f-a7d429674204)
记录获取正常 json导入正常 execl导出正常
json导出异常 只显示表头
另外星铁导入导出都没有问题

**Comment by Scighost** [comment]
感谢反馈

**Comment by Scighost** [comment]
已修复，此 issue 关闭
