### ISSUE TITLE
[Feature] 希望添加进入游戏后关闭starward进程的设置

### ISSUE THREAD

**Issue by w192570** [Scighost/Starward#352]
### Summary

每次从启动器启动游戏时都需要手动关闭starward

### Solution or Design

希望增加一个设置，打开该设置之后可以让我在打开任意游戏时自动结束starward进程，最好系统托盘里也不要有

**Comment by goldenapple1** [comment]
那你为什么还需要启动器？为什么不直接在桌面添加一个游戏主程序的快捷方式？

**Comment by 954150714** [comment]
不需要结束程序，只要打开游戏能自动最小化到托盘就可以了

**Comment by w192570** [comment]
> 
三个游戏三个快捷方式，如果再加上各自的启动器更新器用来更新的话就是6个图标，如果绝区零还是这种的那就是8个图标。放在同一个文件夹虽然能解决但总觉得不太美观 也不太方便，而且starward还有帧率解锁，对我这种懒人很友好

**Comment by w192570** [comment]
> 那你为什么还需要启动器？为什么不直接在桌面添加一个游戏主程序的快捷方式？

三个游戏三个快捷方式，如果再加上各自的启动器更新器用来更新的话就是6个图标，如果绝区零还是这种的那就是8个图标。放在同一个文件夹虽然能解决但总觉得不太美观 也不太方便，而且starward还有帧率解锁，对我这种懒人很友好

**Comment by qiansen1386** [comment]
> 不需要结束程序，只要打开游戏能自动最小化到托盘就可以了

我跟你想法完全相反，能不能不要自动最小化，我要打开两个游戏，每次要去托盘再点一次有点烦。
