### ISSUE TITLE
[Bug] Error occurs when install Genshin firstly by repair mode

### ISSUE THREAD

**Issue by momokll** [Scighost/Starward#357]
### Description

安装游戏提示未知错误

### Reproduction Steps

校验快结束弹出未知错误

### Screenshots

![momo](https://github.com/Scighost/Starward/assets/144450953/616a9e49-9035-4c6d-954a-b48c0144dcb5)

### Starward Version

v0.9.1

### Windows Version

19045.2310

**Comment by Scighost** [comment]
请提供完整的日志文件，此外你是否是第一次安装游戏？

**Comment by momokll** [comment]
[Starward_230908_195759.log](https://github.com/Scighost/Starward/files/12560272/Starward_230908_195759.log)

**Comment by momokll** [comment]
第1次安装游戏

**Comment by Scighost** [comment]
请先创建文件夹 `D:\原神\YuanShen_Data\StreamingAssets` 后，再使用修复模式安装游戏。已确认是内部错误，此问题下个版本修复。
