### ISSUE TITLE
[Feature] 打开游戏后启动器仍然保持在前台，以便打开另一个游戏

### ISSUE THREAD

**Issue by qiansen1386** [Scighost/Starward#359]
### Summary

- 现在的逻辑是：打开游戏后，启动器自动最小化至系统托盘
- 预期的逻辑是：打开游戏后启动器仍然保持在前台，以便打开另一个游戏。
- 理由：如果每次只打开一个游戏为什么要用**聚合**启动器呢？用官方的是一样的呀？很多多修玩家都有多开的需求。
- UX：节省了一个每次打开一个游戏再去托盘打开另一个游戏的步骤。

### Solution or Design

可以考虑提供一个自动最小化至托盘的选项：关闭就保持前台，打开就自动隐藏。

**Comment by Scighost** [comment]
#352
