### ISSUE TITLE
[Bug] 启动器文字消失

### ISSUE THREAD

**Issue by momokll** [Scighost/Starward#363]
### Description

字体也安装了 别的软件都正常 只有启动器和寻空工具箱有问题

### Reproduction Steps

打开启动器后没有文字

### Screenshots

![1](https://github.com/Scighost/Starward/assets/144450953/c8221667-6916-42c1-aa3a-92a68455f2f8)
![2](https://github.com/Scighost/Starward/assets/144450953/69fad7a4-fb1c-4c9f-8ffa-5b751f7a003a)

### Starward Version

v0.9.1

### Windows Version

19045.2310

**Comment by Scighost** [comment]
您好，很遗憾我无法解决您的问题，建议重装系统。
