### ISSUE TITLE
[Bug] 开始菜单中的图标模糊

### ISSUE THREAD

**Issue by Scighost** [Scighost/Starward#364]
更新一次之后连开始菜单的图标都变糊了，可能和这个问题相关

_Originally posted by @Lightczx in https://github.com/Scighost/Starward/issues/251#issuecomment-1717680425_

**Comment by Scighost** [comment]
@Lightczx 图标还是模糊吗？

**Comment by Lightczx** [comment]
已经清晰了

**Comment by Lightczx** [comment]
0.9.1的时候已经清晰了

**Comment by Scighost** [comment]
其实这段时间我没有修改过图标文件

<img src="https://github.com/Scighost/Starward/assets/61003590/710d743f-81a3-4b6d-aaba-0530648a5f3d" width="200px" />

**Comment by Lightczx** [comment]
应该就是windows图标缓存的问题，windows自己定时清理了就好了
