### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by wueeee** [Scighost/Starward#368]
### Description

星铁游戏文件夹从D盘（下载位置）移动至C盘后无法定位（已选中文件夹并确认，但仍显示“安装游戏”而非“开始游戏”）未知其他游戏是否有相同情况

### Reproduction Steps

1.将星铁移动至C盘（非原安装盘）
2.游戏设置-定位游戏-选择星铁文件夹-确认

### Expected Behavior

启动器显示“安装游戏”而非“开始游戏”

### Screenshots

https://github.com/Scighost/Starward/assets/138870196/5343c0cb-5703-4d35-9971-b8bde05b68cf

### Starward Version

0.9.1

### Windows Version

23545.1000

**Comment by Scighost** [comment]
Closed for no title or content.
