### ISSUE TITLE
[Feature] Add the ability to watch for Resin and Trailblaze Powe inside the launcher

### ISSUE THREAD

**Issue by DarkAssassin48** [Scighost/Starward#372]
### Summary

Add the ability to watch for Resin and Trailblaze Powe inside the launcher. Here's an example of what it looks like. 
https://github.com/daidr/pompom-webext
https://github.com/daidr/paimon-webext

### Solution or Design

![Starward_23-09-18_00-21-02](https://github.com/Scighost/Starward/assets/40138340/31f932eb-dd29-4b0e-b064-c100fc33bac5)

**Comment by Scighost** [comment]
Sorry, I have no plan to do this. #333
