### ISSUE TITLE
[Feature] 希望可以增加退出游戏启动器可以在托盘自己动弹出来的功能

### ISSUE THREAD

**Issue by xiaoxingruo** [Scighost/Starward#373]
### Summary

希望可以增加退出游戏启动器可以在托盘自己动弹出来的功能，我是多账号玩的，打开了启动游戏自动隐藏到托盘功能，但是每次关闭游戏想要切换下一个账号就必须自己去打开它，但是如果不隐藏到托盘玩的时候切屏会很麻烦，所以希望可以增加一下这个功能。

### Solution or Design

我不知道……不过希望大佬能加一下

**Comment by Scighost** [comment]
#172
