### ISSUE TITLE
[Feature] 米游社工具箱页的默认账号选择

### ISSUE THREAD

**Issue by Eric-Joker** [Scighost/Starward#377]
### Summary

将米游社工具箱页的默认选择账号设为列表第一个而不是最后添加的那一个，并且可以支持排序
我前两天在把我同学的米游社添加进来后在大多数情况下选择该页默认查看的是我同学的不是我自己的

### Solution or Design

排序可以在展开账号列表的ui直接长按拖动行

**Comment by Scighost** [comment]
当只有一个账号的时候，工具箱的使用体验最佳。虽然支持多个账号，但是很难做好多账号的使用体验。
