### ISSUE TITLE
[Bug] 多账号时，校验账号后仍无法更新数据

### ISSUE THREAD

**Issue by Eric-Joker** [Scighost/Starward#378]
### Description

存在多个米游社账号时，如果每个账号均触发校验账号，只校验当前所选账号仍无法成功更新数据，仍然提示账号异常1034，需要将所有账号全都校验过才能正常更新。

### Reproduction Steps

1.添加多个米游社账号
2.等待一段时间所有账号均触发账号异常1034
3.校验其中一个账号后更新数据

### Expected Behavior

校验当前一个账号后就可以获取当前账号的数据，不是全都校验一遍才能获取当前账号的数据

### Starward Version

0.9.2-pre1

### Windows Version

22621.2283

**Comment by Scighost** [comment]
谢谢你的反馈，这个问题我暂时没有办法解决。

**Comment by Scighost** [comment]
这个问题和 #669 相关，已解决。
