### ISSUE TITLE
[Feature] 原神没办法同时启动两个账号的游戏

### ISSUE THREAD

**Issue by xiaoxingruo** [Scighost/Starward#379]
### Summary

崩坏星穹铁道可以登陆一个账号之后进入游戏然后切换另一个账号就可以同时登陆两个游戏，但是原神不可以。我想用大号带下号，但是手机没那么多内存下载一个手机版的，所以想问一下能不能和崩铁一样启动两个游戏。

### Solution or Design

额……我没学过编程，真的不知道怎么说……

**Comment by Scighost** [comment]
原神不支持多开

**Comment by xiaoxingruo** [comment]
> 原神不支持多开

好吧，那没办法了
