### ISSUE TITLE
[Bug] 更新之后退回到0.9.1版本之后启动游戏不能隐藏到托盘了

### ISSUE THREAD

**Issue by xiaoxingruo** [Scighost/Starward#380]
### Description

更新到0.9.2preview1之后退回到0.9.1版本之后启动游戏不能隐藏到托盘了，只会缩小化，设置里面开了隐藏到托盘，之前是可以的。是最新版本不支持隐藏到托盘了吗？

### Reproduction Steps

更新到0.9.2preview1之后退回到0.9.1版本之后启动游戏不能隐藏到托盘了，只会缩小化

### Expected Behavior

还是希望可以启动游戏后隐藏到托盘，退出游戏之后会再次出现，方便换账号

### Starward Version

0.9.1

### Windows Version

Windows10 教育版

**Comment by Scighost** [comment]
#251
