### ISSUE TITLE
[Feature] 崩3和原神什么时候可以在启动器里面有图像设置？

### ISSUE THREAD

**Issue by bilibiliTMG** [Scighost/Starward#383]
### Summary

崩3和原神什么时候可以像星铁一样在启动器里面有图像设置？
![image](https://github.com/Scighost/Starward/assets/143889343/41ce14f5-6c01-4817-a797-7b950def0b50)
![image](https://github.com/Scighost/Starward/assets/143889343/c2121407-0b62-4dc0-bb72-8058762d0a97)
![image](https://github.com/Scighost/Starward/assets/143889343/8c60d49b-25e3-4a9b-bc3c-7f0bec8358ae)

### Solution or Design

。

**Comment by Scighost** [comment]
星铁在开启高帧率后，游戏中的图像设置会消失，所以才会在启动器中加入相关的图像设置。而崩坏3和原神没有这个问题，自然也不需要。

**Comment by bilibiliTMG** [comment]
> 星铁在开启高帧率后，游戏中的图像设置就会消失，所以就会在启动器中加入相关的图像设置。而崩坏3和原神没有这个问题，自然也不需要。
但是星铁都有了，崩3和原神没有，总感觉怪怪的，而且我觉得原神也可以加解锁帧率进去

**Comment by MetaSquared** [comment]
> > 星铁在开启高帧率后，游戏中的图像设置就会消失，所以就会在启动器中加入相关的图像设置。而崩坏3和原神没有这个问题，自然也不需要。
> > 但是星铁都有了，崩3和原神没有，总感觉怪怪的，而且我觉得原神也可以加解锁帧率进去

对的，既然星铁有这个设置，原神最好也加一下，顺便把120帧解锁了
