### ISSUE TITLE
[Feature] 希望能在全屏模式后增加无边框全屏选项

### ISSUE THREAD

**Issue by qakcn** [Scighost/Starward#390]
### Summary

谢谢作者的好工具，我从刻记牛杂店、寻空一直使用到这个工具，都很好用！

我在玩崩铁在**独占全屏**下会掉帧，**窗口模式**下就正常。
后来发现使用**无边框全屏**可以解决问题。

希望作者可以在全屏的选框后面增加一个无边框全屏的选框。
对应的Unity参数是`-window-mode borderless`。

谢谢！

### Solution or Design

![图片](https://github.com/Scighost/Starward/assets/1809188/6a681971-e203-46c4-9f10-3e68c35be4f2)

**Comment by Scighost** [comment]
你好，无边框窗口不是注册表中的一个设置项，不应该包含在图形设置中，你可以自行添加到 Unity Player 的启动参数中。

**Comment by qakcn** [comment]
是不是注册表设置我不太清楚，但确实是一个开关的选项，目前我用过的几个启动器（[胡桃工具箱](https://hut.ao/)、[原神启动器Plus](https://github.com/DawnFz/Genshin.Launcher.Plus)）都有提供对应选项。
希望作者能考虑考虑。
谢谢！

**Comment by qakcn** [comment]
> > 是不是注册表设置我不太清楚，但确实是一个开关的选项，目前我用过的几个启动器（[胡桃工具箱](https://hut.ao/)、[原神启动器Plus](https://github.com/DawnFz/Genshin.Launcher.Plus)）都有提供对应选项。我只是希望能在崩铁上也能方便地开启。 希望作者能考虑考虑。 谢谢！
> 
> 启动参数加上 -popupwindow就能无边框了

这个参数是不对的，这个参数和游戏内的全屏设置有冲突。正确的参数我一开始就说了，是`-window-mode borderless`。
