### ISSUE TITLE
[Bug] 更新至0.10.0-preview.1后语言更换失效

### ISSUE THREAD

**Issue by jinyiwei2012** [Scighost/Starward#393]
### Description

语言选择的是中文,但界面是英文

### Reproduction Steps

更新至0.10.0-preview.1后就出现

### Expected Behavior

希望能成功切换语言

### Screenshots

![image](https://github.com/Scighost/Starward/assets/116472418/bbb175a5-3639-43ff-a467-c24694a9cd45)

### Starward Version

0.10.0-preview.1

### Windows Version

25951.1010

**Comment by Scighost** [comment]
无法复现，请检查文件是否完整。

**Comment by jinyiwei2012** [comment]
应该是之前更新时报了文件替换错误,更新至最新版已解决

**Comment by BuleDrogon** [comment]
![image](https://github.com/Scighost/Starward/assets/148713443/9fc18e3f-17ed-4991-82a7-c850a93c107f)
问题再次出现，简体中文和繁体中文失效，完全退出重进问题没有消失，版本为0.11.3

**Comment by Scighost** [comment]
@BuleDrogon 请您校验一下文件是否完整，我这一切正常


https://github.com/Scighost/Starward/assets/61003590/ee209956-d203-4ec7-9dfb-66b73b9b974f

**Comment by BuleDrogon** [comment]
> @BuleDrogon 请您校验一下文件是否完整，我这一切正常
> 
>  Starward_Tog4Zzwphw.mp4

校验之后可以了，感谢
