### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by ChuotBuhhh** [Scighost/Starward#396]
### Description

Launcher can't identify game files 

### Reproduction Steps

open launcher-> setting -> locate -> choose game file 

### Screenshots

![image](https://github.com/Scighost/Starward/assets/144521542/ec40f827-fe46-4d78-b993-338b844d2a69)

### Starward Version

0.9.1

### Windows Version

19045.3448

### Log

```shell
nope
```

**Comment by Scighost** [comment]
Closed for no title or content.
