### ISSUE TITLE
[Bug] 账号记录更新数据后页面不会即时更新

### ISSUE THREAD

**Issue by Eric-Joker** [Scighost/Starward#397]
### Description

一个小问题，账号记录功能，在刷新项目数据时如果已在该项目详情页，刷新完成后详情不会即时更新，届时也无法通过直接点该项目标签来刷新页面，需要点其他项目再点回来。

### Reproduction Steps

账号记录→选择一个查询项目→点击该项目的刷新按钮更新数据

### Starward Version

0.10.0-pre2

### Windows Version

22621.2283

### Log

```shell
阿哈？
```

**Comment by Scighost** [comment]
谢谢反馈，功能做得比较匆忙，还没来得及优化使用的体验细节。
