### ISSUE TITLE
[Feature] 将下载分片文件名中删除.slice

### ISSUE THREAD

**Issue by Eric-Joker** [Scighost/Starward#398]
### Summary

我使用该启动器分片下载校验就没成功过，经过压缩软件测试压缩包并没有损坏，希望从文件名中删除.slice字段以方便压缩软件识别为分片压缩包

### Solution or Design

nothing

**Comment by Scighost** [comment]
你好，我从来没有遇到过校验失败的问题，建议你检查设备硬件。
此外，`slice` 文件用于大文件的分片下载，不是分卷压缩文件，不能被删除。

**Comment by Eric-Joker** [comment]
> 你好，我从来没有遇到过校验失败的问题，建议你检查设备硬件。 此外，`slice` 文件用于大文件的分片下载，不是分卷压缩文件，不能被删除。

emmm，7zip这个软件能把分片下载识别为正常无错误的压缩包（
就是得改名。。。

**Comment by Scighost** [comment]
虽然 7zip 可以识别，但是这不是分解压缩包，按分卷压缩的方式解压极有可能造成文件损坏。
