### ISSUE TITLE
[Feature] 账号记录功能一些建议

### ISSUE THREAD

**Issue by Eric-Joker** [Scighost/Starward#399]
### Summary

1.星铁官方查询页会把遗器升级、光锥升级的数量标位-1，原神崩三不了解，启动器这边显示的时候也许可以改为1？
2.随时间筛选精度精确到每小时吧。。
3.消耗/获取 来源搜索筛选

### Solution or Design

nothing

**Comment by Scighost** [comment]
谢谢你的反馈

1. 获取是正数，消耗是负数；
2. 精确到小时会在 UI 方面有比较大的改动，暂时没有精力做出使用方便的设计；
3. 同上

**Comment by Eric-Joker** [comment]
> 谢谢你的反馈
> 
> 1. 获取是正数，消耗是负数；
> 2. 精确到小时会在 UI 方面有比较大的改动，暂时没有精力做出使用方便的设计；
> 3. 同上

升级不算消耗获取吧，，那个网页把所有升级都标为了-1

**Comment by Scighost** [comment]
除了祝圣xx，你升级的时候不消耗其他圣遗物？

**Comment by Eric-Joker** [comment]
> 除了祝圣xx，你升级的时候不消耗其他圣遗物？

好的我是撒比
