### ISSUE TITLE
[Feature] 接入米家

### ISSUE THREAD

**Issue by fr1g** [Scighost/Starward#404]
### Summary

是的, 我希望接入米家. 像是在局域网中模拟设备? 然后通过某些方式来达成:
「小爱同学, 启动原神」, 「小爱同学, 启动XTZJ-20210810上的原神」...

没别的意思, 只是看到米家二字想到了而已. 如果不方便做, 那当我没说(

### Solution or Design

已经在Summary提供了思路.

**Comment by Eric-Joker** [comment]
真逆天，不愧是#404
我要是会c#多少得写个pr

**Comment by Scighost** [comment]
![image](https://github.com/Scighost/Starward/assets/61003590/f675c076-b8dc-4208-a62f-00a296cb31b0)

**Comment by fr1g** [comment]
？我的天呐怎么会（捂嘴Отправлено с iPhone29 сент. 2023 г., в 10:08, Scighost ***@***.***> написал(а):﻿
