### ISSUE TITLE
[Feature] 启动参数添加前缀

### ISSUE THREAD

**Issue by copurxia** [Scighost/Starward#408]
### Summary

用以支持[Juice](https://github.com/Juice-Labs/Juice-Labs)以调用远程gpu
启动命令仅为`juicify .\StarRail.exe`

### Solution or Design

添加一个输入框？

**Comment by Scighost** [comment]
启动参数就是启动参数，不分前后缀。
你的需求是点击开始游戏时启动 `juicify`，请使用自定义启动程序功能。

**Comment by copurxia** [comment]
ok，已成功
