### ISSUE TITLE
[Question] 

### ISSUE THREAD

**Issue by MX-1-a** [Scighost/Starward#414]
### Description

之前的0.8版本还是啥版本可以创立多账号,但由于打不开我把它删掉了，现在0.10.0版本创立不了了是咋回事?
![QQ截图20231004122747](https://github.com/Scighost/Starward/assets/146797283/439e3d36-70a6-4188-8ed9-369d462c26cc)
![QQ截图20231004122759](https://github.com/Scighost/Starward/assets/146797283/a99616e7-e5f8-45e9-8afa-aae0e9853940)

### Starward Version

0.10.0

### Windows Version

1596.958

**Comment by Scighost** [comment]
Closed for no title or content.

**Comment by MX-1-a** [comment]
官方？







                       
原始邮件
                       
                     

发件人："Scighost"< ***@***.*** &gt;;

发件时间：2023/10/4 12:31

收件人："Scighost/Starward"< ***@***.*** &gt;;

抄送人："MX-1-a"< ***@***.*** &gt;;"Author"< ***@***.*** &gt;;

主题：Re: [Scighost/Starward] [Question]  (Issue #414)




 
Closed #414 as not planned.
