### ISSUE TITLE
[Feature] 建议增加下载限速功能

### ISSUE THREAD

**Issue by zlqd123** [Scighost/Starward#417]
### Summary

默认满速下载会影响其他软件或设备的网络，建议增加下载速度限制功能

### Solution or Design

![image](https://github.com/Scighost/Starward/assets/32678715/8c1456b6-ca9e-45ea-88f1-053b566f4f33)

**Comment by Scighost** [comment]
很抱歉，我没有能力做出限制下载速度的功能，你可以通过其他软件实现。
