### ISSUE TITLE
[Feature] 增加崩坏3的米游社工具箱的功能

### ISSUE THREAD

**Issue by Stelle22108126** [Scighost/Starward#418]
### Summary

懒的每次都要拿起手机去米游社看崩3的深渊战报和战场战报了doge

### Solution or Design

![image](https://github.com/Scighost/Starward/assets/143889343/4a313807-0cf1-4c40-8db4-0943345858af)

**Comment by Scighost** [comment]
抱歉，我个人没有在玩崩坏3，所以暂时无法加入工具箱功能。
