### ISSUE TITLE
[Feature] 希望可以不需要页面上下滚动，直接显示完祈愿记录

### ISSUE THREAD

**Issue by yyIntsuki** [Scighost/Starward#421]
### Summary

主要是祈愿记录的页面排版的缘故，导致没有办法以窗口大小显示完所有祈愿，抽得多的只能往下拉，不能直接一张图概括完。为什么不采用类似寻空那种显示方法呢？虽然看着是乱了一点，但是能显示全部也是感觉挺重要的... 

### Solution or Design

可能可以试试角色图标右下角加个小图标显示是多少抽？这样就不用一次出货霸占一整行了

**Comment by Scighost** [comment]
谢谢你的建议，但是抽卡记录页面的设计应该是不会再改变了。
