### ISSUE TITLE
[Feature] 自定义视频壁纸能否关闭声音

### ISSUE THREAD

**Issue by story-x** [Scighost/Starward#422]
### Summary

自定义视频壁纸能否关闭声音

### Solution or Design

增加关闭声音开关

**Comment by Scighost** [comment]
<img width="240" alt="image" src="https://github.com/Scighost/Starward/assets/61003590/73baf369-bc4a-46cb-b5b6-9dccb9f9165e">

**Comment by story-x** [comment]
![image](https://github.com/Scighost/Starward/assets/45375162/02671d44-7300-41e7-927d-7f43ad86bd32)
![image](https://github.com/Scighost/Starward/assets/45375162/aa88a417-1364-41cc-b731-cb846d025b96)

v 0.10.0 无音量条

**Comment by Scighost** [comment]
<img width="562" alt="image" src="https://github.com/Scighost/Starward/assets/61003590/98fe6b96-c973-46ac-a565-0af3e53a316e">
