### ISSUE TITLE
How to solve the Parameter Error?

### ISSUE THREAD

**Issue by tuanronaldp** [Scighost/Starward#426]
### Description

Is there anyway to solve this parameter error, like format the disc or something? If there is a way, please tell me how to solve it. Thank you

### Starward Version

0.10.0

### Windows Version

19045.2965

### Additional Context

![parameter error](https://github.com/Scighost/Starward/assets/147491515/030eaa78-ffc0-413c-b5f6-c478b7a952e6)

**Comment by Scighost** [comment]
Please try again, and upload the latest log file.
