### ISSUE TITLE
[Bug] 无法更新跃迁记录

### ISSUE THREAD

**Issue by LycoreReco** [Scighost/Starward#427]
### Description

![Screenshot 2023-10-11 120236](https://github.com/Scighost/Starward/assets/147578261/dff31e31-c3d5-46c6-8423-778769f4ff7d)
已经把抽卡记录打开了，还是无法更新

### Reproduction Steps

-

### Starward Version

0.10.0

### Windows Version

19045.3448

### Log

```shell
-
```

**Comment by Scighost** [comment]
把 `StarRail_Data\webCaches` 这个文件夹删掉，再打开游戏，点击更新。

**Comment by LycoreReco** [comment]
还是不行

**Comment by Scighost** [comment]
国际服啊，应该是链接变了，等我下个客户端检查一下。

**Comment by LycoreReco** [comment]
没错我是国际服的

**Comment by Scighost** [comment]
我的账号新手剧情还没过完，看不了抽卡记录。麻烦你把 `StarRail_Data\webCaches\2.17.0.0\Cache\Cache_Data\data_2` 这个文件私发给我 scighost@outlook.com ，感谢你的帮助。

**Comment by LycoreReco** [comment]
发了

**Comment by Scighost** [comment]
确定是网页链接改变了，你在我提到的文件中找到以 `https://api-os-takumi.mihoyo.com/common/gacha_record/api/getGachaLog` 开头的链接，然后通过下图中的**输入URL**可暂时更新抽卡记录。

<img width="109" alt="image" src="https://github.com/Scighost/Starward/assets/61003590/873e8384-a64f-4327-87d0-723c86fad067">

**Comment by LycoreReco** [comment]
可以了，感谢你的帮助

**Comment by Scighost** [comment]
已在 0.10.1 中修复此问题
