### ISSUE TITLE
做了个ICO的软件图标，希望大佬喜欢，感谢大佬的辛勤付出！

### ISSUE THREAD

**Issue by Mishseven** [Scighost/Starward#43]
软件光秃秃的，总感觉少点什么，哈哈哈，自己做了一个米游姬的，谢谢大佬制作的软件！
链接：https://pan.baidu.com/s/1ZdMU7amTiG2nZD2yZrdHPQ 
提取码：klx5

**Comment by Scighost** [comment]
感谢你对 Starward 的贡献！

你制作的图片过于突出 miHoYo 和米游社的形象，但是本项目和这两者没有直接关系。并且使用人物头像当作图标，在 Windows 上的开始菜单、任务管理器等地方会显得非常模糊，恕我不能采纳你的作品。
