### ISSUE TITLE
使用Starward进入崩坏星穹铁道(国服)后无法进入提示登录异常，遂切换CDN但三个CDN延迟都在1000+

### ISSUE THREAD

**Issue by 2376801531** [Scighost/Starward#431]
### Description

如题，附图如下
<img width="181" alt="image" src="https://github.com/Scighost/Starward/assets/75020193/ed7726b7-2c1c-44e4-be91-ac61ef27c378">
<img width="630" alt="image" src="https://github.com/Scighost/Starward/assets/75020193/e4fbaeed-705a-460a-a16c-6a3a954a352a">

### Starward Version

0.10.1

### Windows Version

22621.2283

**Comment by Scighost** [comment]
应用内的 CDN 设置是检查更新时用的，和铁道没有任何关系。出现这种情况大概率是你或米哈游的网络出现了问题，请尝试多重复几次。
