### ISSUE TITLE
[Bug] 进入账号记录界面后点击崩坏3，会进入崩坏3的“账号记录”页面

### ISSUE THREAD

**Issue by Waximell** [Scighost/Starward#432]
### Description

如题，但崩3又不支持这个功能，至少侧栏里是没有的。

### Reproduction Steps

在原神或者星铁进入账号记录后，点最上面的崩3图标，就会进入崩3的“账号记录”页面了

### Expected Behavior

如同其他崩3不支持的页面一样，切回主界面咯

### Starward Version

0.10.0&0.10。1

### Windows Version

23H2

### Log

```shell
我相信这个小bug不需要查日志（原谅我懒得去复制了）
```

### Additional Context

有一说一，这个事儿太小了我觉得没必要提一个issue，想着或许大伙都这么想，开发者大大说不定也已经注意到了，只是觉得没必要为此单独更新一个版本，会在下版本顺手修复，但，新版本没有修复，所以这里出现了这个issue

**Comment by Scighost** [comment]
感谢反馈，已修复。
