### ISSUE TITLE
[Feature] 后续会加入原神帧率解锁吗？

### ISSUE THREAD

**Issue by Leonado007** [Scighost/Starward#433]
### Summary

如题

### Solution or Design

这样我就可以把寻空卸载了，嘿嘿~
感觉starward真的很好用啊，点一万个赞！

**Comment by Scighost** [comment]
解锁帧率属于第三方工具的功能，Starward 不会内置。

**Comment by Leonado007** [comment]
好的，辛苦辛苦

**Comment by w-xy** [comment]
+1! Hope there's genshin fps unlock as the same as star rail.

**Comment by Scighost** [comment]
Unfortunately, I have no ability to develop a fps-unlocking tool. So I recommend you to use [genshin-fps-unlock](https://github.com/34736384/genshin-fps-unlock) as custom startup executable.

**Comment by Lightczx** [comment]
https://www.nuget.org/packages/Snap.Hutao.Service.Game.Unlocker/
