### ISSUE TITLE
[Bug] 跃迁记录的五星和四星部分在左右切换的时候会存在排版错误的问题

### ISSUE THREAD

**Issue by bzyyt** [Scighost/Starward#434]
### Description

在跃迁记录中，使用笔记本电脑的触摸板进行五星的列表和四星的列表进行切换的时候会出现列表显示不正常的问题，如下文所附的截图所示

### Reproduction Steps

进入启动器的抽卡记录页面，使用触摸板切换五星和四星的界面，便会出现下图所示的情况

### Screenshots

![屏幕截图 2023-10-12 201837.png](http://tva1.sinaimg.cn/large/007U57bTly1hisr76pq19j317z0qf1kx.jpg)

### Starward Version

0.10.1

### Windows Version

25967.1000

### Log

```shell
这个动作并不会输出任何的log（）
```

**Comment by Scighost** [comment]
我有点没看懂，能更详细地解释一下吗？

**Comment by bzyyt** [comment]
唔，就是抽卡页面的四星和五星这个具体名单的切换是可以通过笔记本触摸板双指左右滑动实现的，
![image.png](http://tva1.sinaimg.cn/large/007U57bTly1hiv7mybutxj30yx07tt9r.jpg)
就是这个拖动两个手指进行滚动
而将指针放置于四星五星名单的位置，将持续朝左右其中之一个方向双指滑动触摸板，就可能出现一些显示异常，比如说类似上图的名单的列表错位，或者说名单不显示的问题

**Comment by Scighost** [comment]
已了解，但是经过我的测试没有出现你描述的现象；如果有的话，像这种 WinUI 框架的问题，我没有办法解决。
