### ISSUE TITLE
[Feature] 崩坏3和星穹铁道中当自动检测出来的帐号UID在已保存的账号UID中时，可以直接替换

### ISSUE THREAD

**Issue by MephistoSatanDevil** [Scighost/Starward#438]
### Summary

目前自动检测出来的UID无论已保存的账号UID中是否存在，都会新增一个空昵称的账号选项，还需要手工编辑添加昵称保存替换。

### Solution or Design

已保存的账号中昵称已经有了，新账号UID与已保存的账号UID相同时，直接添加已保存账号的昵称并替换原账号信息即可。

**Comment by Scighost** [comment]
抱歉，你的需求我无法实现。因为原神无法检测出当前登录账号的 uid，为了保持逻辑一致，均不会自动保存账号的任何信息。如果你只有一个账号，那么不需要关心账号切换的功能。
