### ISSUE TITLE
[Feature] 祈願次數新增已抽幾抽

### ISSUE THREAD

**Issue by Sibaluma** [Scighost/Starward#439]
### Summary

能否顯示目前已抽幾抽 #

### Solution or Design

總計 918 抽已累計8抽未出5星 
如這樣統計字串 #

**Comment by Scighost** [comment]
这两行是你需要的

<img width="249" alt="image" src="https://github.com/Scighost/Starward/assets/61003590/3198ef8c-fa26-4983-9d2c-43a79b5157cc">
