### ISSUE TITLE
[Bug] 米游社账号登录选择输入cookie时无法粘贴

### ISSUE THREAD

**Issue by meng-ru-nan-fa** [Scighost/Starward#442]
### Description

如题，无论是ctrl+v或邮件粘贴都不行。
别问为什么不用网页登录，因为经常掉cookie。

### Reproduction Steps

菜单-米游社工具箱-登录-输入cookie

### Starward Version

0.10.1

### Windows Version

22H2 19045.3086

### Log

```shell
emm...这怎么找
```

**Comment by Scighost** [comment]
抱歉，无法复现。而且文字描述无法清晰的展示你的问题，请使用视频。

<img width="262" alt="image" src="https://github.com/Scighost/Starward/assets/61003590/e36d5aa6-f3b7-4321-a3a6-69797b4c1a95">

**Comment by meng-ru-nan-fa** [comment]
奇怪，过了一晚上可以粘贴了，~~昨晚可能有debuff？~~
目前问题是意料之外的解决了，也许可能有其他因素影响
