### ISSUE TITLE
[Feature] 是否可以使用单实例模式以防止重复启动多个starward？

### ISSUE THREAD

**Issue by MephistoSatanDevil** [Scighost/Starward#443]
### Summary

启动游戏后启动器会自动最小化，有时候退出游戏后干了其他什么事又回来继续上游戏的时候，会因为桌面没有starward窗口而再次启动一次。不影响实际使用但是体验不好。

### Solution or Design

当Starward已经启动时，再次启动starward，不再打开一个新的进程而是把已有进程推到前台即可。

**Comment by Scighost** [comment]
此功能已经实现，启用系统托盘后会转为单实例模式。

<img width="134" alt="image" src="https://github.com/Scighost/Starward/assets/61003590/bde7f6c0-9320-415a-a174-2e9398e3f47e">
