### ISSUE TITLE
[Feature] 修复模式下载失败时不需要重新校验

### ISSUE THREAD

**Issue by ruattd** [Scighost/Starward#444]
### Summary

这是原版启动器最让人头疼的地方之一，修复模式下载时的网络故障跟校验结果没任何关系，为什么要重新校验呢？

### Solution or Design

修复模式下载时发生网络故障，重试应直接重新下载而不是重新开始校验。

**Comment by Scighost** [comment]
抱歉给你造成了不好的体验，因为个人能力有限，正常下载和修复模式的流程都是线性的，除了手动暂停后可以继续下载外，遇到其他的问题只能从头开始。
