### ISSUE TITLE
[Feature] 求在starward里面设置原神的游戏画面，声音等选项

### ISSUE THREAD

**Issue by MetaSquared** [Scighost/Starward#445]
### Summary

如同崩铁那样

### Solution or Design

如同崩铁那样

**Comment by bilibiliTMG** [comment]
已在 #383 有过相关提议

**Comment by Scighost** [comment]
不仅仅是原神不需要图形设置，更重要的是原神存储在注册表中的数据模型很复杂，我没有精力做这个功能。当然，我们非常欢迎你通过 PR 实现它。

**Comment by Lightczx** [comment]
没事，胡桃会做的（
