### ISSUE TITLE
[Feature] 增加是否选择启用快捷键和快捷键自定义功能

### ISSUE THREAD

**Issue by Stelle22108126** [Scighost/Starward#446]
### Summary

自带的快捷键（ctrl+6和ctrl+7）有些人（比如我）按不到，不如增加个可以自定义快捷键的设置；
是否选择启用快捷键为顺便帮朋友提一嘴的功能，因为他不太喜欢用emmmm

### Solution or Design

![image](https://github.com/Scighost/Starward/assets/143889343/38140686-5522-46b5-bb7f-065bdd1e82fd)
在应用设置里添加

**Comment by Scighost** [comment]
谢谢你的建议。
考虑到以后可能会在侧栏中增加更多的内容，一只手按不到快捷键的问题会越来越突出。正确使用快捷键的方式是**在任意位置点击鼠标右键**，这个方法我只在 [Release 0.10.0 - Ayaka](https://github.com/Scighost/Starward/releases/tag/0.10.0) 中提到过，很多人应该不知道。
此外，后续也应该会加入关闭快捷键的方法。

**Comment by Scighost** [comment]
从下个版本开始，你可以通过在 `config.ini` 文件中添加以下内容禁用快捷导航：

``` ini
EnableNavigationShortcut=False
```

**Comment by Scighost** [comment]
修改了一下设置名称，从下个版本开始，你可以通过在 `config.ini` 文件中添加以下内容禁用快捷导航：

``` ini
DisableNavigationShortcut=True
```

**Comment by bilibiliTMG** [comment]
> 修改界面设置名称，从下个版本开始，您可以通过在`config.ini`文件中添加以下内容取消快捷导航：
> 
> ```ini
> DisableNavigationShortcut=True
> ```

那么，请问是否会在后面的版本更新中加入单独的设置按钮来控制此功能，还是继续通过修改config.ini文件来控制？

**Comment by Scighost** [comment]
不会在应用内提供设置选项，只能通过修改 config.ini 。
