### ISSUE TITLE
[Feature] 可否增加原神官服B服互转功能

### ISSUE THREAD

**Issue by HiruOcha** [Scighost/Starward#447]
### Summary

因为同时有官服和B服的账号，所以每次启动前需要手动更改文件，有点麻烦，希望能有一个一键转服的功能

### Solution or Design

转成B服：
修改Genshin Impact Game\config.ini
channel=14
cps=bilibili
在Genshin Impact Game\YuanShen_Data\Plugins内添加PCGameSDK.dll

转回官服
修改Genshin Impact Game\config.ini
channel=1
cps=mihoyo
删除PCGameSDK.dll

**Comment by Scighost** [comment]
谢谢你的建议，但是我没有支持渠道服的计划，如果你有这方面的需求，建议你使用 [Snap Hutao](https://github.com/DGP-Studio/Snap.Hutao) 或 [Collapse Launcher](https://github.com/CollapseLauncher/Collapse)。
