### ISSUE TITLE
便携版真的好么

### ISSUE THREAD

**Issue by HyBoxwood** [Scighost/Starward#45]
便携版，指望我去翻找千余项的下载文件夹或者百余项的桌面，或者专门放文件夹，有点强人所难了。
我基本上所有的软件/固定文件启动方式都是开始+搜索+wizfile，安装版的话就能直接打字直达。
我建议还是安装版，尽管它还是没有图标。

**Comment by Scighost** [comment]
你可以自己创建一个快捷方式，或者固定到开始菜单嘛，安装版无非是帮你找了个地方放文件而已。

相关： #19

**Comment by HyBoxwood** [comment]
win11的开始菜单不是想固定就固定的，比win10磁贴反人类。

**Comment by Scighost** [comment]
你不是用的搜索吗，固定到菜单之后就能搜到了。

**Comment by HyBoxwood** [comment]
更新频繁，你也不想我手动替换吧。

**Comment by sertwen** [comment]
便携版0.6.1到0.6.2有热更新，而且作者说没有微软商店版，如果有安装版了一次次下一步更麻烦 :(

**Comment by XHLiang0** [comment]
现在有热更新其实已经影响不大了，我反而更关心啥时候能弄个图标给它
（现在用的寻空的图标作为客串）

**Comment by Scighost** [comment]
> 这个便捷版能做到完全体吗？我经常重装系统，重装完，打开后还需要设置

@realcirno 不能，因为设置都保存在注册表中，重装后注册表会被清理。

**Comment by HyBoxwood** [comment]
那也不够便携嘛，至少不够绿色（

**Comment by MeiVinEight** [comment]
WindowsApp的管理方式才是反人类，不能自己指定位置，还不能双击exe直接打开，必须用它提供的启动工具。
绿色便携版是好文明！
如果把便携版看作自由管理的话，自动安装版虽然方便但是完全是监狱。自由惯了的人是不能接受被限制的。
