### ISSUE TITLE
[Feature] 希望可以添加一个选择启动游戏时程序最小化到任务栏或最小化到系统托盘的设置项

### ISSUE THREAD

**Issue by Sonoda-Kotori** [Scighost/Starward#450]
### Summary

因为有多个账号需要切换，每次做完一个账号的任务后切换账号都要先点开系统托盘再点开starward然后才能切换账号
如果能在启动游戏后只是最小化到任务栏，可以直接alt+tab，很大程度上简化步骤

### Solution or Design

在应用设置加一个选项就行

**Comment by Scighost** [comment]
关闭托盘功能，启动游戏后就会最小化到托盘；如果你不想关闭托盘，可以等待 #420 实现。

**Comment by Sonoda-Kotori** [comment]
我想了一下，或许可以设置成关闭游戏后自动打开starward应用界面

**Comment by Scighost** [comment]
> 我想了一下，或许可以设置成关闭游戏后自动打开starward应用界面

这个建议我不会采纳
