### ISSUE TITLE
[Feature] 希望可以在原神启动设置里增加像崩铁一样的修改帧率的选项

### ISSUE THREAD

**Issue by rEco1LLLL** [Scighost/Starward#452]
### Summary

希望可以在原神启动设置里增加像崩坏星穹铁道一样的修改帧率的选项

### Solution or Design

希望可以在原神启动设置里增加像崩坏星穹铁道一样的修改帧率的选项

**Comment by Scighost** [comment]
重复的问题，已经聊过很多轮了。
