### ISSUE TITLE
[Bug] 点击原神游戏公告无法加载

### ISSUE THREAD

**Issue by FloatingLifeFS** [Scighost/Starward#456]
### Description

https://github.com/Scighost/Starward/assets/148814293/fb40a001-99a1-4b00-a904-07530f79ec30

### Reproduction Steps

正常使用即可

### Screenshots

<img width="959" alt="{1897E43F-F82C-471b-A047-C1BA4BFBF247}" src="https://github.com/Scighost/Starward/assets/148814293/40a3c616-43b0-4dae-82bd-ead73bb8b155">

### Starward Version

0.10.1

### Windows Version

win11专业版

### Log

```shell
[03:46:30.155] [INFO] 
Welcome to Starward v0.10.1
System: Microsoft Windows NT 10.0.22621.0
Command Line: D:\Portable_Applications\Starward\app-0.10.1\Starward.dll

[03:46:30.193] [INFO] Starward.Services.DatabaseService
Database path is 'D:\Portable_Applications\Starward\AppData'

[03:46:30.211] [INFO] Starward.Services.DatabaseService
Database version is 7, target version is 7.

[03:46:30.255] [INFO] Starward.Pages.MainPage
Select game region is hk4e_cn

[03:46:30.259] [INFO] Starward.Pages.MainPage
Navigate to "LauncherPage" with param hk4e_cn

[03:46:30.589] [INFO] Starward.Pages.LauncherPage
Game install path hk4e_cn: "D:\Applications\MIHOYO\MIHOYO Game\Genshin Impact\Genshin Impact Game"

[03:46:30.610] [INFO] Starward.Services.DownloadGameService
Local game version is "4.1.0" (gameBiz: hk4e_cn)

[03:46:30.913] [INFO] Starward.Services.UpdateService
Start to check update (Preview: False, Arch: X64)

[03:46:31.436] [INFO] Starward.Services.UpdateService
Current version: "0.10.1", latest version: "0.10.1", ignore version: null

[03:46:33.638] [INFO] Starward.Pages.MainPage
Navigate to "GameNoticesPage" with param hk4e_cn

[03:46:36.094] [INFO] Starward.Pages.MainPage
Navigate to "SettingPage" with param hk4e_cn
```

**Comment by Scighost** [comment]
无法复现，你可以在公告页面按下 F12 调出 DevTools 看看有什么异常。

**Comment by FloatingLifeFS** [comment]
> 无法复现，你可以在公告页面按下 F12 调出 DevTools 看看有什么异常。


https://github.com/Scighost/Starward/assets/148814293/986b0053-c3a4-4b60-8bd7-f52c5978faba

**Comment by FloatingLifeFS** [comment]
> 无法复现，你可以在公告页面按下 F12 调出 DevTools 看看有什么异常。

@Scighost 

https://github.com/Scighost/Starward/assets/148814293/eeeee034-429e-4d39-a077-b6a6fb02232c
好像确实少了什么，我看不懂

**Comment by Scighost** [comment]
我也看不出来有什么问题。
你在设置中打开日志文件夹，返回上一级目录，然后删除 webview 文件夹，再测试一下游戏公告。

**Comment by FloatingLifeFS** [comment]
> 我也看不出来有什么问题。 你在设置中打开日志文件夹，返回上一级目录，然后删除 webview 文件夹，再测试一下游戏公告。

恢复正常了！感谢！另外可以讲讲删除 webview 文件夹的作用是什么吗？

**Comment by FloatingLifeFS** [comment]
> > 我也看不出来有什么问题。 你在设置中打开日志文件夹，返回上一级目录，然后删除 webview 文件夹，再测试一下游戏公告。
> 
> 恢复正常了！感谢！另外可以讲讲删除 webview 文件夹的作用是什么吗？

补充：我发现原神公告界面无法呼出右键选项了
<img width="199" alt="屏幕截图 2023-10-26 102602" src="https://github.com/Scighost/Starward/assets/148814293/323ea0c4-36d4-4567-be4f-71f2f15f4735">

**Comment by FloatingLifeFS** [comment]
> 我也看不出来有什么问题。 你在设置中打开日志文件夹，返回上一级目录，然后删除 webview 文件夹，再测试一下游戏公告。

@Scighost 感谢！可以加载出来了！但我不懂删除此文件夹的作用，恳请简单讲解一下。
新的问题补充：原神游戏公告可以加载了，但是加载界面无法如 崩坏：星穹铁道 和 崩坏3 的游戏公告一样可以呼出右键选项。

https://github.com/Scighost/Starward/assets/148814293/29a2cf90-61a3-42de-ada4-b1ddba6e1fe9

**Comment by FloatingLifeFS** [comment]
> > 我也看不出来有什么问题。 你在设置中打开日志文件夹，返回上一级目录，然后删除 webview 文件夹，再测试一下游戏公告。
> 
> @Scighost 感谢！可以加载出来了！但我不懂删除此文件夹的作用，恳请简单讲解一下。 新的问题补充：原神游戏公告可以加载了，但是加载界面无法如 崩坏：星穹铁道 和 崩坏3 的游戏公告一样可以呼出右键选项。
> 
>  QQ20231026-103538.mp4

补充：可以加载出来的原神公告按 F12 调出的界面是这样的
<img width="464" alt="屏幕截图 2023-10-26 105249" src="https://github.com/Scighost/Starward/assets/148814293/914c5e89-0581-4b56-9a42-5e799caa9c82">
，之前加载不出来的时候这里确实少了东西

**Comment by Scighost** [comment]
删除文件夹是为了清理网页缓存，右键无菜单是网页的限制，我没办法改变。

问题已解决，将关闭此 issue。
