### ISSUE TITLE
[Feature] 祈愿记录更新自动转换语言

### ISSUE THREAD

**Issue by ruattd** [Scighost/Starward#458]
### Summary

原神游戏语言与启动器语言不同时，更新祈愿记录角色/武器名称会使用游戏的语言。

有时候这会显得比较奇怪，比如：
![](https://github.com/Scighost/Starward/assets/61044187/c699af4f-36d7-4c03-9f37-6c523c123ee8)

（我没有在炫耀抽卡记录！

### Solution or Design

希望可以加一个自动匹配角色并以当前启动器语言显示的功能。

或许还能同时修复角色/武器名与启动器不为同语言导致匹配不到图标而显示空白的问题。

**Comment by Scighost** [comment]
<img width="225" alt="image" src="https://github.com/Scighost/Starward/assets/61003590/9213c537-fa18-4228-8189-1b80e6f55ae1">

如图，自己填上 zh-cn 就行

**Comment by ruattd** [comment]
谢谢回复，但还是希望能在没填写这个时随启动器自动切换

**Comment by Scighost** [comment]
> 谢谢回复，但还是希望能在没填写这个时随启动器自动切换

按你的想法，强制转换成启动器设置的语言，那使用德语、西班牙语、意大利语的怎么办？

**Comment by ruattd** [comment]
或许可以再添加一个“使用游戏语言”的设置项

**Comment by Lightczx** [comment]
starward 没有使用 物品Id 确定存放的抽卡记录表示的物品，是做不到无缝国际化/本地化体验的

**Comment by Scighost** [comment]
> 或许可以再添加一个“使用游戏语言”的设置项

你的建议加入了一个没有必要的设置项，我不能接受。

**Comment by Scighost** [comment]
> starward 没有使用 物品Id 确定存放的抽卡记录表示的物品，是做不到无缝国际化/本地化体验的

过时的消息，早就可以转换显示的语言了 [docs/Tips.zh-CN.md#转换抽卡记录的语言](https://github.com/Scighost/Starward/blob/main/docs/Tips.zh-CN.md#%E8%BD%AC%E6%8D%A2%E6%8A%BD%E5%8D%A1%E8%AE%B0%E5%BD%95%E7%9A%84%E8%AF%AD%E8%A8%80)

**Comment by Lightczx** [comment]
我的意思就是必须要经过这一步转换，这一步不够无缝（

**Comment by Scighost** [comment]
> 我的意思就是必须要经过这一步转换，这一步不够无缝（

你应该是没用过，这里填入的语言会替换掉 URL 中的语言，新的抽卡记录也是自己指定的语言。

**Comment by Lightczx** [comment]
无缝是指完全不需要填（

**Comment by Lightczx** [comment]
虽然但是我确实没用过（逃
