### ISSUE TITLE
[Feature] 米游社工具箱支持寰宇蝗灾

### ISSUE THREAD

**Issue by Eric-Joker** [Scighost/Starward#459]
### Summary

RT

### Solution or Design

![5269dfeaf82ec208ba68470d34a88bb](https://github.com/Scighost/Starward/assets/60310368/b932da5a-d650-4bb8-8d4e-0aa4b4255c2c)
默认标签页普通模拟宇宙，选择标签页列表数据切换。
也许普通模拟宇宙更应该显示的是积分、通关次数，寰宇蝗灾显示的是最新一局的祝福数、奇物数和扰动等级or倒计时。
标签页栏上面也应该向忘却之庭那个页面弄一个完整周期日期，啧，懒得改图了。阿哈

**Comment by Scighost** [comment]
寰宇蝗灾只有最近三次的通关数据，没有记录的必要。
