### ISSUE TITLE
在使用自定义背景图片的同时打开动态主题色会导致闪退

### ISSUE THREAD

**Issue by Waximell** [Scighost/Starward#46]
如题，bug为0.61版本，更新后打开，闪退前没有机会进应用修改设置，我是在bg文件夹里把自己的图片删了才进去，改了设置，恢复使用。

**Comment by Scighost** [comment]
请发一下崩溃时的日志

**Comment by Waximell** [comment]
这是日志
[Starward_230601_214802.log](https://github.com/Scighost/Starward/files/11626014/Starward_230601_214802.log)
我也发现了是这张图会出问题，我自定义的另一张不会（话说这张还是官图呢）
![星穹铁道2](https://github.com/Scighost/Starward/assets/59529964/26b6ea2e-5d9f-487f-b34e-1af9c91a8e75)

**Comment by Scighost** [comment]
感谢反馈，通过你的图片成功复现了问题。

**崩溃原因**

遍历图片的像素计算主题色时，其中有一个流程出现了错误，导致指针溢出，访问到了进程外的内存区域。
当背景图片适应窗口缩放后的高度为奇数时，会出现这个错误，此时进程被操作系统强行关闭，不会留下崩溃日志。
