### ISSUE TITLE
希望抽卡记录导入功能支持导入从一些主流统计网站导出的文件

### ISSUE THREAD

**Issue by RosieDu21** [Scighost/Starward#460]
### Checklist

- [X] I have already read [docs/Tips.md](https://github.com/Scighost/Starward/blob/main/docs/Tips.md), but my feature is not implemented.
- [X] My suggested feature was not mentioned by others, and it is not a duplicate feature.

### Summary

希望抽卡记录支持导入从 paimon.moe, pom.moe, starrailstaion.com 等统计网站导出的文件。

考虑到大多数玩家应当已经使用了其他平台保存过往的抽卡记录，若能够支持这些平台导出的过往记录，应当可以极大提高玩家对这个功能的兴趣。

### Solution or Design

只要支持解析各平台导出的文件即可。可以在导入按钮旁边加一个列表，选择导入文件的来源。

**Comment by Lightczx** [comment]
https://uigf.org/zh/

**Comment by Lightczx** [comment]
实际上这些平台的开发者十分的高冷，多名UIGF成员与他们交涉均无功而返（

**Comment by Scighost** [comment]
@RosieDu21 如果你有从这些网站导出的文件，可以提供一下。

**Comment by RosieDu21** [comment]
@Scighost 
我有 paimon.moe 和 starrailstation 的 json 文件，但我并不确定其中哪些部分为敏感信息，所以我只能私下提供给你，文件我会发到你的邮箱。作为替代，我找到了以下两个项目，用于将 paimon.moe 的祈愿信息转换成UIGF，希望有所帮助。starrailstation 尚未找到相关项目。

https://github.com/Nats-ji/paimon-wish-uigf-converter
https://github.com/Masterain98/UIGF-Converter

**Comment by Scighost** [comment]
我看了这两个文件，抽卡数据的字段缺失很多或难以转换，无法做到支持导入。

``` json
// genshin
{
    "type": "weapon",
    "code": "302",
    "id": "harbinger_of_dawn",
    "time": "2023-03-05 06:15:21",
    "pity": 1
}
```

``` json
// star rail
{
    "uid": "1695211800000589111",
    "itemId": 20009,
    "timestamp": 1695212087000,
    "gachaType": 11,
    "gachaId": 2010,
    "rarity": 3,
    "manual": false,
    "pity4": 7,
    "pity5": 12,
    "pullNo": 626,
    "result": 0,
    "anchorItemId": "0",
    "sort": 999999374
}
```

**Comment by yyIntsuki** [comment]
在**paimon.moe**的导入EXCEL(WishTally)的格式跟Starward目前的格式是可以转换的，我个人手动转换过，格式对比如下：

## 目前Starward导出的格式为
文件名：**Stardward_Export_GenshinImpact_[uid]_[YYYYMMDDHHMMSS].xlsx**
| uid  | id | time | name | item_type | rank_type | gacha_type | index | pity |
| ------------- | ------------- | ------------- | ------------- | ------------- | ------------- | ------------- | ------------- | ------------- | 
| [uid] | [id] | 2020-09-19 21:22:27  | 铁影阔剑  | 武器 | 3 | NoviceWish | 1 | 1 |
| [uid] | [id] | 2020-09-19 21:22:27  | 弹弓  | 武器  | 3 | CharacterEventWish |  1  | 1 |
| [uid] | [id] | 2020-09-19 21:22:27  | 诺艾尔  | 角色  | 4 | CharacterEventWish_2 | 2 | 2 |
| [uid] | [id] | 2020-09-19 21:22:27  | 莫娜  | 角色  | 5 | CharacterEventWish_2 | 3 | 3 |
| [uid] | [id] | 2020-09-19 21:22:27  | 迪卢克  | 角色  | 5 | PermanentWish | 1 | 1 |

**底部TAB**
| Gacha Log |
| ------------- | 

## WishTally接收的格式为
文件名：**Genshin_Wish_History_[YYYYMMDD]_[HHMMSS].xlsx**
| Timestamp | Reward Name | Reward Type | Rarity (Star) | Wish Count | Pity Count |
| ------------- | ------------- | ------------- | ------------- | ------------- | ------------- | 
| 2020-09-19 21:22:27 | 铁影阔剑    | 武器 | 3  | 1 | 1 | 
| 2020-09-19 21:22:27 | 弹弓        | 武器  | 3  | 2 | 2 | 
| 2020-09-19 21:22:27 | 诺艾尔      | 角色  | 4  | 3 | 3 |
| 2020-09-19 21:22:27 | 莫娜        | 角色  | 5  | 4 | 4 | 
| 2020-09-19 21:22:27 | 迪卢克      | 角色  | 5  | 5 | 1 | 

**底部TAB**
| Character Event Wish | Weapon Event Wish | Permanent Wish | Novice Wishes |
| ------------- | ------------- | ------------- | ------------- |

**WishTally的每个TAB之间都是一模一样的格式，所以就不重复写了。**
### **总之就是**
- uid和id是WishTally这个没有的，然后把Gacha Type分布到四个不同的TAB。
- 角色祈愿-1和角色祈愿-2没有区分，全部都在Character Event Wish里面。
