### ISSUE TITLE
[Feature] 希望繁中語系的躍遷紀錄，5★"保底"能改成"已墊"

### ISSUE THREAD

**Issue by railway5566** [Scighost/Starward#465]
### Checklist

- [X] I have already read [docs/Tips.md](https://github.com/Scighost/Starward/blob/main/docs/Tips.md), but my feature is not implemented.
- [X] My suggested feature was not mentioned by others, and it is not a duplicate feature.

### Summary

希望繁中語系的躍遷紀錄，5★"保底"能改成"已墊"
簡中是已墊，繁中是保底
已墊好像較多人用

### Solution or Design

別款的是寫累計X抽未出5星
已墊幾抽好像比較直觀?
就像前面有人建議要寫幾抽應該也是看到5★保底不知道那是已墊的意思

**Comment by Scighost** [comment]
谢谢你的建议，关于文本翻译的问题，你可以直接在 Crowdin 平台上更改。
https://crowdin.com/project/starward

**Comment by Scighost** [comment]
Starward 中做出的修改已在 0.10.3 中应用。
