### ISSUE TITLE
suggestion

### ISSUE THREAD

**Issue by laoxke** [Scighost/Starward#469]
### Checklist

- [X] I have already read [docs/Tips.md](https://github.com/Scighost/Starward/blob/main/docs/Tips.md), but my feature is not implemented.
- [X] My suggested feature was not mentioned by others, and it is not a duplicate feature.

### Summary

I wish there was a left and right button in the info window on the game's splash screen, otherwise it would be too cumbersome to just click on the dot below

中文意思：我希望在游戏启动界面的那个信息小窗可以加个向左和向右的按钮，不然只靠点击下面的小圆点太麻烦了

### Solution or Design

![屏幕截图 2023-10-29 161524](https://github.com/Scighost/Starward/assets/103014810/c3bf23f9-1113-4cfd-a84e-3667ee7308bd)

**Comment by Lightczx** [comment]
可以用鼠标滚动

**Comment by Scighost** [comment]
#248
