### ISSUE TITLE
奇怪的bug，通过starward启动星穹铁道无法使用ps5手柄

### ISSUE THREAD

**Issue by xing-yv** [Scighost/Starward#47]
如题，在使用starward启动星穹铁道后，ps5手柄可以正常识别，但按键无反应，官方启动器无此问题，使用Xbox360协议的手柄也无此问题，已排除其它因素，触发bug概率100%，蓝牙及有线连接方式均有此问题。

**Comment by Scighost** [comment]
我对比了使用官服启动器和Starward启动游戏时的参数，二者是一致的，不是启动参数不同导致的问题。

因为我没有PS设备，所以以上是我针对这个问题能做到的全部工作，很遗憾没能帮到你。

**Comment by xing-yv** [comment]
> 我对比了使用官服启动器和Starward启动游戏时的参数，二者是一致的，不是启动参数不同导致的问题。
> 
> 因为我没有PS设备，所以以上是我针对这个问题能做到的全部工作，很遗憾没能帮到你。

没关系的

**Comment by xing-yv** [comment]
在更新1.1版本后，问题神奇解决
