### ISSUE TITLE
[Feature] 公告栏大小自适应变化

### ISSUE THREAD

**Issue by Summer907** [Scighost/Starward#471]
### Checklist

- [X] I have already read [docs/Tips.md](https://github.com/Scighost/Starward/blob/main/docs/Tips.md), but my feature is not implemented.
- [X] My suggested feature was not mentioned by others, and it is not a duplicate feature.

### Summary

如图，当系统文本大小设置为100%以上时，下方的四个“按钮”也会同步变大，但公告栏不会，导致看上去不是很协调。

系统文本大小设置

![系统文本大小设置](https://github.com/Scighost/Starward/assets/59035726/2f67b384-6b2b-469b-b781-7533a5ce6254)

100%大小

![100%](https://github.com/Scighost/Starward/assets/59035726/e9615454-9679-40da-9696-928aed05899d)

135%大小

![135%](https://github.com/Scighost/Starward/assets/59035726/7458e2eb-9e17-4926-b5b4-b619afb59373)

### Solution or Design

能否让公告栏也加入像下方按钮这样的自适应大小改变的特性？
（主要希望能完整显示三条公告）

**Comment by Scighost** [comment]
如果你仔细看，改变文本大小之后，公告栏和下方按键的大小其实都没有变化。这个是我针对窗口和背景图调整的最佳位置和大小，跟随字体大小改变的话会显得不协调。
