### ISSUE TITLE
[Feature] 只要游戏在运行就计入游玩时间，不管是不是从starward启动

### ISSUE THREAD

**Issue by Xionghaizi001** [Scighost/Starward#472]
### Checklist

- [X] I have already read [docs/Tips.md](https://github.com/Scighost/Starward/blob/main/docs/Tips.md), but my feature is not implemented.
- [X] My suggested feature was not mentioned by others, and it is not a duplicate feature.

### Summary

如题，我经常使用hutao来启动原神以解锁高帧率，但希望使用starward来记录游玩时间，并且starward可以检测到游戏正在运行，所以希望加入这个小功能

### Solution or Design

同上

**Comment by Scighost** [comment]
@Lightczx 胡桃启动游戏后可以通过 `starward://playtime/{game_biz}` 调用 Starward 的记录游戏时间的功能。
参考 [docs/UrlProtocol.md](https://github.com/Scighost/Starward/blob/main/docs/UrlProtocol.md)

**Comment by Lightczx** [comment]
GameBiz填10有效么@Scighost

**Comment by Scighost** [comment]
https://github.com/Scighost/Starward/blob/476993d5f2342c3b33a794cc0ae6eaf76aa5b3c4/src/Starward/Services/UrlProtocolService.cs#L100

还是用 `hk4e_cn` 和 `hk4e_global` 比较合适

**Comment by Lightczx** [comment]
@Scighost 由于我们能在启动前更改注册表内账号，所以Starward需要具备统计前检测账号变化的能力

**Comment by Lightczx** [comment]
@Xionghaizi001 https://github.com/DGP-Studio/Snap.Hutao/releases/tag/2023.11.5.1 已经实现了此功能

**Comment by Lightczx** [comment]
胡桃 1.7.16 已经发布并包含了此功能 https://github.com/DGP-Studio/Snap.Hutao/releases/tag/1.7.16

@Scighost 此 Issue 可以关闭了

**Comment by Scighost** [comment]
> @Scighost 由于我们能在启动前更改注册表内账号，所以Starward需要具备统计前检测账号变化的能力

设计数据库时没有考虑到统计不同账号的游戏时间，所以实现不了此功能。
