### ISSUE TITLE
[Feature] 希望可以添加一些壁纸自动获取的功能

### ISSUE THREAD

**Issue by Rui-hub1** [Scighost/Starward#474]
### Checklist

- [X] I have already read [docs/Tips.md](https://github.com/Scighost/Starward/blob/main/docs/Tips.md), but my feature is not implemented.
- [X] My suggested feature was not mentioned by others, and it is not a duplicate feature.

### Summary

，自动获取一些好看的壁纸/或者是当前版本祈愿的角色的好看的壁纸

### Solution or Design

【希望我不是异想天开】

**Comment by Scighost** [comment]
> 【希望我不是异想天开】

是的。
