### ISSUE TITLE
[Bug] 检测游戏完整性后会删除已下载的预下载包

### ISSUE THREAD

**Issue by 3856887** [Scighost/Starward#475]
### Checklist

- [X] My issue was not mentioned by others, and it is not a duplicate issue.

### Description

检测游戏完整性后会删除已下载的预下载包

### Reproduction Steps

下载完预下载包后检测游戏完整性

### Starward Version

0.10.2

### Windows Version

22621.2428

### Log

```shell
no
```

**Comment by Scighost** [comment]
感谢反馈，这个问题会在后续版本中修复。

**Comment by Scighost** [comment]
不好意思，我把这个问题搞忘了，请再等待下个版本吧。

**Comment by Scighost** [comment]
已在 0.10.4 中修复。
