### ISSUE TITLE
[Feature] 主页的背景图片边缘模糊

### ISSUE THREAD

**Issue by Duck-Deng** [Scighost/Starward#477]
### Checklist

- [X] I have already read [docs/Tips.md](https://github.com/Scighost/Starward/blob/main/docs/Tips.md), but my feature is not implemented.
- [X] My suggested feature was not mentioned by others, and it is not a duplicate feature.

### Summary

软件背景图片的分辨率似乎不匹配，图片看上去边缘模糊。在官启上的背景图片则清晰。
![image](https://github.com/Scighost/Starward/assets/64295725/0aaf092e-2338-4676-9507-53d7ae4f28c8)
![image](https://github.com/Scighost/Starward/assets/64295725/a7cc2755-c4d1-4f7c-8230-40a8a9dc9094)

### Solution or Design

可能是图片分辨率不匹配导致的缩放问题？也许可以改为获取更高分辨率的图片解决。

**Comment by Scighost** [comment]
背景图片的分辨率只有 1280x730，米哈游不给更大的图，我也没办法。

**Comment by Duck-Deng** [comment]
但是官启的图片分辨率是正常的，Starward可以调用到相关API吗，在官网上我找到了一张高清的图片，不知道是否可以从官网抓取
![image](https://github.com/Scighost/Starward/assets/64295725/82cf7a54-5d87-434b-949c-a405b04623e2)

**Comment by Duck-Deng** [comment]
> 背景图片的分辨率只有 1280x730，米哈游不给更大的图，我也没办法。

但是官启的图片分辨率是正常的，Starward可以调用到相关API吗，在官网上我找到了一张高清的图片，不知道是否可以从官网抓取
![image](https://github.com/Scighost/Starward/assets/64295725/82cf7a54-5d87-434b-949c-a405b04623e2)

**Comment by Duck-Deng** [comment]
> 背景图片的分辨率只有 1280x730，米哈游不给更大的图，我也没办法。

或者使用这个视频作为背景也可以？

**Comment by Scighost** [comment]
很遗憾，不行。
启动器的背景会随着版本和活动更新的，有固定的api。

**Comment by Duck-Deng** [comment]
> 很遗憾，不行。 启动器的背景会随着版本和活动更新的，有固定的api。

那官启的api可以抓取到吗，官网这张图片的id和class确实是变动的，难以定位。或者改为通过启动器的版本更新来更换图片？

**Comment by Scighost** [comment]
现在用的就是官方启动器的api
