### ISSUE TITLE
[Bug] Genshin gacha url (Global Server) was changed

### ISSUE THREAD

**Issue by gawgua** [Scighost/Starward#478]
### Checklist

- [X] My issue was not mentioned by others, and it is not a duplicate issue.

### Description

https://github.com/Scighost/Starward/blob/476993d5f2342c3b33a794cc0ae6eaf76aa5b3c4/src/Starward.Core/Gacha/GachaLogClient.cs#L20

![image](https://github.com/Scighost/Starward/assets/104498646/c7c0003d-61c1-4974-862a-a41c5bf694b5)

### Reproduction Steps

Update Records

### Starward Version

0.10.2

### Windows Version

22635.2700

### Log

```shell
no log
"Cannot find URL, please open the gacha records history page in game." pop-up
```

**Comment by studiobuttermedia** [comment]
Adding a video for it as well. Yes, seems like HoYo change where Web Caches.

https://youtu.be/jHelLj50-LE

**Comment by Scighost** [comment]
Hi, thanks for your feedback. I have adapted to new web cache path from version [0.9.0](https://github.com/Scighost/Starward/releases/tag/0.9.0). Maybe it occurs something I don't know. Could you please delete `webCaches` folder and try again?

**Comment by Lightczx** [comment]
https://gs.hoyoverse.com/genshin/event/e20190909gacha-v2/index.html

**Comment by studiobuttermedia** [comment]
@Scighost I have tried deleting the `webCaches` folder, it doesn't seem to fix the issue. 

Also I tried to launch Console, but it seem that Console doesn't open. I will link that bug in a minute

**Comment by Scighost** [comment]
The prefix of gacha url of global server has been changed, so Starward cannot find it. Version [0.10.3](https://github.com/Scighost/Starward/releases/tag/0.10.3) has adapted to new url.

**Comment by Scighost** [comment]
Issue still exists in 0.10.3, reopen.

**Comment by Cecil-B-Liv** [comment]
so its a bug then, I deleted the web cache like 3 times and it still didnt work

**Comment by Scighost** [comment]
It should be fixed at [8df5726](https://github.com/Scighost/Starward/commit/8df5726b6f789ec7e803c57eaa952b9f36233c52), please download built package from [github actions](https://github.com/Scighost/Starward/actions/runs/6820438013) and try it.

**Comment by studiobuttermedia** [comment]
It is working, I was able to get the recent records of my Wish. 
(Also please don't laugh, I tried to get Furina Weapon but in some reason, I got curse the Luck of Unlucky LOL)

![image](https://github.com/Scighost/Starward/assets/55838591/31fee9be-131e-40f6-bf5f-8cb719e96d0f)

**Comment by Scighost** [comment]
Package from GitHub actions is dev version, which cannot receive update notice. Stable version [0.10.4](https://github.com/Scighost/Starward/releases/tag/0.10.4) has been released, please use it.
