### ISSUE TITLE
请问在任务栏和开始菜单没有icon是正常的吗

### ISSUE THREAD

**Issue by daishanrenL** [Scighost/Starward#48]
RT
![Snipaste_2023-06-01_19-51-08](https://github.com/Scighost/Starward/assets/112452799/e73193c0-c945-4619-9ab2-7deffddbe87b)

**Comment by Scighost** [comment]
是正常的，现在没有图标

**Comment by XHLiang0** [comment]
所以会选哪个角色作为图标呢？
星铁的角色？还是原神的角色？（手动狗头一下）
