### ISSUE TITLE
[Feature] 字体的颜色和按键颜色

### ISSUE THREAD

**Issue by wd4455** [Scighost/Starward#487]
### Checklist

- [X] I have already read [docs/Tips.md](https://github.com/Scighost/Starward/blob/main/docs/Tips.md), but my feature is not implemented.
- [X] My suggested feature was not mentioned by others, and it is not a duplicate feature.

### Summary

根据背景自动计算出的字体颜色和按键颜色确实很棒，但是背景图片灰暗的时候按键颜色也会比较暗淡，总觉得不舒服，如果换了背景图片又和当前的版本有一些冲突。

### Solution or Design

能否固定的几套明暗标准的按钮和文字选择？以及自定义颜色的选择？

**Comment by Scighost** [comment]
之前的版本有使用系统主题色的设置项，但是为了减少设置页面的内容把它删掉了，我会考虑以后加回来。

**Comment by Scighost** [comment]
从 [0.10.6-preview.1](https://github.com/Scighost/Starward/releases/tag/0.10.6-preview.1) 版本开始，你可以在 `config.ini` 文件中添加以下内容启用系统强调色：

``` ini
EnableSystemAccentColor=True
```
