### ISSUE TITLE
Starward更新失败[Question] 

### ISSUE THREAD

**Issue by ba-song** [Scighost/Starward#488]
### Checklist

- [X] I have already read [docs/Tips.md](https://github.com/Scighost/Starward/blob/main/docs/Tips.md), but my question is not solved.
- [X] My question was not mentioned by others, and it is not a duplicate question.

### Description

The process cannot access the file "D:AStarward\app-0.10.2\7zdll'  because it is being used by anotherprocess.
![image](https://github.com/Scighost/Starward/assets/59496830/d9190f4f-041a-46b9-a6ca-96ac1c021b8d)

### Starward Version

0.10.2

### Windows Version

22H2

**Comment by Scighost** [comment]
文件被占用，重启一遍就行了，如果还不行，那就在release中下载后手动覆盖。
