### ISSUE TITLE
[Bug] 原神分辨率1152x864, 1176x664无法使用

### ISSUE THREAD

**Issue by JuniesWu** [Scighost/Starward#489]
### Checklist

- [X] My issue was not mentioned by others, and it is not a duplicate issue.

### Description

原神设置或者Starward设置分辨率1152x864后  再次启动游戏时会强制成1024x768

### Reproduction Steps

Win10  Starward0.9.0开始一直存在
1.<Starward>原神-菜单-游戏设置-分辨率 选择1152x864 
菜单-启动器 开始游戏 
<原神>窗口的窗口大小实际为1024x768
Starward游戏设置的分辨率也会自动变成1024x768

2.<原神>游戏中设置-图像-显示模式 选择1152x864
关闭原神（<Starward>原神-菜单-游戏设置-分辨率 这时已同步）
<Starward> 开始游戏 
<原神>窗口的窗口大小会变成1024x768
Starward游戏设置的分辨率也会自动变成1024x768

### Expected Behavior

由于1150宽左右 最适合和B站最小普通窗口同屏 所以我比较常用

### Screenshots

![image](https://github.com/Scighost/Starward/assets/87684293/b082bd58-0bcc-4a7f-89af-c2fe5144fb95)

### Starward Version

0.10.4

### Windows Version

19045.3570

### Log

```shell
没有报错
```

**Comment by Scighost** [comment]
通过注册表修改的分辨率，不是所有的数值原神都会支持；如果想要自定义任何分辨率，你需要手动填写启动参数。
