### ISSUE TITLE
[Question] 国际服hoyolab添加，网络异常

### ISSUE THREAD

**Issue by zhangqing520** [Scighost/Starward#490]
### Checklist

- [X] I have already read [docs/Tips.md](https://github.com/Scighost/Starward/blob/main/docs/Tips.md), but my question is not solved.
- [X] My question was not mentioned by others, and it is not a duplicate question.

### Description

1

### Starward Version

0.10.4

### Windows Version

2260

### Log

```shell
1
```

### Additional Context

1

**Comment by zhangqing520** [comment]
登录国际服hoyolab时，显示403 Forbidden

**Comment by Scighost** [comment]
hoyolab 禁止中国大陆ip访问，请自行解决。

**Comment by zhangqing520** [comment]
我翻墙了，挂了梯子也一样是403






------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年11月13日(星期一) 下午3:11
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [Scighost/Starward] [Question] 国际服hoyolab添加，网络异常 (Issue #490)





 
hoyolab 禁止中国大陆ip访问，请自行解决。

**Comment by Scighost** [comment]
修改系统代理后，重启 Starward

**Comment by zhangqing520** [comment]
问题解决了




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年11月13日(星期一) 下午3:36
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [Scighost/Starward] [Question] 国际服hoyolab添加，网络异常 (Issue #490)





 
修改系统代理后，重启 Starward

**Comment by zhangqing520** [comment]
为什么开启代理需要重启，软件才能正常运行啊






------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Scighost/Starward"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年11月13日(星期一) 下午3:36
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Scighost/Starward] [Question] 国际服hoyolab添加，网络异常 (Issue #490)





 
修改系统代理后，重启 Starward

**Comment by Scighost** [comment]
> 为什么开启代理需要重启，软件才能正常运行啊

.NET Core 及以上版本在系统代理修改后，不会自动更改程序内部网络代理
