### ISSUE TITLE
[Bug] 崩坏星穹铁道新版本更新后无法应用120帧率设置

### ISSUE THREAD

**Issue by AssestinaR** [Scighost/Starward#494]
### Checklist

- [X] My issue was not mentioned by others, and it is not a duplicate issue.

### Description

如题，1.5更新后在启动器内设置120帧进入游戏后，画面设置依旧可以调整，并且帧率依旧保持60帧，重新打开启动器后发现启动器设置也变回了60帧

### Reproduction Steps

修改启动器设置120帧后正常进入游戏

### Starward Version

0.10.4

### Windows Version

22631.2506

### Log

```shell
[21:46:03.920] [INFO] Starward.Pages.MainPage
Navigate to "SettingPage" with param hkrpg_cn
```

**Comment by Scighost** [comment]
谢谢你的反馈，但是我已经不玩星穹铁道了，所以没办法帮你解决问题。

**Comment by Scighost** [comment]
我把游戏下回来测试了一下，首次进入游戏时会出现你所说的情况；退出游戏并修改帧率后，再次启动游戏可稳定在120帧左右。
<img width="280" alt="image" src="https://github.com/Scighost/Starward/assets/61003590/87d08332-fe5e-4c33-a52b-b57dab685a49">

**Comment by AssestinaR** [comment]
> 我把游戏下回来的测试场景，第一次进入游戏时会出现你所说的情况；退出游戏并修改帧率后，再次启动游戏可稳定在120帧左右。
> 
> 补充：再次修改帧率之前可能需要在游戏中调整图像分别设置。
> 
> <img alt="图像" width="280" src="https://user-images.githubusercontent.com/61003590/283446756-87d08332-fe5e-4c33-a52b-b57dab685a49.png">

**Comment by AssestinaR** [comment]
也许是我的设备问题，我刚刚再次重复重启并修改启动器设置，但依旧无法达到120帧率
![Uploading {F59026D5-5E00-4771-8455-C387C48118E8}.png…]()

**Comment by jsrgszj** [comment]
感谢作者解答

**Comment by rEco1LLLL** [comment]
> 谢谢你的反馈，但是我已经不玩星穹铁道了，所以没办法帮你解决问题。
以后不会再更新星穹铁道相关了吗
