### ISSUE TITLE
在某款游戏登录界面右下角编辑账号信息后切换到另一款游戏进行相同操作，前者编辑好的账号信息会丢失

### ISSUE THREAD

**Issue by RyanSaul** [Scighost/Starward#50]
例如在原神处编辑好账号信息
![image](https://github.com/Scighost/Starward/assets/16830734/f2dd07ce-df75-4975-9cfe-f731ac8b4bff)

再切到星穹铁道编辑账号信息
![image](https://github.com/Scighost/Starward/assets/16830734/d23d5309-b281-4845-81cd-fc6d6127d9dc)

切回原神发现账号信息丢失
![image](https://github.com/Scighost/Starward/assets/16830734/6b551076-010c-42ca-8558-4e7c2e913562)

**Comment by RyanSaul** [comment]
> 请提供一下**出现此问题时**的日志文件

我把原神和星穹铁道的账号昵称分别命名为「原」和「铁」，uid分别命名为 123456789 和 987654321
[Starward_230613_095626.log](https://github.com/Scighost/Starward/files/11729881/Starward_230613_095626.log)

**Comment by Scighost** [comment]
日志内容显示两个账号都保存成功，根据现有的日志详细程度无法排查出问题。

<img width="290" alt="image" src="https://github.com/Scighost/Starward/assets/61003590/35ef299b-a7a9-4739-bc12-1c490e019315">

**Comment by RyanSaul** [comment]
> 日志内容显示两个账号都保存成功，根据现有的日志详细程度无法排查出问题。
> 
> <img alt="image" width="290" src="https://user-images.githubusercontent.com/61003590/245339425-35ef299b-a7a9-4739-bc12-1c490e019315.png">

这个貌似还挺容易复现的，我删除软件目录再重新解压后问题还是照旧

**Comment by ItsFairladyZ** [comment]
我也是这个情况，不过我这儿测出来的是两边不能同时设置ID，不然就会丢一个
另外原神无法自动检测到UID和ID，崩铁只能读到UID
[Starward_230614_173833.log](https://github.com/Scighost/Starward/files/11744259/Starward_230614_173833.log)

**Comment by RyanSaul** [comment]
> 我也是这个情况，不过我这儿测出来的是两边不能同时设置ID，不然就会丢一个 另外原神无法自动检测到UID和ID，崩铁只能读到UID [Starward_230614_173833.log](https://github.com/Scighost/Starward/files/11744259/Starward_230614_173833.log)

一模一样的情况（

**Comment by Scighost** [comment]
突然想到还有一种可能，就是两个游戏在注册表中的登录密钥是一样的，这样把账号保存到数据库的时候会因为主键限制，后保存的账号覆盖了之前保存的账号。

需要你们查找数据库验证这种可能性，或者运行下面的 PowerShell 命令查看输出结果：

``` PowerShell
$ys = Get-ItemProperty 'HKCU:\Software\miHoYo\原神' -Name 'MIHOYOSDK_ADL_PROD_CN_h3123967166';
$sr = Get-ItemProperty 'HKCU:\Software\miHoYo\崩坏：星穹铁道' -Name 'MIHOYOSDK_ADL_PROD_CN_h3123967166'; 
$compare = Compare-Object $ys.MIHOYOSDK_ADL_PROD_CN_h3123967166  $sr.MIHOYOSDK_ADL_PROD_CN_h3123967166;
if ($compare.Length -eq 0) {
    Write-Host '两游戏密钥相同' -Foreground Red;
} else {
    Write-Host '两游戏密钥不同' -Foreground Green;
}
```

**Comment by RyanSaul** [comment]
两游戏密钥相同
![image](https://github.com/Scighost/Starward/assets/16830734/7db0d3a5-586b-418d-8f31-f97c92c4c8a8)

**Comment by Scighost** [comment]
@RyanSaul 感谢你的反馈，我将在下个版本修复这个问题。

**Comment by RyanSaul** [comment]
> @RyanSaul 感谢你的反馈，我将在下个版本修复这个问题。

辛苦了🙏

**Comment by Scighost** [comment]
已修复，此 issue 关闭。
