### ISSUE TITLE
[Feature] 是否考虑添加绝区零选项

### ISSUE THREAD

**Issue by yamadafz** [Scighost/Starward#508]
### Checklist

- [x] I have already read [docs/Tips.md](https://github.com/Scighost/Starward/blob/main/docs/Tips.md), but my feature is not implemented.
- [X] My suggested feature was not mentioned by others, and it is not a duplicate feature.

### Summary

![屏幕截图 2023-11-22 185406](https://github.com/Scighost/Starward/assets/98805571/706ac074-90f1-4c8a-9c8d-4f9201c75098)

### Solution or Design

启动器:https://autopatchcn.juequling.com/download/pclauncher/0.2.0/a3c5b964395a/ZenlessZoneZero(Beta)_20231116123435.exe

完整包:https://autopatchcn.juequling.com/download/windows/0.2.0/j0fGHf10yF5n/JueQuLing(Beta).zip

**Comment by Scighost** [comment]
绝区零正式公测前不会加入的starward中

**Comment by JtnMax** [comment]
有没有安卓的包啊？
