### ISSUE TITLE
崩坏星穹铁道调高帧率之后设置调不了，并有时会让公告卡顿、抽卡记录点不开获取不了地址。

### ISSUE THREAD

**Issue by HyBoxwood** [Scighost/Starward#51]
![QQ截图20230604215234](https://github.com/Scighost/Starward/assets/87700780/421c0985-3ff8-4fe9-b751-afc028ac71ff)
![QQ截图20230604215457](https://github.com/Scighost/Starward/assets/87700780/ed3a5ee9-ad0c-4830-90b7-422039360f60)
![QQ截图20230604215340](https://github.com/Scighost/Starward/assets/87700780/e750d644-1164-4091-a53a-26cac1aaf985)
事发截图，过后几天仅剩设置异常的问题，不调帧率立刻解决。

**Comment by XHLiang0** [comment]
这个东西就不劳烦作者了
这个120FPS导致设置选项异常的问题从开服就有了，以前改FPS是通过修改注册表的形式实现的，而且之前就有人已经试出来这个问题了，我建议你可以去搜一下B站的星铁120帧教程，作者这个相当于帮你做了一个方便修改帧率的工具接口，就免去了进注册表改120FPS的麻烦，但是不代表作者这个插件的120帧能修复这个问题，这样解释应该能理解吧。
至于另外两个问题，理论上也是受解锁高帧率的影响的，只是程度不同而已
