### ISSUE TITLE
[Feature] 官方通过登陆器更新修复的Bug无法被解决

### ISSUE THREAD

**Issue by LimitAL** [Scighost/Starward#510]
### Checklist

- [X] I have already read [docs/Tips.md](https://github.com/Scighost/Starward/blob/main/docs/Tips.md), but my feature is not implemented.
- [X] My suggested feature was not mentioned by others, and it is not a duplicate feature.

### Summary

星穹铁道1.5版本更新后出现：开启显示器HDR设置后，进入游戏画面颜色会异常的问题。
这个问题在国服和国际服版本均出现了。
几天后、国服官方发布了一个登陆器更新，通过更新官方登陆器解决了该问题。
Starward无法捕获这个更新，因此我通过打开国服登陆器，使用官方登陆器更新的方式恢复了正常，此后继续使用Startward启动也恢复了。
但国际服我是通过Starward安装的，下载的包体里并没有包含登陆器在内（也可能是我没找到），因此我无法在国际服客户端修复此问题。

### Solution or Design

是否考虑增加功能，以应对通过发布登陆器更新的方式修复的Bug？

**Comment by Scighost** [comment]
谢谢你的反馈，我无法实现你建议的内容，我无法得知官方启动器每次更新时修改了哪些代码内容，自然也做不到同步修复游戏bug。

至于国际服的问题，你可以尝试一键修复和清理注册表，如果还是有问题，我无能为力。

<img width="254" alt="image" src="https://github.com/Scighost/Starward/assets/61003590/64ce956a-d2e0-4117-823b-6830cb67e735">

**Comment by LimitAL** [comment]
感谢，我尝试了以下方法：
1.清理注册表，启动游戏->无效
2.清理注册表+临时文件，启动游戏->无效
3.完全卸载游戏再次安装->无效
不知道官方到底是在启动器做了什么修复的这个问题，很迷惑……

**Comment by LimitAL** [comment]
最后解决的办法：
1. 到国际服官网下载国际服官方启动器；
2. 在官方启动器中：“设置->游戏资源->安装位置->使用另外一个文件夹->选中Starward安装的国际服游戏本体所在的目录->确认”；
3. 官方启动器“安装游戏”按钮变更为“更新”。
4. 点击官方启动器“更新”按钮。
5. 官方启动器进行了一个0.2GB的数据下载，并更新了游戏。
6. 关闭官方启动器。
7. 使用Starward再次启动游戏。
8. 问题解决。
