### ISSUE TITLE
[Question] 账号记录是什么原理，只要电脑关机就全部失效

### ISSUE THREAD

**Issue by thouwave** [Scighost/Starward#512]
### Checklist

- [X] I have already read [docs/Tips.md](https://github.com/Scighost/Starward/blob/main/docs/Tips.md), but my question is not solved.
- [X] My question was not mentioned by others, and it is not a duplicate question.

### Description

即使是电脑重启达到基本完全一致的操作环境，依然无法通过starward直接登录账号。但是如果电脑选择休眠，那么再开启时就可以正常通过starward直接登录账号

### Starward Version

0.10.4

### Windows Version

22631.2715

**Comment by gaoziqia111217** [comment]
同上

**Comment by Scighost** [comment]
https://github.com/Scighost/Starward/issues/159#issuecomment-1638012150
