### ISSUE TITLE
[Feature] Add BiliBili Server for Genshin Impact and Honkai: Star Rail

### ISSUE THREAD

**Issue by studiobuttermedia** [Scighost/Starward#515]
### Checklist

- [X] I have already read [docs/Tips.md](https://github.com/Scighost/Starward/blob/main/docs/Tips.md), but my feature is not implemented.
- [ ] My suggested feature was not mentioned by others, and it is not a duplicate feature.

### Summary

I recently created and verify a new BiliBili account and got access to BiliBili server version of Genshin Impact and Honkai: Star Rail. I saw another Launcher (Collapse) recently added as an experiment and don't know if we can add it in the server list.

[Genshin Impact](https://www.biligame.com/detail/?id=103496)

[Honkai: Star Rail](https://www.biligame.com/detail/?id=108586)

### Solution or Design

Add a button to switch to BiliBili (China) server for Genshin and Star Rail
![image](https://github.com/Scighost/Starward/assets/55838591/10094539-162a-4fc7-abcd-33ea47eff0c6)

Edit: One of the checklist was unchecked after found out the feature was mentioned before by a Chinese Speaker although using a different method instead.

**Comment by studiobuttermedia** [comment]
The Image somehow broke when copying, tho I hope you get what I mean

**Comment by studiobuttermedia** [comment]
Update: I recently dig to the BiliBili Launcher for Star Rail and found the API Key for Star Rail Download Links

[Star Rail API Link](https://api-launcher-static.mihoyo.com/hkrpg_cn/mdk/launcher/api/resource?channel_id=14&key=fSPJNRwFHRipkprW&launcher_id=28&sub_channel_id=0)

**Comment by studiobuttermedia** [comment]
Update: After 8 hours of sleep and 6 hours of studying. I was able to find the API for Genshin BiliBili download links.

[Genshin BiliBili API Link](https://hk4e-launcher-static.mihoyo.com/hk4e_cn/mdk/launcher/api/resource?channel_id=14&key=KAtdSsoQ&launcher_id=17&sub_channel_id=0)

Also one thing to note: BiliBili server doesn't have the information board and no Social Links

**Comment by Scighost** [comment]
Thanks for your work, but I have no plans to support Bilibili server in the short term. Maybe is would be implemented later, I am not sure.

**Comment by Scighost** [comment]
Implemented on [0.10.7-preview.2](https://github.com/Scighost/Starward/releases/tag/0.10.7-preview.2)
