### ISSUE TITLE
希望原神自定义分辨率下限提高

### ISSUE THREAD

**Issue by gaoziqia111217** [Scighost/Starward#516]
### Checklist

- [X] I have already read [docs/Tips.md](https://github.com/Scighost/Starward/blob/main/docs/Tips.md), but my feature is not implemented.
- [X] My suggested feature was not mentioned by others, and it is not a duplicate feature.

### Summary

原神横向分辨率小于720时会强制更改为768 纵向小于1024会限制变更为1024 这对想要竖屏和21:9 32:9 等玩家们不方便

**Comment by Scighost** [comment]
https://github.com/Scighost/Starward/issues/489#issuecomment-1817450847
