### ISSUE TITLE
崩坏星穹铁道的抽卡记录切换账号的位置这点按钮空间是认真的吗

### ISSUE THREAD

**Issue by HyBoxwood** [Scighost/Starward#52]
![QQ截图20230604214830](https://github.com/Scighost/Starward/assets/87700780/45e4b49b-d7f1-44e5-b5ff-7dba97849392)

**Comment by duobuhui** [comment]
我也遇到了。当uid这部分和导航栏重叠的地方不能被点到 ![screenshot](https://631266.freep.cn/631266/QQ%E6%88%AA%E5%9B%BE20230606212846.png)

**Comment by Lightczx** [comment]
https://github.com/microsoft/microsoft-ui-xaml/issues/7756 @Scighost

**Comment by Lightczx** [comment]
他们总共就10个人

**Comment by Scighost** [comment]
竟然自动关闭了
