### ISSUE TITLE
[Feature] 导航菜单栏常驻窗口左侧

### ISSUE THREAD

**Issue by Scighost** [Scighost/Starward#520]
为了进一步提升在不同页面间的切换效率，考虑把导航菜单栏常驻在窗口左侧。效果图如下：

![image](https://github.com/Scighost/Starward/assets/61003590/cb4095a1-4ae3-4228-96aa-2cb0e940863f)

不可避免地存在许多问题，后面细聊。

**Comment by Scighost** [comment]
- 菜单侧栏无亚克力效果，使用浅色背景图时什么都看不清
- 标题栏图标左侧存在分隔菜单侧栏和主内容区的浅黑色竖线
- 背景图“原神”图标没有和轮播图区域对其

![image](https://github.com/Scighost/Starward/assets/61003590/1f6d1fed-d1da-4c33-b9fb-e3d968ef897d)

**Comment by Scighost** [comment]
- 菜单侧栏第一项选中时的背景高亮区域和标题栏的可拖动区域有少许重合部分，菜单项需整体下移

<img width="257" alt="image" src="https://github.com/Scighost/Starward/assets/61003590/2d2830b6-6aba-41b9-8457-da7a6d3ce703">

- 页面的直角边很丑

<img width="157" alt="image" src="https://github.com/Scighost/Starward/assets/61003590/b493d0c0-ae08-4d4f-8026-5a0fba8d27c8">

**Comment by Scighost** [comment]
- 浏览截图时上方的返回键无法点击，打开导航按键消失不见

![image](https://github.com/Scighost/Starward/assets/61003590/b9ab21e2-2adf-4e9b-a793-3a7cb4348a81)

**Comment by Scighost** [comment]
- 侧栏常驻后，右侧空间减少，导致部分页面出现元素重叠的问题

![image](https://github.com/Scighost/Starward/assets/61003590/f3de68d2-0d0a-464a-931c-e88d86f445ca)

**Comment by Scighost** [comment]
> * 浏览截图时上方的返回键无法点击，打开导航按键消失不见
> 
> ![image](https://private-user-images.githubusercontent.com/61003590/287459884-b9ab21e2-2adf-4e9b-a793-3a7cb4348a81.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDE1Mzg5ODMsIm5iZiI6MTcwMTUzODY4MywicGF0aCI6Ii82MTAwMzU5MC8yODc0NTk4ODQtYjlhYjIxZTItMmFkZi00ZTliLWE3OTMtM2E3Y2I0MzQ4YTgxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjAyVDE3MzgwM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTM1OWI5YWNlMjM2YmY4YzJiNzFkOTM3MDE4ZTk4OTNlZDcyM2M0NGYwNmVhZGVjNzAzZGVkY2ZlM2Q1MzA0ODcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.VzH_F3IMetsuhpH3L4pjdzlmEEyD8dSsurV4C_OhIXA)

此问题仍然存在，将通过 #519 修复

**Comment by Scighost** [comment]
已在 [0.10.6-preview.1](https://github.com/Scighost/Starward/releases/tag/0.10.6-preview.1) 中实现

**Comment by gaoziqia111217** [comment]
@Scighost  可以增加一个自由开关按钮吗 个人觉得之前的好看
