### ISSUE TITLE
添加地图功能

### ISSUE THREAD

**Issue by gaoziqia111217** [Scighost/Starward#521]
### Checklist

- [X] I have already read [docs/Tips.md](https://github.com/Scighost/Starward/blob/main/docs/Tips.md), but my feature is not implemented.
- [X] My suggested feature was not mentioned by others, and it is not a duplicate feature.

### Summary

请在游戏或启动器内添加一个地图(空荧酒馆原神地图是我见过最好用的)

### Solution or Design

.

**Comment by Scighost** [comment]
谢谢你的建议，但是此功能无必要，我拒绝。
