### ISSUE TITLE
[Question] How To Fix the Parameter

### ISSUE THREAD

**Issue by YukiMitsuki** [Scighost/Starward#525]
### Checklist

- [X] I have already read [docs/Tips.md](https://github.com/Scighost/Starward/blob/main/docs/Tips.md), but my question is not solved.
- [X] My question was not mentioned by others, and it is not a duplicate question.

### Description

I have tried a lot to install the game but still trigger with this error, how can i fix (use 0.10.6 but trigger the same error)
![image_2023-12-04_214801266](https://github.com/Scighost/Starward/assets/140571908/e884ff39-216d-431c-b41e-6a3be8ad1d80)

### Starward Version

0.10.4

### Windows Version

19045.3693

**Comment by YukiMitsuki** [comment]
[Uploading log-2023-12-04-pre1.71.3-id1.log…]()

**Comment by YukiMitsuki** [comment]
[log-2023-12-04-pre1.71.3-id1.log](https://github.com/Scighost/Starward/files/13548178/log-2023-12-04-pre1.71.3-id1.log)
here i think ...

**Comment by Scighost** [comment]
Why were you upload the log of Collapse Launcher?

<img src="https://github.com/Scighost/Starward/assets/61003590/d4797ac6-904b-4f0c-9cc3-c757e9d070bf" width="200px" />

**Comment by Scighost** [comment]
In setting page...

<img width="148" alt="image" src="https://github.com/Scighost/Starward/assets/61003590/272d7791-8e17-43a2-8a74-1d419464fca7">

There are many log files in this folder, you should delete all of them firstly. Then try download game again and upload the latest log file.

**Comment by YukiMitsuki** [comment]
[Starward_231204_230602.log](https://github.com/Scighost/Starward/files/13548684/Starward_231204_230602.log)
here ...

**Comment by Scighost** [comment]
You were not allow to choose the root of a drive as the game folder, like `D:\`. You should create a new subfolder and select it.
