### ISSUE TITLE
[Feature] 启动游戏时不自动最小化启动器窗口

### ISSUE THREAD

**Issue by 1625423178** [Scighost/Starward#527]
### Checklist

- [X] I have already read [docs/Tips.md](https://github.com/Scighost/Starward/blob/main/docs/Tips.md), but my feature is not implemented.
- [X] My suggested feature was not mentioned by others, and it is not a duplicate feature.

### Summary

有时候我要同时启动多个游戏，但每次启动第一个游戏，启动器就会最小化到托盘，我需要重新唤醒启动器或者在系统托盘里启动其他游戏。

### Solution or Design

在设置中新增一个 启动游戏时最小化窗口 的开关。

哦对了，新UI很不错耶！

**Comment by Scighost** [comment]
谢谢你的建议

**Comment by RosieDu21** [comment]
@Scighost 

我来求一个相反的：希望加一个选项，所有从启动器启动的游戏关闭后自动弹出启动器，就像官方启动器一样

**Comment by 1625423178** [comment]
> @Scighost
> 
> 我来求一个相反的：希望加一个选项，所有从启动器启动的游戏全部都关闭后自动弹出启动器，就像官方启动器一样

这个需求在我发布的 issue #283 已被提出，作者表明为减少资源占用而不实现此需求。

**Comment by Scighost** [comment]
已实现 [0.10.7-beta.1](https://github.com/Scighost/Starward/releases/tag/0.10.7-beta.1)
