### ISSUE TITLE
[Bug] 切换游戏会导致内存占用增加

### ISSUE THREAD

**Issue by moyujunaimoyu** [Scighost/Starward#528]
### Checklist

- [X] My issue was not mentioned by others, and it is not a duplicate issue.

### Description

在程序使用过程中，在上方切换游戏可能会导致内存增加
从约80MB增长到了约300MB占用

### Reproduction Steps

1.打开软件
2.在上方的三款游戏进行切换
3.在任务管理器中即可看到内存增加

### Screenshots

![1701734914972](https://github.com/Scighost/Starward/assets/125355634/102d228a-9ced-483a-9411-e763d764cca0)

### Starward Version

0.10.4

### Windows Version

19045.3448

### Log

```shell
[07:21:04.660] [INFO] 
Welcome to Starward v0.10.4
System: Microsoft Windows NT 10.0.19045.0
Command Line: "B:\Star Ward\app-0.10.4\Starward.dll" playtime --biz bh3_cn --pid 7256

[07:21:04.718] [INFO] Starward.Services.DatabaseService
Database path is 'B:\Star Ward'

[07:21:04.743] [INFO] Starward.Services.DatabaseService
Database version is 7, target version is 7.
```

**Comment by Scighost** [comment]
内存占用增加是正常现象，我也想尽可能减少内存占用，但是没那个能力你知道嘛

**Comment by moyujunaimoyu** [comment]
我个人觉得这不属于正常现象...
这里有个视频
https://github.com/Scighost/Starward/assets/125355634/318e12c8-3298-45d0-ad3e-1c738df57fa7

**Comment by moyujunaimoyu** [comment]
https://github.com/Scighost/Starward/assets/125355634/2b7e5a22-2be4-4340-a055-ecf7e5e2d9f3

**Comment by Lightczx** [comment]
https://github.com/microsoft/microsoft-ui-xaml/issues/9044
