### ISSUE TITLE
开拓月历功能，别逼我跪下来求你。

### ISSUE THREAD

**Issue by HyBoxwood** [Scighost/Starward#53]

**Comment by HyBoxwood** [comment]
大佬这个月内不更新四月的记录就没得查了，求求了Orz。

**Comment by Scighost** [comment]
不要急，急也没用

![image](https://github.com/Scighost/Starward/assets/61003590/65d0b47a-1096-4235-9e7f-659d7d9e1fd7)

**Comment by HyBoxwood** [comment]
急急急急急
![QQ截图20230611015333](https://github.com/Scighost/Starward/assets/87700780/628c0e94-f9fb-421b-b2d7-9e8eebc61b1e)

**Comment by Scighost** [comment]
最后一天，赶上了
