### ISSUE TITLE
[Bug] 四星角色抽卡数计算有误

### ISSUE THREAD

**Issue by he0119** [Scighost/Starward#531]
### Checklist

- [X] My issue was not mentioned by others, and it is not a duplicate issue.

### Description

当四星中间有五星出现时，会影响抽卡数的计算，导致出现11抽出的奇怪数据。

### Reproduction Steps

两次四星之间有五星出现。

### Expected Behavior

这种时候，这个四星应该是1抽就出？

### Screenshots

![image](https://github.com/Scighost/Starward/assets/5219550/16774d04-1e67-4323-8a75-328706c7a3f3)
![f2621d0d4e56e235ea5b4fde4d91202a](https://github.com/Scighost/Starward/assets/5219550/2f5f82fa-dae3-42c5-8f7a-9b90bef31d5a)
![0e77ca2025ce3a618be716fb65ab6a1b](https://github.com/Scighost/Starward/assets/5219550/194c1893-c618-40ae-9c1b-1611d9b6dd26)
![afc333a23f6f1ace8130d3ce94d3d664](https://github.com/Scighost/Starward/assets/5219550/53beaad9-bc27-4f25-a36e-00ab1b3e0463)

### Starward Version

0.10.4

### Windows Version

22631.2715

### Log

```shell
无
```

**Comment by Scighost** [comment]
没有问题，五星把四星挤到后面去了
