### ISSUE TITLE
备份数据库如何使用？

### ISSUE THREAD

**Issue by Xie19990416** [Scighost/Starward#534]
### Checklist

- [X] I have already read [docs/Tips.md](https://github.com/Scighost/Starward/blob/main/docs/Tips.md), but my question is not solved.
- [X] My question was not mentioned by others, and it is not a duplicate question.

### Description

请问启动器里面备份数据库保存的数据如何使用？
我不小心删除了软件重新下载回来是全新的，有以前的备份数据库的文件不知道如何利用它恢复以前的抽卡记录

### Starward Version

1

### Windows Version

22621

**Comment by Scighost** [comment]
备份数据库是为了防止主数据库文件损坏，在你选择的数据文件夹中找到 `DatabaseBackup` 文件夹里的数据库备份文件，类似 `StarwardDatabase_20231209_163814.db`。删除掉文件命末尾的时间日期后替换上一级的文件 `StarwardDatabase.db`。

**Comment by Xie19990416** [comment]
> 备份数据库是为了防止主数据库文件损坏，在你选择的数据文件夹中找到 文件夹里的数据库备份文件，类似 。删除掉文件命末尾的时间日期后替换上一级的文件 。`DatabaseBackup``StarwardDatabase_20231209_163814.db``StarwardDatabase.db`

谢谢，就是这个，我的抽卡记录都回来了！
