### ISSUE TITLE
[Feature] Manually input gacha records

### ISSUE THREAD

**Issue by Flyingbacen** [Scighost/Starward#535]
### Checklist

- [X] I have already read [docs/Tips.md](https://github.com/Scighost/Starward/blob/main/docs/Tips.md), but my feature is not implemented.
- [X] My suggested feature was not mentioned by others, and it is not a duplicate feature.

### Summary

I had to reinstall Star Rail recently, along with Starward, and after updating gacha records, it didn't obtain records from a few months ago around when it launched. I have the complete record on starrail station, but their [json export](https://github.com/Scighost/Starward/files/13626293/starrailstation-backup_2023-12-8.json) isn't compatible with yours.

### Solution or Design

add a button to manually add a record, including time and character/item in the records page

**Comment by Scighost** [comment]
Thanks for your feedback. Starward only accepts data in the HoYoverse API format. An example is provided below.

``` json
{
      "gacha_id": "1001",
      "uid": "123456789",
      "id": "1682475000047139489",
      "gacha_type": "1",
      "name": "艾丝妲",
      "item_type": "角色",
      "rank_type": "4",
      "time": "2023-04-26 10:56:54",
      "item_id": "1009",
      "count": "1",
      "lang": "zh-cn"
}
```

Any JSON file containing the data model mentioned above can be imported into Starward. However, the files exported from Starrail Station use a custom format, so they are not supported for import.

In addition, manually editing records can be a complex work. I recommend you directly edit the Starward SQLite3 database file `StarwardDatabase.db`. Professional database management tools offer powerful editing features far beyond what I can compare to. The table corresponding to warp records is `StarRailGachaItem` in the Starward database.

**Comment by Flyingbacen** [comment]
May I ask how I'm supposed to find the Id/ItemID? Not too versed in hoyoverse api

**Comment by Scighost** [comment]
| hoyoverse | starrail station|
|---|---|
| uid |  |
| uid |  |
| uid |  |
| uid |  |

**Comment by Flyingbacen** [comment]
ah, thank you
