### ISSUE TITLE
[Feature] 可否考虑增加从BetterGI启动原神的功能

### ISSUE THREAD

**Issue by goldenapple1** [Scighost/Starward#537]
### Checklist

- [X] I have already read [docs/Tips.md](https://github.com/Scighost/Starward/blob/main/docs/Tips.md), but my feature is not implemented.
- [X] My suggested feature was not mentioned by others, and it is not a duplicate feature.

### Summary

如题

### Solution or Design

https://github.com/babalae/better-genshin-impact
我觉得只是从命令行启动就相当足够了，大不了我再多点一次启动原神

**Comment by Scighost** [comment]
我无法从标题中理解你的需求，能否更详细地描述一下。

**Comment by Duck-Deng** [comment]
> 我无法从标题中理解你的需求，能否更详细地描述一下。

BatterGI是一个“基于计算机视觉技术的原神辅助软件”[GitHub](https://github.com/babalae/better-genshin-impact)，议题的意思可能是支持通过BatterGI来启动游戏，因为只有这样才能使用该软件的功能
![image](https://github.com/Scighost/Starward/assets/64295725/d85f1eff-32a2-4e73-b0c3-1f87d5f7cfc3)

**Comment by Duck-Deng** [comment]
![image](https://github.com/Scighost/Starward/assets/64295725/a2d1cc46-1ae0-4d88-ac8a-38ce4a1eac10)
通过自定义启动程序能不能实现这一功能？将这个路径指向batterGI

**Comment by goldenapple1** [comment]
> ![image](https://private-user-images.githubusercontent.com/64295725/289370155-a2d1cc46-1ae0-4d88-ac8a-38ce4a1eac10.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDIyMzYxNDMsIm5iZiI6MTcwMjIzNTg0MywicGF0aCI6Ii82NDI5NTcyNS8yODkzNzAxNTUtYTJkMWNjNDYtMWFlMC00ZDg4LWFjOGEtMzhjZTRhMWVhYzEwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjEwVDE5MTcyM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTFmNTE5MGMyYzIzYjlkNGIxY2YwZDkwMTYzYWQ5NTYxYmJmZGI5MzI4ZTA1NjZlMzQ1N2UwMzgxNGRmN2RlNDUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.a7CdAbTmfPLol3Fit_07rCVvKLiRvHRK7sK6a8QbH0k) 通过自定义启动程序能不能实现这一功能？将这个路径指向batterGI

不完全是我想要的，但是很接近了，我想让starward启动betterGI并且启动游戏，或者给betterGI传参数让betterGI启动游戏？

**Comment by goldenapple1** [comment]
顺便我刚刚好像发现starward 0.10.4没有单例模式，这个建议作者加上

**Comment by Scighost** [comment]
> 不完全是我想要的，但是很接近了，我想让starward启动betterGI并且启动游戏，或者给betterGI传参数让betterGI启动游戏？

@goldenapple1 Starward 不支持给自定义启动程序传递参数，Better GI 也暂时不支持接受启动参数。我建议你编写一个 bat 脚本分别启动原神和 Better GI，然后把脚本文件设置为 Starward 的启动程序。

> 顺便我刚刚好像发现starward 0.10.4没有单例模式，这个建议作者加上

@goldenapple1 启用系统托盘功能后是单例模式

**Comment by goldenapple1** [comment]
> @goldenapple1 Starward 不支持给自定义启动程序传递参数，Better GI 也暂时不支持接受启动参数。我建议你编写一个 bat 脚本分别启动原神和 Better GI，然后把脚本文件设置为 Starward 的启动程序。

确实可以是一种临时解决方案，这个问题暂时挂在这里吧，如果BetterGI那边支持启动参数了我再来这边同步（也有可能我哪天闲的蛋疼就去给BetterGI发PR加上这个功能了

> @goldenapple1 启用系统托盘功能后是单例模式

![image](https://github.com/Scighost/Starward/assets/56142186/2e918760-16a3-41a5-a1ff-11f9a83bd193)

但是似乎在我开机之后没有重启资源管理器的情况下单例模式是不生效的，而且重启了不仅是starward的图标有概率回不来，还有概率把我Steam和TranslucentTB的图标给扬了

![image](https://github.com/Scighost/Starward/assets/56142186/c6d858e8-78bc-401e-aa5a-ea87bf24c109)

TranslucentTB好像跟starward用了同一种框架，Steam新版我不太清楚，有可能是框架本身的问题导致的。
我又试了几下，好像只要有一次重启之后图标出现了，单例模式和图标功能就不会再出问题，即使进程关闭之后再开软件也不会再有问题

我在我本地开关托盘图标或者直接点击放在桌面上的快捷方式都有机会把程序玩坏一次，不知道是什么原理，有时候是可以双例但是不能开更多，但是和上面一样，出过一次就不能复现。

我觉得全局单例可能更好，单例模式和托盘绑定这听起来很奇怪。

**Comment by goldenapple1** [comment]
> 勾选这一项可以吗，如果实现不完美，可能得要等batterGI支持参数启动

暂时能用吧，只能等一手BetterGI的自定义参数实现了

**Comment by Lightczx** [comment]
@goldenapple1 
![image](https://github.com/Scighost/Starward/assets/36357191/a19e222f-2b70-4b62-8e53-5258dc29e3d5)
BetterGIy已经实现此功能

@Scighost FYI

**Comment by goldenapple1** [comment]
@Lightczx 我说的启动参数不是指betterGI启动原神的时候要填的参数，而是指betterGI程序本身的参数，比如通过参数直接启动自己的实例并且启动原神。目前应该是只实现了URL协议启动

**Comment by Lightczx** [comment]
目前可以不使用Starward启动原神了，所以这个功能没有必要

**Comment by goldenapple1** [comment]
> 目前可以不使用Starward启动原神了，所以这个功能没有必要

但是betterGI只管原神不管其他的

**Comment by WoshiRedstone** [comment]
> > 目前可以不使用Starward启动原神了，所以这个功能没有必要
> 
> 但是betterGI只管原神不管其他的
bettergi有url协议
bettergi://start
