### ISSUE TITLE
修复按钮是灰色的

### ISSUE THREAD

**Issue by lijusting** [Scighost/Starward#541]
![PixPin_2023-12-15_05-50-13](https://github.com/Scighost/Starward/assets/74657956/95eb9450-227f-43d1-9079-42b626b92bc3)

第一次使用，根据教程，定位游戏安装目录之后，修复按钮为灰色，点不了
希望能有更加详细的教程，找不到日志文件

starward版本 0.10.6
window版本 22635.2915

**Comment by Scighost** [comment]
安装目录是包含 `YuanShen.exe` 的文件夹

**Comment by lijusting** [comment]
了解了，谢谢，已经弄好了，建议把这句话 “安装目录是包含 YuanShen.exe 的文件夹“ 加入到使用教程中，让更多的人更容易理解一些
![PixPin_2023-12-16_07-42-59](https://github.com/Scighost/Starward/assets/74657956/8e336846-dd9d-401e-821f-91aac678bc4b)
