### ISSUE TITLE
[Feature] 希望祈愿记录页面中切换uid的下拉框内容增加昵称

### ISSUE THREAD

**Issue by supersux** [Scighost/Starward#542]
### Checklist

- [X] I have already read [docs/Tips.md](https://github.com/Scighost/Starward/blob/main/docs/Tips.md), but my feature is not implemented.
- [X] My suggested feature was not mentioned by others, and it is not a duplicate feature.

### Summary

当前祈愿记录页面下拉框中只有`uid`，`uid`  这个东西不是很好记，在切换的时候通常不知道切换到哪个昵称的账号了，这对于多账号多记录的人来说非常的难受，希望增加一下昵称，作者大大可以有限实现一下，谢谢作者大大❤️❤️了

`当前状态`
![1702653740627](https://cdn.jsdelivr.net/gh/supersux/pichub@main/1702653740627.webp)

`目标状态`
![1702653740629](https://cdn.jsdelivr.net/gh/supersux/pichub@main/1702653740629.webp)

### Solution or Design

不知道这个昵称可以直接从请求中提取，如果提取不出来的话可以增加自己编辑的选项

**Comment by Scighost** [comment]
谢谢你的建议，但是昵称只能由你自己填写

**Comment by Scighost** [comment]
抱歉，我错看成了账号切换的昵称。

抽卡记录的页面不能显示昵称，也不能自己填写。当初在设计数据库结构的时候没有考虑到这一点，以后可能会加上。

**Comment by supersux** [comment]
> 抱歉，我错看成了账号切换的昵称。
> 
> 抽卡记录的页面不能显示昵称，也不能自己填写。当初在设计数据库结构的时候没有考虑到这一点，以后可能会加上。

因为在切换账号的时候是可以自己添加昵称的，所以在展示抽卡记录的时候是否可以直接读取一下这里保存的内容

**Comment by Scighost** [comment]
抱歉，经考虑后我决定不实现此功能。
