### ISSUE TITLE
[Question] 星穷铁道启动问题

### ISSUE THREAD

**Issue by PJnoeru** [Scighost/Starward#544]
### Checklist

- [X] I have already read [docs/Tips.md](https://github.com/Scighost/Starward/blob/main/docs/Tips.md), but my question is not solved.
- [X] My question was not mentioned by others, and it is not a duplicate question.

### Description

在使用官方启动器时，可以正常启动游戏，使用starward启动游戏时提示（3，1051，150002 您的游戏环境异常，请重启机器后再试）
![image](https://github.com/Scighost/Starward/assets/41642563/c700e4c6-5929-450a-8e3e-b37a928f26d7)

不知道是游戏更新了什么，还是windows更新了什么，之前一直没有问题。突然开始提示该问题。包括直接运行游戏目录下的【StarRail.exe】

### Starward Version

0.10.6-preview.1

### Windows Version

22631.2861

**Comment by Scighost** [comment]
很抱歉，我已经不玩星穹铁道了，没办法帮助到你

**Comment by PJnoeru** [comment]
好吧，询问了朋友，说是可能和（卡拉彼丘）一样，为了防作弊，只能官方启动器启动

目前的解决方案是自定义启动程序到官方启动器
![image](https://github.com/Scighost/Starward/assets/41642563/46a49ee0-49ee-4ce4-a32b-7c6a924a77e0)

**Comment by whomtao** [comment]
> 好吧，询问了朋友，说是可能和（卡拉彼丘）一样，为了防作弊，只能官方启动器启动
> 
> 目前的解决方案是自定义启动程序到官方启动器 ![image](https://private-user-images.githubusercontent.com/41642563/290990148-46a49ee0-49ee-4ce4-a32b-7c6a924a77e0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI4MTU2NjUsIm5iZiI6MTcwMjgxNTM2NSwicGF0aCI6Ii80MTY0MjU2My8yOTA5OTAxNDgtNDZhNDllZTAtNDllZS00Y2U0LWEzMmItN2M2YTkyNGE3N2UwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjE3VDEyMTYwNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTFjOTY1OGUwM2JkYmVhNzNkZTAxZTE0YTRlMDk1Mjg1NmFkZDkyYmE5MjM5Njc3OWYyMWIwZDMxYTA3MGUzZDYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Lz9E_Uek3luelhCToZzm7Jbr2JcOJ8uZYC8EKeHEU84)

我没遇到这个问题诶，就是默认的参数，通过starward就能直接运行崩铁
![QQ截图20231217201750](https://github.com/Scighost/Starward/assets/35491658/78ea60e0-0735-4783-a12c-d7370b12548c)

**Comment by PJnoeru** [comment]
> > 好吧，询问了朋友，说是可能和（卡拉彼丘）一样，为了防作弊，只能官方启动器启动
> > 目前的解决方案是自定义启动程序到官方启动器![图像](https://private-user-images.githubusercontent.com/41642563/290990148-46a49ee0-49ee-4ce4-a32b-7c6a924a77e0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI4MTU2NjUsIm5iZiI6MTcwMjgxNTM2NSwicGF0aCI6Ii80MTY0MjU2My8yOTA5OTAxNDgtNDZhNDllZTAtNDllZS00Y2U0LWEzMmItN2M2YTkyNGE3N2UwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjE3VDEyMTYwNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTFjOTY1OGUwM2JkYmVhNzNkZTAxZTE0YTRlMDk1Mjg1NmFkZDkyYmE5MjM5Njc3OWYyMWIwZDMxYTA3MGUzZDYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Lz9E_Uek3luelhCToZzm7Jbr2JcOJ8uZYC8EKeHEU84)
> 
> 我没遇到这个问题诶，就是默认的参数，通过starward就能直接运行崩铁 ![QQ截图20231217201750](https://private-user-images.githubusercontent.com/35491658/291061248-78ea60e0-0735-4783-a12c-d7370b12548c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI4MTY3NTEsIm5iZiI6MTcwMjgxNjQ1MSwicGF0aCI6Ii8zNTQ5MTY1OC8yOTEwNjEyNDgtNzhlYTYwZTAtMDczNS00NzgzLWExMmMtZDczNzBiMTI1NDhjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjE3VDEyMzQxMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWYyNDhiMTNjNDVkMzdlNDdkZTU1MzViY2QyYWE5MGIzMmZmZWQyNDEwYzI5ZWFmMWVjMjBjZTU0M2UyMzI1MTAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.cyOz4dxRFLoi1Mz2DBzdtfdVDRNmJlAI-VvCyc9Y7bc)

不知道是哪里的问题，两台电脑均有该情况，即使是手动启动游戏目录中的exe程序也会提示，有时候启动没问题，大部分时间都是提示环境异常

**Comment by gongfuture** [comment]
可能是运行中的软件有被误判成作弊器的？比如说我之前测试过，cheat engine打开的时候启动星铁就会弹这个，关掉就好了

**Comment by PJnoeru** [comment]
> 可能是运行中的软件有被误判成作弊器的？比如说我之前测试过，cheat engine打开的时候启动星铁就会弹这个，关掉就好了

![image](https://github.com/Scighost/Starward/assets/41642563/bc36c906-6845-41ec-a801-9a4d76c0290a)
并没有任何类似ce的修改器在后台运行。。。

**Comment by PJnoeru** [comment]
> 可能是运行中的软件有被误判成作弊器的？比如说我之前测试过，cheat engine打开的时候启动星铁就会弹这个，关掉就好了

![image](https://github.com/Scighost/Starward/assets/41642563/1055dfc5-632f-4289-ae04-8cdf85c24368)

并没有任何类似ce的修改器在后台运行。。。

**Comment by gongfuture** [comment]
好神奇的防撤回bot（

**Comment by gongfuture** [comment]
> > 可能是运行中的软件有被误判成作弊器的？比如说我之前测试过，cheat engine打开的时候启动星铁就会弹这个，关掉就好了
> 
> ![image](https://private-user-images.githubusercontent.com/41642563/291145248-1055dfc5-632f-4289-ae04-8cdf85c24368.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI4NzE3NzgsIm5iZiI6MTcwMjg3MTQ3OCwicGF0aCI6Ii80MTY0MjU2My8yOTExNDUyNDgtMTA1NWRmYzUtNjMyZi00Mjg5LWFlMDQtOGNkZjg1YzI0MzY4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjE4VDAzNTExOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTk3YWNkN2Q1ZjAxYWYwOGI5ODg3M2Y0M2M1ZDk2MTY4Zjg0NGY2ZGJiMWZiZTU3NjI3YjllM2FlMGVmMmRjMGEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.WqEu2RTeGQD-DcRCHB0UCKW5Z4rlRqgXbeU2VhbeN9Y)
> 
> 并没有任何类似ce的修改器在后台运行。。。

这我就不清楚了啊qwq，我只是提供一个思路，你可以一点点的排查看看，我估计是名字相似被星铁误判了可能

**Comment by PJnoeru** [comment]
发现用官方启动器运行的星铁，obs无法通过游戏源捕捉画面（obs已经以管理员权限运行）

> > > 可能是运行中的软件有被误判成作弊器的？比如说我之前测试过，cheat engine打开的时候启动星铁就会弹这个，关掉就好了
> > 
> > 
> > ![image](https://private-user-images.githubusercontent.com/41642563/291145248-1055dfc5-632f-4289-ae04-8cdf85c24368.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI4NzE3NzgsIm5iZiI6MTcwMjg3MTQ3OCwicGF0aCI6Ii80MTY0MjU2My8yOTExNDUyNDgtMTA1NWRmYzUtNjMyZi00Mjg5LWFlMDQtOGNkZjg1YzI0MzY4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjE4VDAzNTExOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTk3YWNkN2Q1ZjAxYWYwOGI5ODg3M2Y0M2M1ZDk2MTY4Zjg0NGY2ZGJiMWZiZTU3NjI3YjllM2FlMGVmMmRjMGEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.WqEu2RTeGQD-DcRCHB0UCKW5Z4rlRqgXbeU2VhbeN9Y)
> > 并没有任何类似ce的修改器在后台运行。。。
> 
> 这我就不清楚了啊qwq，我只是提供一个思路，你可以一点点的排查看看，我估计是名字相似被星铁误判了可能

以官方启动器运行的星铁，无法在管理员权限运行的obs中通过游戏源捕捉画面。。
稍后把后台程序全部退出后尝试看看。

**Comment by PJnoeru** [comment]
> 可能是运行中的软件有被误判成作弊器的？比如说我之前测试过，cheat engine打开的时候启动星铁就会弹这个，关掉就好了

微软电脑管家。。。3.3.9.0版本，，一台电脑退出正常了，一台电脑卸载后正常了，在退出的电脑上再次打开微软电脑管家，环境异常再次出现。。。。
![2d681f1f139fb78b2d38832b71466fc1_720](https://github.com/Scighost/Starward/assets/41642563/ed9519e7-693b-4bbe-8058-f23ca6618b52)

**Comment by aoout** [comment]
无法复现。

**Comment by PJnoeru** [comment]
> 无法复现。

我已经习惯了，starward启动官方启动器再启动游戏算了 QAQ
