### ISSUE TITLE
[Feature] 下载中途断开后在一段时间内自动尝试重连

### ISSUE THREAD

**Issue by CMBill** [Scighost/Starward#545]
### Checklist

- [X] I have already read [docs/Tips.md](https://github.com/Scighost/Starward/blob/main/docs/Tips.md), but my feature is not implemented.
- [X] My suggested feature was not mentioned by others, and it is not a duplicate feature.

### Summary

目前下载游戏数据中途，如果出现网络波动等问题会导致下载中断，不能自动重连，只能手动点击重试继续下载。

### Solution or Design

可以设定在一段时间内间隔固定时间自动尝试重连，超过这个时间后再停止下载，并报错提示使用者手动重试。

**Comment by Scighost** [comment]
谢谢你的建议

**Comment by Scighost** [comment]
转移到 #547
