### ISSUE TITLE
[Bug] 下载原神时参数错误

### ISSUE THREAD

**Issue by thouwave** [Scighost/Starward#548]
### Checklist

- [X] My issue was not mentioned by others, and it is not a duplicate issue.

### Description

![image](https://github.com/Scighost/Starward/assets/74224254/00cc1a8e-b066-4509-9cb3-43c73ab1c79f)
今天更新，试图通过starward下载回来玩玩时提示这个

### Reproduction Steps

电脑上没有原神，通过starward安装原神

### Starward Version

0.10.4

### Windows Version

22631.2861

### Log

```shell
描述里面的图片
```

**Comment by Scighost** [comment]
#525

**Comment by thouwave** [comment]
已解决，直接下载到E盘是不行的，下面新建一个文件夹就可以，十分感谢
