### ISSUE TITLE
[Bug] 使用自訂啟動程式時似乎無法傳遞啟動參數

### ISSUE THREAD

**Issue by XPRAMT** [Scighost/Starward#551]
### Checklist

- [X] My issue was not mentioned by others, and it is not a duplicate issue.

### Description

使用自訂啟動程式時似乎無法傳遞啟動參數

### Reproduction Steps

透過Starward將手機版啟動參數"use_mobile_platform -is_cloud 1 -platform_type CLOUD_THIRD_PARTY_MOBILE"傳遞給解鎖幀數程式，但原神還是啟動電腦版，單獨使用解鎖幀數程式是可以正常啟動手機版的
使用的解鎖幀數程式 [https://github.com/xiaonian233/genshin-fps-unlock](https://github.com/xiaonian233/genshin-fps-unlock )
![螢幕擷取畫面 2023-12-22 135051](https://github.com/Scighost/Starward/assets/34093551/e8ee34af-5341-457b-8655-71fc0f3ac371)

### Starward Version

0.10.6

### Windows Version

22635.2915

### Log

```shell
[13:56:20.752] [INFO] 
Welcome to Starward v0.10.6-preview.1
System: Microsoft Windows NT 10.0.22635.0
Command Line: G:\Game\Starward\app-0.10.6-preview.1\Starward.dll playtime --biz hk4e_global --pid 13372

[13:56:20.784] [INFO] Starward.Services.DatabaseService
Database path is 'G:\Game\Starward'

[13:56:20.806] [INFO] Starward.Services.DatabaseService
Database version is 7, target version is 7.
```

**Comment by Scighost** [comment]
是的，自定义启动程序不会传递命令行参数，如有需要你可以使用批处理脚本(.bat)代替.exe
