### ISSUE TITLE
[Bug] bug in HSR gacha url parsing

### ISSUE THREAD

**Issue by gawgua** [Scighost/Starward#552]
### Checklist

- [X] My issue was not mentioned by others, and it is not a duplicate issue.

### Description

Cant find the gacha url 
Used [.ps1 script](https://gist.githubusercontent.com/Star-Rail-Station/2512df54c4f35d399cc9abbde665e8f0/raw/get_warp_link_os.ps1?cachebust=srs) from starrailstation and it outputted url in https://api-os-takumi.mihoyo.com/common/gacha_record/api/getGachaLog?..... format
But the existed regex is not the one that has problem 
![image](https://github.com/Scighost/Starward/assets/104498646/d9ad6a15-0bd5-4258-a018-95c32a0ddfbf)

### Reproduction Steps

click Update Records

### Screenshots

![image](https://github.com/Scighost/Starward/assets/104498646/40ecc917-fff4-487c-a246-53c10ceb51f8)

### Starward Version

0.10.4

### Windows Version

22635.2915

### Log

```shell
[12:49:25.599] [INFO] 
Welcome to Starward v0.10.4
System: Microsoft Windows NT 10.0.22635.0
Command Line: D:\Downloads\Starward_Portable_0.8.3_x64\app-0.10.4\Starward.dll playtime --biz hk4e_global --pid 3648

[12:49:25.657] [INFO] Starward.Services.DatabaseService
Database path is 'D:\Downloads\Starward_Portable_0.8.3_x64'

[12:49:25.690] [INFO] Starward.Services.DatabaseService
Database version is 7, target version is 7.
```

**Comment by Scighost** [comment]
Please click this button and try again.

<img width="194" alt="image" src="https://github.com/Scighost/Starward/assets/61003590/b8ef8a38-a8a4-4a9f-a558-23f9b2715254">
