### ISSUE TITLE
[Feature] 支持快捷添加启动参数

### ISSUE THREAD

**Issue by ab-Royo** [Scighost/Starward#553]
### Checklist

- [X] I have already read [docs/Tips.md](https://github.com/Scighost/Starward/blob/main/docs/Tips.md), but my feature is not implemented.
- [X] My suggested feature was not mentioned by others, and it is not a duplicate feature.

### Summary

添加保存自定义参数的功能，让使用过的参数或者直接设定的参数成为快捷参数方式
这样功能更加全面，而且可以避免直接提供对游戏界面做出改变的功能

比如
- 窗口化全屏  -popupwindow
-  使用移动端UI  use_mobile_platform -is_cloud 1 -platform_type CLOUD_THIRD_PARTY_MOBILE

### Solution or Design

![20231223-183656](https://github.com/Scighost/Starward/assets/104680423/402b7eef-40e9-4bd5-a317-f61efc1e344b)

**Comment by Scighost** [comment]
#539
