### ISSUE TITLE
[Bug] Crash for Open my HoYoLAB Toolbox me Profile 

### ISSUE THREAD

**Issue by DarkAssassin48** [Scighost/Starward#554]
### Checklist

- [x] My issue was not mentioned by others, and it is not a duplicate issue.

### Description

When you click on my account, the app crashes

### Reproduction Steps

Clicking on my profile and a crash occurs

### Screenshots

![Starward_23-12-24_16-19-57](https://github.com/Scighost/Starward/assets/40138340/75f29679-9d68-49b7-85ea-b55e31050efd)

https://github.com/Scighost/Starward/assets/40138340/6e58830d-e8d0-4b90-af3e-50439082e42a

### Starward Version

0.10.4

### Windows Version

22631.2861

### Log

```shell
[16:29:46.481] [INFO] 
Welcome to Starward v0.10.4
System: Microsoft Windows NT 10.0.22631.0
Command Line: I:\Game\Starward\app-0.10.4\Starward.dll

[16:29:46.534] [INFO] Starward.Services.DatabaseService
Database path is 'I:\Game\Starward'

[16:29:46.557] [INFO] Starward.Services.DatabaseService
Database version is 7, target version is 7.

[16:29:46.606] [INFO] Starward.Pages.MainPage
Select game region is hk4e_global

[16:29:46.612] [INFO] Starward.Pages.MainPage
Navigate to "LauncherPage" with param hk4e_global

[16:29:46.911] [INFO] Starward.Pages.LauncherPage
Game install path hk4e_global: "I:\Game\GenshinImpact\Genshin Impact game"

[16:29:46.951] [INFO] Starward.Pages.LauncherPage
Game is running ("GenshinImpact", 14536)

[16:29:46.960] [INFO] Starward.Services.DownloadGameService
Local game version is "4.3.0" (gameBiz: hk4e_global)

[16:29:46.981] [WARN] Starward.Services.GameService
Game uninstalled path not found (hk4e_cn)

[16:29:46.981] [WARN] Starward.Services.GameService
Game uninstalled path not found (hk4e_cloud)

[16:29:46.982] [WARN] Starward.Services.GameService
Game uninstalled path not found (bh3_cn)

[16:29:46.982] [WARN] Starward.Services.GameService
Game uninstalled path not found (bh3_global)

[16:29:46.982] [WARN] Starward.Services.GameService
Game uninstalled path not found (bh3_jp)

[16:29:46.983] [WARN] Starward.Services.GameService
Game uninstalled path not found (bh3_kr)

[16:29:46.983] [WARN] Starward.Services.GameService
Game uninstalled path not found (bh3_overseas)

[16:29:46.983] [WARN] Starward.Services.GameService
Game uninstalled path not found (bh3_tw)

[16:29:47.507] [INFO] Starward.Services.UpdateService
Start to check update (Preview: False, Arch: X64)

[16:29:47.589] [INFO] Starward.Services.UpdateService
Current version: "0.10.4", latest version: "0.10.4", ignore version: "0.10.6-preview.1"

[16:29:52.794] [INFO] Starward.Pages.MainPage
Navigate to "HoyolabToolboxPage" with param hk4e_global

[16:29:52.805] [INFO] Starward.Services.GameRecordService
Change region to Global.
```

### Additional Context
[crash_20231224_163000.txt](https://github.com/Scighost/Starward/files/13761973/crash_20231224_163000.txt)

_No response_

**Comment by Scighost** [comment]
Thanks for your feedback. It may occur because of 

https://github.com/Scighost/Starward/blob/3aed70b49deb10c8a8fc308cf3e2a7b9a680cc7d/src/Starward/Pages/HoyolabToolbox/SpiralAbyssPage.xaml#L495

In spiral abyss floor 9-12, every chamber has two battles. Please see spiral abyss records in HoYoLAB app, is there any record only has one-half battle in some chamber?

**Comment by DarkAssassin48** [comment]
All floors have been passed
![screencapture-act-hoyolab-app-community-game-records-sea-index-html-2023-12-24-19_05_15](https://github.com/Scighost/Starward/assets/40138340/48859478-ee49-40dd-a7bc-e3a74d5690d8)

**Comment by Scighost** [comment]
Please try again, and if it is still happen, send your `StarwardDatabase.db` to my email, I will check it.

**Comment by Scighost** [comment]
The recent two abyss records of uid `70...54` have no battle data, it caused a crash. This may be an error in the data returned by HoYoverse's server at a specific time.

You should open `StarwardDatabase.db` with any database edit software, and then execute the following SQL, which will delete the last two record of the account.

``` sql
DELETE FROM SpiralAbyssInfo WHERE Uid LIKE '70%54' AND ScheduleId IN (83, 84);
```

<img width="173" alt="image" src="https://github.com/Scighost/Starward/assets/61003590/fb7f3343-8fea-42af-8027-b7bdda03176e">

**Comment by Scighost** [comment]
**PS: This SQL is only used to solve this problem and cannot be used again in the future.**

**Comment by DarkAssassin48** [comment]
Thanks, everything worked
[image: image.png]

пн, 25 дек. 2023 г. в 18:39, Scighost ***@***.***>:

**Comment by Scighost** [comment]
Issue doesn't occur on [0.10.7-beta.1](https://github.com/Scighost/Starward/releases/tag/0.10.7-beta.1).
