### ISSUE TITLE
[Feature]自定义选择隐藏显示UI上方的游戏

### ISSUE THREAD

**Issue by Chenxi4218** [Scighost/Starward#556]
### Checklist

- [X] I have already read [docs/Tips.md](https://github.com/Scighost/Starward/blob/main/docs/Tips.md), but my feature is not implemented.
- [X] My suggested feature was not mentioned by others, and it is not a duplicate feature.

### Summary

建议上方三款米家游戏可以自定义选择隐藏显示

### Solution or Design

为三款游戏设置隐藏显示开关

**Comment by Scighost** [comment]
谢谢你的建议

**Comment by CuteLittleSky** [comment]
非常需要这个功能:D
退游了不想看见...
