### ISSUE TITLE
[Question] 更换电脑后，如何将游戏时长的数据导出到新电脑呢

### ISSUE THREAD

**Issue by LumineSakura** [Scighost/Starward#562]
### Checklist

- [X] I have already read [docs/Tips.md](https://github.com/Scighost/Starward/blob/main/docs/Tips.md), but my question is not solved.
- [X] My question was not mentioned by others, and it is not a duplicate question.

### Description

![图片](https://github.com/Scighost/Starward/assets/80190029/6634c2de-a969-4f96-a831-3ffe7c17e3d3)

如何将游戏时长导入到新电脑中

### Starward Version

0.10.6preview.1

### Windows Version

19044.2486

**Comment by Scighost** [comment]
把旧电脑数据文件夹中的 `StarwardDatabase.db` 文件复制到新电脑的数据文件夹中

**Comment by shenbourne** [comment]
> 把旧电脑数据文件夹中的`StarwardDatabase.db`文件复制到新电脑的数据文件夹中

我将这个文件复制后，抽卡记录消失了。有什么办法可以恢复抽卡记录吗？

**Comment by Scighost** [comment]
你提供的信息太少了，我无法判断问题原因。
但是你可以在原电脑上导出抽卡数据，然后在新电脑中导入。
