### ISSUE TITLE
[Feature] 将记录的游戏时间转换为以秒为单位，以方便与其他游戏管理器同步游玩记录

### ISSUE THREAD

**Issue by Xionghaizi001** [Scighost/Starward#563]
### Checklist

- [X] I have already read [docs/Tips.md](https://github.com/Scighost/Starward/blob/main/docs/Tips.md), but my feature is not implemented.
- [X] My suggested feature was not mentioned by others, and it is not a duplicate feature.

### Summary

诸如Playnite等多平台游戏管理器都使用了以秒作为单位的游戏时间记录，希望starward也能加入这项功能，以方便用户将它们进行同步。同时希望增加“上月”这一统计维度。

### Solution or Design

用户点击具体时间时，软件将以秒表示的时间复制到剪贴板。
例如点击“本月”行的 20h 35m，软件将以秒表示的“74100”复制到剪贴板。

**Comment by Xionghaizi001** [comment]
补充信息：Playnite软件的游戏时间记录编辑页面
![image](https://github.com/Scighost/Starward/assets/50747104/2f0856e1-238e-4fa5-844a-a6c3f3a97473)

**Comment by Scighost** [comment]
谢谢你的建议，但是我不清楚你提到的其他游戏管理器是如何记录游戏时间的，所以可能不会实现此功能。
