### ISSUE TITLE
账号保存方式有点不好理解，能不能添加个直接保存当前登录账号的摁钮。

### ISSUE THREAD

**Issue by Tatsuya7239** [Scighost/Starward#57]
![image](https://github.com/Scighost/Starward/assets/83299813/ab111c90-855d-422d-9044-074372486e91)
启动器的账号跟我游戏里的账号不是同一个，我只能修改启动器里账号的信息，没办法保存现在登入的账号

**Comment by Scighost** [comment]
一个账号信息由 **密钥**、**昵称**、**Uid** 三部分组成，其中**密钥**从注册表读取，是区分不同账号的唯一依据。**昵称**和**Uid**可以在切换账号右边的铅笔图标处修改。

<img width="191" alt="image" src="https://github.com/Scighost/Starward/assets/61003590/91b8edc9-5aa7-40a0-b7da-dcb5bfb206d3">

只有在点击上图中的保存按键后，账号信息才会被保存在本地，游戏中登录的账号切换后，还能看到之前保存的账号。

上图左下角的✔标志代表的是当前在游戏中登录的账号，不同账号可能会生成多个密钥，需要手动删除保存在本地已过期的密钥。

**Comment by Sielier** [comment]
这个确实有点问题，我的原神貌似是因为移动了资源文件夹，它读不出我的uid，一直是0，修改没有作用？不知能不能弄个修复的指引啥的

**Comment by Tatsuya7239** [comment]
@Scighost 这个我倒是理解了，不过在用启动器登入游戏后再切换账号好像是会覆盖掉当前保存的账号。要是想要登入前一个账号的话又需要再次输入账号密码。可不可以弄成登入一个新账号就新生成一个文件而不是覆盖掉当前账号的文件

**Comment by Scighost** [comment]
@Tatsuya7239 为什么启动器里只有一个账号？因为你没有点**保存**，只有点过保存键后，当前账号才会保存在启动器中，游戏中的账号切换后也不会消失。

**Comment by Scighost** [comment]
Close issue for long time no response.
