### ISSUE TITLE
[Question] 请问抽卡记录导入只支持json吗？

### ISSUE THREAD

**Issue by ahshy1996** [Scighost/Starward#571]
### Checklist

- [X] I have already read [docs/Tips.md](https://github.com/Scighost/Starward/blob/main/docs/Tips.md), but my question is not solved.
- [X] My question was not mentioned by others, and it is not a duplicate question.

### Description

导出可以选择excel和json，导入是支持json吗。可以增加excel转json的功能吗？
谢谢

### Starward Version

0.10.6

### Windows Version

22621.2861

**Comment by Scighost** [comment]
> 导入是支持json吗

是的

> 可以增加excel转json的功能吗？

对不起，做不到
