### ISSUE TITLE
[Feature] Star Rail Cloud (China)

### ISSUE THREAD

**Issue by studiobuttermedia** [Scighost/Starward#573]
### Checklist

- [X] I have already read [docs/Tips.md](https://github.com/Scighost/Starward/blob/main/docs/Tips.md), but my feature is not implemented.
- [X] My suggested feature was not mentioned by others, and it is not a duplicate feature.

### Summary

Add ability to play Honkai: Star Rail Cloud server like Genshin Impact (once the Public Test Concludes)

miHoYo recently announced releasing Star Rail Cloud version on January 10th 2023 as a Open Beta Test. End date will announce soon.

[Link to the Original Announcement on BiliBili](https://b23.tv/KsHPf9L)

Hope to see this added to the launcher once the Test Concludes and is available to the public 

### Solution or Design

Add “Cloud China” in the Star Rail Region Swtich context menu (once this version is out of Testing and release to the Public)

**Comment by Scighost** [comment]
Star Rail Cloud doesn't yet have Windows desktop client.
