### ISSUE TITLE
[Feature] 希望可以发布不带运行时的版本

### ISSUE THREAD

**Issue by KKatationer** [Scighost/Starward#574]
### Checklist

- [X] I have already read [docs/Tips.md](https://github.com/Scighost/Starward/blob/main/docs/Tips.md), but my feature is not implemented.
- [X] My suggested feature was not mentioned by others, and it is not a duplicate feature.

### Summary

如图
![image](https://github.com/Scighost/Starward/assets/35140122/cf08c5f4-9204-478b-b843-a15842343ad2)

### Solution or Design

减少大小

**Comment by Scighost** [comment]
对不起，没必要
