### ISSUE TITLE
[Feature] 可以下载特定历史版本的原神的游戏资源吗，尽管它可能不是为了玩游戏。

### ISSUE THREAD

**Issue by HyBoxwood** [Scighost/Starward#575]
### Checklist

- [X] I have already read [docs/Tips.md](https://github.com/Scighost/Starward/blob/main/docs/Tips.md), but my feature is not implemented.
- [X] My suggested feature was not mentioned by others, and it is not a duplicate feature.

### Summary

这个修复模式真好用。不过它只支持现行版本吗？如果想获取历史版本的游戏本体可以实现吗？

能获取历史版本啊喂，这也是官方启动器也做不到的罢(

### Solution or Design

参考Minecraft的启动器，可以下载到任意历史版本的游戏，当然那是因为历史版本是可以游玩的，但是你知道的，如果要获取一些限时内容的游戏资源可能需要下载历史版本了，此时下载和存储压缩包是有一定困难的，如果能以这个修复模式的方式获取它们会很方便。或者退而求其次只是下载升级包也不是不行(

**Comment by Scighost** [comment]
https://github.com/MAnggiarMustofa/GI-Download-Library

如你所见，仓库被 DMCA 了

**Comment by HyBoxwood** [comment]
好像不是第一次(

**Comment by HyBoxwood** [comment]
https://github.com/JRSKelvin/GenshinRepository

**Comment by Scighost** [comment]
下载历史版本不是正常的游戏需求，我不会加入此功能。
