### ISSUE TITLE
关于游戏启动后starward的变化

### ISSUE THREAD

**Issue by meng-ru-nan-fa** [Scighost/Starward#58]
每次启动完都是最小化，能否添加一个选项可选择使其缩小至右下角托盘？

**Comment by Sielier** [comment]
首先是给任务栏腾空间吧，启动器放托盘最合适，顺便还可以弄个右击快速选择启动；其次是减少误触，目前版本win11还不能用大标签，很容易点错（

**Comment by meng-ru-nan-fa** [comment]
1.每次启动完之后启动起都占着一个后台，使得我alt+tab切换应用较为繁琐
2.启动器启动之后只需记录应用使用时间，放托盘最合适
3.为防止有其他用户希望不放在托盘里而是保留界面，故我希望增加相应选项

**Comment by Scighost** [comment]
你们给出的理由并不充分。

首先，记录游戏时间是独立的无窗口进程，启动游戏后可以直接关闭启动器，不存在占用任务栏的问题。
其次，现有的所有功能都不需要启动器进程保持长期运行，增加托盘功能不符合**启动使用关闭**的设计原则。

此 issue 将被标记为未完成然后关闭。

**Comment by meng-ru-nan-fa** [comment]
目前，启动器所采用的是启动游戏后最小化的方式，不符合您所说的启动使用关闭。
按您所说，启动器在启动游戏后打开了计时程序应该自动关闭。（毕竟几乎没有人会同时启动多个游戏）
此外，您的该作品包含祈愿统计等附加功能，为用户手动执行的操作，若关闭程序则需更为繁琐地重新启动starward。
在我看来，添加托盘功能利大于弊
