### ISSUE TITLE
Genshin Imppact更新不了抽卡链接[Bug] 

### ISSUE THREAD

**Issue by Pizazz-stack** [Scighost/Starward#580]
### Checklist

- [X] My issue was not mentioned by others, and it is not a duplicate issue.

### Description

点击更新Genshin Impact抽卡记录，显示无法找到URL

### Reproduction Steps

在游戏内点开历史记录—关闭，切换至starward—更新记录

### Starward Version

0.10.4

### Windows Version

19045.3930

### Log

```shell
不懂
```

**Comment by Scighost** [comment]
#271
