### ISSUE TITLE
能不能多给几个账号保存选项，两个根本不够啊

### ISSUE THREAD

**Issue by yingwuzong** [Scighost/Starward#592]
### Checklist

- [X] I have already read [docs/Tips.md](https://github.com/Scighost/Starward/blob/main/docs/Tips.md), but my feature is not implemented.
- [X] My suggested feature was not mentioned by others, and it is not a duplicate feature.

### Summary

如题

### Solution or Design

如题

**Comment by Scighost** [comment]
不好意思，我看不懂你在说什么

**Comment by Scighost** [comment]
如果你需要切换更多的账号，Starward不适合你，你应该使用其他的工具。

**Comment by yingwuzong** [comment]
可是我就喜欢Starward
