### ISSUE TITLE
每次启动游戏后都要重新登录

### ISSUE THREAD

**Issue by 1onelyman** [Scighost/Starward#595]
### Checklist

- [X] I have already read [docs/Tips.md](https://github.com/Scighost/Starward/blob/main/docs/Tips.md), but my question is not solved.
- [X] My question was not mentioned by others, and it is not a duplicate question.

### Description

每次用starward启动星穹铁道都要重新登录一遍账号

### Starward Version

0.10.7-beta.1

### Windows Version

19045.3803

**Comment by Scighost** [comment]
你自己的设备参数改变了，和 Starward 无关。

**Comment by 1onelyman** [comment]
> 你自己的设备参数改变了，和 Starward 无关。

但是我没动什么呀
