### ISSUE TITLE
[Feature] 添加 下载队列/下载完成后执行... 功能

### ISSUE THREAD

**Issue by ymy139** [Scighost/Starward#596]
### Checklist

- [X] I have already read [docs/Tips.md](https://github.com/Scighost/Starward/blob/main/docs/Tips.md), but my feature is not implemented.
- [X] My suggested feature was not mentioned by others, and it is not a duplicate feature.

### Summary

考虑到当今米家游戏的分量越来越大，更新耗时越来越长，可以考虑增加`下载队列`功能（即更新完某游戏后开始更新队列中的下一个游戏）与 `下载完成后执行...` 功能（例如更新完成后关机等动作）

*这对苦逼学生三修党将十分友好*~~*（指10点到家打开电脑开始更新然后睡觉）*~~

### Solution or Design

*不会UI/UX，菜鸡一个，仅供参考*
### `下载队列`功能
1. 点击`更新游戏`按钮时，在弹出的对话框中添加一个`加入队列`按钮
2. 点击`加入队列`按钮后弹出一个队列对话框，其中包括队列，`下载完成后执行...`单选框，`开始下载`按钮，`取消队列`按钮
3. 点击`开始下载`按钮后按照正常下载流程执行，完成一个更新任务后自动开始下一个更新任务
### `下载完成后执行...` 功能
点击`更新游戏`按钮时，在弹出的对话框中加入`下载完成后执行...`单选框

**Comment by Scighost** [comment]
谢谢你的建议，但是我认为没有必要
