### ISSUE TITLE
安装后就有乱码

### ISSUE THREAD

**Issue by 11389698** [Scighost/Starward#60]
如图，路径没有中文，安装后就一直这样有部分乱码中文
![image](https://github.com/Scighost/Starward/assets/79733561/935e5c95-7911-4bc7-9c0a-85fe607089d7)

**Comment by Scighost** [comment]
图中有两个问题
一是缺少 Segoe Fluent Icon 字体，在这里下载 https://aka.ms/SegoeFluentIcons
二是因为系统设置中关闭了透明效果，软件内大量使用的亚克力材质被回退为黑色半透明颜色，可能会导致体验不佳，启用方式：系统设置-个性化-颜色-透明效果。

**Comment by Scighost** [comment]
#61

**Comment by 11389698** [comment]
> 

解决率200%，感谢

**Comment by 11389698** [comment]
> 图中有两个问题 一是缺少 Segoe Fluent Icon 字体，在这里下载 https://aka.ms/SegoeFluentIcons 二是因为系统设置中关闭了透明效果，软件内大量使用的亚克力材质被回退为黑色半透明颜色，可能会导致体验不佳，启用方式：系统设置-个性化-颜色-透明效果。

解决率200%，感谢
