### ISSUE TITLE
很喜欢启动器打开时没有选择游戏的状态下的背景图片

### ISSUE THREAD

**Issue by AssestinaR** [Scighost/Starward#601]
请问这个图片有没有

**Comment by Scighost** [comment]
`app-*\Assets\Image\StartUpBG2.png`

**Comment by AssestinaR** [comment]
> `app-*\Assets\Image\StartUpBG2.png`

谢谢！

**Comment by Scighost** [comment]
这是原图

![March7thBg](https://github.com/Scighost/Starward/assets/61003590/628a21ae-9d19-4bee-b9e7-3dd1f8d21861)
