### ISSUE TITLE
[Feature] Add option to automatically remove old starward update files

### ISSUE THREAD

**Issue by Flyingbacen** [Scighost/Starward#603]
### Checklist

- [X] I have already read [docs/Tips.md](https://github.com/Scighost/Starward/blob/main/docs/Tips.md), but my feature is not implemented.
- [X] My suggested feature was not mentioned by others, and it is not a duplicate feature.

### Summary

After an update is finished, give an option to automatically remove the old update files

### Solution or Design

After confirming that all the files are correct, delete the old folder so that it doesn't have to be done manually after prompting the user post-update.

**Comment by Scighost** [comment]
The old version folder will be deleted automatically when you run starward on the second time after update.
