### ISSUE TITLE
[Question] 运行后出现有You must install .NET Desktop Runtime to run this application.字样的弹窗

### ISSUE THREAD

**Issue by Hydrogenated233** [Scighost/Starward#605]
### Checklist

- [x] I have already read [docs/Tips.md](https://github.com/Scighost/Starward/blob/main/docs/Tips.md), but my question is not solved.
- [X] My question was not mentioned by others, and it is not a duplicate question.

### Description

运行后出现有You must install .NET Desktop Runtime to run this application.字样的弹窗
![image](https://github.com/Scighost/Starward/assets/109909020/ffb3ec4e-c376-4717-a163-29ef5554119b)
点击Download it now 后窗口消失无后续反应
在网上下载.NET Desktop Runtime后依然如此

### Starward Version

0.10.4

### Windows Version

22621.3007

**Comment by Scighost** [comment]
你是从哪里下载的Starward？

**Comment by Hydrogenated233** [comment]
github下的
