### ISSUE TITLE
[Feature] 加个内置浏览器

### ISSUE THREAD

**Issue by wsd114514** [Scighost/Starward#609]
### Checklist

- [X] I have already read [docs/Tips.md](https://github.com/Scighost/Starward/blob/main/docs/Tips.md), but my feature is not implemented.
- [X] My suggested feature was not mentioned by others, and it is not a duplicate feature.

### Summary

打开![image](https://github.com/Scighost/Starward/assets/116425752/458b64c2-3f49-4675-8f48-7c698f2a2dc8)时建议在一个内置浏览器中打开，不然浏览器还要加载一段时间，非常不高效

### Solution or Design

看图
![image](https://github.com/Scighost/Starward/assets/116425752/a269d37f-c9d8-4bf9-bd19-652476a426a5)

**Comment by Scighost** [comment]
我拒绝，应用内浏览资讯的体验并不好
