### ISSUE TITLE
请求新增对崩坏3rdBilibili服的支持[Feature] 

### ISSUE THREAD

**Issue by LoveElysia1314** [Scighost/Starward#615]
### Checklist

- [X] I have already read [docs/Tips.md](https://github.com/Scighost/Starward/blob/main/docs/Tips.md), but my feature is not implemented.
- [X] My suggested feature was not mentioned by others, and it is not a duplicate feature.

### Summary

能否新增对崩坏3rdB服的支持

### Solution or Design

有一种思路是内置扫码器，用户配置好b站账户信息后，每次进入游戏后以每秒一次的频率检测屏幕，出现二维码时扫码器自动扫描（可能涉及权限和隐私问题）

**Comment by Scighost** [comment]
谢谢你的建议，但是崩坏3（B服）没有独立的客户端，只能通过移动端扫码登录，我也没有能力逆向移动端的功能。

**Comment by LoveElysia1314** [comment]
***@***.***_cen制作了一款b服扫码器（主页Hao_cen的个人空间-Hao_cen个人主页-哔哩哔哩视频 (bilibili.com)<https://space.bilibili.com/269140934/?spm_id_from=333.999.0.0>）

[仅B服]PC扫码器v1.4.6.exe - 蓝奏云
https://haocen.lanzoum.com/ieham19wvqxi

用户先行配置账户信息后，配置信息会储存在一个json配置文件中。该扫码器会不断扫描剪贴板的图片，在用户进入扫码登陆界面并主动拷屏后，即可完成登陆。
如果您能联系到作者并获取其许可，或许可以将这个软件内置或取得源代码。（不过看他的动态，这个功能可能用到了他自己的服务器？）
实在不行的话也没关系，如果只是自用的话，这个功能我自己应该可以用python脚本实现。
总之，starward已经是一款很实用的软件了
感谢大佬们的付出[比心]
________________________________
发件人: Scighost ***@***.***>
发送时间: 2024年1月29日 13:05
收件人: Scighost/Starward ***@***.***>
抄送: LoveElysia1314 ***@***.***>; Author ***@***.***>
主题: Re: [Scighost/Starward] 请求新增对崩坏3rdBilibili服的支持[Feature] (Issue #615)


谢谢你的建议，但是崩坏3（B服）没有独立的客户端，只能通过移动端扫码登录，我也没有能力逆向移动端的功能。

―
