### ISSUE TITLE
[Feature] 精简托盘后右键的菜单

### ISSUE THREAD

**Issue by mxia9416** [Scighost/Starward#616]
### Checklist

- [X] I have already read [docs/Tips.md](https://github.com/Scighost/Starward/blob/main/docs/Tips.md), but my feature is not implemented.
- [X] My suggested feature was not mentioned by others, and it is not a duplicate feature.

### Summary

请问能否精简一下进入托盘后右键打开的菜单？今天更新了0.10.7-preview 2后，该菜单强制增加了原神和星铁的哔哩哔哩服选项。作为不玩b服的玩家，感觉不如之前简洁，因为对我来说是无关且冗余选项。

### Solution or Design

请加一个开关可以自行选择显示B服与否，或者智能识别如果没有登录过B服就不显示？感谢大佬！

**Comment by Scighost** [comment]
两种办法解决

- 删除B服的游戏定位

<img width="338" alt="image" src="https://github.com/Scighost/Starward/assets/61003590/24f6e2fa-6f47-45ee-83ec-f10c7c1920dd">

- 修复官服的游戏资源

<img width="336" alt="image" src="https://github.com/Scighost/Starward/assets/61003590/627a2126-aaaa-496c-98cc-bb1a30b35a2e">

**Comment by mxia9416** [comment]
已通过修复官服解决
