### ISSUE TITLE
[Bug] Can't see the Markdown Image in Update

### ISSUE THREAD

**Issue by phucho0237** [Scighost/Starward#625]
### Checklist

- [X] My issue was not mentioned by others, and it is not a duplicate issue.

### Description

![image](https://github.com/Scighost/Starward/assets/88989555/b854b852-a937-46c2-8548-200ebb89bdf0)

### Reproduction Steps

- Open Starward
- Click "Join Preview Release Channel" in Setting
- Click "Check for Update"

### Expected Behavior

See the image in Markdown

### Starward Version

0.10.7-preview.2

### Windows Version

Windows 10 22H2 - Build 19045.3930

### Log

```shell
[20:36:39.094] [INFO] 
Welcome to Starward v0.10.7-preview.2
System: Microsoft Windows NT 10.0.19045.0
Command Line: "C:\Program Files\Starward\app-0.10.7-preview.2\Starward.dll"

[20:36:39.136] [INFO] Starward.Services.DatabaseService
Database path is 'C:\Program Files\Starward'

[20:36:39.170] [INFO] Starward.Services.DatabaseService
Database version is 8, target version is 8.

[20:36:39.262] [INFO] Starward.Pages.MainPage
Last game region is hkrpg_global

[20:36:39.273] [INFO] Starward.Pages.MainPage
Navigate to "LauncherPage" with param hkrpg_global

[20:36:39.982] [INFO] Starward.Pages.LauncherPage
Game install path hkrpg_global: "C:\Program Files\Star Rail"

[20:36:39.982] [INFO] Starward.Pages.LauncherPage
Install path of hkrpg_global: "C:\Program Files\Star Rail"

[20:36:40.015] [INFO] Starward.Services.GameResourceService
Local game version is "1.6.0" (gameBiz: hkrpg_global)

[20:36:41.269] [INFO] Starward.Services.UpdateService
Start to check update (Preview: True, Arch: X64)

[20:36:41.439] [INFO] Starward.Services.UpdateService
Current version: "0.10.7-preview.2", latest version: "0.10.7-preview.3", ignore version: null
```

### Additional Context

Webview2 Runtime 120.0.2210.144

**Comment by phucho0237** [comment]
![image](https://github.com/Scighost/Starward/assets/88989555/98c00cde-ec53-4705-96ed-c225faf6e1da)

Tried updating with [Webview2 Evergreen Bootstrapper](https://developer.microsoft.com/en-us/microsoft-edge/webview2/?form=MA13LH#download), still in version 120.0.2210.144

**Comment by phucho0237** [comment]
Found [this link](https://www.catalog.update.microsoft.com/Search.aspx?q=webview2) has an updated version of Webview2, I will try it

**Comment by Scighost** [comment]
I updated WebView2 by clicking `Repair`.

<img width="576" alt="image" src="https://github.com/Scighost/Starward/assets/61003590/a2e2346c-6191-4667-a397-f76c7c74541e">

**Comment by phucho0237** [comment]
Not working for me

**Comment by phucho0237** [comment]
> Currently only Edge version 121 supports AIVF format, so it is natural to not see the image if you use version 120 and lower. ![image](https://private-user-images.githubusercontent.com/89702898/301209196-54d31cb2-49de-41df-a9ad-aab5acae1a8a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY3ODU2NzIsIm5iZiI6MTcwNjc4NTM3MiwicGF0aCI6Ii84OTcwMjg5OC8zMDEyMDkxOTYtNTRkMzFjYjItNDlkZS00MWRmLWE5YWQtYWFiNWFjYWUxYThhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjAxVDExMDI1MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTdjM2U1MDEzMGVkMThiMGVlYTNkZGM2ZGJlNGI0OWFmYTQ0NjM2YmEyMjVjMzYwZjhlMjg4N2FmN2JmOGRhYWEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.RnJphIAkmIXZS5EGV2Twd-_uWupCM8SGaYUtsNDPi4M)

How can I update to 121?

**Comment by Scighost** [comment]
@phucho0237 Don't worry, not being able to update to 121 will not affect normal use. It may take some time before Microsoft can push it on a large scale.

**Comment by Lightczx** [comment]
> Tried updating with [Webview2 Evergreen Bootstrapper](https://developer.microsoft.com/en-us/microsoft-edge/webview2/?form=MA13LH#download), still in version 120.0.2210.144

@phucho0237 Try uninstall/reinstall or upgrade Edge Browser? Edge Webview Runtime is just a wrapper for the Edge.

**Comment by phucho0237** [comment]
> > Tried updating with [Webview2 Evergreen Bootstrapper](https://developer.microsoft.com/en-us/microsoft-edge/webview2/?form=MA13LH#download), still in version 120.0.2210.144
> 
> @phucho0237 Try uninstall/reinstall or upgrade Edge Browser? Edge Webview Runtime is just a wrapper for the Edge.

I uninstalled Edge browser using the [ShadowWhisperer Script](https://github.com/ShadowWhisperer/Remove-MS-Edge). Does Webview really need a Edge browser?

**Comment by prpjzz** [comment]
> > > Tried updating with [Webview2 Evergreen Bootstrapper](https://developer.microsoft.com/en-us/microsoft-edge/webview2/?form=MA13LH#download), still in version 120.0.2210.144
> > 
> > 
> > @phucho0237 Try uninstall/reinstall or upgrade Edge Browser? Edge Webview Runtime is just a wrapper for the Edge.
> 
> I uninstalled Edge browser using the [ShadowWhisperer Script](https://github.com/ShadowWhisperer/Remove-MS-Edge). Does Webview really need a Edge browser?

Webview2 don't need Edge Browser.

**Comment by Lightczx** [comment]
If you install a Edge browser, it will use the browser'core instead of the one it carried.

**Comment by phucho0237** [comment]
Using [Christitus Tool] (https://raw.githubusercontent.com/ChrisTitusTech/winutil/main/winutil.ps1) and uninstalling with the built-in Edge Remover, then installing Edge again, it works as expected.

![image](https://github.com/Scighost/Starward/assets/88989555/bd203617-c8de-4461-b7a7-49ef4c5e0400)
![image](https://github.com/Scighost/Starward/assets/88989555/bcee8894-8b20-4203-a563-76a4e4b9b348)
![image](https://github.com/Scighost/Starward/assets/88989555/5f4d4db4-be56-4971-862f-1d0f06ea531c)
