### ISSUE TITLE
[Bug] 同时更新多个游戏时下载速度异常

### ISSUE THREAD

**Issue by RosieDu21** [Scighost/Starward#626]
### Checklist

- [X] My issue was not mentioned by others, and it is not a duplicate issue.

### Description

今天同时更新原神和崩坏3，发现下载速度出现异常，具体表现如下：

1. 平时的正常下载速度在20~30M/s
2. 同时更新时，崩3更新速度稳定在4~5M/s，原神虽能达到12M/s，但大约十几秒后速度会降为0，需手动暂停后再继续，可以重新恢复到12M/s左右，但依然只能持续10s左右，如此循环
3. 暂停崩3后，手动暂停并重新继续原神，速度恢复到27M/s
4. 原神更新下载完毕后，继续更新崩3，速度依然不足5M/s（怀疑有服务器问题）

主要的问题是2和3，还望作者检查。

十分感谢

### Reproduction Steps

见描述

### Starward Version

0.10.7-preview.3

### Windows Version

22631.3078

### Log

```shell
没有相关日志
日志里只记录了我开始更新和更新完成的时间，没有错误报告
```

**Comment by Scighost** [comment]
谢谢你的反馈，0.10.7-preview.3 为了兼容官方启动器，改成了单文件单线程下载，相较于之前版本，下载速度可能会变慢一些。
此外，就我个人的体验，因为CDN的质量问题，崩坏3的游戏资源的下载速度比其他俩要慢很多。如有需要，你可以使用其他的下载工具。
