### ISSUE TITLE
[Feature] 建议优化托盘游戏列表提示文字显示

### ISSUE THREAD

**Issue by smallg0at** [Scighost/Starward#627]
### Checklist

- [X] I have already read [docs/Tips.md](https://github.com/Scighost/Starward/blob/main/docs/Tips.md), but my feature is not implemented.
- [X] My suggested feature was not mentioned by others, and it is not a duplicate feature.

### Summary

目前我的托盘长这样：（0.10.7）
![image](https://github.com/Scighost/Starward/assets/30719670/d1f14a9d-356a-4ddd-8491-950247503175)

但实际使用下来，发现我用托盘经常开错游戏，问就是 LOGO 长得太像了，右面文字也没区分。

### Solution or Design

可考虑如下优化方案：

- 仅有一个服务器启用时，右侧文本直接显示游戏名
- 调整 UI 布局，把服务器选择放入二级菜单

**Comment by Scighost** [comment]
谢谢你的建议，但是我短时间内没有优化的意愿。
