### ISSUE TITLE
[Bug] Bilibili服的客户端在选择官服是仍然显示

### ISSUE THREAD

**Issue by CNChestnut** [Scighost/Starward#628]
### Checklist

- [X] My issue was not mentioned by others, and it is not a duplicate issue.

### Description

![屏幕截图 2024-02-02 004500](https://github.com/Scighost/Starward/assets/98728485/a63efc33-6c05-44da-a26a-f379f3857ac9)
如图，我只安装了B服，但是官服这边显示可以启动游戏，而且右下角账号显示 `0` 并且登录后如图所示
![屏幕截图 2024-02-02 004917](https://github.com/Scighost/Starward/assets/98728485/0c02aaa4-1a34-44a8-9492-a14d131f9c92)
还是B服的登录页面

### Reproduction Steps

我不清楚，但是我可以明确以下几点

- 我之前一直使用官服模式进行游玩，UID 也一直是 `0`
- 我目前的客户端是B服的官服启动器安装的，包括 `4.4` 版本

### Expected Behavior

他应该认为没有官服无法启动才对

顺带建议：

- 没有下载的版本如国际版，显示 `安装游戏` 的同时给予 `转换客户端` 的快捷方式
- 账号添加删除功能

### Screenshots

在上面已经出现了

### Starward Version

0.10.7 Preview.2

### Windows Version

22621.2215

### Log

[Starward_240202_002133.log](https://github.com/Scighost/Starward/files/14128479/Starward_240202_002133.log)
[Starward_240202_002551.log](https://github.com/Scighost/Starward/files/14128480/Starward_240202_002551.log)
[Starward_240202_002719.log](https://github.com/Scighost/Starward/files/14128481/Starward_240202_002719.log)
[Starward_240202_003055.log](https://github.com/Scighost/Starward/files/14128482/Starward_240202_003055.log)
[Starward_240202_003429.log](https://github.com/Scighost/Starward/files/14128483/Starward_240202_003429.log)
[Starward_240202_003609.log](https://github.com/Scighost/Starward/files/14128484/Starward_240202_003609.log)
[Starward_240202_003900.log](https://github.com/Scighost/Starward/files/14128486/Starward_240202_003900.log)
[Starward_240202_004746.log](https://github.com/Scighost/Starward/files/14128487/Starward_240202_004746.log)

**Comment by CNChestnut** [comment]
# 更新（这样子再发一条醒目一点）
发现使用卸载游戏可以修复次问题，但我认为在这个问题出现后，用户很难找到解决方案。
首先我从更新记录才发现如何卸载游戏，正常人可能都不敢点击去。。。

**Comment by Scighost** [comment]
> 仅安装了B服，但是官服也存在

B服和官服的差别仅有极少数文件和配置文件，如果安装了官方启动器，Starward中的B服和官服都会定位到同一路径，并且无法区分。在任意服的页面中点击修复游戏可解决。

> UID 是 0

曾经登录过多个账号，UID 全部记录在注册表中，但无法识别是哪一个，只能显示 0 。
**可能是上述原因，我不玩B服，不能肯定。**

**Comment by CNChestnut** [comment]
或许是 Starward 根本就无法识别b服 UID，反正我之前一直是这么认为的。在这台电脑，我只玩过b服的号。

还有一个小建议
对于没有下载的版本如国际版，显示 `安装游戏` 的同时给予 `转换客户端` 的快捷方式

**Comment by CNChestnut** [comment]
感谢
