### ISSUE TITLE
[Feature] 

### ISSUE THREAD

**Issue by chengwangy** [Scighost/Starward#636]
### Checklist

- [X] I have already read [docs/Tips.md](https://github.com/Scighost/Starward/blob/main/docs/Tips.md), but my feature is not implemented.
- [X] My suggested feature was not mentioned by others, and it is not a duplicate feature.

### Summary

能不增加将抽卡记录和设置保存在网盘的功能，方便更换电脑时，找回数据。

### Solution or Design

比如通过网盘的WebDAV功能。

**Comment by ZSXB2468** [comment]
你可以试试用rclone来同步
