### ISSUE TITLE
[Feature] 添加其他应用启动功能

### ISSUE THREAD

**Issue by wsd114514** [Scighost/Starward#637]
### Checklist

- [X] I have already read [docs/Tips.md](https://github.com/Scighost/Starward/blob/main/docs/Tips.md), but my feature is not implemented.
- [X] My suggested feature was not mentioned by others, and it is not a duplicate feature.

### Summary

能自己添加应用启动

### Solution or Design

上面说的有点抽象，以微信为例
![image](https://github.com/Scighost/Starward/assets/116425752/479b5996-577c-49f7-8b6e-049a078ac176)

**Comment by CNChestnut** [comment]
你是认真的吗？
