### ISSUE TITLE
更新0.7.0后报毒打不开

### ISSUE THREAD

**Issue by ShingekinoTerebikun** [Scighost/Starward#64]
rt 怎么解 直接给隔离了
![image](https://github.com/Scighost/Starward/assets/59349123/9bf06e8f-705d-454d-8c93-c1d668568ede)

**Comment by Scighost** [comment]
0.7.0 版本 `Starward.dll` 的 SHA256 如下：
x64：`32BF62BCE15F43D65214949C31BAF83EC10C714CFBD76587433AE4A929626D16`
arm64：`9A82BDFE8426B53967B11EC1E7EFD5D196FF77086F79103E3D18193685C420CF`

首先请确认你的本地文件没有被篡改，其次我使用 Windows Defender 扫描之后没有报毒。

<img width="393" alt="image" src="https://github.com/Scighost/Starward/assets/61003590/b4f83da9-1cf2-443d-815f-11a2897077ae">

使用 [VirusTotal](https://www.virustotal.com/) 检测也没有任何问题。
https://www.virustotal.com/gui/url/fcecb20f7b8297fc0784d9e9c19c2d9530dd107ab917d3018ac27fc41211ab20
https://www.virustotal.com/gui/url/3d6412062ee84fb23fd1059d0986608bd5079838db44a1d70da4835687b580a1

本项目在编译和发布流程上由 GitHub Actions 全自动执行，排除供应链投毒的风险，通过正常渠道下载的文件一定是和源码相符合的，不存在我个人替换二进制文件的可能。

**Comment by Scighost** [comment]
长时间未回复，关闭此 issue。
