### ISSUE TITLE
[Question] 任务栏固定在启动器更新后无法保存

### ISSUE THREAD

**Issue by zqsrios** [Scighost/Starward#643]
### Checklist

- [x] I have already read [docs/Tips.md](https://github.com/Scighost/Starward/blob/main/docs/Tips.md), but my question is not solved.
- [X] My question was not mentioned by others, and it is not a duplicate question.

### Description

[Question] 任务栏固定在启动器更新后无法保存

### Starward Version

0.11.0

### Windows Version

22621.1928

**Comment by Scighost** [comment]
新年好

你需要固定的是 `app-*` 文件夹外的那个 `Starward.exe`
