### ISSUE TITLE
[Feature] 顶部图标右键服务器选择列表内容建议加入 i18n

### ISSUE THREAD

**Issue by BTMuli** [Scighost/Starward#644]
### Checklist

- [X] I have already read [docs/Tips.md](https://github.com/Scighost/Starward/blob/main/docs/Tips.md), but my feature is not implemented.
- [X] My suggested feature was not mentioned by others, and it is not a duplicate feature.

### Summary

rt，目前右键切换服务器为英文文本

![image](https://github.com/Scighost/Starward/assets/72692909/ad80ba62-6d30-457f-a3e2-671e1bd521b4)

### Solution or Design

将右侧文件内容也加入国际化中

**Comment by Scighost** [comment]
新年好

谢谢你的建议，但是我认为没有必要。
