### ISSUE TITLE
[Feature] 切换服务器建议加一个切换国际服的功能

### ISSUE THREAD

**Issue by kndxhz** [Scighost/Starward#645]
### Checklist

- [X] I have already read [docs/Tips.md](https://github.com/Scighost/Starward/blob/main/docs/Tips.md), but my feature is not implemented.
- [X] My suggested feature was not mentioned by others, and it is not a duplicate feature.

### Summary

切换国际服，而不是重新下载

### Solution or Design

只需要每个版本制作一个大概500MB的切服包，然后解压到游戏目录并改变一点配置文件和dll即可切到国际服
再做一个切国服的就可以互切

此方法崩坏三、原神、星穹铁道通用
可以参考 https://blog.tomys.top/2022-07/genshinlauncher/ 这个软件和这个博客里的星穹铁道启动器

**Comment by kndxhz** [comment]
别问我为什么这么清楚，因为我手动切服过，测试过
并且制作过切服包（只需要包含除了缓存以外的所有国服和国际服的差异文件即可）

**Comment by Xionghaizi001** [comment]
啊。有没有可能有相当一部分玩家只玩一个服，他们不需要这些额外的空间占用

**Comment by Apkeniqo** [comment]
> 啊。有没有可能有相当一部分玩家只玩一个服，他们不需要这些额外的空间占用

没说强制下载这部分资源啊，像胡桃工具箱那样需要的人下载就可以啊

**Comment by Small-Ku** [comment]
見 https://github.com/Scighost/Starward/blob/main/docs/Tips.zh-CN.md#转换游戏客户端

**Comment by kndxhz** [comment]
> > @Small-Ku deleted the following comment
> > published at 2024-02-06 09:01:57 +00:00
> > updated at 2024-02-06 09:05:37 +00:00
> 
> 見 [https://github.com/Scighost/Starward/blob/main/docs/Tips.zh-CN.md#转换游戏客户端](https://github.com/Scighost/Starward/blob/main/docs/Tips.zh-CN.md#%E8%BD%AC%E6%8D%A2%E6%B8%B8%E6%88%8F%E5%AE%A2%E6%88%B7%E7%AB%AF) duplicate #572 #513 #354 #195

和这个没关系，我知道可以转换，但是不能转国际服

**Comment by kndxhz** [comment]
> > 啊。有没有可能有相当一部分玩家只玩一个服，他们不需要这些额外的空间占用
> 
> 没说强制下载这部分资源啊，像胡桃工具箱那样需要的人下载就可以啊

是的，我就是从胡桃工具箱的启动游戏转过来的

**Comment by Scighost** [comment]
新年好

你需要的客户端切换功能在这里

<img width="141" alt="image" src="https://github.com/Scighost/Starward/assets/61003590/2b851fee-23cc-40d0-b5c0-83dfefc745ae">

**Comment by kndxhz** [comment]
是的，正如#652，希望
![image](https://github.com/Scighost/Starward/assets/113306265/19254404-4eeb-441a-9c74-247a8a90111e)
你们的这个教程能够更新一下
不对啊，我也会markdown啊，我发个拉取请求更新吧

**Comment by kndxhz** [comment]
但是我只会中文，更多版本请各位志愿者更新，谢谢
