### ISSUE TITLE
[Bug] 无法获取到新一期虚构叙事的战绩

### ISSUE THREAD

**Issue by Eric-Joker** [Scighost/Starward#647]
### Checklist

- [X] My issue was not mentioned by others, and it is not a duplicate issue.

### Description

RT

### Reproduction Steps

米游社工具箱→虚构叙事→刷新

### Starward Version

0.11.0

### Windows Version

22631.3085

### Log

```shell
控制台未启用状态下无任何日志
```

### Additional Context

此期为第一次双期同时存在的虚构叙事，只是因为米游社排版更新没有适配吧。

**Comment by Scighost** [comment]
已解决，但是存在新的问题，参考 #704
