### ISSUE TITLE
Some images in README

### ISSUE THREAD

**Issue by Scighost** [Scighost/Starward#65]
<img width="787" alt="屏幕截图 2023-06-17 194739" src="https://github.com/Scighost/Starward/assets/61003590/56adfd7f-0e5f-471b-beeb-f6ec4430f89b">

![image](https://github.com/Scighost/Starward/assets/61003590/f19b5ae7-33f8-41ac-8130-6d0069fde27a)

**Comment by Scighost** [comment]
<img width="787" alt="屏幕截图 2023-06-17 202905" src="https://github.com/Scighost/Starward/assets/61003590/4979ce4e-4dd2-41d9-ae45-1d1b5cba7a0d">

**Comment by Scighost** [comment]
https://www.pixiv.net/artworks/100739915

![100739915_p0.jpg](https://github.com/Scighost/Starward/assets/61003590/f14dd131-6d24-47a9-b90b-91e938481a03)

**Comment by phucho0237** [comment]
![image](https://github.com/Scighost/Starward/assets/88989555/df61f32e-1327-422a-9219-c3ccee56f8ef)

**Comment by Scighost** [comment]
@phucho0237 emmmm, please notice your uid.

**Comment by phucho0237** [comment]
@Scighost  heh, I don't understand

**Comment by phucho0237** [comment]
@Scighost need to change to another uid different than my uid ?

**Comment by phucho0237** [comment]
![image](https://github.com/Scighost/Starward/assets/88989555/d02d1448-e2cb-4836-8d4c-a6e3962808f3)

**Comment by Scighost** [comment]
@phucho0237 I didn't express myself clearly, your uid was exposed. If you don't mind, I'll merge the pull requeset.

**Comment by phucho0237** [comment]
okay, I think if my uid was exposed I will have a problem in the future, but now nevermind

**Comment by phucho0237** [comment]
maybe I will edit it later

**Comment by phucho0237** [comment]
![image](https://github.com/Scighost/Starward/assets/88989555/8d83c941-cfcc-4655-8bf1-2ccd16792336)
