### ISSUE TITLE
关于切换服务器和ui改进建议

### ISSUE THREAD

**Issue by xshaon** [Scighost/Starward#652]
### Checklist

- [X] I have already read [docs/Tips.md](https://github.com/Scighost/Starward/blob/main/docs/Tips.md), but my feature is not implemented.
- [X] My suggested feature was not mentioned by others, and it is not a duplicate feature.

### Summary

1.切换服务器功能更加方便
2.ui功能建议改进

### Solution or Design

1.切换需要右键图标，为什么不能设计点右边的服务器切换，可以不需要点多次右键
2.切换服务器可不可以隐藏powershell这个窗口，提瓦特之钥的替换（缺点就是切换会运行官方启动器，Starward可不依赖官方启动器）挺好的，可以添加一个快捷图标一键替换，不需要弹出其他窗口。
3.我个人觉得切换服务器有点繁琐，我选择了其他服点开始游戏那块地方还得再选择一次需要的服务器，有些许麻烦。建议可以选择了服务器立马后台替换文件（如果文件需要下载可以提示下载下次更换不需要再下载，可以让不需要其他服务器小伙伴不用付出多的内存空间），如果怕部分电脑会卡顿可以尝试添加对话框恢复原来的方法。
4.之前版本的右键可以快捷呼出那些祈愿记录文字菜单感觉好很多，现在只能点左上角才能显示文字菜单
以上是我的建议，望开发者采纳，也希望Starward能越做越好，谢谢
<img width="938" alt="image" src="https://github.com/Scighost/Starward/assets/31439445/cdac11d1-7397-4762-a531-36daa78e112b">

**Comment by CNChestnut** [comment]
切换服务器自动切换文件感觉不太合适，首先官服到b服还好说，比较小，官服到国际服的切换还是比较复杂的。先不说有些人没事喜欢点一下切换一下服务器（比如我，不是），真的误触了，面临的是无法暂停的切换中，何况还要等待切换回来。

在我之前的 issue #628 中，我顺带建议了一个UI问题。

就是在选择服务器后，如果客户端未安装，将`下载客户端`按钮直接替换成`切换客户端`。这样子也挺方便的。

作者也采纳了这个意见，但是在我安装了b服客户端，切换到官服时，这个切换客户端的按钮正常生效，但是我到国际服时，仍然提示下载游戏，这好像又是另一个bug。

还有就是点右边的服务器切换，确实是更符合一般用户的操作逻辑以及人性化的方案。

**Comment by Scighost** [comment]
新年好

谢谢你的反馈，标题栏的服务器切换只会改变应用配置，不会修改游戏资源文件；切换游戏客户端需要对比两客户端之间的差异，这个过程可能需要数十秒，如果需要下载额外资源，这个过程可能长至数分钟，需要一个额外的界面完成这一操作。

**Comment by BlankMya** [comment]
有一个小建议，就是可以在主界面界面选择完服务器点击切换服务器之后，直接弹出提示框确认即可，不需要在“切换服务器”的窗口中再选择一次。

**Comment by Lightczx** [comment]
> 提瓦特之钥

这玩意2.1之后就断更了，现在还能用？
