### ISSUE TITLE
[Bug] 铁道米游社工具箱无法获取包括模拟宇宙在内的信息

### ISSUE THREAD

**Issue by larmit** [Scighost/Starward#653]
### Checklist

- [X] My issue was not mentioned by others, and it is not a duplicate issue.

### Description

![image](https://github.com/Scighost/Starward/assets/46461441/6eaa2986-b8a9-4c66-a1d0-a11595887365)
如图所示，反复登录账号之后仍无法获取信息并提示错误，只有开拓月历可以正常获取。

### Reproduction Steps

在米游社工具箱登录账号后刷新模拟宇宙、忘却之庭或虚构叙事

### Starward Version

0.11.0

### Windows Version

Win 10 22H2-19045.3930

### Log

```shell
账号异常（10035）
```

**Comment by lijian12345** [comment]
同样的问题

**Comment by dfdfwff** [comment]
我也是

**Comment by xuan06zyx** [comment]
坐等解决方法qwq

**Comment by lingliuli** [comment]
同样

**Comment by Chen-2905** [comment]
still not fixed

**Comment by Entity616** [comment]
蹲个修复方法，原也同样无法获取，报错5003

**Comment by yyfmhyx** [comment]
期待作者解答，翻阅使用介绍并重新安装相关前置和软件后也没有得到解决

**Comment by Scighost** [comment]
参考 #704
