### ISSUE TITLE
[Feature]增加崩坏：星穹铁道China Cloud服务器（云·星穹铁道）选项

### ISSUE THREAD

**Issue by RobinJBK** [Scighost/Starward#654]
### Checklist

- [X] I have already read [docs/Tips.md](https://github.com/Scighost/Starward/blob/main/docs/Tips.md), but my feature is not implemented.
- [X] My suggested feature was not mentioned by others, and it is not a duplicate feature.

### Summary

2月6日，米哈游官方推出了[云·星穹铁道](https://sr.mihoyo.com/cloud/#/)，但是目前为止没有更新这一服务器（恼
目前虽未发布了Windows端，但是有网页版，所以能否增加这一服务器，启动时启动到[云·星穹铁道网页版](https://sr.mihoyo.com/cloud/#/)

### Solution or Design

增加这一服务器，启动时启动到[云·星穹铁道网页版](https://sr.mihoyo.com/cloud/#/)，可以应用内置Webview渲染网页

**Comment by RobinJBK** [comment]
大概这样？
P图技术不高请谅解
![Uploading 网页捕获_9-2-2024_153515_sr.mihoyo.com.jpeg…]()

**Comment by Scighost** [comment]
新年好

谢谢你的建议，云铁道没有桌面客户端的版本，请使用浏览器游玩以获得更好的体验。
