### ISSUE TITLE
[Feature] Autostart & Configuration Option

### ISSUE THREAD

**Issue by GhostVPN1** [Scighost/Starward#655]
### Checklist

- [X] I have already read [docs/Tips.md](https://github.com/Scighost/Starward/blob/main/docs/Tips.md), but my feature is not implemented.
- [X] My suggested feature was not mentioned by others, and it is not a duplicate feature.

### Summary

Add autostart to the luncher and posibility to use acces the game settings via shift + luncher 

### Solution or Design

- Start when Windows start > Check in/out box 
- Start the Configuration window before game lunch > Chech in box | After game lunch the state goes from 1 to 0 and the usser need mark the option every time.

**Comment by Scighost** [comment]
Thank you for your suggestion, I have no plans to add the startup feature. But you can implement by yourself.
- Create a shortcut for Starward.exe
- Change the startup parameter to `--hide true`
- Move the shortcut file to the [startup folder](https://support.microsoft.com/en-us/windows/add-an-app-to-run-automatically-at-startup-in-windows-10-150da165-dcd9-7230-517b-cf3c295d89dd)
