### ISSUE TITLE
[Feature] 优化祈愿/跃迁记录

### ISSUE THREAD

**Issue by misaka10384** [Scighost/Starward#657]
### Checklist

- [X] I have already read [docs/Tips.md](https://github.com/Scighost/Starward/blob/main/docs/Tips.md), but my feature is not implemented.
- [X] My suggested feature was not mentioned by others, and it is not a duplicate feature.

### Summary

希望加入历史记录 比如 历史上某个池子我抽了几发  主要是为了星穹铁道  原神的话胡桃就可以胜任了

### Solution or Design

参考胡桃
![image](https://github.com/Scighost/Starward/assets/61707010/9d1c9f61-e6d0-4b08-9a2d-073c820b528c)

**Comment by CNChestnut** [comment]
我觉得这个功能加到启动器里或许有一些臃肿？

在一个专门的工具箱里显然是更好的。作者的另一个项目 [寻空](https://github.com/xunkong/xunkong) 里有类似的功能。

不过行空貌似也挺久没有更新的了，作者似乎主要就在更新 Starward，胡桃的功能性上我觉得更强，寻空目前来说我认为唯一的亮点就是有关于角色复刻的那个图。

此外，星空也提供了跟胡桃一样的**最基础**的启动游戏功能。

虽然现在的 Starward 功能好像也似乎有点多。

或许可以考虑 Starward 和寻空做一个整合，现在我确实觉得有一些雍肿，主要是 Starward 中自带的一些小功能，而这些功能基本上在工具箱中也会存在，而工具箱也提供基础的启动功能。虽然说我明白各个软件有自身的侧重点，但用起来确实怪怪的。

**Comment by misaka10384** [comment]
> 我觉得这个功能加到启动器里或许有一些臃肿？
> 
> 在一个专门的工具箱里显然是更好的。作者的另一个项目 [寻空](https://github.com/xunkong/xunkong) 里有类似的功能。
> 
> 不过寻空貌似也挺久没有更新的了，作者似乎主要就在更新 Starward，胡桃的功能性上我觉得更强，寻空目前来说我认为唯一的亮点就是有关于角色复刻的那个图。
> 
> 此外，星空也提供了跟胡桃一样的**最基础**的启动游戏功能。
> 
> 虽然现在的 Starward 功能好像也似乎有点多。
> 
> 或许可以考虑 Starward 和寻空做一个整合，现在我确实觉得有一些雍肿，主要是 Starward 中自带的一些小功能，而这些功能基本上在工具箱中也会存在，而工具箱也提供基础的启动功能。虽然说我明白各个软件有自身的侧重点，但用起来确实怪怪的。

主要是目前我没找到什么太好用的查看星铁历史卡池记录的应用

**Comment by Scighost** [comment]
新年好

谢谢你的建议，但是我不会考虑实现这个功能。
