### ISSUE TITLE
[Bug] An error occurs when using starward's repair mode

### ISSUE THREAD

**Issue by hi-kds** [Scighost/Starward#658]
### Checklist

- [ ] My issue was not mentioned by others, and it is not a duplicate issue.

### Description

未知错误： Could not find a part of the path 'C:\Games\GenshinImpact\YuanShen_Data\Native\Data\Metadata\global-metadata.dat'.

### Reproduction Steps

Install Genshin Impact using repair mode

### Screenshots

![Desktop Screenshot 2024 02 12 - 11 36 19 00](https://github.com/Scighost/Starward/assets/69287770/32931a0f-6d95-43c0-a66c-ef975d9dedb9)

### Starward Version

0.11.0

### Windows Version

Windows11 23H2

### Log

```shell
[11:37:30.517] [INFO] 
Welcome to Starward v0.11.0
System: Microsoft Windows NT 10.0.22631.0
Command Line: C:\Users\Fang\Documents\Starward\app-0.11.0\Starward.dll repair --biz hk4e_cn --loc "D:\Program Files\Genshin Impact\Game" --lang 1

[11:37:30.541] [INFO] Starward.Services.DatabaseService
Database path is 'C:\Users\Fang\Documents\Starward'

[11:37:30.556] [INFO] Starward.Services.DatabaseService
Database version is 8, target version is 8.

[11:37:30.752] [INFO] Starward.Services.InstallGame.GenshinInstallGameService
Initialize install game service
biz: hk4e_cn
path: "D:\Program Files\Genshin Impact\Game"
lang: Chinese
repair: True
reinstall: False

[11:37:30.774] [INFO] Starward.Services.InstallGame.GenshinInstallGameService
Start install game, skipVerify: False

[11:37:30.774] [INFO] Starward.Services.InstallGame.GenshinInstallGameService
Repair mode, prepare for repair.

[11:37:31.274] [INFO] Starward.Services.InstallGame.GenshinInstallGameService
Repair mode, verify files.
```

**Comment by hi-kds** [comment]
Honkai: Star Rai seems to have a similar problem

**Comment by hi-kds** [comment]
Github cannot upload the complete log. For details, access https://drive.google.com/file/d/1sSXmKQ9rj-XChV1zmT3xqqWHG5t2Acye/view?usp=sharing

**Comment by Scighost** [comment]
新年好，thanks for your feedback, it would be repaired latter.
