### ISSUE TITLE
[Question] 把starward数据文件存放在小米云盘里自动备份，存在数据文件自动删除的情况

### ISSUE THREAD

**Issue by AizawaHikaru233** [Scighost/Starward#660]
### Checklist

- [X] I have already read [docs/Tips.md](https://github.com/Scighost/Starward/blob/main/docs/Tips.md), but my question is not solved.
- [x] My question was not mentioned by others, and it is not a duplicate question.

### Description

猜测是由于备份机制是先删除源文件然后再新建文件导致云盘出现误判以为文件被删除导致的

### Starward Version

0.11.0

### Windows Version

22621.2861

### Log

```shell
无
```

### Additional Context

小米云盘 2.5.4 Mi Laptop

**Comment by Scighost** [comment]
新年好

你的描述不是很清楚，是原始数据文件被删除还是备份的数据文件被删除，以及你的操作步骤是什么？

**Comment by AizawaHikaru233** [comment]
> 新年好
> 
> 你的描述不是很清楚，是原始数据文件被删除还是备份的数据文件被删除，以及你的操作步骤是什么？

![image](https://github.com/Scighost/Starward/assets/79595843/e73ab650-ab18-49f6-9a92-a9c60bab0881)（图里备份文件是我把数据文件从本地磁盘复制到云盘里之后手动删的）
只有原始文件被删除，且没有备份文件产生，如果触发这个问题，打开starward会卡住什么都不显示，跟下图里一样
![image](https://github.com/Scighost/Starward/assets/79595843/2a24d488-5411-483c-8883-080eba15a949)

**Comment by Scighost** [comment]
不用担心
`*-shm` 和 `*-wal` 文件是 SQLite 数据库读写过程中产生的日志文件，正常情况下它们会在进程结束时被自动删除。如果强制结束进程则会导致这两个文件删除失败，从而被小米云盘自动备份。打开 Starward 卡住**可能**是因为小米云盘备份过程中独占了文件，软件无法读取数据库，等备份完成后才能继续运行。
