### ISSUE TITLE
关于右键快捷打开菜单

### ISSUE THREAD

**Issue by Pizazz-stack** [Scighost/Starward#662]
### Checklist

- [X] I have already read [docs/Tips.md](https://github.com/Scighost/Starward/blob/main/docs/Tips.md), but my feature is not implemented.
- [X] My suggested feature was not mentioned by others, and it is not a duplicate feature.

### Summary

我觉得那个功能挺好用的，能不能加回来？

### Solution or Design

改成那种可开关的

**Comment by Scighost** [comment]
新年好

谢谢你的建议，你可以在设置中启用 `始终显示导航侧栏图标`
