### ISSUE TITLE
[Feature] 希望增加gitee项目地址，解决国区网络功能受限问题，增加原神120帧设置

### ISSUE THREAD

**Issue by fanxingbenchen** [Scighost/Starward#663]
### Checklist

- [X] I have already read [docs/Tips.md](https://github.com/Scighost/Starward/blob/main/docs/Tips.md), but my feature is not implemented.
- [X] My suggested feature was not mentioned by others, and it is not a duplicate feature.

### Summary

希望增加gitee项目地址，解决国区网络功能受限问题，增加原神120帧设置

### Solution or Design

能否模仿胡桃工具箱改进界面

**Comment by Scighost** [comment]
新年好

谢谢你的建议，因为 Gitee 相比于 GitHub 缺少了很多功能，我没有使用 Gitee 的计划；请自行使用第三方工具解锁原神帧率。
