### ISSUE TITLE
[Feature] 铁道游戏设置帧数会导致自定义启动器失效

### ISSUE THREAD

**Issue by 233YUZI** [Scighost/Starward#672]
### Checklist

- [X] I have already read [docs/Tips.md](https://github.com/Scighost/Starward/blob/main/docs/Tips.md), but my feature is not implemented.
- [X] My suggested feature was not mentioned by others, and it is not a duplicate feature.

### Summary

启动器的游戏设置的帧率设置是写死的，是全局生效的，设置完后即使不用starward启动，直接用米哈游官方启动，也会生效。**导致自定义启动程序功能失效**
![image](https://github.com/Scighost/Starward/assets/69708373/7a47169e-d43d-40b5-98d3-801ef1799e5f)
我的需求是**解锁铁道120帧**，可是启动器的方案是修改注册表，**导致游戏内图形设置无法使用**
![image](https://github.com/Scighost/Starward/assets/69708373/11c976bb-27b9-4b72-90c4-5fb9a9d1b39c)
我使用的[自定义启动器](https://www.bilibili.com/video/BV1am4y117gn)是支持修改帧率的同时保证游戏内图形设置正常使用的。
希望能给游戏设置选项加一个判断条件，使用自定义启动器时自动禁用启动器内设置。
还有，游戏设置必须在starward内启动才生效，这种写死的太恶心了，导致我现在都不知道怎么改回来，以至于改回60帧，我的自定义启动器仍然失效

### Solution or Design

游戏设置参数必须在starward内且不使用自定义启动器才生效，这样直接可以避免参数写死导致自定义启动器失效
我现在即使改回60帧，我的自定义启动器仍然失效，告诉我怎么改回未使用starward之前的状态
![image](https://github.com/Scighost/Starward/assets/69708373/5becbf51-c0a3-4442-9c26-1604729bef8d)

**Comment by Scighost** [comment]
抱歉，你的描述太过混乱，我无法理解。
