### ISSUE TITLE
[Feature] German

### ISSUE THREAD

**Issue by GhostVPN1** [Scighost/Starward#673]
### Checklist

- [X] I have already read [docs/Tips.md](https://github.com/Scighost/Starward/blob/main/docs/Tips.md), but my feature is not implemented.
- [X] My suggested feature was not mentioned by others, and it is not a duplicate feature.

### Summary

Please add to Crowdin, L: German 

### Solution or Design

I do the translation job in free time

**Comment by Scighost** [comment]
Hi, thank you for helping us with our localization translation work. I have already added German in Crowdin.
