### ISSUE TITLE
[Bug] 导出的Json文件名拼写错误

### ISSUE THREAD

**Issue by AuroraZiling** [Scighost/Starward#675]
### Checklist

- [X] My issue was not mentioned by others, and it is not a duplicate issue.

### Description

代码行：[GachaLogPage.xaml.cs](https://github.com/Scighost/Starward/blob/5961712d10a67b2d3b59ef3ef430efa3b65154cc/src/Starward/Pages/GachaLogPage.xaml.cs#L569)
`Stardward` -> `Starward`

### Reproduction Steps

导出Json文件

### Starward Version

0.11.0

### Windows Version

22631.3155

### Log

```shell
无需
```

**Comment by Scighost** [comment]
感谢你的反馈
