### ISSUE TITLE
[Question] 请问该如何任务栏右键菜单中的其他服务器

### ISSUE THREAD

**Issue by DWin233** [Scighost/Starward#676]
### Checklist

- [X] I have already read [docs/Tips.md](https://github.com/Scighost/Starward/blob/main/docs/Tips.md), but my question is not solved.
- [X] My question was not mentioned by others, and it is not a duplicate question.

### Description

我没有使用其他服务器的必要，但是不知道进行过什么操作之后任务栏右键菜单中出现了哔哩哔哩服。我想知道该如何移除它们？

### Starward Version

0.11.0

### Windows Version

22621.3155

**Comment by DWin233** [comment]
(https://github.com/Scighost/Starward/assets/60612754/bf217aef-4736-40eb-88c3-e3f262ba98ca)

**Comment by DWin233** [comment]
![屏幕截图 2024-02-28 134116](https://github.com/Scighost/Starward/assets/60612754/612dab43-c39c-45d2-8bc2-7b4f29f3788b)

**Comment by Scighost** [comment]
在对应的游戏页面点击 `一键修复` 即可
