### ISSUE TITLE
[Question] 希望能填加一个后台自动静音的功能

### ISSUE THREAD

**Issue by yatokszc** [Scighost/Starward#677]
### Checklist

- [X] I have already read [docs/Tips.md](https://github.com/Scighost/Starward/blob/main/docs/Tips.md), but my question is not solved.
- [X] My question was not mentioned by others, and it is not a duplicate question.

### Description

希望能出一个后台自动静音的功能

### Starward Version

0.11.0

### Windows Version

22631.3155

**Comment by Scighost** [comment]
能再详细地描述一下吗

**Comment by Rimliya** [comment]
> 能再详细地描述一下吗

其实就是 不在前台焦点时，游戏静音

**Comment by Scighost** [comment]
这个是游戏自身的功能
