### ISSUE TITLE
[Feature] 首页可嵌入下载菜单，可添加第三方工具箱

### ISSUE THREAD

**Issue by anzheerdiya** [Scighost/Starward#679]
### Checklist

- [X] I have already read [docs/Tips.md](https://github.com/Scighost/Starward/blob/main/docs/Tips.md), but my feature is not implemented.
- [X] My suggested feature was not mentioned by others, and it is not a duplicate feature.

### Summary

下载菜单可以嵌入到主页中，无需二级目录菜单。
您可以添加第三方工具箱。
### Solution or Design

![屏幕截图 2024-03-02 000135](https://github.com/Scighost/Starward/assets/83170394/9440cc12-2a9f-4726-a951-3a15934e6521)
![屏幕截图 2024-03-02 003059](https://github.com/Scighost/Starward/assets/83170394/e1cb0657-c887-4fe9-846a-e91e7daa74f3)

**Comment by Scighost** [comment]
谢谢你的建议，但是 Starward 不强制使用管理员权限启动，所以做不到在进程内下载游戏；以及内置的浏览器没有去广告插件，第三方工具的体验不会很好。
如果你有这方面的需求，建议使用 [Collapse](https://github.com/CollapseLauncher/Collapse) 。
