### ISSUE TITLE
[Bug] B服转国际服不会自动删除PCGameSDK.dll

### ISSUE THREAD

**Issue by HiruOcha** [Scighost/Starward#680]
### Checklist

- [x] My issue was not mentioned by others, and it is not a duplicate issue.

### Description

从B服直接切换客户端到国际服时，不会自动删除Plugins文件夹里的PCGameSDK.dll,导致进游戏后显示错误

### Reproduction Steps

切换客户端：原神 - 哔哩哔哩服 → 原神 - 国际服

### Starward Version

0.11.0

### Windows Version

22631.3235

### Log

```shell
无
```

**Comment by Scighost** [comment]
谢谢你反馈
