### ISSUE TITLE
[Bug] ExplorerPatcher Shell Conflicts with Starward

### ISSUE THREAD

**Issue by studiobuttermedia** [Scighost/Starward#681]
### Checklist

- [X] My issue was not mentioned by others, and it is not a duplicate issue.

### Description

There's an issue where if you have ExplorerPatcher (a Windows tweak to change Explorer Behaviors) and have the option "Register as Shell Extension" enabled, Starward will crash. This behavior was found thru Windows Event Viewer as Logs doesn't show all the needed info.

### Reproduction Steps

Install [ExplorerPatcher](https://github.com/valinet/ExplorerPatcher), open "Properties (ExplorerPatcher)", under File Explorer, enable "Register as Shell Extension". (Restarting is Optional)
Try to open Starward.

### Expected Behavior

It should stay on

### Starward Version

0.11.0

### Windows Version

22631.3155

### Log

```shell
[In-App Log]
[20:15:30.829] [INFO] 
Welcome to Starward v0.11.0
System: Microsoft Windows NT 10.0.22631.0
Command Line: C:\Launchers\Starward-Dev\app-0.11.0\Starward.dll

[20:15:30.859] [INFO] Starward.Services.DatabaseService
Database path is 'C:\Launchers\Starward-Dev'

[20:15:30.893] [INFO] Starward.Services.DatabaseService
Database version is 8, target version is 8.

[20:15:30.957] [INFO] Starward.Pages.MainPage
Last game region is hk4e_global

[20:15:30.968] [INFO] Starward.Pages.MainPage
Navigate to "LauncherPage" with param hk4e_global

[20:15:31.639] [INFO] Starward.Pages.LauncherPage
Game install path of hk4e_global: "C:\Program Files\Genshin Impact\Genshin Impact game"

[20:15:31.682] [INFO] Starward.Pages.LauncherPage
Acutal version and gamebiz of hk4e_global is "4.4.0", None.

[20:15:33.752] [INFO] Starward.Services.UpdateService
Start to check update (Preview: False, Arch: X64)

[Windows Event Viewer]
Faulting application name: Starward.exe, version: 0.11.0.0, time stamp: 0x65680000
Faulting module name: ExplorerPatcher.amd64.dll, version: 22621.3007.63.2, time stamp: 0x65ce6630
Exception code: 0xc0000005
Fault offset: 0x000000000000d433
Faulting process id: 0x0x5BBC
Faulting application start time: 0x0x1DA6CA3B35EB1CC
Faulting application path: C:\Launchers\Starward-Dev\app-0.11.0\Starward.exe
Faulting module path: C:\Program Files\ExplorerPatcher\ExplorerPatcher.amd64.dll
Report Id: a66a6c63-9f77-4175-8d72-03ac5db4219d
Faulting package full name: 
Faulting package-relative application ID:
```

### Additional Context

ExplorerPatcher also have a CN Localization version [here](https://github.com/zetaloop/ExplorerPatcher)

Additionally if anyone using ExplorerPatcher or any similar Windows Explorer Tweaks and experience crashes, try to Disable "Register as Shell Extension" or any Shell related features

**Comment by Scighost** [comment]
Thanks for your feedback.
According to the logs, ExplorerPatcher.amd64.dll was injected into the Starward.exe process causing the crash. Unfortunately though, this is not a normal usage process and I don't have any plans to try to fix this.
