### ISSUE TITLE
[Question] 句柄数超两千，这个现象正常吗？

### ISSUE THREAD

**Issue by MJSummer** [Scighost/Starward#682]
### Checklist

- [X] I have already read [docs/Tips.md](https://github.com/Scighost/Starward/blob/main/docs/Tips.md), but my question is not solved.
- [X] My question was not mentioned by others, and it is not a duplicate question.

### Description

电脑开机7天，句柄数干到了20w+，所以突发奇想问问这样的软件多少句柄数是比较正常的？
![image](https://github.com/Scighost/Starward/assets/73144479/9ffb91d8-dbe9-4855-9324-4f7a1e8c38e8)

### Starward Version

0.11.0

### Windows Version

19045.3930

**Comment by Scighost** [comment]
确实挺多的，不过对正常使用没有影响。

**Comment by Lightczx** [comment]
我就这么说吧，Windows资源管理器有4K左右的句柄
