### ISSUE TITLE
[Feature] 建议将“游戏正在运行”检测限制到当前Session，与游戏本体保持同步

### ISSUE THREAD

**Issue by oloukou1** [Scighost/Starward#692]
### Checklist

- [X] I have already read [docs/Tips.md](https://github.com/Scighost/Starward/blob/main/docs/Tips.md), but my feature is not implemented.
- [X] My suggested feature was not mentioned by others, and it is not a duplicate feature.

### Summary

当前游戏即使在其他login session运行也仍然会被starward检测到，导致无法从starward二次启动。但其实游戏本身并不会检索到其他session，只要当前session内没有原神在运行即可运行第二个。主要影响windows server和rdpwrap用户

### Solution or Design

检测位置在https://github.com/Scighost/Starward/blob/38fe04d2078389c70947ea66287fa1cf7a61882b/src/Starward/Services/GameService.cs#L77 ，只要对获得的ProcessID的SessionID跟当前进程的SessionID再对比一次即可，代码补完一下大概是这个样子？
```
return Process.GetProcessesByName(name).Where(p => p.SessionId == Process.GetCurrentProcess().SessionId).ToArray().FirstOrDefault();
```
该修改理论上应该对无此需求的其他用户无影响。

**Comment by Scighost** [comment]
谢谢你的建议，我的测试结果也如同你描述的那样。
