### ISSUE TITLE
[Feature] 允许通过启动参数设置静默启动

### ISSUE THREAD

**Issue by PeterBilly** [Scighost/Starward#693]
### Checklist

- [X] I have already read [docs/Tips.md](https://github.com/Scighost/Starward/blob/main/docs/Tips.md), but my feature is not implemented.
- [X] My suggested feature was not mentioned by others, and it is not a duplicate feature.

### Summary

我通过添加Windows 计划任务程序让Starward用管理员权限在开机的时候自动启动。以便能无UAC弹窗地启动游戏。但是代价是每次开机后都会显示Starward的界面。
是否存在或者能否添加一个启动参数，以便能静默地启动Starward，而不显示界面？

### Solution or Design

添加一个基于如 --silent 启动参数的静默启动功能

**Comment by Scighost** [comment]
`Starward.exe --hide true`
