### ISSUE TITLE
[Feature] 免解压下载

### ISSUE THREAD

**Issue by kndxhz** [Scighost/Starward#696]
### Checklist

- [X] I have already read [docs/Tips.md](https://github.com/Scighost/Starward/blob/main/docs/Tips.md), but my feature is not implemented.
- [X] My suggested feature was not mentioned by others, and it is not a duplicate feature.

### Summary

希望能够更新原神官启刚更新的免解压下载，减少磁盘占用

### Solution or Design

![image](https://github.com/Scighost/Starward/assets/113306265/d6eae13b-b3b9-4b6a-9c8e-66c1cc33f948)
抓包数据
` 
GET /client_app/download/pc_zip/20240119183624_htNiHcgyl05jgCo9/ScatteredFiles/YuanShen_Data/StreamingAssets/AudioAssets/Music1.pck HTTP/1.1
Host: autopatchcn.yuanshen.com
Connection: Keep-Alive
Accept-Language: zh-CN,en,*
User-Agent: Mozilla/5.0
Accept-Encoding: gzip, deflate
`

**Comment by Scighost** [comment]
谢谢你的建议，但是你没有给出任何有用的信息，我将关闭此 issue
