### ISSUE TITLE
Changes to the way download works

### ISSUE THREAD

**Issue by studiobuttermedia** [Scighost/Starward#698]
### Checklist

- [X] I have already read [docs/Tips.md](https://github.com/Scighost/Starward/blob/main/docs/Tips.md), but my feature is not implemented.
- [X] My suggested feature was not mentioned by others, and it is not a duplicate feature.

### Summary

Recently HoYoverse just announced that Genshin Launchers will be doing an A/B test between the Old Download method and the new one which download a ton of Chunked Files that use zstd-compressed method. 
There will be a lot of download links and passwords for those.
Currently the Collapse Team are aware about this.
I’m also suspecting that other HoYoverse Games will be using this method instead. (Including the upcoming game Zenless Zone Zero)

Here’s the main File URLs

https://sg-public-api.hoyoverse.com/downloader/sophon_chunk/api/getBuild?branch=main&package_id=Ul0pnnZo8h&password=SSaKNEvZjrK0&plat_app=cxhpq4g4rgg0

https://sg-public-api.hoyoverse.com/downloader/sophon_chunk/api/getBuild?branch=predownload&package_id=Ul0pnnZo8h&password=yran8QsvU88T&plat_app=cxhpq4g4rgg0

### Solution or Design

Changes how the new Download method work

**Comment by Scighost** [comment]
Thanks for your suggestion, you help me a lot.

**Comment by Scighost** [comment]
Traced by #725
