### ISSUE TITLE
[Question]  账号切换功能需要周期性重新登陆

### ISSUE THREAD

**Issue by BlueXin108** [Scighost/Starward#699]
### Checklist

- [X] I have already read [docs/Tips.md](https://github.com/Scighost/Starward/blob/main/docs/Tips.md), but my question is not solved.
- [X] My question was not mentioned by others, and it is not a duplicate question.

### Description

2个不同的游戏账号切换时 会概率性遇到需要重新输入账密登录的问题

尤其是如果不对当前账号进行定期手动的重新保存
时间长了以后2个账号只要产生切换都会要重新输入账密

目前只启动崩铁所以只在崩铁遇到过

### Starward Version

0.11.1

### Windows Version

23631.3155

**Comment by Scighost** [comment]
如果网络环境发生了变化，会导致当前登录的账号失效，这是正常现象。

**Comment by BlueXin108** [comment]
> 如果网络环境发生了变化，会导致当前登录的账号失效，这是正常现象。
感谢 可能是因为这边一直使用手机热点的问题
