### ISSUE TITLE
[Question] 原神b服每一次版本的预下载再打开就会变成官服 请问是我的个人问题吗

### ISSUE THREAD

**Issue by subailin89** [Scighost/Starward#700]
### Checklist

- [X] I have already read [docs/Tips.md](https://github.com/Scighost/Starward/blob/main/docs/Tips.md), but my question is not solved.
- [X] My question was not mentioned by others, and it is not a duplicate question.

### Description

 原神b服每一次版本的预下载再打开就会变成官服 请问是我的个人问题吗

### Starward Version

0.11.0

### Windows Version

10.0.19045版本 19045

**Comment by Scighost** [comment]
抱歉，我的B服客户端在预下载完成后，没有出现你遇到的问题。
