### ISSUE TITLE
[Feature] uninstall.exe缺失

### ISSUE THREAD

**Issue by The-Fool-Veneto** [Scighost/Starward#701]
### Checklist

- [X] I have already read [docs/Tips.md](https://github.com/Scighost/Starward/blob/main/docs/Tips.md), but my feature is not implemented.
- [X] My suggested feature was not mentioned by others, and it is not a duplicate feature.

### Summary

我想卸载重新安装，却没有uninstall.exe执行，如果删去程序文件夹则无法解决注册表的冗余。

### Solution or Design

整一个uninstall.exe即可。

**Comment by Scighost** [comment]
![image](https://github.com/Scighost/Starward/assets/61003590/2e3200fc-d332-42cf-812a-ed48a5fe99b3)

**Comment by gongfuture** [comment]
> ![image](https://private-user-images.githubusercontent.com/61003590/312082140-2e3200fc-d332-42cf-812a-ed48a5fe99b3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTAzMDA0MTUsIm5iZiI6MTcxMDMwMDExNSwicGF0aCI6Ii82MTAwMzU5MC8zMTIwODIxNDAtMmUzMjAwZmMtZDMzMi00MmNmLTgxMmEtZWQ0OGE1ZmU5OWIzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzEzVDAzMjE1NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTU1ZmI5MWYzMzczZjlkODhiMjQ4MWExN2U4YTRiMDAxZmE2OGMyYmExYTYxYWUwNmI3MjQ2ZDMwMWJjMDI0OTImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.uzHJlwfSVxzD1PTiJv3zokjej66-Q-_G7b-o3jJeE20)

我感觉他的意思是starward的卸载

**Comment by Scighost** [comment]
便携打包的不需要卸载程序，记得把 `%LocalAppData%\Starward` 文件夹删掉就好。

**Comment by The-Fool-Veneto** [comment]
> 便携打包的不需要卸载程序，记得把 `%LocalAppData%\Starward` 文件夹删掉就好。

⭐
