### ISSUE TITLE
用Starward启动游戏会出现游戏内公告/资讯等页面的字体显示异常

### ISSUE THREAD

**Issue by MikoAoi** [Scighost/Starward#71]
星铁出现了原神的字体，原神出现了无衬线体
大退之后用官方启动器启动游戏恢复了正常显示

![2](https://github.com/Scighost/Starward/assets/64834877/aad1fabb-b675-4fb2-af3f-122384e32584)
![3](https://github.com/Scighost/Starward/assets/64834877/ac885e76-a0e2-403e-86ae-a6841572958c)

**Comment by Scighost** [comment]
公告页面的字体是由游戏客户端通过 1221 端口提供的，但是此端口只有一个，如果同时启动多个游戏，大概率会出现字体混乱的问题。

**Comment by MikoAoi** [comment]
> 公告页面的字体是由游戏客户端通过 1221 端口提供的，但是此端口只有一个，如果同时启动多个游戏，大概率会出现字体混乱的问题。

谢谢作者还耐心回复！我后面发现跟启动器木有关系就关闭问题啦>< 再次感谢！
