### ISSUE TITLE
[Question] 关于旧版本的软件抽卡记录导出

### ISSUE THREAD

**Issue by TohoKabo** [Scighost/Starward#710]
### Checklist

- [X] I have already read [docs/Tips.md](https://github.com/Scighost/Starward/blob/main/docs/Tips.md), but my question is not solved.
- [X] My question was not mentioned by others, and it is not a duplicate question.

### Description

我之前有一个starward0.10.7的，之前提示需要安装.net desktop才能运行，但是我安装上之后还是不能启动，我重新下载新版本之后可以使用新的，但是现在想把旧的抽卡记录导出来，有什么办法没有

### Starward Version

0.10.7

### Windows Version

22631.3235

**Comment by Scighost** [comment]
把老的 `StarwardDatabase.db` 移动到新设定的文件夹里
