### ISSUE TITLE
大大能不能把它放到winget上去啊[Question] 

### ISSUE THREAD

**Issue by syh192508** [Scighost/Starward#711]
### Checklist

- [X] I have already read [docs/Tips.md](https://github.com/Scighost/Starward/blob/main/docs/Tips.md), but my question is not solved.
- [X] My question was not mentioned by others, and it is not a duplicate question.

### Description

如题

### Starward Version

0.12

### Windows Version

22621.1928

**Comment by Scighost** [comment]
谢谢你的建议，但是目前没有这个想法。
