### ISSUE TITLE
[Feature] 建议隐藏风险项目

### ISSUE THREAD

**Issue by 858622025** [Scighost/Starward#715]
### Checklist

- [X] I have already read [docs/Tips.md](https://github.com/Scighost/Starward/blob/main/docs/Tips.md), but my feature is not implemented.
- [X] My suggested feature was not mentioned by others, and it is not a duplicate feature.

### Summary

建议设置中加入一个配置选项，隐藏掉风险项目的入口，防止误触后频繁弹窗确认。或者拒绝后自动隐藏，不要风险功能的入口显现出来

### Solution or Design

建议设置中加入一个配置选项

**Comment by Scighost** [comment]
你提到的风险项目是什么？

**Comment by 858622025** [comment]
祈愿、跃迁记录，米游社工具箱，账号记录



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年3月16日(周六) 下午5:45
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [Scighost/Starward] [Feature] 建议隐藏风险项目 (Issue #715)




 
你提到的风险项目是什么？

**Comment by Scighost** [comment]
如果你不需要这些功能，可以无视它们，这不会影响到你使用其他的功能。
