### ISSUE TITLE
[Feature] 我希望可以增加从SToken获取祈愿记录

### ISSUE THREAD

**Issue by CreeperAWA** [Scighost/Starward#717]
### Checklist

- [X] I have already read [docs/Tips.md](https://github.com/Scighost/Starward/blob/main/docs/Tips.md), but my feature is not implemented.
- [X] My suggested feature was not mentioned by others, and it is not a duplicate feature.

### Summary

我希望可以增加从SToken获取祈愿记录

### Solution or Design

在祈愿记录刷新下拉菜单中增加从SToken获取祈愿记录，就像Snap Hutao一样

**Comment by Scighost** [comment]
谢谢你的建议，但是短时间内没有这方面的计划。
