### ISSUE TITLE
[Feature] 希望能够选择隐藏集录祈愿

### ISSUE THREAD

**Issue by ERYtrdfgc** [Scighost/Starward#718]
### Checklist

- [X] I have already read [docs/Tips.md](https://github.com/Scighost/Starward/blob/main/docs/Tips.md), but my feature is not implemented.
- [X] My suggested feature was not mentioned by others, and it is not a duplicate feature.

### Summary

在固定的区域显示四种甚至五种不同类型的记录显得很拥挤（且与隔壁的崩铁不对称），并且我个人并不喜欢这个新出的记录祈愿，再加上前瞻直播中提到它是”不定时开放“，以及在剩余时间处可以发现本期集录祈愿仅持续到上半卡池结束。各种迹象表明，它不一定能够一直开放，因此希望能像新手池一样设置一个隐藏选项

### Solution or Design

![Uploading 屏幕截图 2024-03-16 230720.png…]()

**Comment by Scighost** [comment]
谢谢你的建议，但是我不想实现这个功能。
