### ISSUE TITLE
[Feature] 希望能够联网同步祈愿/跃迁记录或游戏时间记录

### ISSUE THREAD

**Issue by swimfishx** [Scighost/Starward#720]
### Checklist

- [X] I have already read [docs/Tips.md](https://github.com/Scighost/Starward/blob/main/docs/Tips.md), but my feature is not implemented.
- [X] My suggested feature was not mentioned by others, and it is not a duplicate feature.

### Summary

如题
希望能够联网同步祈愿/跃迁记录或游戏时间记录
如果由于某些原因需更换设备/或者应用被不小心删除时
会导致祈愿/跃迁记录与游戏时间记录被清空
增加了联网服务器同步可以很好的解决这种情况
如上，感谢

### Solution or Design

联网同步祈愿/跃迁记录或游戏时间记录

**Comment by Scighost** [comment]
谢谢你的建议，备份功能需要你使用同步网盘解决，我不会提供相关服务。

**Comment by yuyanlike** [comment]
> 谢谢你的建议，备份功能需要你使用同步网盘解决，我不会提供相关服务。

你好 

> 谢谢你的建议，备份功能需要你使用同步网盘解决，我不会提供相关服务。

你好，是否能增加自行设置 webdav 地址的功能实现自有云盘数据同步功能。 
另请问目前有两台电脑的数据合并的方案吗。

**Comment by Scighost** [comment]
> 你好，是否能增加自行设置 webdav 地址的功能实现自有云盘数据同步功能。
> 另请问目前有两台电脑的数据合并的方案吗。

很遗憾，软件的设计仅考虑了单一设备使用的情况；即使是 WebDav 也只能完整地备份、还原整个数据库文件，也没有设计合并数据的方案。还是建议你使用成熟的同步网盘。
