### ISSUE TITLE
[Feature] 添加开关：切换抽卡记录界面是否开启宽度调整动画

### ISSUE THREAD

**Issue by zhuoxin-lzk** [Scighost/Starward#721]
### Checklist

- [X] I have already read [docs/Tips.md](https://github.com/Scighost/Starward/blob/main/docs/Tips.md), but my feature is not implemented.
- [X] My suggested feature was not mentioned by others, and it is not a duplicate feature.

### Summary

想让抽卡记录界面每个卡池的宽度不改变

### Solution or Design

平均分配宽度

**Comment by Scighost** [comment]
谢谢你的建议，但是我不想实现这个功能。

**Comment by zhuoxin-lzk** [comment]
> 谢谢你的建议，但是我不想实现这个功能。

😭
