### ISSUE TITLE
[Question] 请问一下，我在使用starward软件对 崩铁国际服进行抽卡分析的时候，明明在游戏中打开了抽卡分析界面，但是软件总是显示请在游戏中打开抽卡记录页面后再重试 Authkey Timeout

### ISSUE THREAD

**Issue by zhangqing520** [Scighost/Starward#733]
### Checklist

- [X] I have already read [docs/Tips.md](https://github.com/Scighost/Starward/blob/main/docs/Tips.md), but my question is not solved.
- [X] My question was not mentioned by others, and it is not a duplicate question.

### Description

[Question] 请问一下，我在使用starward软件对 崩铁国际服进行抽卡分析的时候，明明在游戏中打开了抽卡分析界面，但是软件总是显示请在游戏中打开抽卡记录页面后再重试 Authkey Timeout

### Starward Version

0.11.3

### Windows Version

2260

### Log

```shell
无
```

### Additional Context

无

**Comment by zhangqing520** [comment]
![image](https://github.com/Scighost/Starward/assets/76688987/57434e2c-6f83-41c9-8f4f-151d9248a6a9)

**Comment by Scighost** [comment]
把图中的这些文件夹删了再试试吧

**Comment by zhangqing520** [comment]
好像搞明白问题所在了。我这个国际服是通过第三方转换器，从国服转换过来的。国际服和国服的游戏启动目录名字不一样，国际服是Game，国服是Games，原作者为了省事，全部把两个统一成了Games，所以可能starward软件在获取抽卡文件时，使用的原来默认的文件路径，没有进行及时调整




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2024年3月21日(星期四) 下午3:42
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [Scighost/Starward] [Question] 请问一下，我在使用starward软件对 崩铁国际服进行抽卡分析的时候，明明在游戏中打开了抽卡分析界面，但是软件总是显示请在游戏中打开抽卡记录页面后再重试 Authkey Timeout (Issue #733)





 
把图中的这些文件夹删了再试试吧
