### ISSUE TITLE
[Bug] 预下载速度过慢

### ISSUE THREAD

**Issue by zhao0349** [Scighost/Starward#738]
### Checklist

- [X] My issue was not mentioned by others, and it is not a duplicate issue.

### Description

今天开启了崩坏：星穹铁道的2.1版本预下载，我在预下载的过程中发现starwards的下载速度远远低于官方启动器的速度，希望能排查一下原因

### Reproduction Steps

分别在两个客户端进行预下载，发现进度可以互通，但速度不一样

### Screenshots

![屏幕截图 2024-03-25 151340](https://github.com/Scighost/Starward/assets/65272027/00dc5540-04df-49d2-9563-1e8ed97cc522)
![屏幕截图 2024-03-25 151411](https://github.com/Scighost/Starward/assets/65272027/46d6b746-593c-4190-8eb3-01c7e80d7e5f)

### Starward Version

0.11.3

### Windows Version

26085.1

### Log

```shell
[15:13:47.365] [INFO] 
Welcome to Starward v0.11.3
System: Microsoft Windows NT 10.0.26085.0
Command Line: D:\Starward\app-0.11.3\Starward.dll

[15:13:47.398] [INFO] Starward.Services.DatabaseService
Database path is 'D:\Starward'

[15:13:47.426] [INFO] Starward.Services.DatabaseService
Database version is 8, target version is 8.

[15:13:47.509] [INFO] Starward.Pages.MainPage
Last game region is hkrpg_cn

[15:13:47.520] [INFO] Starward.Pages.MainPage
Navigate to "LauncherPage" with param hkrpg_cn

[15:13:48.220] [INFO] Starward.Pages.LauncherPage
Game install path of hkrpg_cn: "D:\Star Rail\Game"

[15:13:48.257] [INFO] Starward.Pages.LauncherPage
Acutal version and gamebiz of hkrpg_cn is "2.0.0", hkrpg_cn.

[15:13:49.455] [INFO] Starward.Services.UpdateService
Start to check update (Preview: True, Arch: X64)

[15:14:03.118] [INFO] Starward.Services.UpdateService
Current version: "0.11.3", latest version: "0.11.3", ignore version: null
```

**Comment by XYY1411** [comment]
同样，之前的时候能跑满带宽，现在用的 `1aaaedc3949ba59ab3wawculztf7oqtc4s4vdxjerr4.vegslb.com` 这个只能跑十几MB/s

**Comment by Womsxd** [comment]
> 同样，之前的时候能跑满带宽，现在用的 `1aaaedc3949ba59ab3wawculztf7oqtc4s4vdxjerr4.vegslb.com` 这个只能跑不到10MB/s

米哈游购买了字节跳动(抖音)的融合CDN服务，这个是**字节**的PCDN节点，当用户被解析到字节跳动的CDN上的时候会有概率会被字节调度到PCDN上面去

**Comment by Womsxd** [comment]
![image](https://github.com/Scighost/Starward/assets/45663319/c65f3867-fa6c-492b-9f09-a92aac4531c9)

pcdn已经没了，但是可能因为cdn服务商压力过大导致速度依然很慢，建议错峰下载

**Comment by XYY1411** [comment]
> > ![image](https://private-user-images.githubusercontent.com/45663319/324322476-c65f3867-fa6c-492b-9f09-a92aac4531c9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM3NjA4MzgsIm5iZiI6MTcxMzc2MDUzOCwicGF0aCI6Ii80NTY2MzMxOS8zMjQzMjI0NzYtYzY1ZjM4NjctZmE2Yy00OTJiLTlmMDktYTkyYWFjNDUzMWM5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDIyVDA0MzUzOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTg3ZTRmYTQ0NjliN2FjMGI5NzQyNmRjMjIyMWRlYzc3OWYyOWQxOTdjYjNlMDk0MzZiYmJkZDA2NWY5ZWQ0MGEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.64vQiXc6P5qCbYtwGCQtI_WVry2DtNEapXWMYu9X2SI)
> > pcdn已经没了，但是可能因为cdn服务商压力过大导致速度依然很慢，建议错峰下载
> 
> 今天原神的预下载倒是跟官方启动器差别没那么大了，官方启动器大约40MB/s，Starward是30MB/s，差别不大但不知为何仍然有些许差别![🤔](https://cdn.jsdelivr.net/gh/twitter/twemoji@14.0.2/assets/svg/1f914.svg)

我Starward下载只有13MB/s，官方启动器跑满带宽60MB/s
上次也是这样

**Comment by cxw620** [comment]
单纯是有些节点负载高有些节点负载低吧, 反正一年后再看这个 issue, 火山云还是最不行的那个, 晚高峰时段基本没速度, 别的也好不到哪里去都是抽奖, 拿到负载低的节点的 IP 就能跑满带宽, 要不然还是慢.

~~实在不行弄个测速得了~~
