### ISSUE TITLE
[Feature] 能否增加云游戏的时间总计

### ISSUE THREAD

**Issue by VanTesla** [Scighost/Starward#740]
### Checklist

- [X] I have already read [docs/Tips.md](https://github.com/Scighost/Starward/blob/main/docs/Tips.md), but my feature is not implemented.
- [X] My suggested feature was not mentioned by others, and it is not a duplicate feature.

### Summary

能否将云原神和云星铁游戏时长纳入检测，并且与原神和星铁的游戏时间累计？

### Solution or Design

在游戏界面增加选项是否使用云游戏启动

**Comment by Scighost** [comment]
抱歉，我没有明白你的需求，不过星穹铁道没有客户端版，不会被统计游戏时间。
