### ISSUE TITLE
崩铁导出祈愿记录为Excel后，使用excel打开提示需要修复

### ISSUE THREAD

**Issue by abandonstudy** [Scighost/Starward#744]
### Checklist

- [X] My issue was not mentioned by others, and it is not a duplicate issue.

### Description

崩铁导出祈愿记录为Excel后，使用excel打开提示需要修复。修复后查看内容是正常的

### Reproduction Steps

刷新起源记录，导出

### Expected Behavior

正常打开记录

### Screenshots

![image](https://github.com/Scighost/Starward/assets/94209629/be190ea7-ea25-4579-b02c-2db2996286f3)

### Starward Version

0.11.3

### Windows Version

19045.4170

### Log

```shell
none
```

**Comment by Scighost** [comment]
谢谢你的反馈，此问题存在很长时间了，我还没找到解决办法。

**Comment by aizhimoran** [comment]
对比修复前后的excel内部xml文件，差别最大的是sheet1.xml（表格数据）和sharedStrings.xml（重复字段索引文件）。
![Snipaste_2024-04-14_00-54-15](https://github.com/Scighost/Starward/assets/30517336/e92429a0-bcb9-4a74-8fd2-3930262e6e4e)
![Snipaste_2024-04-14_00-53-40](https://github.com/Scighost/Starward/assets/30517336/98bad29c-3e23-40f1-adb9-7fa8f5e8423b)
![Snipaste_2024-04-14_00-59-27](https://github.com/Scighost/Starward/assets/30517336/b4b36fda-e815-433e-afb8-5e86665479e5)
对比这两个文件感觉excel的修复内容是把原始的重复字段用索引的方式重构了
是不是上游的MiniExcel这部分代码造成的的？
![Snipaste_2024-04-14_01-05-13](https://github.com/Scighost/Starward/assets/30517336/9bdb585d-795d-425a-9fb7-cb1b32e6ac1d)
