### ISSUE TITLE
[Feature] Add a way to navigate through the "events" slideshow (again)

### ISSUE THREAD

**Issue by raw-binary** [Scighost/Starward#745]
### Checklist

- [X] I have already read [docs/Tips.md](https://github.com/Scighost/Starward/blob/main/docs/Tips.md), but my feature is not implemented.
- [X] My suggested feature was not mentioned by others, and it is not a duplicate feature.

### Summary

A few versions ago, I remember that you were able to navigate this "events" tab by either clicking on some bubbles that appear at the bottom right of the tab, and, if I remember correctly, left and right arrows so you can go back and forth.
![image](https://github.com/Scighost/Starward/assets/155600866/53e00175-0e07-4dbe-b545-757292142500)
This seems to have been removed and replaced with a number of the current tab you're on. It automatically moves to the next slide unless you hover over it, and you cannot go back to the start unless you switch games, i.e. from HSR to Genshin, or wait for it to reach the final slide.

### Solution or Design

I suggest adding arrows that let you navigate to the next and previous tabs, or at least bring back the bubbles that let you pick which event tab you were on, from previous versions of the launcher.

**Comment by Scighost** [comment]
Thanks for your feedback. I changed the style of banner because of:
- The button disappeared slowly
- Only 5 bubbles can be displayed at most

Now you could switch banner image by mouse wheel or swiping.
