### ISSUE TITLE
[Question] 请问能否固定应用本体所在文件夹的名称？

### ISSUE THREAD

**Issue by KeeLee2005** [Scighost/Starward#748]
### Checklist

- [X] I have already read [docs/Tips.md](https://github.com/Scighost/Starward/blob/main/docs/Tips.md), but my question is not solved.
- [X] My question was not mentioned by others, and it is not a duplicate question.

### Description

毫无疑问 Starward 是相当有用且有时候使用频率相当频繁的工具箱，所以我把它的打开窗口固定到了任务栏和开始菜单中以便快速打开。
但是由于应用本体位于 ./app-0.11.3 文件夹下，且这个文件夹的名称会随着版本更新而更改后面的版本号，导致每次更新我都需要重新固定或者修改快捷方式。
所以我想询问能否修改应用本体所在文件夹的名称，使其名称固定不再更改以免快捷方式随着版本更新而出现问题？

感谢开发者的付出！愿 Starward 越做越好！

### Starward Version

0.11.3

### Windows Version

19045.4170

**Comment by Scighost** [comment]
谢谢你的反馈，在 `app-0.11.3` 文件夹外有一个 422KB 的 `Starward.exe`，我称之为启动器的启动器，你把它固定为快捷方式就行。
