### ISSUE TITLE
[Bug] 应用无法启动

### ISSUE THREAD

**Issue by TheMyceliumOfAntan** [Scighost/Starward#750]
### Checklist

- [X] My issue was not mentioned by others, and it is not a duplicate issue.

### Description

运行后软件进程存在几秒后自动退出，没有任何报错、错误信息或日志输出，已安装.net运行库和WinAppSDK

### Reproduction Steps

直接双击Starward.exe后自动退出

### Starward Version

0.11.3，0.11.2

### Windows Version

19045.4046

### Log

```shell
没有任何日志输出
```

**Comment by Scighost** [comment]
谢谢你的反馈，但是你没有提供任何有用的信息，我也没法给你任何有用的帮助。
