### ISSUE TITLE
[Feature] 是否考虑可以添加Up角色/光锥的数据显示

### ISSUE THREAD

**Issue by chen274** [Scighost/Starward#751]
### Checklist

- [X] I have already read [docs/Tips.md](https://github.com/Scighost/Starward/blob/main/docs/Tips.md), but my feature is not implemented.
- [X] My suggested feature was not mentioned by others, and it is not a duplicate feature.

### Summary

目前仅有显示平均全五星，但是其实角色/光锥的UP池子，我理解的是，UP池子的数据，我感觉更有价值的数据是出UP角色的平均抽数而不是全五星抽数，希望可以考虑添加一下。

### Solution or Design

个人感觉简单的处理，UP角色/光锥的总抽数 / （总五星数量-常驻数量）即可，甚至总五星数量/常驻数量  歪的概率也能显示。

**Comment by chen274** [comment]
因为按照常驻来计算，后续应该也没用太多维护修改成本。

**Comment by Scighost** [comment]
谢谢你的建议，但是我不会考虑**有**维护成本的功能
