### ISSUE TITLE
[Feature] 希望加入成就统计功能

### ISSUE THREAD

**Issue by CXF233** [Scighost/Starward#752]
### Checklist

- [X] I have already read [docs/Tips.md](https://github.com/Scighost/Starward/blob/main/docs/Tips.md), but my feature is not implemented.
- [X] My suggested feature was not mentioned by others, and it is not a duplicate feature.

### Summary

我希望启动器可以加入成就统计功能，具体功能包括识别游戏账号内已有成就、对比数据库显示未完成成就、可以根据版本和分类等筛选成就

### Solution or Design

或许一些ocr的库有助于实现这个功能

**Comment by Scighost** [comment]
谢谢你建议，如果你有成就相关的需求，推荐你使用[胡桃工具箱](https://github.com/DGP-Studio/Snap.Hutao)。

**Comment by CXF233** [comment]
谢谢@Scighost 的推荐，不过星穹铁道似乎并不能使用胡桃工具箱统计成就，希望得到reopen或其他的理由
