### ISSUE TITLE
[Bug] 点更新因为国内访问github有时候不行，导致一直0进度，直接关闭后就打不开了

### ISSUE THREAD

**Issue by ssssshql** [Scighost/Starward#756]
### Checklist

- [X] My issue was not mentioned by others, and it is not a duplicate issue.

### Description

如题

### Reproduction Steps

如题

### Starward Version

all

### Windows Version

19045.3693

### Log

```shell
如题
```

**Comment by Scighost** [comment]
你给出的信息不足，很抱歉我不能给你任何帮助，建议重新下载。
