### ISSUE TITLE
[Question] 请问有人遇到快捷方式消失然后抽卡记录全部消失的情况吗

### ISSUE THREAD

**Issue by Dongagent** [Scighost/Starward#761]
### Checklist

- [X] I have already read [docs/Tips.md](https://github.com/Scighost/Starward/blob/main/docs/Tips.md), but my question is not solved.
- [X] My question was not mentioned by others, and it is not a duplicate question.

### Description

昨天还在用的好好的，今天开机发现桌面的快捷方式消失了，找到原始的文件夹打开看到初次使用的界面，心想不妙，然后一路点进去发现确实抽卡记录都没了。游戏路径的话BH3和Star rail是反的，原倒是路径对的。但原和铁的抽卡记录都空了。这下不知道怎么办了，想请问有没有json路径之类的呢？看看我能不能导回来

### Starward Version

0.11.4

### Windows Version

19045.2251

**Comment by Scighost** [comment]
不要慌，你的软件和数据文件夹都放在哪个地方，这几天有没有什么更新软件或系统文件清理的操作？

**Comment by Dongagent** [comment]
> 不要慌，你的软件和数据文件夹都放在哪个地方，这几天有没有什么更新软件或系统文件清理的操作？

并没有，软件在D盘，数据文件夹没理解错应该在默认路径。没印象更新软件什么的。我看了下数据文件夹（C:\Users\mlDSY\AppData\Local\Starward）里面的log文件夹能追溯到去年12月也就是我刚开始用的时候。Starward_231231_115740
至于抽卡记录对应的db或者其他文件我不太清楚是哪一个，所以现在在找抽卡记录（一直觉得这个本地软件不会出现数据丢失）

**Comment by Scighost** [comment]
一般来说，如果你没有明确更改的画，数据文件就在Starward文件夹里，建议你下载 Everything 查一下本地所有的 `StarwardDatabase.db` 文件。

**Comment by Dongagent** [comment]
感谢感谢！找到了！最开始担心文件丢失没放C盘，然后也确实不知道软件发生了什么，桌面快捷方式突然消失，并且在portable文件夹里打开以后无法自动找到之前设置的数据位置。反正解决啦！数据也没丢！感谢！
