### ISSUE TITLE
[Feature] 自定义启动程序，在结束游戏后自动关闭

### ISSUE THREAD

**Issue by beilove** [Scighost/Starward#769]
### Checklist

- [X] I have already read [docs/Tips.md](https://github.com/Scighost/Starward/blob/main/docs/Tips.md), but my feature is not implemented.
- [X] My suggested feature was not mentioned by others, and it is not a duplicate feature.

### Summary

在自定义启动程序后，游戏结束后，这个自定义的程序不会自动结束，如果Starward想再次运行这个游戏的话，会在启用一次自定义的程序，这时候就会启动失败，希望可以加一个选项，在游戏进程结束后，可以自动关闭自定义的程序（比如原神的帧率解锁插件）

### Solution or Design

emm

**Comment by Scighost** [comment]
谢谢你的建议，但是 Starward 仅负责启动进程，不会考虑强制结束的功能。

**Comment by beilove** [comment]
好滴，谢谢
