### ISSUE TITLE
Update Content (0.8.0 - Dan Heng)

### ISSUE THREAD

**Issue by Scighost** [Scighost/Starward#77]
This is about update content for version [0.8.0 - Dan Heng](https://github.com/Scighost/Starward/releases/tag/0.8.0). Welcome to help us translate it.

Previous version and commit: [0.7.1-Venti](https://github.com/Scighost/Starward/releases/tag/0.7.1) af9b6b1a2f3f2d3ead8c51adfd6d1cea78440e32

The latest commit of this version: d1a9dba9ccae8620cfb374efae36972fa2760f3a

**Comment by Scighost** [comment]
# English

## Broken Changes

Set the storage location from registry to database

(Unfinished)

## Other Changes

- Fix the Chinese text error in gacha records page #72 b536963c7bc660765622abf8d8343eee6905d770
- Fix the error of line break in localized text 85e447a66b0032fb6fad7824686f1b2faab7def0
- Fix the error of console not showing log output #75 8c6d54dbe854b399d309ba1ca9bd5189c86a7789
- To avoid blocking UDP connection by operators in mainland China and affecting normal use, fallback to HTTP2 #70 7d76bc4179a3252231c2fa75d3db9a5239e6f054
- Fix the spelling error of some English text fb9775d6bb821fd5d59682bef6eaa45f97a2bb02

**Comment by phucho0237** [comment]
<h1>Tiếng Việt</h1>

<h2>Thay đổi không tương thích</h2>
<p>Đặt vị trí lưu trữ từ registry sang database</p>

<p>(Chưa hoàn thành)</p>

<h2>Thay đổi khác</h2>

-  Sửa lỗi văn bản tiếng Trung trong trang bản ghi gacha #72 b536963c7bc660765622abf8d8343eee6905d770
-  Sửa lỗi ngắt dòng trong văn bản đã bản địa hoá 85e447a66b0032fb6fad7824686f1b2faab7def0
-  Sửa lỗi console không hiện thị log đầu ra #75 8c6d54dbe854b399d309ba1ca9bd5189c86a7789
-  Để tránh chặn kết nối UDP bởi các nhà điều hành ở Trung Quốc Đại Lục và ảnh hưởng đến việc sử dụng thông thường, chuyển sang HTTP2 #70 7d76bc4179a3252231c2fa75d3db9a5239e6f054
-  Sửa lỗi chính tả một số văn bản tiếng Anh fb9775d6bb821fd5d59682bef6eaa45f97a2bb02
