### ISSUE TITLE
[Feature] 希望能统计up的5星的平均抽数

### ISSUE THREAD

**Issue by annihilationsc** [Scighost/Starward#770]
### Checklist

- [X] I have already read [docs/Tips.md](https://github.com/Scighost/Starward/blob/main/docs/Tips.md), but my feature is not implemented.
- [X] My suggested feature was not mentioned by others, and it is not a duplicate feature.

### Summary

目前似乎只统计5星的平均抽数，但我更关注up的平均抽数
所以希望增加对应的统计项

### Solution or Design

可以直接将歪了的5星减去，剩下的数量就是up的了吧
常驻角色相对固定，后续应该也几乎不需要更新代码

**Comment by Scighost** [comment]
#751
