### ISSUE TITLE
启动器首页游戏图标可自定义删减/抽卡记录增加手动导入6个月前数据

### ISSUE THREAD

**Issue by Suifulv** [Scighost/Starward#773]
### Checklist

- [X] I have already read [docs/Tips.md](https://github.com/Scighost/Starward/blob/main/docs/Tips.md), but my feature is not implemented.
- [X] My suggested feature was not mentioned by others, and it is not a duplicate feature.

### Summary

1.启动器首页上方游戏图标可自定义隐藏
2.抽卡记录增加手动导入6个月前数据

### Solution or Design

1.对于想用此启动器，但又不同时玩3个游戏的人，启动器主页上方3个游戏图标可能影响观感，建议在设置中增加游戏图标可隐藏。
2.增加修改记录最后一个金抽数以及补全6个月前抽卡记录的功能，想要手动补全所有记录，这对一个强迫症来说很有必要，启动器仅有抽卡记录，并没有分析及排行等功能，不强求数据真实性，假设补全数据恶意填报，应该也不会对其他人造成任何影响，所以建议加入补全功能。

**Comment by Scighost** [comment]
1. #556
2. 不全数据需要的操作及UI设计很繁琐，你可以通过编辑抽卡记录的 JSON 文件达成目的
