### ISSUE TITLE
希望改进帧率解锁功能

### ISSUE THREAD

**Issue by biliPowerShell** [Scighost/Starward#774]
### Checklist

- [X] I have already read [docs/Tips.md](https://github.com/Scighost/Starward/blob/main/docs/Tips.md), but my feature is not implemented.
- [X] My suggested feature was not mentioned by others, and it is not a duplicate feature.

### Summary

给原神增加帧率解锁功能

### Solution or Design

给原神增加帧率解锁功能

**Comment by Scighost** [comment]
谢谢你的建议，但我不会实现此类需要修改游戏内存的功能。
