### ISSUE TITLE
[Feature] Progressive upgrade if versions skipped

### ISSUE THREAD

**Issue by Emojigit** [Scighost/Starward#777]
### Checklist

- [X] I have already read [docs/Tips.md](https://github.com/Scighost/Starward/blob/main/docs/Tips.md), but my feature is not implemented.
- [X] My suggested feature was not mentioned by others, and it is not a duplicate feature.

### Summary

The differential packages of HoYoverse games (in my case, Genshin Impact) upgrade the game by modifying the files in the previous version. This approach is optimal for most players as it reduces the size of the data downloaded.

However, for players skipping (one or more) versions, the current approach may not be optimal in terms of disk usage. Starward and the official launcher (IIRC) download all the differential packages at once but still apply them one by one due to their technical nature. During an iteration, differential packages not used in this iteration are redundant, yet still span up disk spaces, resulting in extra disk usage.

### Solution or Design

Updates can be handled step-by-step: download the differential package of the version after the installed one, apply its patch, delete the package, and then repeat these steps for the next version. This will be useful for players having a disk space shortage, especially if the available space is a few GBs larger than the required size.

**Comment by Scighost** [comment]
Your suggestion is very good, but in fact it is not feasible. The latest version is 4.6, and the versions that can be updated through differential packages are 4.4 and 4.5. If a player's local game version is 4.3, I have no way to get the differential packages from 4.3 to 4.4 or 4.5.
