### ISSUE TITLE
[Feature] Fork to Linux

### ISSUE THREAD

**Issue by Mooling0602** [Scighost/Starward#781]
### Checklist

- [X] I have already read [docs/Tips.md](https://github.com/Scighost/Starward/blob/main/docs/Tips.md), but my feature is not implemented.
- [X] My suggested feature was not mentioned by others, and it is not a duplicate feature.

### Summary

As title. The .NET platform supports Linux, I think this may be possible to realize.

### Solution or Design

As title

**Comment by driver1998** [comment]
This app is based on WinUI 3, porting to Linux means a complete UI rewrite...

**Comment by Scighost** [comment]
> This app is based on WinUI 3, porting to Linux should be possible with Uno Platform.

@Mooling0602 Yeah, .NET does support Linux, but WinUI does not.

**Comment by driver1998** [comment]
@Scighost Uno Platform is an API-compatible reimplementation of WinUI, hopefully it should just work.

**Comment by Scighost** [comment]
@driver1998  Migrating to the Uno platform requires a lot of work, and I don’t have the time to complete it. And I don’t think Starward needs to be adapted for Linux because miHoYo’s games do not support Linux. If you play game in Wine, maybe Starward can also run in Wine.

**Comment by Mooling0602** [comment]
> @driver1998 Migrating to the Uno platform requires a lot of work, and I don’t have the time to complete it. And I don’t think Starward needs to be adapted for Linux because miHoYo’s games do not support Linux. If you play game in Wine, maybe Starward can also run in Wine.

I have tested it and failed.

**Comment by Mooling0602** [comment]
Maybe other developers will do this.

**Comment by Mooling0602** [comment]
Maybe other developers will do this.
