### ISSUE TITLE
[Feature] 给原神、星铁启动器界面提供一个打开地图的超链接选项

### ISSUE THREAD

**Issue by Because66666** [Scighost/Starward#782]
### Checklist

- [X] I have already read [docs/Tips.md](https://github.com/Scighost/Starward/blob/main/docs/Tips.md), but my feature is not implemented.
- [X] My suggested feature was not mentioned by others, and it is not a duplicate feature.

### Summary

一个小的ui建议

### Solution or Design

官方启动器的右侧会有一个提供打开大地图的选项，建议把这个功能板块加上。当然放哪随意，但是希望有这个功能。

**Comment by Scighost** [comment]
谢谢你的建议，但是因为 WebView2 没办法主动回收内存，内置大地图会带来不好的体验，我建议你使用浏览器查看大地图。

**Comment by devil233-ui** [comment]
> 谢谢你的建议，但是因为 WebView2 没办法主动回收内存，内置大地图会带来不好的体验，我建议你使用浏览器查看大地图。

额他的意思其实就是跳转到浏览器，官方的现在长这样
![image](https://github.com/Scighost/Starward/assets/69190444/3fe73df9-b97f-4f57-b03c-c03f35cd6de0)
点下去就是https://act.mihoyo.com/ys/app/interactive-map/index.html?bbs_presentation_style=no_header&lang=zh-cn&utm_source=game&utm_medium=ys&utm_campaign=side&_markerFps=24#/map/2?shown_types=&center=2008.50,-1084.00&zoom=-3.00

**Comment by Because66666** [comment]
对，其实就是内置一个按钮，然后点进去会打开电脑本地浏览器，而不是内置一个浏览器。
以及，建议左侧


这个活动图片这里，增加一个左右翻页的透明按钮。


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Scighost/Starward"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年5月14日(星期二) 晚上9:45
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Scighost/Starward] [Feature] 给原神、星铁启动器界面提供一个打开地图的超链接选项 (Issue #782)





  
谢谢你的建议，但是因为 WebView2 没办法主动回收内存，内置大地图会带来不好的体验，我建议你使用浏览器查看大地图。
  
额他的意思其实就是跳转到浏览器，官方的现在长这样
 image.png (view on web)
 点下去就是https://act.mihoyo.com/ys/app/interactive-map/index.html?bbs_presentation_style=no_header&amp;lang=zh-cn&amp;utm_source=game&amp;utm_medium=ys&amp;utm_campaign=side&amp;_markerFps=24#/map/2?shown_types=&amp;center=2008.50,-1084.00&amp;zoom=-3.00

**Comment by Because66666** [comment]
对，其实就是内置一个按钮，然后点进去会打开电脑本地浏览器，而不是内置一个浏览器。
以及，建议左侧

![屏幕截图 2024-05-16 113202](https://github.com/Scighost/Starward/assets/110363085/ab8fefda-eea8-442e-99f7-e562aaba94e6)

这个活动图片这里，增加一个左右翻页的透明按钮。

**Comment by 1755835318** [comment]
作者是否了解过 空莹酒馆原神地图工具，希望启动器能够添加启动这个工具的功能
![Uploading QQ截图20240522210034.png…]()
