### ISSUE TITLE
[Feature] Add link to UIGF/SRGF standard

### ISSUE THREAD

**Issue by Emojigit** [Scighost/Starward#783]
### Checklist

- [X] I have already read [docs/Tips.md](https://github.com/Scighost/Starward/blob/main/docs/Tips.md), but my feature is not implemented.
- [X] My suggested feature was not mentioned by others, and it is not a duplicate feature.

### Summary

According to the UIGF/SRGF standard, "Application must declare support of UIGF/SRGF data format only after [...] provide link _[sic]_ to [UIGF-Org](https://uigf.org/) in the associated page."[^1] However, such links are not present on Starward.

[^1]: Found on their official website. For UIGF, see <https://uigf.org/en/standards/uigf.html>. For SRGF, see <https://uigf.org/en/standards/srgf.html>.

### Solution or Design

A "question mark" more information button can be added next to the export/import function. Upon clicking it, it shows a message saying "Supports importing JSON files in the UIGF data format," where UIGF/SRGF points to the specification page or the UIGF-Org main page.

After adding this link, we can also officially declare support for UIGF/SRGF data.

Examples:

![螢幕擷取畫面 2024-05-07 063325](https://github.com/Scighost/Starward/assets/55009343/7db8e330-84ec-4477-a184-e645cc86739b)
![螢幕擷取畫面 2024-05-07 063840](https://github.com/Scighost/Starward/assets/55009343/21e48904-5072-4157-9b4b-ff6b1aea5b66)

**Comment by Scighost** [comment]
Thanks for your suggestion, I will implement latter.
