### ISSUE TITLE
[Feature] 希望可以先删除deletefiles.txt里的文件再解压应用更新

### ISSUE THREAD

**Issue by livilivi** [Scighost/Starward#784]
### Checklist

- [X] I have already read [docs/Tips.md](https://github.com/Scighost/Starward/blob/main/docs/Tips.md), but my feature is not implemented.
- [X] My suggested feature was not mentioned by others, and it is not a duplicate feature.

### Summary

像这次预更新，deletefiles.txt列出的文件总共有12.6G
在解压后应用更新前多占用的空间=压缩包+解压后的hdiff体积+12.6G

### Solution or Design

如果可以先删掉12.6G再解压和hpatchz，能避免很多空间不足倒腾游戏盘的情况。

还可以边解压边删除zip里已解压文件
参考：https://github.com/auto-Dog/delete_when_unzip

**Comment by Scighost** [comment]
后续使用新的下载模式后，不会再有 `deletefiles.txt` 文件了
