### ISSUE TITLE
星铁客服网址有变化

### ISSUE THREAD

**Issue by vvb2060** [Scighost/Starward#786]
https://github.com/Scighost/Starward/blob/176a0896535cca542ca8bf291c0929fbde83f05f/src/Starward.Core/SelfQuery/SelfQueryClient.cs#L90-L105

https://cs.hoyoverse.com/csc-service-center-fe/index.html
国际服现在是cs.hoyoverse.com，国服和原不清楚

**Comment by Scighost** [comment]
#759
