### ISSUE TITLE
[Feature] Add option to hidde chronicas wish 

### ISSUE THREAD

**Issue by GhostVPN1** [Scighost/Starward#788]
### Checklist

- [X] I have already read [docs/Tips.md](https://github.com/Scighost/Starward/blob/main/docs/Tips.md), but my feature is not implemented.
- [X] My suggested feature was not mentioned by others, and it is not a duplicate feature.

### Summary

Hey! I think we need the same option for Chronical Wisch as for Newbie Banner, I think don't much people pull on it recently. 

### Solution or Design

The option are already in launcher

**Comment by Scighost** [comment]
Thanks for your suggestion. This feature has been implemented https://github.com/Scighost/Starward/commit/176a0896535cca542ca8bf291c0929fbde83f05f, it will publish on the next version.
