### ISSUE TITLE
[Question] 感谢作者，做了我之前想做的事

### ISSUE THREAD

**Issue by ArchangelXu** [Scighost/Starward#789]
### Checklist

- [X] I have already read [docs/Tips.md](https://github.com/Scighost/Starward/blob/main/docs/Tips.md), but my question is not solved.
- [X] My question was not mentioned by others, and it is not a duplicate question.

### Description

本打算用Flutter写一个跨平台的（Windows和移动端上启动游戏，mac上启动云游戏）带抽卡统计的米家游戏启动器，今天偶然看到你这个，已经非常完善了...

向你致敬，巡海游侠！

### Starward Version

0

### Windows Version

0

**Comment by Scighost** [comment]
感谢你的支持，希望你能够拥有愉快的体验。

<img src="https://github.com/Scighost/Starward/assets/61003590/44552992-e2c5-451f-9c2a-73176e8e4e93" width="240px" />
