### ISSUE TITLE
［功能建议］图形设置保存为模版

### ISSUE THREAD

**Issue by Gouzuang** [Scighost/Starward#79]
可以把图形设置保存为模版，并快速切换不同的模版，应用场景如：
模版1，全低画质，720p窗口化，用于日常划水，不过多占用系统资源
模版2，全高画质，4K全屏，用于好好游玩游戏。
这样可以更好的利用软件的图形设置功能吧。

另外，现在启动游戏按钮旁的设置按钮打开的是Starward的设置，但这个应该是低频使用功能，换成图形设置或游戏检测工具可能会好一点？

**Comment by Scighost** [comment]
很好的建议，但是无法实现。
原神在注册表中保存配置的数据模型很复杂，如你所见无法在应用内调节原神的图形设置，你建议的模板功能更做不到了。

启动游戏旁的设置按键中包含**游戏设置**和**背景设置**，**游戏设置**中包含与启动游戏相关的设置项，**背景设置**放在这是因为只有启动器页面才能看到清晰的背景图。这里的东西已经很多，放不下其他设置选项了。

**Comment by Gouzuang** [comment]
您好，如果原神部分难以实现这个功能的话，可否在已经有图形设置的星铁部分实现呢？![image](https://github.com/Scighost/Starward/assets/87839812/61ea1f0a-d0bb-4a92-9658-76b6c6058d1c)

**Comment by Scighost** [comment]
不再考虑实现此功能
