### ISSUE TITLE
[Question] 如何看待官方出的 米哈游启动器，是否借鉴了starward

### ISSUE THREAD

**Issue by ashsteins** [Scighost/Starward#791]
### Checklist

- [X] I have already read [docs/Tips.md](https://github.com/Scighost/Starward/blob/main/docs/Tips.md), but my question is not solved.
- [X] My question was not mentioned by others, and it is not a duplicate question.

### Description

[Question] 如何看待官方出的 米哈游启动器，是否借鉴了starward

### Starward Version

win11

### Windows Version

1

### Log

```shell
.
```

### Additional Context

.

**Comment by Scighost** [comment]
Starward 的设计不是我的个人原创，我在开发之初就借鉴了 [Collaspe](https://github.com/CollapseLauncher/Collapse) 的很多内容。Starward 旨在解决米哈游旗下游戏老版本启动器的冗余问题，给和我一样同时游玩多款游戏的玩家更好的使用体验。遗憾的是非官方工具能够覆盖到的玩家群体终究是有限的。

现在米哈游推出了类似功能的全新官方启动器，把更好的体验带给了所有玩家，我由衷地对这一举措感到高兴。同时，Starward 也将仍然保持更新，适配新的官方启动器，维护官方启动器没有的特色功能。
