### ISSUE TITLE
[Feature] Starward是否可以增添更多游戏的启动及功能

### ISSUE THREAD

**Issue by 1755835318** [Scighost/Starward#792]
### Checklist

- [X] I have already read [docs/Tips.md](https://github.com/Scighost/Starward/blob/main/docs/Tips.md), but my feature is not implemented.
- [X] My suggested feature was not mentioned by others, and it is not a duplicate feature.

### Summary

国内二游市场逐渐扩大，玩家需求不仅于米家旗下

### Solution or Design

希望能添加更多二游的启动，或者能够支持自由的启动系统

**Comment by Scighost** [comment]
谢谢你的建议，不过很遗憾我没有相关的想法。

每个游戏的公告界面、下载方式可能都不同，不同游戏之中很难总结出一个统一的安装流程，每次新增一个游戏都需要修改大量的代码，我个人没有精力维护更多的游戏了。

**Comment by 1755835318** [comment]
> 谢谢你的建议，不过很遗憾我没有相关的想法。
> 
> 每个游戏的公告界面、下载方式可能都不同，不同游戏之中很难总结出一个统一的安装流程，每次新增一个游戏都需要修改大量的代码，我个人没有精力维护更多的游戏了。

能够理解，幸苦

**Comment by Lightczx** [comment]
@Scighost Consider this as duplication of #793 ?

**Comment by tianjiangqiji** [comment]
> 谢谢你的建议，不过很遗憾我没有相关的想法。
> 
> 每个游戏的公告界面、下载方式可能都不同，不同游戏之中很难总结出一个统一的安装流程，每次新增一个游戏都需要修改大量的代码，我个人没有精力维护更多的游戏了。

如果仅仅是在顶部添加一个加号，更新和公告并不提供，用户需要添加游戏路径，游戏背景，就像steam添加外部游戏一样，有没有想法

**Comment by Scighost** [comment]
> 如果仅仅是在顶部添加一个加号，更新和公告并不提供，用户需要添加游戏路径，游戏背景，就像steam添加外部游戏一样，有没有想法

@tianjiangqiji 谢谢你的建议，但是这样做的话，既和 Steam 没用区别，也不符合 Starward 的界面风格。
