### ISSUE TITLE
[Question] 有考虑把鸣潮 和其他有pc版的二游整合进去吗

### ISSUE THREAD

**Issue by hjtao889** [Scighost/Starward#793]
### Checklist

- [X] I have already read [docs/Tips.md](https://github.com/Scighost/Starward/blob/main/docs/Tips.md), but my question is not solved.
- [X] My question was not mentioned by others, and it is not a duplicate question.

### Description

有考虑把鸣潮 和其他有pc版的二游整合进去吗

### Starward Version

win11

### Windows Version

1

### Log

```shell
.
```

### Additional Context

.

**Comment by CaraLynn-online** [comment]
如果这个issue被批准的话能不能顺便也加入永杰无间？
它的[官网](https://www.yjwujian.cn/download/#/)也有提供完整包和增量包下载

![image](https://github.com/Scighost/Starward/assets/69111766/427b8fe8-203c-4ad3-b3cd-e7d6f5664fde)

**Comment by xuan06zyx** [comment]
+1

**Comment by hahayzl** [comment]
+1 建议加入TitaniumProxyServer方法获取抽卡记录

**Comment by Scighost** [comment]
谢谢建议，不过很遗憾我没有相关的想法。

每个游戏的公告界面、下载方式可能都不同，不同游戏之中很难总结出一个统一的安装流程，每次新增一个游戏都需要修改大量的代码，我个人没有精力维护更多的游戏了。

**Comment by Because66666** [comment]
确实没必要整合其他的，毕竟代码不能复用。不过我很好奇在米哈游启动器出来之后，作者还会维护这个项目吗

**Comment by CreeperAWA** [comment]
我不建议，如果这样的话启动器会变得很臃肿，启动器本来是用来启动米哈游的游戏的，如果这样的话那我建议再内置Minecraft基岩版和JAVA版，基岩版可用启动器切换版本、修改配置、安装资源包，JAVA版可用启动器快速下载安装mod、资源包，并支持离线启动，可以用启动器修改正版皮肤，可以使用其他玩家的皮肤和披风，并且两个版本都支持启动时自动注入科技

很显然，这样下去就越来越臃肿了，已经违背了初衷

**Comment by CaraLynn-online** [comment]
> 我不建议，如果这样的话启动器会变得很臃肿，启动器本来是用来启动米哈游的游戏的，如果这样的话那我建议再内置Minecraft基岩版和JAVA版，基岩版可用启动器切换版本、修改配置、安装资源包，JAVA版可用启动器快速下载安装mod、资源包，并支持离线启动，可以用启动器修改正版皮肤，可以使用其他玩家的皮肤和披风，并且两个版本都支持启动时自动注入科技
> 
> 很显然，这样下去就越来越臃肿了，已经违背了初衷

我认为并不会变得臃肿
首先这里目前并没有人提出要加入mc

在这里所提出游戏都是**数据较大**且官方启动器运行效率极低的（比如：需要下载、解压、检验几十甚至几百的游戏资源），所以需要一款运行效率高的启动器来替代官方启动器。

而mc是一款**原生数据较小**且**扩展性极强**的游戏，并且已经有多个成熟的启动器可以达到玩家的需求。

再者说，像以上玩家们所提出建议加入的游戏也不会需要像mc那样的高扩展需求，顶多也就是查看抽卡记录和官方公告这些的。

**Comment by CreeperAWA** [comment]
但是我认为这个启动器做好米哈游的游戏就OK了，其他游戏的启动器还是单独比较好

> > 我不建议，如果这样的话启动器会变得很臃肿，启动器本来是用来启动米哈游的游戏的，如果这样的话那我建议再内置Minecraft基岩版和JAVA版，基岩版可用启动器切换版本、修改配置、安装资源包，JAVA版可用启动器快速下载安装mod、资源包，并支持离线启动，可以用启动器修改正版皮肤，可以使用其他玩家的皮肤和披风，并且两个版本都支持启动时自动注入科技
> > 很显然，这样下去就越来越臃肿了，已经违背了初衷
> 
> 我认为你是多虑了 首先这里目前并没有且大概率不会有人提出要加入mc
> 
> 在这里所提出游戏都是**数据较大**且官方启动器运行效率极低的（比如：需要下载、解压、检验几十甚至几百的游戏资源），所以需要一款运行效率高的启动器来替代官方启动器。
> 
> 而mc是一款**原生数据较小**且**扩展性极强**的游戏，并且已经有多个成熟的启动器可以达到玩家的需求。
> 
> 再者说，像以上玩家们所提出建议加入的游戏也不会需要像mc那样的高扩展需求，顶多也就是查看抽卡记录和官方公告这些的。

**Comment by Lightczx** [comment]
> 米哈游启动器出来之后，作者还会维护这个项目吗

米哈游启动器依托，而且没有抽卡/深渊等等，除非官方把这些加了不然理论上是会持续维护的

**Comment by LaoshuBaby** [comment]
> 如果这个issue被批准的话能不能顺便也加入永杰无间？
> 它的[官网](https://www.yjwujian.cn/download/#/)也有提供完整包和增量包下载

~~说实话第一眼没看出这是认真在请求还是在换一种非常离谱的去嘲讽~~

但无论如何永劫无间和这些差异应该实在是太大了，起码长得不像，不是同类游戏（bushi

而鸣潮呢，或许未来也会有其他人做泛二游的一站式启动管理，也或许没有，但这个问题上面作者已经表态没有支持意愿，那看起来应该不是本项目存续范围内值得讨论的了，那就这样吧（逃

**Comment by CNChestnut** [comment]
都米家游戏启动器了，搞一下太麻烦了吧，而且也确实麻烦。

> 谢谢建议，不过很遗憾我没有相关的想法。
> 
> 每个游戏的公告界面、下载方式可能都不同，不同游戏之中很难总结出一个统一的安装流程，每次新增一个游戏都需要修改大量的代码，我个人没有精力维护更多的游戏了。

**Comment by InTka** [comment]
1
