### ISSUE TITLE
[Question] 托盘图标的右键菜单里为什么始终有一个星穹铁道的B服选项？

### ISSUE THREAD

**Issue by MephistoSatanDevil** [Scighost/Starward#797]
### Checklist

- [X] I have already read [docs/Tips.md](https://github.com/Scighost/Starward/blob/main/docs/Tips.md), but my question is not solved.
- [X] My question was not mentioned by others, and it is not a duplicate question.

### Description

这种选项应该是在游戏启动界面切换服务器那里设置好然后那边就固定的么？而且原神也有B服为什么原神B服就没有单独在那个位置出现？这种渠道服快速启动的选项是不是应该要么都显示，要么都不显示才对？
或者设置里给个开关如何？控制托盘图标的右键菜单是否显示B服或者渠道服。
![QQ截图20240525174608](https://github.com/Scighost/Starward/assets/1319061/70503b5d-a5f2-4e23-971f-374b1b313ac9)

### Starward Version

0.11.6

### Windows Version

26217.5000

**Comment by Scighost** [comment]
你需要在官服启动页面的游戏设置中完成一次一键修复

**Comment by MephistoSatanDevil** [comment]
> 你需要在官服启动页面的游戏设置中完成一次一键修复

谢谢

**Comment by KoakiMiku** [comment]
> 你需要在官服启动页面的游戏设置中完成一次一键修复

已经一键修复过了，但是右键菜单里还是有B服

**Comment by TomIsFat** [comment]
> 你需要在官服启动页面的游戏设置中完成一次一键修复

没用，这个bug很久了
