### ISSUE TITLE
[Feature] 原神120帧启动

### ISSUE THREAD

**Issue by AllureDirge** [Scighost/Starward#799]
### Checklist

- [X] I have already read [docs/Tips.md](https://github.com/Scighost/Starward/blob/main/docs/Tips.md), but my feature is not implemented.
- [X] My suggested feature was not mentioned by others, and it is not a duplicate feature.

### Summary

增加原神120帧启动

### Solution or Design

作者有考虑实行原神120帧启动吗

**Comment by xuan06zyx** [comment]
#774
