### ISSUE TITLE
无法运行程序

### ISSUE THREAD

**Issue by scqy2000** [Scighost/Starward#8]
下载解压后双击打开出现黑色界面，随后直接消失，没有任何报错反馈。
![QQ截图20230520183930](https://github.com/Scighost/Starward/assets/19802266/c3329770-0e2b-4f7b-9468-ec5c24549568)
但是之前release里那个0.1.0版本的demo可以正常打开。
系统版本为Windows 11专业版_22H2_22621.1702
PS：collapse也无法运行，会出现同样问题。

**Comment by Scighost** [comment]
感谢反馈

你遇到的问题似乎与 https://github.com/microsoft/WindowsAppSDK/issues/3616 是一样的，但是在这个 issue 中没有给出解决办法。0.2.0 版本的 Windows App SDK 升级到了 1.3.1，这可能是造成错误的原因。

请你按照以下步骤来尝试解决问题，请注意顺序：

1. 下载 [Starward_Portable_0.2.1-preview.1_x64.7z]()，是否能正常运行，这是使用 WinAppSDK 1.3.0 构建的
2. 下载并安装 [Windows App Runtime 1.3.1](https://download.microsoft.com/download/d/3/2/d322dcd4-e89d-4b69-bb5b-a9090644471d/WindowsAppRuntimeInstall.exe) 
3. 再尝试运行 0.2.0 版本的程序

如要卸载第2步安装的程序，在 PowerShell 中执行 `Get-AppxPackage Microsoft.WindowsAppRuntime.1.3 | Remove-AppPackage`

**Comment by scqy2000** [comment]
感谢提供帮助

按照步骤尝试解决问题时，无论是使用0.2.1版本还是安装runtime之后重新运行0.2.0版本，错误依旧复现，参考https://github.com/microsoft/WindowsAppSDK/issues/3616 查看Windows事件管理器，可以发现两个版本均存在原issue中提到的报错

0.2.0版本
![020](https://github.com/Scighost/Starward/assets/19802266/aa736bd0-621d-4876-b912-e9a207fe3c2d)
0.2.1版本
![021](https://github.com/Scighost/Starward/assets/19802266/28c3e787-8268-4b77-979d-35fa37185a39)

**Comment by Scighost** [comment]
这是使用未剪裁配置发布的包，用来检验是否是剪裁功能导致的问题。
[Starward_Portable_0.2.1-preview.2_x64.7z](https://starward.scighost.com/release/package/dev/Starward_Portable_0.2.1-preview.2_x64.7z)

**Comment by scqy2000** [comment]
非常遗憾，但似乎不是裁剪功能导致的问题，使用此版本依旧会得到和之前一样的情况。
![0 2 1_2](https://github.com/Scighost/Starward/assets/19802266/3e6511f2-ab76-4a6c-987a-bdcfe67f2649)

**Comment by Scighost** [comment]
很遗憾，没有找到问题原因和解决办法，但是还有一个最后的选项，重装操作系统。
**但是这会破坏已经熟悉的软件环境，还可能因为疏忽丢失文件，是否重装由你自己决定。**

**Comment by scqy2000** [comment]
在虚拟机中进行测试发现程序可以正常运行，看来确实和我的系统有关系，考虑重装系统的建议，此issue可以关闭，感谢您的帮助。

**Comment by Scighost** [comment]
可能还有其他人会遇到这个问题，暂时不关闭。

**Comment by pbxs666** [comment]
> 可能还有其他人会遇到这个问题，暂时不关闭。

是啊，我就遇到了😂

试了下安装Windows App Runtime 1.3.1，还是闪退打不开。

**Comment by issligang** [comment]
我这边也遇到了，系统是win11
Windows 11 家庭中文版 22H2
最新的Canary（Windows Feature Experience Pack 1000.25350.1000.0）

**Comment by AlierKitten** [comment]
我win10，22H2也是这个问题，用了0.2.2的包也不行
Windows Feature Experience Pack 120.2212.4190.0

**Comment by AlierKitten** [comment]
> 我win10，22H2也是这个问题，用了0.2.2的包也不行 Windows Feature Experience Pack 120.2212.4190.0

我又试了下Collapse启动器，用installer安装后可以运行，而portable版也是打开黑屏闪退

**Comment by Scighost** [comment]
[Starward_Portable_0.2.2_x64.7z](https://starward.scighost.com/release/package/dev/Starward_Portable_0.2.2_x64.7z)

这是使用 Windows App SDK 1.2.5 编译的版本，**应该**不会再有打不开的问题了，但是有可能会出现其他未知的错误。还有如果在应用中检测到了新版本，请谨慎更新。

**请存在和楼主同样问题的朋友在这条回复中点个赞，没有问题但看到了的点个围观（两只眼睛），我会视情况考虑在后续版本把 Windows App SDK 降级为 1.2.5。**

**Comment by Allens660** [comment]
试了下，作者发的SDK1.2.5可以正常运行，release的版本出现和楼主一样的黑色界面闪退问题，win10，22H2

**Comment by Guducat** [comment]
release闪退，使用 Windows App SDK 1.2.5 编译的版本正常运行

**Comment by XM-HAQ** [comment]
1.2.5 SDK版本运行正常，release下载就闪退，Win11 22H2家庭版

**Comment by issligang** [comment]
SDK1.2.5的运行正常

**Comment by Scighost** [comment]
还请各位帮忙测试一下：

- 下载 [Release](https://github.com/Scighost/Starward/releases/tag/0.2.2) 中的版本
- 进入 `app-0.2.2` 文件夹，找到 `Starward.exe` 并运行
- 下载这个文件 [Starward.zip](https://github.com/Scighost/Starward/files/11542919/Starward.zip)，替换下图中的 `Starward.exe`
- 再直接运行该文件

两次运行的情况如何？

<img width="143" alt="image" src="https://github.com/Scighost/Starward/assets/61003590/4f65b488-9c29-4e65-812c-2287a0c910fe">

**Comment by issligang** [comment]
上述可行，但现在又出现另一个问题，打开后，有个命令窗口，且不会自己消失，手动关闭命令窗口，启动器也会自己关闭
![image](https://github.com/Scighost/Starward/assets/48896199/ef833759-13b1-4898-bf22-a45f1c1ec75b)

**Comment by Mirror1934** [comment]
> 

在测试过程中发现一个新情况：
系统为Windows11 22H2 22621.1702
1.直接使用Release中的版本，黑屏闪退，事件查看器报错与楼主相同。
2.使用1.2.5 SDK的版本，成功运行并完成配置进入启动器主界面。
3.删除1.2.5版本，重新解压Release中的版本，运行正常（未替换Starward.exe）
有理由推测问题出在欢迎页面

**Comment by Scighost** [comment]
@Mirror1934 非常感谢，你的测试过程对解决问题有很大的帮助。

现在还有一些步骤需要你帮忙完成：

- 成功打开一次 Release 页面的 Starward
- 在注册表中删除 `AccentColor` 键
- 再尝试打开 Release 页面的 Starward

忘了一件事，`%LocalAppData%\Starward\crash` 文件夹中是否有崩溃记录？

**Comment by Mirror1934** [comment]
> 删除AccentColor键后Release版本仍然可以正常运行，且运行程序后该键重新生成。
LocalAppData下的Starward文件夹内只有cache文件夹，不存在崩溃记录。

**Comment by Scighost** [comment]
@Mirror1934 删除注册表的所有设置后，直接运行 `app-0.2.0` 中的 `Starward.exe` 是否有问题？

**Comment by Mirror1934** [comment]
> @Mirror1934 删除注册表的所有设置后，直接运行 `app-0.2.0` 中的 `Starward.exe` 是否有问题？
删除后直接运行也是黑框闪退，报错与楼主一致，Starward依然不能生成崩溃记录

**Comment by Scighost** [comment]
@Mirror1934 还是 Release 中的版本

打开应用后进入设置页面启用日志控制台，然后在注册表中添加 DWORD 键 `EnableDynamicAccentColor` 值为 `0`，再重新启动应用。

控制台是否输出错误信息，应用内按键的颜色是否和系统设置的主题色一致（这时系统主题色不要设置为黄色 #FFD52A）。

**Comment by Mirror1934** [comment]
> @Mirror1934 还是 Release 中的版本
> 
> 打开应用后进入设置页面启用日志控制台，然后在注册表中添加 DWORD 键 `EnableDynamicAccentColor` 值为 `0`，再重新启动应用。
> 
> 控制台是否输出错误信息，应用内按键的颜色是否和系统设置的主题色一致（这时系统主题色不要设置为黄色 #FFD52A）。
控制台无错误信息，颜色与系统主题色一致，更换主题色再次测试后可正常跟随系统设置变化

**Comment by Mirror1934** [comment]
> @Mirror1934 还是 Release 中的版本
> 
> 打开应用后进入设置页面启用日志控制台，然后在注册表中添加 DWORD 键 `EnableDynamicAccentColor` 值为 `0`，再重新启动应用。
> 
> 控制台是否输出错误信息，应用内按键的颜色是否和系统设置的主题色一致（这时系统主题色不要设置为黄色 #FFD52A）。

控制台无错误信息，颜色与系统主题色一致，更换主题色再次测试后可正常跟随系统设置变化。
但执行任何操作控制台无任何显示

**Comment by CLXiao-1029** [comment]
我在最新的0.3.0中的第二步闪退。已经安装 Windows App Runtime 1.3.1 。
选择语言后，选择数据存放目录时，点击选择目录后黑屏闪退。
在我一台win11系统的电脑上正常，在win10专业版-22H2-19045.2965-Windows Feature Experience Pack 1000.19041.1000.0中运行闪退。

版本	Windows 10 专业版
版本号	22H2
操作系统内部版本	19045.2965
体验	Windows Feature Experience Pack 1000.19041.1000.0

**Comment by Scighost** [comment]
@CLXiao-1029 你遇到的问题在这里解决了 #15

**Comment by CLXiao-1029** [comment]
> @CLXiao-1029 你遇到的问题在这里解决了 #15

下载0.3.1dev问题已解决

**Comment by R01EE** [comment]
您好，Scighost。我这边在下载最新的Starward后。直接打开程序。程序先创建了一个窗体。之后闪退。我尝试使用控制台输出模式来启动Starward。Starward控制台输出了以下信息。之后闪退。
![{C4FAAB31-E1F0-4b63-9FAE-61252E4FD9E1}](https://github.com/Scighost/Starward/assets/110150303/627c8997-40e9-4624-b655-ca121aa0e931)
之后尝试用README的说明启动。结果Starward成功启动，但没有进入初始配置状态。
系统信息：
系统：Windows 11 专业版 22H2
版本：22621.1928

**Comment by Tatsuya7239** [comment]
下载更新解压后双击打开出现黑屏情况并且还会闪退。但是退级回到0.6.2版本后却能正常打开画面。但是不管使用程序内置更新还是便捷版更新都是变成黑屏闪退的情况，也升级了Windows App Runtime 1.3.2。还是会出现一样的问题。
系统：Windows 11 专业版 21H2
![photomode_13062023_024038](https://github.com/Scighost/Starward/assets/83299813/ccedeab8-1e53-4a6c-a0d0-ddb723fb37d2)

**Comment by Scighost** [comment]
@Tatsuya7239 
我在 [0.8.0 的更新记录](https://github.com/Scighost/Starward/issues/77#issuecomment-1600821935)中提到了你们遇到的问题，但是你没有在 0.8.0 版本期间更新应用，所以没有看到我的提醒。你可以参考 [README/#下载](https://github.com/Scighost/Starward/blob/main/docs/README.zh-CN.md#%E4%B8%8B%E8%BD%BD) 部分解决这个问题。

@R01EE
初始配置过程中最重要的是选择数据文件夹的位置，你已经在 `config.ini` 中设置过了。

**Comment by Scighost** [comment]
新的测试版本来了，如果之前的版本碰到了闪退，下载 [0.8.4 Preview 2](https://github.com/Scighost/Starward/releases/tag/0.8.4-preview.2) 看看还有没有闪退。

**Comment by Scighost** [comment]
长时间无人反馈，关闭此 issue
