### ISSUE TITLE
[Question] 如何切换账号

### ISSUE THREAD

**Issue by LingYuYo** [Scighost/Starward#802]
### Checklist

- [X] I have already read [docs/Tips.md](https://github.com/Scighost/Starward/blob/main/docs/Tips.md), but my question is not solved.
- [X] My question was not mentioned by others, and it is not a duplicate question.

### Description

之前保存的切换账号，随着版本更新后使用不了了，早上试着又弄回来了，但是很不理想，重启之后又不行了，我不知道是不是自己的操作问题，希望大大出个法子

### Starward Version

app-0.11.6-preview.1

### Windows Version

22631.3593

**Comment by Scighost** [comment]
切换账号的操作比较麻烦，首先你需要登录游戏后，刷新启动器页面，在右下角的保存当前已登录账号的密钥；然后在需要切换账号时，先退出游戏，再切换账号。

**Comment by LingYuYo** [comment]
能否添加一个添加新账户的功能
![图](https://github.com/Scighost/Starward/assets/91359198/04143c65-4790-45ff-a45b-28667e27e392)
我时常出现这种问题无法添加新的账户，关闭后重新打开也依旧是只有一个账户可以选择

**Comment by LingYuYo** [comment]
![图1](https://github.com/Scighost/Starward/assets/91359198/e4a51cdb-9167-4f6e-b0b3-658b1ea7dfd7)
