### ISSUE TITLE
[Feature] 崩铁养成建议&材料计算

### ISSUE THREAD

**Issue by xinyihl** [Scighost/Starward#805]
### Checklist

- [X] I have already read [docs/Tips.md](https://github.com/Scighost/Starward/blob/main/docs/Tips.md), but my feature is not implemented.
- [X] My suggested feature was not mentioned by others, and it is not a duplicate feature.

### Summary

崩铁出了一个新的网页工具包括养成建议&材料计算。
是否有考虑将其添加到米游社工具箱。
https://act.mihoyo.com/sr/event/cultivation-tool/index.html

### Solution or Design

无

**Comment by Scighost** [comment]
谢谢你的建议，但是我没有这个想法。星铁的养成建议工具不仅限于在米游社使用，你可以把它添加到浏览器收藏夹。
