### ISSUE TITLE
[Feature] Wuthering waves (wuwa) support

### ISSUE THREAD

**Issue by manolito62** [Scighost/Starward#807]
### Checklist

- [X] I have already read [docs/Tips.md](https://github.com/Scighost/Starward/blob/main/docs/Tips.md), but my feature is not implemented.
- [X] My suggested feature was not mentioned by others, and it is not a duplicate feature.

### Summary

It should be okay, right?

### Solution or Design

No idea, i am not a designer, but following the same one for the others should be okay.

**Comment by GhostVPN1** [comment]
I think it shuld be better to make rename the luncher to Multi Game-Luncher and add another games like ToF and other, the design is here and i dont think that need be much redisign for it.

**Comment by GeneYu404** [comment]
绝了

**Comment by Scighost** [comment]
Same as https://github.com/Scighost/Starward/issues/793#issuecomment-2131164740
