### ISSUE TITLE
已下载原神game_4.5.0_4.6.0_hdiff_kiOtCmQKDxTEojvz.zip该如何使用Starward更新游戏呢？

### ISSUE THREAD

**Issue by wbmins** [Scighost/Starward#809]
### Checklist

- [X] I have already read [docs/Tips.md](https://github.com/Scighost/Starward/blob/main/docs/Tips.md), but my question is not solved.
- [X] My question was not mentioned by others, and it is not a duplicate question.

### Description

已下载原神game_4.5.0_4.6.0_hdiff_kiOtCmQKDxTEojvz.zip该如何使用Starward更新游戏呢？

### Starward Version

0.11.6

### Windows Version

22631.3593

### Log

```shell
-
```

### Additional Context

-

**Comment by Scighost** [comment]
建议再等两天直接更新到4.7

**Comment by wbmins** [comment]
4.7还会有这汇总  *-hdiff*.zip么
