### ISSUE TITLE
[Feature] 启动器响应慢

### ISSUE THREAD

**Issue by DreamToffee** [Scighost/Starward#810]
### Checklist

- [ ] I have already read [docs/Tips.md](https://github.com/Scighost/Starward/blob/main/docs/Tips.md), but my feature is not implemented.
- [ ] My suggested feature was not mentioned by others, and it is not a duplicate feature.

### Summary

不知道是不是我个人遇到这个问题，启动器打开时响应时间过长，经常要半分钟左右才能打开界面。我朋友更是一分钟才打开。不知道是否可以优化一下

### Solution or Design

无

**Comment by Lightczx** [comment]
像是SmartScreen干的

**Comment by DreamToffee** [comment]
> 像是SmartScreen干的

![fd2062fa-387b-4459-9ccf-c950f47688fc](https://github.com/Scighost/Starward/assets/96325268/7fba8e0e-eafe-4bd8-bf55-a4a460df7a16)
我看了一下，我这边关闭了

**Comment by DreamToffee** [comment]
> 像是SmartScreen干的

又试了一下，响应速度又正常了，基本秒开，不清楚原因

**Comment by Scighost** [comment]
大概是启动的时候被安全软件扫描了，除了添加到白名单以外，没有比较好的解决办法，但是我**不建议**这么做。

如果还碰到这种问题，请你使用命令参数 `.\Starward.exe --trace`，我想看一下它会输出什么。

**Comment by DreamToffee** [comment]
> 大概是启动的时候被安全软件扫描了，除了添加到白名单以外，没有比较好的解决办法，但是我**不建议**这么做。
> 
> 如果还碰到这种问题，请你使用命令参数 `.\Starward.exe --trace`，我想看一下它会输出什么。

![image](https://github.com/Scighost/Starward/assets/96325268/d29f2804-cb4a-41d5-b2a4-f0da053719ff)
然后等一会，界面还没打开就闪退了，我朋友遇到的

**Comment by DreamToffee** [comment]
> 大概是启动的时候被安全软件扫描了，除了添加到白名单以外，没有比较好的解决办法，但是我**不建议**这么做。
> 
> 如果还碰到这种问题，请你使用命令参数 `.\Starward.exe --trace`，我想看一下它会输出什么。

https://github.com/Scighost/Starward/assets/96325268/5e537fbf-298b-4790-b83c-c51182eb0c8d

简单录了一个视频30秒左右

**Comment by DreamToffee** [comment]
> 大概是启动的时候被安全软件扫描了，除了添加到白名单以外，没有比较好的解决办法，但是我**不建议**这么做。
> 
> 如果还碰到这种问题，请你使用命令参数 `.\Starward.exe --trace`，我想看一下它会输出什么。


https://github.com/Scighost/Starward/assets/96325268/e9a2a036-c981-4ccd-8619-08f75f45288c

重新录了一个界面更清楚的，十多秒后程序闪退了。但是后面重新试了几次，又可以正常启动，问题出现在刚开机的时候，像是没有缓存导致的问题

**Comment by Scighost** [comment]
@DreamToffee 谢谢你的回复，情况和我的回复基本一致，是安全软件拖慢了启动速度。

**Comment by DreamToffee** [comment]
@Scighost 闪退也是这个原因吗

**Comment by Scighost** [comment]
> @Scighost 闪退也是这个原因吗

@DreamToffee 我没有在你的视频中看到闪退，如果你是指加上 `--trace` 参数后出现的命令行窗口突然关闭，这是正常的，因为这个窗口无法交互，只能定时关闭。
