### ISSUE TITLE
[Bug] 由于未知原因导致的窗口大小异常

### ISSUE THREAD

**Issue by adampan0527** [Scighost/Starward#812]
### Checklist

- [X] My issue was not mentioned by others, and it is not a duplicate issue.

### Description

如题，原因未知，窗口大小的异常均为窗口比正常大小要大，而非更小

### Reproduction Steps

目前已知的触发方式为：放在后台，电脑待机，重新解锁并进入后窗口会变大。
尚不清楚是否有其他触发方式。

### Starward Version

0.11.6

### Windows Version

19045.4291

### Log

```shell
该异常没有报错，没有对应的log
```

**Comment by adampan0527** [comment]
已知关闭后台并重启可以解决该问题

**Comment by Scighost** [comment]
很遗憾，你的描述缺少有用信息，我没有办法帮你找到具体原因。
