### ISSUE TITLE
[Bug] 自定义视频壁纸选中4k壁纸

### ISSUE THREAD

**Issue by story-x** [Scighost/Starward#813]
### Checklist

- [X] My issue was not mentioned by others, and it is not a duplicate issue.

### Description

自定义视频壁纸选中4k（3840x2160），程序就卡死，强制关闭后，软件就启动不了，重启电脑也不行

### Reproduction Steps

自定义视频壁纸选一个4k（3840x2160）视频壁纸

### Screenshots

![image](https://github.com/Scighost/Starward/assets/45375162/5de4ad22-0a9d-433e-8174-f38df724f0ba)

### Starward Version

0.11.6

### Windows Version

22631.3672

### Log

```shell
[21:00:10.886] [INFO] 
Welcome to Starward v0.11.6
System: Microsoft Windows NT 10.0.22631.0
Command Line: D:\Starward\Starward\app-0.11.6\Starward.dll

[21:00:10.913] [INFO] Starward.Services.DatabaseService
Database path is 'D:\Starward\data'

[21:00:10.932] [INFO] Starward.Services.DatabaseService
Database version is 8, target version is 8.

[21:00:10.980] [INFO] Starward.Pages.MainPage
Last game region is hkrpg_cn

[21:00:10.988] [INFO] Starward.Pages.MainPage
Navigate to "LauncherPage" with param hkrpg_cn

[21:00:11.296] [WARN] Starward.Services.GameResourceService
config.ini not found: "D:\Program Files\Genshin Impact Cloud Game\config.ini"

[21:00:11.582] [WARN] Starward.Services.GameResourceService
config.ini not found: "D:\Program Files\Genshin Impact Cloud Game\config.ini"

[21:00:11.603] [INFO] Starward.Pages.LauncherPage
Game install path of hkrpg_cn: "D:\Game\Star Rail\Game"

[21:00:11.641] [INFO] Starward.Pages.LauncherPage
Acutal version and gamebiz of hkrpg_cn is "2.2.0", hkrpg_cn.

[21:00:13.593] [INFO] Starward.Services.UpdateService
Start to check update (Preview: True, Arch: X64)

[21:00:16.427] [INFO] Starward.Services.UpdateService
Current version: "0.11.6", latest version: "0.11.6", ignore version: null
```

**Comment by Scighost** [comment]
谢谢你的反馈，因为窗口大小没有达到 3840x2160 的规模，我建议你使用更小分辨率的视频。我从你的描述中无法判断是什么原因，还请你提供一下视频样本。

**Comment by story-x** [comment]
> 谢谢你的反馈，因为窗口大小没有达到 3840x2160 的规模，我建议你使用更小分辨率的视频。我从你的描述中无法判断是什么原因，还请你提供一下视频样本。

4k 视频壁纸 
https://www.123pan.com/s/jIMKVv-FJnfv.html提取码:2pYF

选的时候没看分辨率，选完实时就生效了

**Comment by Scighost** [comment]
我已经测试过了你的视频，视频本身就是正常的 mp4 AVC 编码，在我的设备上作为背景可正常播放。你尝试重启过吗？

**Comment by story-x** [comment]
> 我已经测试过了你的视频，视频本身就是正常的 mp4 AVC 编码，在我的设备上作为背景可正常播放。你尝试重启过吗？

我现在选完之后就程序就卡死了重启后也是一样，是我系统问题吗？
![2f2895c93d1fc749b779e1af5c6a3546](https://github.com/Scighost/Starward/assets/45375162/615f0892-2ebe-4481-b9c3-888de1426973)
选到4k的壁纸就卡死了，直接未响应
![image](https://github.com/Scighost/Starward/assets/45375162/5ef7462b-a8f4-470a-83b2-27294e8d5119)

我直接改数据库把这视频路径删了就可以进去了

**Comment by story-x** [comment]
1080p的视频无影响

**Comment by story-x** [comment]
![image](https://github.com/Scighost/Starward/assets/45375162/ea9521fb-11bd-4411-a653-853bcd59e7f0)

**Comment by story-x** [comment]
有没有可以看到详细的log的渠道

**Comment by huiyadanli** [comment]
![image](https://github.com/Scighost/Starward/assets/15783049/faa2274c-4cb6-4ce5-bc58-e95796351d9b)

Windows 11 23H2 测试正常，就是有点卡，Starward 窗体大小本身就有限制，建议缩小分辨率压制后重试

**Comment by story-x** [comment]
> ![image](https://private-user-images.githubusercontent.com/15783049/339046419-faa2274c-4cb6-4ce5-bc58-e95796351d9b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTgyMDg2ODIsIm5iZiI6MTcxODIwODM4MiwicGF0aCI6Ii8xNTc4MzA0OS8zMzkwNDY0MTktZmFhMjI3NGMtNGNiNi00Y2U1LWJjNTgtZTk1Nzk2MzUxZDliLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjEyVDE2MDYyMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWNhYTkyYWY3ODFhMTU2ZDY0MWVlNDE2MzZhOWIwODBkZDkxY2M1YjFiY2I2ZTU1Yjc1Yjg1YmM4OWQzODAzNWUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.pJk6A1VDLhCDA6M6U54IgjoYgMKKKev-Dr_CxQOrJPE)
> 
> Windows 11 23H2 测试正常，就是有点卡，Starward 窗体大小本身就有限制，建议缩小分辨率压制后重试

你再重启一下看看，我刚直接下载解压选中就卡死了

**Comment by Scighost** [comment]
Windows 平台下出现窗口未响应的原因是 UI 线程未能及时处理消息，经过验证，软件和视频都没有问题，那么可能的原因是播放视频需要的计算量超出了处理器的能力。4K 视频解码需要很大的计算量，而 11900KF 自身没有解码单元，需要你确认一下播放视频时显卡有没有工作。此外，因为 Starward 窗口限制了大小，我还是建议你使用更小分辨率的视频。
