### ISSUE TITLE
能否增加一个保存原神设置的功能?

### ISSUE THREAD

**Issue by wd4455** [Scighost/Starward#815]
### Checklist

- [X] I have already read [docs/Tips.md](https://github.com/Scighost/Starward/blob/main/docs/Tips.md), but my feature is not implemented.
- [X] My suggested feature was not mentioned by others, and it is not a duplicate feature.

### Summary

原神重新安安装后按键什么的都需要再次设置一次,能不能保存原神的设置,再次安装后释放原神的设置?

### Solution or Design

**Comment by Scighost** [comment]
游戏设置都存储在注册表中，你只需要卸载游戏时取消勾选**清理注册表**即可。

![image](https://github.com/Scighost/Starward/assets/61003590/179c4f64-fb3e-4617-b250-e860743c3f26)
