### ISSUE TITLE
怎么卸载？

### ISSUE THREAD

**Issue by InTka** [Scighost/Starward#816]
### Checklist

- [X] I have already read [docs/Tips.md](https://github.com/Scighost/Starward/blob/main/docs/Tips.md), but my question is not solved.
- [X] My question was not mentioned by others, and it is not a duplicate question.

### Description

怎么卸载？直接删除Starward文件夹吗

### Starward Version

0.11.6

### Windows Version

11

**Comment by Scighost** [comment]
如果后续仍有使用的需要的话，请先把数据文件 `StarwardDatabase.db` 备份。

删除你提到的 Starward 文件夹和 `%LocalAppData%\Starward` 就行了。
