### ISSUE TITLE
Mandatory Migration

### ISSUE THREAD

**Issue by studiobuttermedia** [Scighost/Starward#817]
With the new HoYoPlay launcher released, HoYo is pushing the update to everyone it seems, additionally, HoYo announced that the old launcher will be discontinued on June 17th, 2024.

Hopefully you can migrate this launcher to HoYoPlay soon before the day comes.

I have all the APIs needed for HoYoPlay for all the servers.

**Comment by studiobuttermedia** [comment]
The only one that still haven't changed is Honkai Impact 3rd (excluding Mainland China server)

**Comment by HoraceHuang-ui** [comment]
Hi there, I'm the dev of [another launcher project](https://github.com/HoraceHuang-ui/MiHOYO-MiXED-Launcher), aiming to migrate to the new combined launcher. Would you share the APIs of the new launcher to me? Thanks in advance, appreciate your work! :)

**Comment by studiobuttermedia** [comment]
> Hi there, I'm the dev of [another launcher project](https://github.com/HoraceHuang-ui/MiHOYO-MiXED-Launcher), aiming to migrate to the new combined launcher. Would you share the APIs of the new launcher to me? Thanks in advance, appreciate your work! :)

Hey! Yes, but I’ll need to change some stuff before sharing the Repository. I’ll reply soon!

**Comment by studiobuttermedia** [comment]
@HoraceHuang-ui If you need to access the Repo early, please contact me thru [email](mailto:bebosua05@outlook.com) or let me your where to contact. I have a lot of them from Telegram to WeChat

**Comment by HoraceHuang-ui** [comment]
Thanks for your reply! Well I'm not sure if miHoYo will deprecate the APIs of the old launcher immediately in 6.17. If so, I think the migration should be the earlier the better. If you are OK to share, my email is [horacehuang17@gmail.com](mailto:horacehuang17@gmail.com). Thanks again! 另外我也是国人，so it's OK to speak Chinese ;)

**Comment by HoraceHuang-ui** [comment]
![image](https://github.com/Scighost/Starward/assets/67905897/38b97805-013d-4dce-8f81-cfde4fc9334c)
I've completed the migration thanks to your work, thanks again! ;)

**Comment by studiobuttermedia** [comment]
If anyone need to migrate to the new HYP API, I have compiled them in a repository [here]([url](https://github.com/studiobuttermedia/anime_api))!

**Comment by studiobuttermedia** [comment]
The issue have been temporarily resolved for a while. I’ll close this issue.
