### ISSUE TITLE
55555555

### ISSUE THREAD

**Issue by InTka** [Scighost/Starward#818]
### Checklist

- [X] I have already read [docs/Tips.md](https://github.com/Scighost/Starward/blob/main/docs/Tips.md), but my feature is not implemented.
- [X] My suggested feature was not mentioned by others, and it is not a duplicate feature.

### Summary

![0056BF94BA6B1816CC82EA55DC1C0E0A](https://github.com/Scighost/Starward/assets/167493374/c2c87947-e97d-4177-bf2d-92e93f23fa55)
作者大大你这软件老是被360报毒啊肿么办~

### Solution or Design

![0056BF94BA6B1816CC82EA55DC1C0E0A](https://github.com/Scighost/Starward/assets/167493374/49cc2f75-f679-4465-8a7b-579439cc23a8)
隔壁胡桃是不会被360报毒的，但是胡桃不能直接下载游戏。，。，。

**Comment by HoraceHuang-ui** [comment]
那就把它加入360白名单啊…

**Comment by Lightczx** [comment]
我们签了证书自然不会被360报毒

**Comment by Masterain98** [comment]
> 我们签了证书自然不会被360报毒

别说了，你天天被微软追着杀

**Comment by cangerjun** [comment]
我啥杀毒软件都不用，微软也不找麻烦
