### ISSUE TITLE
[Question] 原神的默认UID会切换到0

### ISSUE THREAD

**Issue by nicklly** [Scighost/Starward#819]
### Checklist

- [X] I have already read [docs/Tips.md](https://github.com/Scighost/Starward/blob/main/docs/Tips.md), but my question is not solved.
- [X] My question was not mentioned by others, and it is not a duplicate question.

### Description

![QQ截图20240616094508](https://github.com/Scighost/Starward/assets/17716585/843c9ed2-4272-44cf-aee6-40f1060d9d81)
如图所示.... 即便我在启动游戏前把为0的UID删掉了 然后退出游戏后再次打开启动器（有大概率会出现，并非100%） 这个为0的UID又会变成默认的UID.... 

不知道是我设置问题还是其他问题.. 请指教

### Starward Version

0.11.6

### Windows Version

22631.3593

**Comment by qmzmdqs** [comment]
老问题了。我的解决方式是删掉已保存的，用新的这个重新保存

**Comment by nicklly** [comment]
> 老问题了。我的解决方式是删掉已保存的，用新的这个重新保存

可是保存新的还是有概率变成0为默认哈哈哈哈😂

**Comment by Scighost** [comment]
原神已在注册表中存储当前登录账号的uid，非特殊情况不再会出现uid为0的问题
