### ISSUE TITLE
对右键菜单显示项目提供可选设置

### ISSUE THREAD

**Issue by wlfairlong** [Scighost/Starward#820]
### Checklist

- [X] I have already read [docs/Tips.md](https://github.com/Scighost/Starward/blob/main/docs/Tips.md), but my feature is not implemented.
- [X] My suggested feature was not mentioned by others, and it is not a duplicate feature.

### Summary

能否提供设置，右键菜单只显示自己有的版本，我并没有哔哩哔哩版本，不想在选项中看到它们，有时会影响选择效率
![image](https://github.com/Scighost/Starward/assets/33645701/e4822eb6-0b16-495d-a69a-4da5c4219887)

### Solution or Design

提供一个设置选项，允许关闭右键菜单中不想看到的版本

**Comment by Eric-Joker** [comment]
[#420](https://github.com/Scighost/Starward/issues/420#issuecomment-1872971125)
WinUI限制

**Comment by KoakiMiku** [comment]
> [#797](https://github.com/Scighost/Starward/issues/797#issuecomment-2131168169)

已经一键修复过了，但是右键菜单里还是有B服

**Comment by KoakiMiku** [comment]
我的建议是右键菜单和新的面板联动
![image](https://github.com/Scighost/Starward/assets/34326561/b31791d1-916d-4001-843f-4161f51df41a)

**Comment by Eric-Joker** [comment]
> 已经一键修复过了，但是右键菜单里还是有B服

预览版修改了相关逻辑且未完善

**Comment by Eric-Joker** [comment]
> 我的建议是右键菜单和新的面板联动

好建议，可惜我要肝zzz没时间pr（）
希望作者能看到

**Comment by Scighost** [comment]
托盘菜单的目的是快速启动游戏，在这里会显示所有已经安装的游戏，而主页面的面板上可能存在已启用但没有安装完成的游戏，二者不应该相互关联。
