### ISSUE TITLE
[Feature] 可否通过Webview2嵌入网页版的云游戏

### ISSUE THREAD

**Issue by LiarOnce** [Scighost/Starward#821]
### Checklist

- [X] I have already read [docs/Tips.md](https://github.com/Scighost/Starward/blob/main/docs/Tips.md), but my feature is not implemented.
- [X] My suggested feature was not mentioned by others, and it is not a duplicate feature.

### Summary

例如云原神，其实云原神的Windows版客户端与网页版区别并不大，直接将网页版嵌入到启动器内或许比打开浏览器体验更好（？

### Solution or Design

将网页版云游戏直接嵌入到启动器内（实际上与 #654 期望相同

**Comment by Scighost** [comment]
因为这个问题 https://github.com/MicrosoftEdge/WebView2Feedback/issues/1925 ，使用嵌入 WebView2 时，光标既不会变成游戏内的样式，也不会被隐藏。游戏的体验很差，这一点你可以在**抽卡记录页面**的**更新下拉栏**中点击 `更新(云游戏)` 确认。
