### ISSUE TITLE
[Bug] 崩铁在全面更新新启动器后无法检测到预下载了，疑似旧的预下载api被移除了？

### ISSUE THREAD

**Issue by forchannot** [Scighost/Starward#824]
### Checklist

- [X] My issue was not mentioned by others, and it is not a duplicate issue.

### Description

今天是崩铁2.3预下载，但starward已经无法检测出来了

### Reproduction Steps

.

### Starward Version

0.11.6

### Windows Version

22631

### Log

```shell
[14:41:34.280] [INFO] 
Welcome to Starward v0.11.6
System: Microsoft Windows NT 10.0.22631.0
Command Line: F:\starward\app-0.11.6\Starward.dll

[14:41:34.313] [INFO] Starward.Services.DatabaseService
Database path is 'F:\starward'

[14:41:34.336] [INFO] Starward.Services.DatabaseService
Database version is 8, target version is 8.

[14:41:34.402] [INFO] Starward.Pages.MainPage
Last game region is hkrpg_cn

[14:41:34.410] [INFO] Starward.Pages.MainPage
Navigate to "LauncherPage" with param hkrpg_cn

[14:41:34.636] [WARN] Starward.Services.GameResourceService
config.ini not found: "D:\genshin\config.ini"

[14:41:35.077] [WARN] Starward.Services.GameResourceService
config.ini not found: "D:\genshin\config.ini"

[14:41:35.102] [INFO] Starward.Pages.LauncherPage
Game install path of hkrpg_cn: "F:\Star Rail\Game"

[14:41:35.136] [INFO] Starward.Pages.LauncherPage
Acutal version and gamebiz of hkrpg_cn is "2.2.0", hkrpg_cn.

[14:41:35.272] [WARN] Starward.Services.LauncherContentService
Background of mihoyo api is null (hkrpg_cn)

[14:41:37.006] [INFO] Starward.Services.UpdateService
Start to check update (Preview: True, Arch: X64)

[14:41:37.896] [INFO] Starward.Services.UpdateService
Current version: "0.11.6", latest version: "0.11.6", ignore version: null
```

**Comment by link-fgfgui** [comment]
GET https://hyp-api.mihoyo.com/hyp/hyp-connect/api/getGamePackages?game_ids[]=1Z8W5NHUQb&game_ids[]=osvnlOc0S8&game_ids[]=64kMb5iAWu&launcher_id=jGHBHlcOq1 HTTP/1.1
Host: hyp-api.mihoyo.com
content-type: application/json

{"retcode":0,"message":"OK","data":{"game_packages":[{"game":{"id":"1Z8W5NHUQb","biz":"hk4e_cn"},"main":{"major":{"version":"4.7.0","game_pkgs":[{"url":"https://autopatchcn.yuanshen.com/client_app/download/pc_zip/20240524181110_KeC850jf18J0oRII/YuanShen_4.7.0.zip.001","md5":"8e673710736b3a625d49512dd2e20ba8","size":"10737418240","decompressed_size":"21485322240"},{"url":"https://autopatchcn.yuanshen.com/client_app/download/pc_zip/20240524181110_KeC850jf18J0oRII/YuanShen_4.7.0.zip.002","md5":"58c0668ae80e92e6491d341c2581da74","size":"10737418240","decompressed_size":"21485322240"},{"url":"https://autopatchcn.yuanshen.com/client_app/download/pc_zip/20240524181110_KeC850jf18J0oRII/YuanShen_4.7.0.zip.003","md5":"0b3f83f4d65e11a57c2d3447b1211314","size":"10737418240","decompressed_size":"21485322240"},{"url":"https://autopatchcn.yuanshen.com/client_app/download/pc_zip/20240524181110_KeC850jf18J0oRII/YuanShen_4.7.0.zip.004","md5":"917fe849b3c6d3fb319f685c56e0ccdc","size":"10737418240","decompressed_size":"21485322240"},{"url":"https://autopatchcn.yuanshen.com/client_app/download/pc_zip/20240524181110_KeC850jf18J0oRII/YuanShen_4.7.0.zip.005","md5":"b10a1fee419e200d15c9cda5416ac1b6","size":"10737418240","decompressed_size":"21485322240"},{"url":"https://autopatchcn.yuanshen.com/client_app/download/pc_zip/20240524181110_KeC850jf18J0oRII/YuanShen_4.7.0.zip.006","md5":"38d665f5dcb1461f9a6d232df9e82279","size":"7151257211","decompressed_size":"14313000182"}],"audio_pkgs":[{"language":"zh-cn","url":"https://autopatchcn.yuanshen.com/client_app/download/pc_zip/20240524181110_KeC850jf18J0oRII/Audio_Chinese_4.7.0.zip","md5":"fd7729d003118f24952c3aac47486f7e","size":"14656148562","decompressed_size":"29322782884"},{"language":"en-us","url":"https://autopatchcn.yuanshen.com/client_app/download/pc_zip/20240524181110_KeC850jf18J0oRII/Audio_English(US)_4.7.0.zip","md5":"8f18c5db87b25f6304b4054ac23b67ac","size":"17116958429","decompressed_size":"34244402618"},{"language":"ja-jp","url":"https://autopatchcn.yuanshen.com/client_app/download/pc_zip/20240524181110_KeC850jf18J0oRII/Audio_Japanese_4.7.0.zip","md5":"1d8f13639f636ccdee7612365bb1982f","size":"19217110713","decompressed_size":"38444707186"},{"language":"ko-kr","url":"https://autopatchcn.yuanshen.com/client_app/download/pc_zip/20240524181110_KeC850jf18J0oRII/Audio_Korean_4.7.0.zip","md5":"5c36f875dc9db7e410d00fc9e39cfcf8","size":"14393186291","decompressed_size":"28796858342"}],"res_list_url":"https://autopatchcn.yuanshen.com/client_app/download/pc_zip/20240524181110_KeC850jf18J0oRII/ScatteredFiles"},"patches":[{"version":"4.6.0","game_pkgs":[{"url":"https://autopatchcn.yuanshen.com/client_app/update/hk4e_cn/18/game_4.6.0_4.7.0_hdiff_xrMCwjTting6IubX.zip","md5":"292EC8386448668C0402BE7CD8BFB75A","size":"26159840519","decompressed_size":"53105584319"}],"audio_pkgs":[{"language":"zh-cn","url":"https://autopatchcn.yuanshen.com/client_app/update/hk4e_cn/18/zh-cn_4.6.0_4.7.0_hdiff_mRiPScjVzsZHlx1u.zip","md5":"6D9AA08E47F2A8207BCEC6B3A15E05F0","size":"538537419","decompressed_size":"1163901247"},{"language":"en-us","url":"https://autopatchcn.yuanshen.com/client_app/update/hk4e_cn/18/en-us_4.6.0_4.7.0_hdiff_PeQspaEOWljGHcbS.zip","md5":"3D571A373195C8A9E78D8867384B040E","size":"636831292","decompressed_size":"1350160761"},{"language":"ja-jp","url":"https://autopatchcn.yuanshen.com/client_app/update/hk4e_cn/18/ja-jp_4.6.0_4.7.0_hdiff_rLT1nMcAam4wgqxe.zip","md5":"02B4C3FE67A7FD947AA7BBAFF66144E9","size":"607978211","decompressed_size":"1381541678"},{"language":"ko-kr","url":"https://autopatchcn.yuanshen.com/client_app/update/hk4e_cn/18/ko-kr_4.6.0_4.7.0_hdiff_ck7wjJfSXVi1svAb.zip","md5":"72090F654B804DAC7F7C04A4F84154B5","size":"480983403","decompressed_size":"1061377924"}],"res_list_url":""},{"version":"4.5.0","game_pkgs":[{"url":"https://autopatchcn.yuanshen.com/client_app/update/hk4e_cn/18/game_4.5.0_4.7.0_hdiff_Dgw4Eo0AxTXNq9Jk.zip","md5":"2E8754D20B170ECD13DC7748937B4A7C","size":"31998782704","decompressed_size":"64848661944"}],"audio_pkgs":[{"language":"zh-cn","url":"https://autopatchcn.yuanshen.com/client_app/update/hk4e_cn/18/zh-cn_4.5.0_4.7.0_hdiff_X7w9BIauA5H6Zl1W.zip","md5":"174C98777B602BAC075D70235CA88AB1","size":"859912239","decompressed_size":"1848339271"},{"language":"en-us","url":"https://autopatchcn.yuanshen.com/client_app/update/hk4e_cn/18/en-us_4.5.0_4.7.0_hdiff_7EqaT0G4svSW5Cci.zip","md5":"0E28A020A7F9995DF9B0E0750A24C6EE","size":"1055345969","decompressed_size":"2228509971"},{"language":"ja-jp","url":"https://autopatchcn.yuanshen.com/client_app/update/hk4e_cn/18/ja-jp_4.5.0_4.7.0_hdiff_aITuEBRVUsNLedk3.zip","md5":"A5BAE933F88AB16BF47FAF92F96DE18C","size":"962945895","decompressed_size":"2196408610"},{"language":"ko-kr","url":"https://autopatchcn.yuanshen.com/client_app/update/hk4e_cn/18/ko-kr_4.5.0_4.7.0_hdiff_XY2sPVrw4WMJedkT.zip","md5":"4106329910009C7879BD2462C15E454D","size":"768179942","decompressed_size":"1697937423"}],"res_list_url":""}]},"pre_download":{"major":null,"patches":[]}},{"game":{"id":"osvnlOc0S8","biz":"bh3_cn"},"main":{"major":{"version":"7.5.0","game_pkgs":[{"url":"https://bundle.bh3.com/ptpublic/rel/20240506104443_Eb7wY4fRoYiICW5J/PC/BH3_v7.5.0_c3433332d6a2.7z","md5":"31a6bda0cae4049804a895c0430d6537","size":"17891545746","decompressed_size":"35793577252"}],"audio_pkgs":[],"res_list_url":"https://bundle.bh3.com/ptpublic/rel/20240506104443_Eb7wY4fRoYiICW5J/PC/extract"},"patches":[]},"pre_download":{"major":null,"patches":[]}},{"game":{"id":"64kMb5iAWu","biz":"hkrpg_cn"},"main":{"major":{"version":"2.2.0","game_pkgs":[{"url":"https://autopatchcn.bhsr.com/client/cn/20240425223452_X67JiqezhqpvBZW8/PC/StarRail_2.2.0.zip","md5":"bce27503f6f93b9e4846b84d28660531","size":"33959600744","decompressed_size":"67929687248"}],"audio_pkgs":[{"language":"zh-cn","url":"https://autopatchcn.bhsr.com/client/cn/20240425223452_X67JiqezhqpvBZW8/PC/Chinese.zip","md5":"df10fae26649d570744d49f6e3d31a20","size":"4548320624","decompressed_size":"9107127008"},{"language":"zh-tw","url":"https://autopatchcn.bhsr.com/client/cn/20240425223452_X67JiqezhqpvBZW8/PC/Chinese.zip","md5":"df10fae26649d570744d49f6e3d31a20","size":"4548320624","decompressed_size":"9107127008"},{"language":"en-us","url":"https://autopatchcn.bhsr.com/client/cn/20240425223452_X67JiqezhqpvBZW8/PC/English.zip","md5":"5c1e42dfd9911c2d45eb34d852a79919","size":"5428937683","decompressed_size":"10868361126"},{"language":"ja-jp","url":"https://autopatchcn.bhsr.com/client/cn/20240425223452_X67JiqezhqpvBZW8/PC/Japanese.zip","md5":"b2bfda217280526652e04afb4253bcd0","size":"5790872609","decompressed_size":"11592230978"},{"language":"ko-kr","url":"https://autopatchcn.bhsr.com/client/cn/20240425223452_X67JiqezhqpvBZW8/PC/Korean.zip","md5":"01cf2ac132200323eeaa43d7be7c8456","size":"4587944120","decompressed_size":"9186374000"}],"res_list_url":"https://autopatchcn.bhsr.com/client/cn/20240425223452_X67JiqezhqpvBZW8/PC/unzip"},"patches":[{"version":"2.1.0","game_pkgs":[{"url":"https://autopatchcn.bhsr.com/client/hkrpg_cn/33/game_2.1.0_2.2.0_hdiff_I8kM3Gp2cfa0x9Cq.zip","md5":"EF8F7828267E549911E5F0545D96A0DE","size":"16170898842","decompressed_size":"34301737412"}],"audio_pkgs":[{"language":"zh-cn","url":"https://autopatchcn.bhsr.com/client/hkrpg_cn/33/zh-cn_2.1.0_2.2.0_hdiff_3iOR1loABDIkcFMd.zip","md5":"D6C7773F3099ABF3F77DCA8F6D86C2E6","size":"486920993","decompressed_size":"984620528"},{"language":"zh-tw","url":"https://autopatchcn.bhsr.com/client/hkrpg_cn/33/zh-tw_2.1.0_2.2.0_hdiff_eMJ6dxlGFThCt2aX.zip","md5":"B6CC2ADA1BEAE686535ED18C6F37E417","size":"486920993","decompressed_size":"984620528"},{"language":"en-us","url":"https://autopatchcn.bhsr.com/client/hkrpg_cn/33/en-us_2.1.0_2.2.0_hdiff_Hr0ejtlAhDYJabE1.zip","md5":"8DBD3EE94C431873E4625A654690543C","size":"586036528","decompressed_size":"1182934620"},{"language":"ja-jp","url":"https://autopatchcn.bhsr.com/client/hkrpg_cn/33/ja-jp_2.1.0_2.2.0_hdiff_ODK1XIAjEl7vgRCy.zip","md5":"63D3E1DE6DE24CFA2711B2307BCF9F7F","size":"609967259","decompressed_size":"1231073764"},{"language":"ko-kr","url":"https://autopatchcn.bhsr.com/client/hkrpg_cn/33/ko-kr_2.1.0_2.2.0_hdiff_S27Zc5QpuyAOI6R1.zip","md5":"911349D8A51120E9FA826D57F9B36396","size":"479632570","decompressed_size":"970290425"}],"res_list_url":""}]},"pre_download":{"major":{"version":"2.3.0","game_pkgs":[{"url":"https://autopatchcn.bhsr.com/client/cn/20240608161617_2zjrqfLT5RZmEzcR/PC/StarRail_2.3.0.zip","md5":"20755d1dca15524928c1da5611fa356f","size":"35308293537","decompressed_size":"70627072834"}],"audio_pkgs":[{"language":"zh-cn","url":"https://autopatchcn.bhsr.com/client/cn/20240608161617_2zjrqfLT5RZmEzcR/PC/Chinese.zip","md5":"a67f7c4729f78d37444ca63bcd29996a","size":"4781237787","decompressed_size":"9572961334"},{"language":"zh-tw","url":"https://autopatchcn.bhsr.com/client/cn/20240608161617_2zjrqfLT5RZmEzcR/PC/Chinese.zip","md5":"a67f7c4729f78d37444ca63bcd29996a","size":"4781237787","decompressed_size":"9572961334"},{"language":"en-us","url":"https://autopatchcn.bhsr.com/client/cn/20240608161617_2zjrqfLT5RZmEzcR/PC/English.zip","md5":"e342e0441786ee64edf3367fe5df8bac","size":"5676154808","decompressed_size":"11362795376"},{"language":"ja-jp","url":"https://autopatchcn.bhsr.com/client/cn/20240608161617_2zjrqfLT5RZmEzcR/PC/Japanese.zip","md5":"2a47b18df89fa23075f5ac9305b6ab0c","size":"6071277521","decompressed_size":"12153040802"},{"language":"ko-kr","url":"https://autopatchcn.bhsr.com/client/cn/20240608161617_2zjrqfLT5RZmEzcR/PC/Korean.zip","md5":"4b76f48d141cffb6daf953e7d068afb3","size":"4821826098","decompressed_size":"9654137956"}],"res_list_url":"https://autopatchcn.bhsr.com/client/cn/20240608161617_2zjrqfLT5RZmEzcR/PC/unzip"},"patches":[{"version":"2.2.0","game_pkgs":[{"url":"https://autopatchcn.bhsr.com/client/diff/hkrpg_cn/game_2.2.0_2.3.0_hdiff_bUOAKNttlfhuVbOa.zip","md5":"7240a99240a02370ad438a668afb12ed","size":"22635015077","decompressed_size":"47962728012"}],"audio_pkgs":[{"language":"zh-cn","url":"https://autopatchcn.bhsr.com/client/diff/hkrpg_cn/audio_zh-cn_2.2.0_2.3.0_hdiff_lARHmKlxgnlxDerc.zip","md5":"d5e66572fc3b2cd50f640aaa068340fa","size":"233315579","decompressed_size":"477245282"},{"language":"zh-tw","url":"https://autopatchcn.bhsr.com/client/diff/hkrpg_cn/audio_zh-tw_2.2.0_2.3.0_hdiff_WndXLSLONtMaMrek.zip","md5":"33e8393bad03bc433e9feec143a056f3","size":"233315579","decompressed_size":"477245282"},{"language":"ko-kr","url":"https://autopatchcn.bhsr.com/client/diff/hkrpg_cn/audio_ko-kr_2.2.0_2.3.0_hdiff_RhsgNyXJBOeErhDP.zip","md5":"88993b830ce23610ef9efe9cbba0d49b","size":"238191368","decompressed_size":"487040497"},{"language":"en-us","url":"https://autopatchcn.bhsr.com/client/diff/hkrpg_cn/audio_en-us_2.2.0_2.3.0_hdiff_sYzOFJJydRWzPliE.zip","md5":"2322791502ab160596b122aa2374b320","size":"258699468","decompressed_size":"528031062"},{"language":"ja-jp","url":"https://autopatchcn.bhsr.com/client/diff/hkrpg_cn/audio_ja-jp_2.2.0_2.3.0_hdiff_oBXBkHpjiWqOpgyG.zip","md5":"f662b46d8a7f7e6facc522d3e24aee2f","size":"282483948","decompressed_size":"575637594"}],"res_list_url":""}]}}]}}

**Comment by link-fgfgui** [comment]
新api是这样的

**Comment by link-fgfgui** [comment]
<details> 
<summary><font size="4" >Show Code</font></summary> 
<pre><code>GET https://api-launcher-static.mihoyo.com/hkrpg_cn/mdk/launcher/api/resource?channel_id=1&key=6KcVuOkbcqjJomjZ&launcher_id=33&sub_channel_id=1 HTTP/1.1
Host: api-launcher-static.mihoyo.com
User-Agent: Starward/0.11.6
Accept-Encoding: gzip, deflate, br

{"retcode":0,"message":"OK","data":{"game":{"latest":{"name":"","version":"2.2.0","path":"https://autopatchcn.bhsr.com/client/cn/20240425223452_X67JiqezhqpvBZW8/PC/StarRail_2.2.0.zip","size":"67929687248","md5":"bce27503f6f93b9e4846b84d28660531","entry":"StarRail.exe","voice_packs":[{"language":"zh-cn","name":"","path":"https://autopatchcn.bhsr.com/client/cn/20240425223452_X67JiqezhqpvBZW8/PC/Chinese.zip","size":"9107127008","md5":"df10fae26649d570744d49f6e3d31a20","package_size":"4548320624"},{"language":"zh-tw","name":"","path":"https://autopatchcn.bhsr.com/client/cn/20240425223452_X67JiqezhqpvBZW8/PC/Chinese.zip","size":"9107127008","md5":"df10fae26649d570744d49f6e3d31a20","package_size":"4548320624"},{"language":"en-us","name":"","path":"https://autopatchcn.bhsr.com/client/cn/20240425223452_X67JiqezhqpvBZW8/PC/English.zip","size":"10868361126","md5":"5c1e42dfd9911c2d45eb34d852a79919","package_size":"5428937683"},{"language":"ja-jp","name":"","path":"https://autopatchcn.bhsr.com/client/cn/20240425223452_X67JiqezhqpvBZW8/PC/Japanese.zip","size":"11592230978","md5":"b2bfda217280526652e04afb4253bcd0","package_size":"5790872609"},{"language":"ko-kr","name":"","path":"https://autopatchcn.bhsr.com/client/cn/20240425223452_X67JiqezhqpvBZW8/PC/Korean.zip","size":"9186374000","md5":"01cf2ac132200323eeaa43d7be7c8456","package_size":"4587944120"}],"decompressed_path":"https://autopatchcn.bhsr.com/client/cn/20240425223452_X67JiqezhqpvBZW8/PC/unzip","segments":[],"package_size":"33959600744"},"diffs":[{"name":"game_2.1.0_2.2.0_hdiff_I8kM3Gp2cfa0x9Cq.zip","version":"2.1.0","path":"https://autopatchcn.bhsr.com/client/hkrpg_cn/33/game_2.1.0_2.2.0_hdiff_I8kM3Gp2cfa0x9Cq.zip","size":"34301737412","md5":"EF8F7828267E549911E5F0545D96A0DE","is_recommended_update":false,"voice_packs":[{"language":"zh-cn","name":"zh-cn_2.1.0_2.2.0_hdiff_3iOR1loABDIkcFMd.zip","path":"https://autopatchcn.bhsr.com/client/hkrpg_cn/33/zh-cn_2.1.0_2.2.0_hdiff_3iOR1loABDIkcFMd.zip","size":"984620528","md5":"D6C7773F3099ABF3F77DCA8F6D86C2E6","package_size":"486920993"},{"language":"zh-tw","name":"zh-tw_2.1.0_2.2.0_hdiff_eMJ6dxlGFThCt2aX.zip","path":"https://autopatchcn.bhsr.com/client/hkrpg_cn/33/zh-tw_2.1.0_2.2.0_hdiff_eMJ6dxlGFThCt2aX.zip","size":"984620528","md5":"B6CC2ADA1BEAE686535ED18C6F37E417","package_size":"486920993"},{"language":"en-us","name":"en-us_2.1.0_2.2.0_hdiff_Hr0ejtlAhDYJabE1.zip","path":"https://autopatchcn.bhsr.com/client/hkrpg_cn/33/en-us_2.1.0_2.2.0_hdiff_Hr0ejtlAhDYJabE1.zip","size":"1182934620","md5":"8DBD3EE94C431873E4625A654690543C","package_size":"586036528"},{"language":"ja-jp","name":"ja-jp_2.1.0_2.2.0_hdiff_ODK1XIAjEl7vgRCy.zip","path":"https://autopatchcn.bhsr.com/client/hkrpg_cn/33/ja-jp_2.1.0_2.2.0_hdiff_ODK1XIAjEl7vgRCy.zip","size":"1231073764","md5":"63D3E1DE6DE24CFA2711B2307BCF9F7F","package_size":"609967259"},{"language":"ko-kr","name":"ko-kr_2.1.0_2.2.0_hdiff_S27Zc5QpuyAOI6R1.zip","path":"https://autopatchcn.bhsr.com/client/hkrpg_cn/33/ko-kr_2.1.0_2.2.0_hdiff_S27Zc5QpuyAOI6R1.zip","size":"970290425","md5":"911349D8A51120E9FA826D57F9B36396","package_size":"479632570"}],"package_size":"16170898842"}]},"plugin":{"plugins":[{"name":"DXSETUP.zip","version":"","path":"https://autopatchcn.bhsr.com/client/DXSETUP.zip","size":"100647892","md5":"ca2ac3835d7d7da6cb8624fefb177083","entry":"","package_size":"0"}],"version":"1"},"web_url":"https://hkrpg.mihoyo.com/launcher","force_update":null,"pre_download_game":null,"deprecated_packages":[{"name":"game_2.0.0_2.1.0_hdiff_KjPUTRqDO6ZWGeyp.zip","md5":"E0B1FD73E543939C52A37BBEB6BF6AF8"},{"name":"zh-cn_2.0.0_2.1.0_hdiff_tsNrHUifmELWAxn0.zip","md5":"E898F44B5DB766745A888F6532B685C6"},{"name":"zh-tw_2.0.0_2.1.0_hdiff_K38ZCQnmXBjaDOgx.zip","md5":"2F28894AF6EA4361E95DFD690A475560"},{"name":"en-us_2.0.0_2.1.0_hdiff_MK2tnjZE1xPb90Le.zip","md5":"05E8AD772743393D18E3F401CE2CC997"},{"name":"ja-jp_2.0.0_2.1.0_hdiff_MaToxcp6VgdzW7sn.zip","md5":"2098CF31B700A0833C9D4DC7D90A192A"},{"name":"ko-kr_2.0.0_2.1.0_hdiff_DOI64wNZX3rStxcE.zip","md5":"DDD199503CC53D93FFB0B137899BB84F"},{"name":"StarRail_2.1.0.zip","md5":"bfdbb18fba9231d63e72e5808b6521d0"},{"name":"Chinese.zip","md5":"5737ad765fa7b6eac8210ee4f2eeeb39"},{"name":"Chinese.zip","md5":"5737ad765fa7b6eac8210ee4f2eeeb39"},{"name":"English.zip","md5":"1f6a530b341f4b82f612fe6004b1bdbf"},{"name":"Japanese.zip","md5":"f9b0c514915369f3b9155127684f8d51"},{"name":"Korean.zip","md5":"5443d68b0a5adb03ab92c8fb4eb7df24"},{"name":"game_1.6.0_2.0.0_hdiff_mT4gkop1jCKyVuD0.zip","md5":"C23BD6852256B176B410BC71A1836015"},{"name":"zh-cn_1.6.0_2.0.0_hdiff_YCNdkg2V5MjX8v3B.zip","md5":"95774CAA02F21BD2C6CE45102787EB0F"},{"name":"zh-tw_1.6.0_2.0.0_hdiff_xwlRpK7zNFZHBVTh.zip","md5":"BEC91DC25C90AA79FD3E069AC731077A"},{"name":"en-us_1.6.0_2.0.0_hdiff_AjEnKPVeXUov2MsO.zip","md5":"72F5256CDBE62C7E03834463DE3831AF"},{"name":"ja-jp_1.6.0_2.0.0_hdiff_ZAjg5I8CmbxoLOi4.zip","md5":"10A90B0A6543D817D4982EEE9120029B"},{"name":"ko-kr_1.6.0_2.0.0_hdiff_tgYl09UoAnuV7cCi.zip","md5":"6C3777ECBDDCFF427404CC9F92BEA1FD"},{"name":"StarRail_2.0.0.zip","md5":"781caf4f888dd21a3ef4f8c36960f915"},{"name":"Chinese.zip","md5":"785d6d79fcdaa0cdb847718ad17a4f82"},{"name":"Chinese.zip","md5":"785d6d79fcdaa0cdb847718ad17a4f82"},{"name":"English.zip","md5":"41eb4b50d668a349fab3cb4b5ac1f75e"},{"name":"Japanese.zip","md5":"42bc301b19e51b0ff72fb232b3043137"},{"name":"Korean.zip","md5":"5d4d3f4829cd69dcee13b11b58310c35"},{"name":"game_1.5.0_1.6.0_hdiff_J95qxDtHQf2vBRal.zip","md5":"6431BEBB280133EE22D976533B94B8D4"},{"name":"zh-cn_1.5.0_1.6.0_hdiff_s6iunpdeBXTcqYGw.zip","md5":"38E5BA0B4DDFF2B62744DFF8BD90D394"},{"name":"zh-tw_1.5.0_1.6.0_hdiff_i3VdYwWoZyIra5ju.zip","md5":"90EE76BF094447BBEB4CEFBEDBC0DEEB"},{"name":"en-us_1.5.0_1.6.0_hdiff_Cm5WeNnawEg9HtGZ.zip","md5":"C0FDF1B4FE89292A419DD223EADABFE8"},{"name":"ja-jp_1.5.0_1.6.0_hdiff_u3MlzpydKDRY2PGk.zip","md5":"BD8EC980A07A9417B70506491CF18BFA"},{"name":"ko-kr_1.5.0_1.6.0_hdiff_GZp4t5D1TSj7c8MB.zip","md5":"76283E44EE5EC3ECF6A389488630CC12"},{"name":"StarRail_1.6.0.zip","md5":"b06aae06e1541e8e1c35ae840371daaa"},{"name":"Chinese.zip","md5":"10d364567cc5a5f0ccc80c4250c19eed"},{"name":"Chinese.zip","md5":"10d364567cc5a5f0ccc80c4250c19eed"},{"name":"English.zip","md5":"593d5cc23bd0d03c7f70a08e572b890e"},{"name":"Japanese.zip","md5":"ea158062f4638c257c64c459b1f5963d"},{"name":"Korean.zip","md5":"d54988b95af7d35f689ccb82d5b6cd1b"},{"name":"game_1.4.0_1.5.0_hdiff_TnhRMscqGdQuNyDU.zip","md5":"39ACC996C7D3EB4209E6A8C8F8C69869"},{"name":"StarRail_1.5.0.zip","md5":"2b5d401eebf9998cfda1bf04f933c2b1"},{"name":"Chinese.zip","md5":"5b9e8df354d5fce4f9c3d2e06c4f8756"},{"name":"Chinese.zip","md5":"5b9e8df354d5fce4f9c3d2e06c4f8756"},{"name":"English.zip","md5":"cc57a7ec5e4fd553eea14a598792492b"},{"name":"Japanese.zip","md5":"5a3714636e54682c5b50d45959e53278"},{"name":"Korean.zip","md5":"93cc9b33916bab709dc05490e4601e74"},{"name":"game_1.2.0_1.4.0_hdiff_T5ZwNtghdjbMl0s8.zip","md5":"7C0AA6C0152DEEFD96B86F19D0E34E7C"},{"name":"game_1.3.0_1.4.0_hdiff_cyokQi1nq6ZGtCUv.zip","md5":"4E82618C30F028E6D88BFEA9BBE5EC58"}],"sdk":null,"deprecated_files":[]}}</code>
</pre> </details>

**Comment by link-fgfgui** [comment]
旧api能正常返回旧数据

**Comment by link-fgfgui** [comment]
新api直接把原神，崩铁，崩坏3合并了

**Comment by noaione** [comment]
Global:
```
GET https://sg-hyp-api.hoyoverse.com/hyp/hyp-connect/api/getGamePackages?game_ids[]=gopR6Cufr3&game_ids[]=4ziysqXOQ8&launcher_id=VYTpXlbWo8
```

Genshin: `gopR6Cufr3`
H:SR: `4ziysqXOQ8`
HI3: `5TIVvvcwtM` (Global)
ZZZ: `U5hbdsT9W7`
Launcher ID: `VYTpXlbWo8`

**Comment by WakiJi** [comment]
相关代码段在https://github.com/Scighost/Starward/blob/main/src/Starward.Core/Launcher/LauncherClient.cs#L159-L160，分不同游戏资源获取的话可以给game_ids加不同参数

比如**只需要**获取崩铁的数据的话，走这个link就行https://hyp-api.mihoyo.com/hyp/hyp-connect/api/getGamePackages?game_ids[]=64kMb5iAWu&launcher_id=jGHBHlcOq1

**Comment by WakiJi** [comment]
相关代码段在[这里](https://github.com/Scighost/Starward/blob/main/src/Starward.Core/Launcher/LauncherClient.cs#L159-L160)，分不同游戏资源获取的话可以给game_ids加不同参数

比如**只需要**获取崩铁的数据的话，走这个link就行https://hyp-api.mihoyo.com/hyp/hyp-connect/api/getGamePackages?game_ids[]=64kMb5iAWu&launcher_id=jGHBHlcOq1

**Comment by Loqiai** [comment]
能出个具体的教程吗

**Comment by VanDark2001** [comment]
等一个更新或者解决办法

**Comment by link-fgfgui** [comment]
明天就更新了，不如用官启 : (

**Comment by WakiJi** [comment]
水了个 pull request 不知道好不好使

**Comment by T-007KB** [comment]
什么时候可以正常下载？

**Comment by love98ooo** [comment]
> 这软件要是不更新，就要废了呀，旧的api都没用了，项目大佬给给解决方法 :(

用官方启动器更新，不影响用 Starward 启动游戏

**Comment by jhll1124** [comment]
本来以为只有我有这种情况，但看了看资源包有预下载的，盲猜一波API寄了

**Comment by Whuihuan** [comment]
可能旧的API已经不更新了，前天开始就没预下载，今天也没提示更新游戏，官启是有更新游戏选项的

**Comment by Eric-Joker** [comment]
https://github.com/Eric-Joker/Starward/actions/runs/9568870284

**Comment by Capoouo** [comment]
> https://github.com/Eric-Joker/Starward/actions/runs/9568870284

大佬 目前有能轉B服了嗎

**Comment by Eric-Joker** [comment]
> > https://github.com/Eric-Joker/Starward/actions/runs/9568870284
> 
> 大佬 目前有能轉B服了嗎

我无法找到我认为有效的新的SDK相关API，暂时没法适配

**Comment by Capoouo** [comment]
> > > https://github.com/Eric-Joker/Starward/actions/runs/9568870284
> 
> > 
> 
> > 大佬 目前有能轉B服了嗎
> 
> 
> 
> 我无法找到我认为有效的新的SDK相关API，暂时没法适配

行 辛苦了

**Comment by Eric-Joker** [comment]
> 大佬 目前有能轉B服了嗎

可以了

**Comment by Scighost** [comment]
很抱歉这么晚才回复这个问题，本人因为身体原因，没能及时适配米哈游启动器，给大家带来了不好的体验，对此我深表歉意。适配工作还需要一段时间，感谢你的理解与支持。
