### ISSUE TITLE
[Question] 我无法检测到星穹铁道的预下载

### ISSUE THREAD

**Issue by Gpan666** [Scighost/Starward#829]
### Checklist

- [X] I have already read [docs/Tips.md](https://github.com/Scighost/Starward/blob/main/docs/Tips.md), but my question is not solved.
- [X] My question was not mentioned by others, and it is not a duplicate question.

### Description

我无法检测到星穹铁道的预下载
![Uploading PixPin_2024-06-18_14-44-39.png…]()

### Starward Version

0.11.6

### Windows Version

22631.3737

**Comment by drpasserby** [comment]
米哈游更换了预下载的API，PR里面有一个更新，但是作者还没有合并进去。等作者打包之后更新吧。

**Comment by HuangHB2000** [comment]
#824已经提到过这个问题了。作者还没更，稍微等一下吧www
反正等到明天就不需要预下载了www

**Comment by Eric-Joker** [comment]
https://github.com/Eric-Joker/Starward/actions/runs/9568870284
