### ISSUE TITLE
在6月19日当天无法收到崩坏·星穹铁道的更新/I can not be able to receive updates on Honkai Star Rail on June 19th

### ISSUE THREAD

**Issue by qinglangchaoke** [Scighost/Starward#831]
### Checklist

- [x] I have already read [docs/Tips.md](https://github.com/Scighost/Starward/blob/main/docs/Tips.md), but my feature is not implemented.
- [X] My suggested feature was not mentioned by others, and it is not a duplicate feature.

### Summary

为什么会这样，希望作者可以在未来的版本重新更新此功能（xx游戏预下载和提前更新）//Why is this happening, hopefully the author can re-update this feature in a future version (xx game pre-download and early update)

### Solution or Design

希望作者可以在xx游戏预下载/更新时及时更新到starward中，谢谢！//Hopefully, the author will be updated into Starward in time when the xx game pre-download/update。thanks！

**Comment by songzhuoru** [comment]
我现在也是，不知道怎么解决，游戏已经更新了，但是我没办法更新

**Comment by ReeYoung** [comment]
在官方启动器更新后，预下载、升级与更新的api已经变更。请使用官方启动器或者collapose更新，或者等作者解决这个问题。

**Comment by Jasper-rm** [comment]
好像新启动器出来之后许多api都变了，就连宣传内容的都接收不到了

**Comment by cangerjun** [comment]
https://autopatchcn.bhsr.com/client/diff/hkrpg_cn/audio_zh-cn_2.2.0_2.3.0_hdiff_lARHmKlxgnlxDerc.zip 中文语音
https://autopatchcn.bhsr.com/client/diff/hkrpg_cn/game_2.2.0_2.3.0_hdiff_bUOAKNttlfhuVbOa.zip 地图
https://autopatchcn.bhsr.com/client/diff/hkrpg_cn/audio_ja-jp_2.2.0_2.3.0_hdiff_oBXBkHpjiWqOpgyG.zip 日语语音

**Comment by xiaosuyyds** [comment]
可以用https://github.com/Eric-Joker/Starward/actions/runs/9568870284

**Comment by Yuuki-Rin** [comment]
> 我现在也是，不知道怎么解决，游戏已经更新了，但是我没办法更新

直接使用官方的聚合启动器先更新吧

**Comment by xiaosuyyds** [comment]
> 可以用https://github.com/Eric-Joker/Starward/actions/runs/9568870284

https://github.com/Scighost/Starward/pull/830

**Comment by GUODAMING3124** [comment]
旧的api已经用不了了。你可以先用官方启动器更新好了再用starward玩，这个等作者修复吧，别急
