### ISSUE TITLE
[Feature] 背景图改进

### ISSUE THREAD

**Issue by Rui3128** [Scighost/Starward#833]
### Checklist

- [X] I have already read [docs/Tips.md](https://github.com/Scighost/Starward/blob/main/docs/Tips.md), but my feature is not implemented.
- [X] My suggested feature was not mentioned by others, and it is not a duplicate feature.

### Summary

云·原神 背景图
星穹铁道 背景图

### Solution or Design

云·原神背景图可以用这个api就不用把公告移动到另一侧了
替换height和width参数为窗口宽高会自动返回合适的排版
https://[api-cloudgame.mihoyo.com/hk4e_cg_cn/gamer/api/getUIConfig?height=1266&width=761&type=2](https://api-cloudgame.mihoyo.com/hk4e_cg_cn/gamer/api/getUIConfig?height=1266&width=761&type=2)

旧版星穹铁道启动器已经停止支持，背景图API已经没图片链接返回了
![image](https://github.com/Scighost/Starward/assets/85873279/514075c4-53b8-46c6-ad89-9cc402e98b0c)
新版启动器背景图API
https://[hyp-api.mihoyo.com/hyp/hyp-connect/api/getAllGameBasicInfo?launcher_id=jGHBHlcOq1&language=zh-cn&game_id=64kMb5iAWu](https://hyp-api.mihoyo.com/hyp/hyp-connect/api/getAllGameBasicInfo?launcher_id=jGHBHlcOq1&language=zh-cn&game_id=64kMb5iAWu)
国际服
https://[sg-hyp-api.hoyoverse.com/hyp/hyp-connect/api/getAllGameBasicInfo?launcher_id=VYTpXlbWo8&language=zh-cn7D&game_id=4ziysqXOQ8](https://sg-hyp-api.hoyoverse.com/hyp/hyp-connect/api/getAllGameBasicInfo?launcher_id=VYTpXlbWo8&language=zh-cn7D&game_id=4ziysqXOQ8)
替换game_id参数还有别的几个游戏背景图

name  biz  game_id
绝区零  nap_cn  x6znKlJ0xK
崩坏星穹铁道  hkrpg_cn  64kMb5iAWu
原神  hk4e_cn  1Z8W5NHUQb
崩坏3  bh3_cn  osvnlOc0S8
ZenlessZoneZero  nap_global  U5hbdsT9W7
HonkaiStarRail  hkrpg_global  4ziysqXOQ8
GenshinImpact  hk4e_global  gopR6Cufr3
HonkaiImpact3rd  bh3_global  5TIVvvcwtM

**Comment by Eric-Joker** [comment]
#830 
https://github.com/Eric-Joker/Starward/actions/runs/9589003640
