### ISSUE TITLE
[Feature] 部分人能下载到需要的更新包，有没有工具能进行合并

### ISSUE THREAD

**Issue by cangerjun** [Scighost/Starward#835]
### Checklist

- [X] I have already read [docs/Tips.md](https://github.com/Scighost/Starward/blob/main/docs/Tips.md), but my feature is not implemented.
- [X] My suggested feature was not mentioned by others, and it is not a duplicate feature.

### Summary

我有HoyoLuncher官方启动器，能抓到更新包的下载链接，我的朋友没有下载HoyoLuncher他下载更新包之后如何合并。
I have Hoyoluncher, I can get a download link for the updated package.
But my friend didn't download Hoyoluncher, How does he do the merge after downloading the update package.
就像这一次官方API 出现重大变更，Starwrd 更新不及时的情况下。
Just like this time, there is a major change in the official API, Our Startward is not updated in time.

### Solution or Design

合并功能单独做一个按钮，在startward三个游戏的设置里。
The merge function is a separate button in the settings of the three game interfaces of startward.

**Comment by Eric-Joker** [comment]
#830 
goto my fork action

**Comment by Eric-Joker** [comment]
> > @Eric-Joker deleted the following comment
> > published at 2024-06-20 05:33:42 +00:00
> > updated at 2024-06-20 05:33:42 +00:00
> 
> #830 goto my fork action

我没审题，不好意思（

**Comment by cangerjun** [comment]
> > > @Eric-Joker deleted the following comment
> > > published at 2024-06-20 05:33:42 +00:00
> > > updated at 2024-06-20 05:33:42 +00:00
> > 
> > 
> > #830 goto my fork action
> 
> 我没审题，不好意思（ 理论上你可以将包移动到游戏文件夹下，文件名符合格式时就可以触发解压罢

在我下载你的分支之前，我为我的朋友尝试了，地图更新没有出问题，语音文件更新是在原有的文件上基础更新，如果已有文件是001.xxx(1450 kb)解压的文件是001.xxx.xxx(37kb),需要将这两个文件合并在一起。没并打开游戏是运行不了的

**Comment by cangerjun** [comment]
> > > @Eric-Joker deleted the following comment
> > > published at 2024-06-20 05:33:42 +00:00
> > > updated at 2024-06-20 05:33:42 +00:00
> > 
> > 
> > #830 goto my fork action
> 
> 我没审题，不好意思（ 理论上你可以将包移动到游戏文件夹下，文件名符合格式时就可以激活安装按钮罢

差不多，下载好更新包在游戏文件夹下，在启动器中选择更新包去更新。就是把解压以及后面合并校验的功能单独使用

**Comment by Eric-Joker** [comment]
> 在我下载你的分支之前，我为我的朋友尝试了，地图更新没有出问题，语音文件更新是在原有的文件上基础更新，如果已有文件是001.xxx(1450 kb)解压的文件是001.xxx.xxx(37kb),需要将这两个文件合并在一起。没并打开游戏是运行不了的

我隐约记得语音文件合并是使用第三方程序来着
看readme里可能是这个？https://github.com/sisong/HDiffPatch

**Comment by cangerjun** [comment]
@Eric-Joker 你把预览通道，检查更新映射到你的仓库呀！！！

**Comment by Eric-Joker** [comment]
> @Eric-Joker 你把预览通道，检查更新映射到你的仓库呀！！！

我只是为了pr，不发布标签

**Comment by cangerjun** [comment]
> > @Eric-Joker 你把预览通道，检查更新映射到你的仓库呀！！！
> 
> 我只是为了pr，不发布标签

你更新了我还得重新下载覆盖+删除上个版本的文件

**Comment by cangerjun** [comment]
> > 在我下载你的分支之前，我为我的朋友尝试了，地图更新没有出问题，语音文件更新是在原有的文件上基础更新，如果已有文件是001.xxx(1450 kb)解压的文件是001.xxx.xxx(37kb),需要将这两个文件合并在一起。没并打开游戏是运行不了的
> 
> 我隐约记得语音文件合并是使用第三方程序来着 看readme里可能是这个？https://github.com/sisong/HDiffPatch

这个需要Visual Studio为基础，我根本安装不上这个

**Comment by Eric-Joker** [comment]
> 你更新了我还得重新下载覆盖+删除上个版本的文件

本来也只是作者不上线的临时解决方案（

**Comment by Eric-Joker** [comment]
> 你更新了我还得重新下载覆盖+删除上个版本的文件

哦对，你可以直接覆盖，它会自己删旧版本目录的

**Comment by cangerjun** [comment]
> > 你更新了我还得重新下载覆盖+删除上个版本的文件
> 
> 哦对，你可以直接覆盖，它会自己删旧版本目录的

好吧，这个议题差不多可以结束了，我要开新的议题了
