### ISSUE TITLE
关于适配米哈游启动器 About adapting HoYoPlay

### ISSUE THREAD

**Issue by Scighost** [Scighost/Starward#836]
亲爱的开拓者，很抱歉这么晚才回复相关的问题。这几天本人因为身体不适，没有关注外界的信息，所以没有及时适配米哈游启动器的新变化，给大家带来了不好的体验，对此我深表歉意。适配的工作还需要一段时间，在新版本发布之前，可以使用其他开发者 fork 后修改的版本。感谢你的理解和支持。

<br>

Dear trailblazer, I am sorry for replying to relevant questions so late. Due to my poor health, I have not paid attention to external information in the past few days, so I have not adapted to the new changes of HoYoPlay in time, which has brought a bad experience to everyone. I deeply apologize for this. The adaptation work will take some time. Before the new version is released, you can use the version modified by other developers after forking. Thank you for your understanding and support.

<br>

Scighost
2024-06-20

**Comment by muyuer6** [comment]
谢谢大佬，大佬好好休息。

**Comment by gitaraya** [comment]
好好休息啊，启动器的事情可以先放一边

**Comment by 1molCu** [comment]
大佬好好休息！

**Comment by long45343** [comment]
身体第一
注意身体啊

**Comment by Youwenqwq** [comment]
大佬好好休息qwq调理好健康状态为先~φ(*￣0￣)

**Comment by Sakurashiling** [comment]
感谢大佬，大佬要注意身体健康！

**Comment by jonilchan** [comment]
感谢，好好休息

**Comment by Stelle22108126** [comment]
感谢大佬，大佬注意好好休息

**Comment by oldeightLB** [comment]
感谢，差点提交issue

**Comment by FloatDreamK** [comment]
大佬注意休息，注意身体

**Comment by Jerry-FaGe** [comment]
你不许道歉！

**Comment by wuhai007007** [comment]
注意休息

**Comment by O-mo-i** [comment]
没事大佬，自己先休息好比较重要

**Comment by HuangHB2000** [comment]
谢谢大佬，大佬好好休息！身体是革命的本钱，我们会耐心等待的！

**Comment by g1fts** [comment]
米哈游好像开始检测了，我刚才打开星铁给了不良软件得警告。。。

**Comment by my57575757** [comment]
没必要抱歉,本来就没有义务实时更新的,好好休息
