### ISSUE TITLE
[Feature] 新版被景图与公告位置

### ISSUE THREAD

**Issue by cangerjun** [Scighost/Starward#837]
### Checklist

- [X] I have already read [docs/Tips.md](https://github.com/Scighost/Starward/blob/main/docs/Tips.md), but my feature is not implemented.
- [X] My suggested feature was not mentioned by others, and it is not a duplicate feature.

### Summary

新版被景图与现有公告位置有些冲突遮挡

### Solution or Design

经过对比背景图（1440*2560）公告至少需要向下移动约266像素，因此得知在不改变公告等UI大小情况下，窗口框体需!扩大（18.47222......%≈18.47%）
![image](https://github.com/Scighost/Starward/assets/73055671/c363457e-6589-4830-9a41-632012d089d2)

**Comment by Eric-Joker** [comment]
#830 pr已提相关问题，另外不建议将其他仓库的版本于此仓库建立议题

**Comment by cangerjun** [comment]
> #830 已提相关问题，另外请不要将其他仓库版本的问题于此仓库建立议题

你倒是把你的仓库开通议题功能呀{生气竖中指.jpg)

**Comment by cangerjun** [comment]
> #830 已提相关问题，另外请不要将其他仓库版本的问题于此仓库建立议题

可以直接按120%调整，而且你的项目是从这里分支的，这个的问题都是需要改的。
在这里建立议题你和原作者都是可以看到的。

**Comment by Eric-Joker** [comment]
> 可以直接按120%调整，而且你的项目是从这里分支的，这个的问题都是需要改的。 在这里建立议题你和原作者都是可以看到的。

此仓库最新提交大致修复了这个问题，但是无法使用hoyoplay接口和其他页面（抽卡工具箱等）
