### ISSUE TITLE
由于目标计算机积极拒绝，无法连接。（127.0.0.1:7890）

### ISSUE THREAD

**Issue by 1onelyman** [Scighost/Starward#839]
### Checklist

- [X] I have already read [docs/Tips.md](https://github.com/Scighost/Starward/blob/main/docs/Tips.md), but my question is not solved.
- [X] My question was not mentioned by others, and it is not a duplicate question.

### Description

如题

### Starward Version

0.11.6

### Windows Version

19045.4291

**Comment by Geekmemz** [comment]
clash忘关了

**Comment by 1onelyman** [comment]
> Clash忘关了
我确实关了，不过你一说然后我去看了任务管理器发现有个clash core service，把他结束了就好了，宝了个贝的

**Comment by Youwenqwq** [comment]
> > Clash忘关了
> > 我确实关了，不过你一说然后我去看了任务管理器发现有个clash core service，把他结束了就好了，宝了个贝的

Close一下issue罢qwq
