### ISSUE TITLE
[Feature] 米游社工具箱添加差分宇宙与末日幻影战绩查询

### ISSUE THREAD

**Issue by xiguayo233** [Scighost/Starward#842]
### Checklist

- [X] I have already read [docs/Tips.md](https://github.com/Scighost/Starward/blob/main/docs/Tips.md), but my feature is not implemented.
- [X] My suggested feature was not mentioned by others, and it is not a duplicate feature.

### Summary

如题，虽然不是特别需要这个功能，但是既然有了先前模拟宇宙和逐光拾金的战绩查询功能，这俩顺理成章也应该有吧，不然强迫症犯了）

### Solution or Design

实现起来应该跟先前几个一样，不会很难吧，米游社也是提供这些查询功能的

**Comment by Eric-Joker** [comment]
#840 差分宇宙我还没玩所以我先不搞（
