### ISSUE TITLE
[Feature] 公告遮挡背景图

### ISSUE THREAD

**Issue by oldeightLB** [Scighost/Starward#843]
### Checklist

- [X] I have already read [docs/Tips.md](https://github.com/Scighost/Starward/blob/main/docs/Tips.md), but my feature is not implemented.
- [X] My suggested feature was not mentioned by others, and it is not a duplicate feature.

### Summary

软件版本 0.11.7-dev.1
崩铁的米哈游启动器更新适配后背景图有遮挡问题
<img width="810" alt="image" src="https://github.com/Scighost/Starward/assets/109260128/dcb483f2-3f30-4102-b7fd-8f8e92098c45">
建议调节位置

### Solution or Design

调节公告位置

**Comment by Eric-Joker** [comment]
版本更新日志已提相关问题
