### ISSUE TITLE
[Feature] 希望更改一下服务器切换的体验

### ISSUE THREAD

**Issue by Apkeniqo** [Scighost/Starward#845]
### Checklist

- [X] I have already read [docs/Tips.md](https://github.com/Scighost/Starward/blob/main/docs/Tips.md), but my feature is not implemented.
- [X] My suggested feature was not mentioned by others, and it is not a duplicate feature.

### Summary

现有的服务器切换逻辑有点奇怪，已经在图标上右键切换到想要的服务器，却还得多点几下完成“从原服务器切换到新服务器”这个操作，有点过于繁琐了

### Solution or Design

在游戏图标上右键选择想要的服务器后，点击“开始游戏”后检测当前服务器，若服务器不匹配则自动替换为所选服务器的文件并启动游戏，这样对多服玩家更加友好
希望能被采纳，不胜感谢

**Comment by Eric-Joker** [comment]
切换客户端SDK需要修改外部资源，理应多一步确认

**Comment by Apkeniqo** [comment]
即使如此现在的方式也有些过于繁琐了，可以在切换前多一个弹窗询问是否切换，也更加合适> 切换客户端SDK需要修改外部资源，理应多一步确认

**Comment by Eric-Joker** [comment]
> 即使如此现在的方式也有些过于繁琐了，可以在切换前多一个弹窗询问是否切换，也更加合适> 切换客户端SDK需要修改外部资源，理应多一步确认

好主意，作者现在看起来没时间我这两天找时间p个r（

**Comment by Apkeniqo** [comment]
> > 即使如此现在的方式也有些过于繁琐了，可以在切换前多一个弹窗询问是否切换，也更加合适> 切换客户端SDK需要修改外部资源，理应多一步确认
> 
> 好主意，作者现在看起来没时间我这两天找时间p个r（

感谢🙏

**Comment by Scighost** [comment]
https://github.com/Scighost/Starward/releases/tag/0.12.2-preview.1
