### ISSUE TITLE
文本叙述问题

### ISSUE THREAD

**Issue by yjc20061008** [Scighost/Starward#85]
![image](https://github.com/Scighost/Starward/assets/94227484/82250af1-29c9-429e-8633-75e3b2f59218)
如图，我明明已经改了CDN，但是下面的文字没变

**Comment by Scighost** [comment]
> 应用将从 CloudFlare 下载所需的资源，请确保它可以正常连接。

你指的是这句话中的 `CloudFlare` 吗？
切换的 CDN 只作用于检查更新的过程，需要的文件还是从 CloudFlare 下载。
