### ISSUE TITLE
考虑加入不玩的游戏隐藏功能

### ISSUE THREAD

**Issue by Ahmojin** [Scighost/Starward#850]
### Checklist

- [X] I have already read [docs/Tips.md](https://github.com/Scighost/Starward/blob/main/docs/Tips.md), but my feature is not implemented.
- [X] My suggested feature was not mentioned by others, and it is not a duplicate feature.

### Summary

亲爱的开发者你好：
我玩米家游戏目前只玩崩铁 每次登录的时候看见原和崩三总是感觉有点别扭（只是因为我不玩），所以我在想您能不能开发个功能。可以把原和崩三在上方切换栏中隐藏。
谢谢

### Solution or Design

亲爱的开发者你好：
我玩米家游戏目前只玩崩铁 每次登录的时候看见原和崩三总是感觉有点别扭（只是因为我不玩），所以我在想您能不能开发个功能。可以把原和崩三在上方切换栏中隐藏。
谢谢

**Comment by Eric-Joker** [comment]
最新提交已有相关功能
