### ISSUE TITLE
希望能设置一个关闭更新通知的选项以及开启原神的帧率解锁[Feature] 

### ISSUE THREAD

**Issue by testCool-20777** [Scighost/Starward#854]
### Checklist

- [X] I have already read [docs/Tips.md](https://github.com/Scighost/Starward/blob/main/docs/Tips.md), but my feature is not implemented.
- [X] My suggested feature was not mentioned by others, and it is not a duplicate feature.

### Summary

使用启动器老是弹出更新通知，很烦人，但是没有关闭的渠道。希望在后续版本上加入关闭更新通知的功能，以及希望能在原神的游戏设置里出一个解锁游戏帧率的功能

### Solution or Design

设置关闭更新通知的选项，以及希望像hutao工具箱一样能解锁原神的游戏帧率

**Comment by Eric-Joker** [comment]
[#210](https://github.com/Scighost/Starward/issues/210#issuecomment-1652978871)

**Comment by DuckDeng** [comment]
作者表示过，不会添加原神FPS解锁功能。https://github.com/Scighost/Starward/issues/210#issuecomment-1652978871
通过自定义启动程序来间接实现它

**Comment by Xionghaizi001** [comment]
[胡桃](https://github.com/DGP-Studio/Snap.Hutao)欢迎你（滑稽

**Comment by ERYtrdfgc** [comment]
原神是动作游戏，帧率会影响动作，解锁帧率有被认定为作弊的风险，没有被封可能只是米哈游觉得没必要

**Comment by Scighost** [comment]
没有办法禁止更新通知，但是你可以选择忽略这个版本的更新提醒。

不会加入侵入式的解锁帧率的功能。
