### ISSUE TITLE
此项目是否在gitcode.com上发布？

### ISSUE THREAD

**Issue by Jasper-rm** [Scighost/Starward#855]
### Checklist

- [X] I have already read [docs/Tips.md](https://github.com/Scighost/Starward/blob/main/docs/Tips.md), but my question is not solved.
- [X] My question was not mentioned by others, and it is not a duplicate question.

### Description

![Screenshot_2024-06-26-09-45-31-858_com microsoft emmx-edit](https://github.com/Scighost/Starward/assets/62084844/056d3afa-079f-44c5-9b96-30fa5172f3c6)
作者您好，您是否在除了github之外的其他平台授权发布了本项目？

### Starward Version

None

### Windows Version

None

**Comment by xinyihl** [comment]
实际上是狗屎gitcode自己爬取的

**Comment by Eric-Joker** [comment]
https://github.com/ReChronoRain/HyperCeiler/blob/main/fuck_csdn.txt
emmm

**Comment by Jasper-rm** [comment]
> https://github.com/ReChronoRain/HyperCeiler/blob/main/fuck_csdn.txt emmm

建议作者及时关注gitcode等一系列国内平台的无耻行为

**Comment by Jasper-rm** [comment]
破案了，脑残gitcode搬得，哈哈哈

**Comment by Eric-Joker** [comment]
> 破案了，脑残gitcode搬得，哈哈哈

要想让作者注意到最好别关（
但感觉作者近期一长段时间没啥时间整理issue

**Comment by Jasper-rm** [comment]
> 理

开了

**Comment by Jasper-rm** [comment]
最新进展，gitcode删了

**Comment by devil233-ui** [comment]
> 最新进展，gitcode删了

祝贺~~不过我一直以为是gitee后面越看越不对劲才发现根本不认识这网站~~

**Comment by Jasper-rm** [comment]
> > 最新进展，gitcode删了
> 
> 祝贺~不过我一直以为是gitee后面越看越不对劲才发现根本不认识这网站~

还真是，什么叫Copy, Steal and Pay to Download Network啊（战术后仰）

**Comment by Scighost** [comment]
gitcode.com 上的任何内容与我无关
