### ISSUE TITLE
启动速度慢

### ISSUE THREAD

**Issue by yixiamoyou** [Scighost/Starward#856]
### Checklist

- [X] I have already read [docs/Tips.md](https://github.com/Scighost/Starward/blob/main/docs/Tips.md), but my question is not solved.
- [X] My question was not mentioned by others, and it is not a duplicate question.

### Description

我每次重启电脑后再次启动Starward都会非常缓慢，要等好久才能启动，验证文件完整性也没问题，我并没有动设置里面的任何配置,是我用的是win11还是启动本来就很慢？

### Starward Version

0.11.7-bev.1

### Windows Version

23H2

**Comment by Eric-Joker** [comment]
设备硬件问题和[#810](https://github.com/Scighost/Starward/issues/810#issuecomment-2151299641)
starward算不上轻量，，，我这每次启动必占用一百多MB内存，不知道是哪的问题

**Comment by Xionghaizi001** [comment]
win10 22H2，i5-12450H，从按下回车键到能启动游戏只需要五秒（滑稽
~所以你需要win10~

**Comment by yixiamoyou** [comment]
![屏幕截图 2024-06-27 201152](https://github.com/Scighost/Starward/assets/173890046/c485f8be-f688-4d57-9477-5d28fc8dc4b5)
3060也不算太弱啊，进入还是慢

**Comment by HenryAWE** [comment]
Win11 23H2，CPU i9-14900HX
Starward 版本 0.11.7-dev.1，已校验过文件完整性
一样有这个问题，每次重启电脑之后首次打开程序要非常久。开启过一次之后关闭再开，就能够几乎秒开

**Comment by loading-blip** [comment]
我以前的测试感觉会和网络有点联系，之前的版本能选择cdn，但最近发现选项没了

**Comment by Scighost** [comment]
启动慢这个问题已经发生过很多次了，已有的结论是安全软件拖慢了启动速度。
如果你把对应文件夹加入到白名单应该能解决这个问题，但是我不建议这样做。

**Comment by HenryAWE** [comment]
> 启动慢这个问题已经发生过很多次了，已有的结论是安全软件拖慢了启动速度。 如果你把对应文件夹加入到白名单应该能解决这个问题，但是我不建议这样做。

测试了下，将软件所在的文件夹添加进安全软件白名单能有效缓解启动慢的问题。从原来的要卡上好一会，变成了基本秒开

**Comment by yixiamoyou** [comment]
> 启动慢这个问题已经发生过很多次了，已有的结论是安全软件拖慢了启动速度。 如果你把对应文件夹加入到白名单应该能解决这个问题，但是我不建议这样做。

我做过对照，我把整个文件夹拖进火绒的信任区（白名单），但是还是启动慢。我还卸载过火绒，但是启动速度并无差别

**Comment by long45343** [comment]
同样的问题
重新安装24H2之后我也是启动要等很久加了白名单也不行
trace和之前的issue也没有什么区别

**Comment by long45343** [comment]
> 同样的问题 重新安装24H2之后我也是启动要等很久加了白名单也不行 trace和之前的issue也没有什么区别

但是过了一段时间竟让自己好了
玄学啊！
