### ISSUE TITLE
[Question] 7月2号当日是否会接入绝区零的预下载？

### ISSUE THREAD

**Issue by Kal-tsit63** [Scighost/Starward#858]
### Checklist

- [X] I have already read [docs/Tips.md](https://github.com/Scighost/Starward/blob/main/docs/Tips.md), but my question is not solved.
- [X] My question was not mentioned by others, and it is not a duplicate question.

### Description

如题，想请问一下，2号当天会接入预下载吗？还是说等四号开服。

### Starward Version

0.11.7-dev.1

### Windows Version

19045.4529

**Comment by Eric-Joker** [comment]
作者有时间就会接入，但很明显已经失踪了几天。我fork的仓库简单做了下，不一定能用

**Comment by xuan06zyx** [comment]
> 作者有时间就会接入，但很明显已经失踪了几天。我fork的仓库简单做了下，不一定能用

感谢大佬

**Comment by ShiinaRinne** [comment]
> > 感谢大佬
> 
> 经测试还不能用 在调试 我先吃饭）

https://github.com/Scighost/Starward/issues/861
大佬看看这个

**Comment by Jasper-rm** [comment]
目前来看并不能，作者也没推送更新

**Comment by crrashh1542** [comment]
> 目前来看并不能，作者也没推送更新

作者复活了， 04203b1ee1ed28ab37e4dfa580f66f1cca31556c 中已经加入相关内容，一会儿应该就会发版了
