### ISSUE TITLE
打开程序后会弹出一个cmd框然后才弹出程序

### ISSUE THREAD

**Issue by QiFenQAQ** [Scighost/Starward#86]
RT
![截图20230627160319](https://github.com/Scighost/Starward/assets/137874785/f0e48d10-001b-40f9-9f73-a2d1637703d3)

**Comment by Scighost** [comment]
RT

<img width="122" alt="image" src="https://github.com/Scighost/Starward/assets/61003590/8bd8e65d-4406-40fd-8f82-51bb824d61c5">

**Comment by QiFenQAQ** [comment]
谢谢~
