### ISSUE TITLE
[Feature] 希望加入绝区零的启动

### ISSUE THREAD

**Issue by ChenHunGE** [Scighost/Starward#862]
### Checklist

- [X] I have already read [docs/Tips.md](https://github.com/Scighost/Starward/blob/main/docs/Tips.md), but my feature is not implemented.
- [X] My suggested feature was not mentioned by others, and it is not a duplicate feature.

### Summary

最近绝区零即将上线，希望能够加入相关启动功能

### Solution or Design

就像之前那样加入

**Comment by Kal-tsit63** [comment]
#858

**Comment by ChenHunGE** [comment]
非常感谢:)
