### ISSUE TITLE
[Feature] 能否添加直链复制功能

### ISSUE THREAD

**Issue by f59375543** [Scighost/Starward#863]
### Checklist

- [X] I have already read [docs/Tips.md](https://github.com/Scighost/Starward/blob/main/docs/Tips.md), but my feature is not implemented.
- [X] My suggested feature was not mentioned by others, and it is not a duplicate feature.

### Summary

启动器下载速度不知道为什么总不能跑满速，我获取直链后用第三方下载器可以跑满，但是每次手动抓取直链比较麻烦

### Solution or Design

能否提供一个按钮，可以直接复制下载链接，然后自行选择使用什么工具来下载

**Comment by Nekoler** [comment]
作者在 #142 提到了该功能，大概率不会加入

**Comment by Scighost** [comment]
这个功能在 0.11.7-preview.1 之前是有的，最近几个版本删了，不久以后会再加回来。
