### ISSUE TITLE
[Question] 最新 0.11.7 预览版 1 是否删除了抽卡记录，米游社工具等功能

### ISSUE THREAD

**Issue by T-007KB** [Scighost/Starward#867]
### Checklist

- [X] I have already read [docs/Tips.md](https://github.com/Scighost/Starward/blob/main/docs/Tips.md), but my question is not solved.
- [X] My question was not mentioned by others, and it is not a duplicate question.

### Description

 最新版 0.11.7 预览版 1 是否删除了抽卡记录，米游社工具等功能

### Starward Version

0.11.7 预览版 1

### Windows Version

23H2

**Comment by YiFan04** [comment]
我的也没了 增加个绝区零预下载还能把功能更新没了 要是就是启动我为什么不用官方的？

**Comment by Virace** [comment]
> 我的也没了 增加个绝区零预下载还能把功能更新没了 要是就是启动我为什么不用官方的？

急什么

**Comment by Eric-Joker** [comment]
https://github.com/Scighost/Starward/issues/858#issuecomment-2201611230

**Comment by Rimliya** [comment]
> > 我的也没了 增加个绝区零预下载还能把功能更新没了 要是就是启动我为什么不用官方的？
> 
> 急什么

他说的也没毛病啊 纯粹启动确实不如官方启动器了

**Comment by Eric-Joker** [comment]
> 他说的也没毛病啊 纯粹启动确实不如官方启动器了

别急~作者要么没时间要么还抱恙。功能都没删就是启动页大改后入口UI没做适配

**Comment by Virace** [comment]
> > > 我的也没了 增加个绝区零预下载还能把功能更新没了 要是就是启动我为什么不用官方的？
> > 
> > 
> > 急什么
> 
> 他说的也没毛病啊 纯粹启动确实不如官方启动器了

开源软件，纯靠开发者爱发电，我是比较烦上来没搞清楚问题就对"预览版"程序就直接吐槽的。 你可以不用，有问题也可以像题主一样开issues询问，而不是 还有搭腔的说 什么 "没毛病"。

预览版本身就属于一个不稳定的测试版本，不建议"小白"使用

**Comment by Scighost** [comment]
请看一下 #869

**Comment by LIJY2003** [comment]
> 请看看#869

宝子加油
