### ISSUE TITLE
[Feature] - Add Zenless Zone Zero

### ISSUE THREAD

**Issue by HungNoPro** [Scighost/Starward#868]
### Checklist

- [X] I have already read [docs/Tips.md](https://github.com/Scighost/Starward/blob/main/docs/Tips.md), but my feature is not implemented.
- [X] My suggested feature was not mentioned by others, and it is not a duplicate feature.

### Summary

ZZZ will be release soon and game allowed pre-download

### Solution or Design

.

**Comment by kokoropie** [comment]
Join Preview Release Channel then update

**Comment by HungNoPro** [comment]
> Join Preview Release Channel then update, but u won't like it

Yea, some useful function disappeared

**Comment by Eric-Joker** [comment]
> > Join Preview Release Channel then update, but u won't like it
> 
> Yea, some useful function disappeared

https://github.com/Scighost/Starward/issues/858#issuecomment-2201611230
Help test it? :)

**Comment by Scighost** [comment]
Please see #869
