### ISSUE TITLE
[Bug] 侧栏功能按键消失 The sidebar function buttons disappear

### ISSUE THREAD

**Issue by Scighost** [Scighost/Starward#869]
0.11.7-preview 版本正常的界面应如下图所示。

The normal interface of version 0.11.7-preview should be as shown below.

<img src="https://github.com/Scighost/Starward/assets/61003590/bd502632-b1a9-4bc8-b639-98512fafa280" width="600" />

但是部分设备上因为不知名原因出现了UI整体左移的问题，导致侧栏功能按键消失。

However, due to unknown reasons, the entire UI shifted to the left on some devices, causing the sidebar function buttons to disappear.

<img src="https://github.com/Scighost/Starward/assets/63293483/31a31440-54e0-47b2-ae92-e1b6269aed1c" width="600" />

~~这些功能没有被移除，只是因为显示错误不见了。请碰到这个问题的玩家重新下载完整压缩包。如果问题仍然存在，请在此 issue 下回复：~~

- ~~Windows 版本信息~~
- ~~屏幕分辨率~~
- ~~系统缩放率~~

~~These features have not been removed, they are just missing due to display errors. Players who encounter this problem should re-download the full zip file. If the problem persists, please reply to this issue:~~

- ~~Windows version information~~
- ~~Screen resolution~~
- ~~System scaling~~

~~**另外，请显示正常的玩家给此 issue 点赞👍，碰到了问题的玩家点踩👎。**~~

~~**In addition, please like👍 this issue if you have no problem, and dislike👎 it if you encounter the problem.**~~

**问题原因已查明，请等待稍后更新的版本。**

**The cause of the problem has been found, please wait for the updated version later.**

**Comment by Rimliya** [comment]
![image](https://github.com/Scighost/Starward/assets/48489813/b56c069d-8a0e-4846-b5aa-4d914245fa19)
重新下载完整包没有变化，包括完全删除重装
Windows版本26100.863
分辨率2560*1440
系统缩放175%

**Comment by KazeMai** [comment]
- Windows 版本信息：Windows 10 22H2
- 屏幕分辨率：2560 x 1440
- 系统缩放率：100%

**Comment by IMxingyus** [comment]
- Windows 版本信息：
版本	Windows 11 专业版
版本号	23H2
操作系统版本	22631.3737
体验	Windows Feature Experience Pack 1000.22700.1009.0

- 屏幕分辨率：3440x1440

- 系统缩放率：100%

**Comment by long45343** [comment]
![image](https://github.com/Scighost/Starward/assets/51872789/fe744460-8603-41f4-a78b-0f7289b06000)
重新安装后仍然无法解决
Windows版本：Windows11 23H2 22631.3810
分辨率1920✖1080
缩放率100%

**Comment by streesobrs** [comment]
![QQ_1719919892660](https://github.com/Scighost/Starward/assets/101034124/9dc1ad15-6759-4b49-8091-f71bdb6151e2)

重新下载压缩包后还是有这个问题
Windows 版本信息：Windows 11 家庭中文版 23H2 22635.3858
屏幕分辨率：2560 x 1440
系统缩放：150%

**Comment by HY-pt** [comment]
![QQ截图20240702192641](https://github.com/Scighost/Starward/assets/173921258/68277b2d-19fa-4691-af0f-11274ba6da0b)

- Windows 版本信息：Windows 11 专业版 23H2 | 22631.3810
- 屏幕分辨率：1920*1080
- 缩放比例：100%

**Comment by jinyiwei2012** [comment]
重新安装后仍然无法解决
Windows版本：Windows 10 专业版 22H2 19045.4412
分辨率1920✖1080
缩放率100%

**Comment by swrtx** [comment]
侧边栏倒是没问题，各种功能也可以用，就是抽卡记录一点就闪退，是bug不？

**Comment by Scighost** [comment]
@swrtx 请重新创建一个 issue，然后上传崩溃日志

**Comment by swrtx** [comment]
> @swrtx请重新创建一个问题，然后上传崩溃日志

虽然我也想帮上忙，但是很抱歉，我是第一次使用这个网站不知道如何导出崩溃日志和创建issue

**Comment by wtcpython** [comment]
![image](https://github.com/Scighost/Starward/assets/119155053/192c2ed2-8ad0-464c-ad9a-2eb6d7a6f70b)

Windows 版本：22631.3810
屏幕分辨率：2560x1600
系统缩放率：150%

**Comment by HungNoPro** [comment]
![image](https://github.com/Scighost/Starward/assets/87181735/7d318190-74ed-4d52-8b9b-581dcc166727)
Windows 11 22631.3810
Resolution 1920 x 1080
Scale 125%

**Comment by balh55y** [comment]
![image](https://github.com/Scighost/Starward/assets/85926883/f039ec70-ecbb-470d-8cc7-3b747786726d)
Windows 11 22635.3858
Resolution 2560 x 1440
Scale 125%

**Comment by RedChuak** [comment]
版本	Windows 10 专业版
版本号	22H2
安装日期	‎2023/‎10/‎5
操作系统内部版本	19045.4529
体验	Windows Feature Experience Pack 1000.19058.1000.0

屏幕分辨率：2560x1440

系统缩放率：125%

**Comment by WhiteArnold** [comment]
版本	Windows 11 专业版
版本号	23H2
安装日期	‎2024/‎2/‎23 ‎星期五
操作系统版本	22631.3737
体验	Windows Feature Experience Pack 1000.22700.1009.0
屏幕分辨率：1980×1080
系统缩放率：125%

**Comment by WhiteArnold** [comment]
版本 Windows 11 专业版 23H2
操作系统版本 22631.3737
屏幕分辨率：1980×1080
系统缩放率：125%
