### ISSUE TITLE
[Feature] 关于国区绝区零和国际服绝区零的区服转换

### ISSUE THREAD

**Issue by ghhccghk** [Scighost/Starward#870]
### Checklist

- [X] I have already read [docs/Tips.md](https://github.com/Scighost/Starward/blob/main/docs/Tips.md), but my feature is not implemented.
- [X] My suggested feature was not mentioned by others, and it is not a duplicate feature.

### Summary

我同时下载了国区绝区零和国际服绝区零，并在更新完成后，对他们的程序和数据使用WinMerge进行比较生成下面的比较报告，希望能对其他开发者能有帮助

### Solution or Design

[22.txt](https://github.com/user-attachments/files/16067202/22.txt)

完整的报告 带cn是国服

**Comment by cangerjun** [comment]
+1 国际打开是国服

**Comment by Scighost** [comment]
谢谢你的建议，但是在实现 #861 或绝区零支持修复文件之前，这个功能很难做到。
