### ISSUE TITLE
[Bug] 点抽卡记录就闪退

### ISSUE THREAD

**Issue by Eric-Joker** [Scighost/Starward#871]
### Checklist

- [X] My issue was not mentioned by others, and it is not a duplicate issue.

### Description

RT

### Reproduction Steps

RT

### Starward Version

0.11.7.pre.1

### Windows Version

22631.3810

### Log

```shell
Microsoft.UI.Xaml.LayoutCycleException: 无法找到与此错误代码关联的文本。
Layout cycle detected.  Layout could not complete.
```

**Comment by Scighost** [comment]
@swrtx 请上传 `%UserProfile%\AppData\Local\Starward\crash` 文件夹里的文件

**Comment by Scighost** [comment]
闪退的问题是必定出现还是有时出现？

**Comment by swrtx** [comment]
[crash_20240702_201837.txt](https://github.com/user-attachments/files/16067965/crash_20240702_201837.txt)
闪退的问题是必定出现 @Scighost 是这样吗？

**Comment by Eric-Joker** [comment]
呕吼，报错还不一样了）

**Comment by balh55y** [comment]
![image](https://github.com/Scighost/Starward/assets/85926883/05170941-cd72-4cc8-bfd4-936bf4e773a8)
同样,星铁点击抽卡记录就会闪退,两个内容都是这个
软件版本是action中标题为修复侧边栏按钮消失的那个
app-build.c494eb0

**Comment by Scighost** [comment]
LayoutCycleException 是很经典的问题，暂时找不到解决的办法，InvalidCastException 给出的信息太少了。
@Eric-Joker 把 WinAppSDK 回退到 1.4 呢？

**Comment by Eric-Joker** [comment]
我尝试一下

**Comment by Eric-Joker** [comment]
问题依旧

**Comment by Scighost** [comment]
> 问题依旧

我能想到的可以影响到抽卡页面的更改只有窗口大小，但是我不知道为什么修改窗口大小后可能会造成崩溃。

**Comment by Eric-Joker** [comment]
> LayoutCycleException

比如父元素要所有子元素的大小，然后子元素要父元素的大小？（

**Comment by ChenJL66666** [comment]
这么快就有人反映了

**Comment by Henryxjh** [comment]
我发现点原神的抽卡记录会显示左边的错误信息，点星铁的抽卡记录会显示右边的错误信息
![image](https://github.com/Scighost/Starward/assets/58125754/e3340054-1369-4986-8ca1-314067bff8ab)

**Comment by ReeYoung** [comment]
已在0.11.7pre2版本中出现bug：在原神或者崩坏：星穹铁道的抽卡记录页面100%出现闪退。日志内容如下：

===
System.InvalidCastException: 不支持此接口

不支持此接口
===

有概率出现：

===
Microsoft.UI.Xaml.LayoutCycleException: 无法找到与此错误代码关联的文本。

Layout cycle detected.  Layout could not complete.
===

观测到在进入次页面时首先没有正常的亚克力效果，之后立即卡死崩溃，可能与显示效果有关。请注意修复，感谢作者。

**Comment by balh55y** [comment]
![image](https://github.com/Scighost/Starward/assets/85926883/cf4306f5-0a9c-4f21-aa98-56374262f43f)
我将缩放调整为100%后可以打开抽卡记录,并且在抽卡记录打开的情况下调整为125%,软件会先卡主后闪退

**Comment by Henryxjh** [comment]
> 我发现点原神的抽卡记录会显示左边的错误信息，点星铁的抽卡记录会显示右边的错误信息 ![image](https://private-user-images.githubusercontent.com/58125754/345046616-e3340054-1369-4986-8ca1-314067bff8ab.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk5MjcyODUsIm5iZiI6MTcxOTkyNjk4NSwicGF0aCI6Ii81ODEyNTc1NC8zNDUwNDY2MTYtZTMzNDAwNTQtMTM2OS00OTg2LThjYTEtMzE0MDY3YmZmOGFiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzAyVDEzMjk0NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWFmMDZkNGI4OTQyNjBiYzdmNWVhZjcxYjRlMTc0OWMzNDk1ZjhkNzkyY2U0NDNiODY5YWYxNDQ1MzY1MWEzNTkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.jjekph_T3osFDUt2YPDh9Bun-kPsrheOFedTUjLLBzw)

也不是，我现在是两种错误信息交替出现

**Comment by Scighost** [comment]
@balh55y 复现成功，非 50% 倍数的系统缩放率会导致崩溃

**Comment by Eric-Joker** [comment]
找到了个https://github.com/CommunityToolkit/Windows/issues/359不知道有没有关

**Comment by balh55y** [comment]
![image](https://github.com/Scighost/Starward/assets/85926883/0f794604-200e-496e-b58f-c9495f2323c6)
在兼容模式中这么设置可以不闪退,但界面会有些糊

**Comment by RedChuak** [comment]
我这显示器 2k屏 设置125% 比较合适 100%太小 150%太大 遭不住

**Comment by charlotte00100** [comment]
> 闪退的问题是必定出现还是有时出现？

我也是这个问题

**Comment by RedChuak** [comment]
![微信图片_20240702214455](https://github.com/Scighost/Starward/assets/76555967/228ce9d6-e235-405b-a9a7-78bdd389fccd)
有意思

**Comment by Eric-Joker** [comment]
经测试，将CommunityToolkit.WinUI.Control.Segmented替换成最新预发行版解决了该问题 @Scighost
