### ISSUE TITLE
[Question] 公告栏的滚动大图点击无法跳转

### ISSUE THREAD

**Issue by ERYtrdfgc** [Scighost/Starward#876]
### Checklist

- [X] I have already read [docs/Tips.md](https://github.com/Scighost/Starward/blob/main/docs/Tips.md), but my question is not solved.
- [X] My question was not mentioned by others, and it is not a duplicate question.

### Description

但下方文字公告可以正常跳转，不知道是不是我自己的问题

### Starward Version

0.11.7-previwe.2

### Windows Version

22635.3858

**Comment by Phoenix1996** [comment]
我也有这样的问题
