### ISSUE TITLE
[Feature] 希望原神和云原神能并列出现

### ISSUE THREAD

**Issue by qmzmdqs** [Scighost/Starward#877]
### Checklist

- [X] I have already read [docs/Tips.md](https://github.com/Scighost/Starward/blob/main/docs/Tips.md), but my feature is not implemented.
- [X] My suggested feature was not mentioned by others, and it is not a duplicate feature.

### Summary

首先我个人，电脑就同时装了原神和云原神时，现在的并不方便。

其次，比如帮别人上号做每日，赶时间时，就可以一个本体，一个云，联机做每日和打本

### Solution or Design

将云原神单独显示出来

**Comment by Eric-Joker** [comment]
启用两者然后固定

**Comment by Small-Ku** [comment]
目前 preview 版本
![圖片](https://github.com/Scighost/Starward/assets/16464896/dc5a4456-e426-417f-8e56-b8da5168ec17)
