### ISSUE TITLE
感觉切换游戏多点一次没有必要

### ISSUE THREAD

**Issue by Ailynhm** [Scighost/Starward#882]
### Checklist

- [X] I have already read [docs/Tips.md](https://github.com/Scighost/Starward/blob/main/docs/Tips.md), but my feature is not implemented.
- [X] My suggested feature was not mentioned by others, and it is not a duplicate feature.

### Summary

可以添加需要的游戏挺好的，就是换游戏要多一步

### Solution or Design

1

**Comment by Eric-Joker** [comment]
可以固定游戏选择器

**Comment by kasimir82** [comment]
> 可以固定游戏选择器

感觉并不需要把钉子也固定在界面上, 设置里面给个选项就行了, 之前版本不也是设置么

**Comment by Eric-Joker** [comment]
雀食
