### ISSUE TITLE
[Question] 最新starward版本如何切换服务器？

### ISSUE THREAD

**Issue by link-fgfgui** [Scighost/Starward#883]
### Checklist

- [X] I have already read [docs/Tips.md](https://github.com/Scighost/Starward/blob/main/docs/Tips.md), but my question is not solved.
- [X] My question was not mentioned by others, and it is not a duplicate question.

### Description

Tips.md中提到的倒三角不存在
![image](https://github.com/Scighost/Starward/assets/96362154/3c2fe7f5-b183-41cc-a85b-d4758c990718)

### Starward Version

0.11.7 Preview 4

### Windows Version

22631.3737

**Comment by Eric-Joker** [comment]
看更新日志，暂时移除了该功能

**Comment by linlord** [comment]
可以通过一键修复切换，但是终归是临时的举措，太费时间了

**Comment by Scighost** [comment]
https://github.com/Scighost/Starward/releases/tag/0.12.2-preview.1
