### ISSUE TITLE
[Bug] 无法关闭游戏公告

### ISSUE THREAD

**Issue by shelbyy54** [Scighost/Starward#886]
### Checklist

- [ ] My issue was not mentioned by others, and it is not a duplicate issue.

### Description

在设置内关闭“显示游戏公告“后，切换选择游戏或者重新启动程序都会导致游戏公告重新出现

### Reproduction Steps

1.随意打开一个游戏的启动界面
2.点击右侧的设置按钮
3.将”显示游戏公告“设置为关闭
4.切换其他的游戏启动界面  或  重新启动程序
5.游戏公告重新出现

### Expected Behavior

将”显示游戏公告“设置为关闭后无论进行什么操作都不应该显示游戏公告

### Starward Version

0.11.7-preview.4

### Windows Version

22631.3810

### Log

```shell
无
```

**Comment by DreamToffee** [comment]
![Uploading image.png…]()
还有不显示的

**Comment by DreamToffee** [comment]
![Uploading 4547ab0f-7ad0-4165-930a-e616e5bcb242.png…]()、

**Comment by DreamToffee** [comment]
我好像发不了图片，不过原神的公告我这边开了但是不显示
