### ISSUE TITLE
希望祈愿记录导入支持excel文件

### ISSUE THREAD

**Issue by WHeathcliff** [Scighost/Starward#89]
之前用其他插件导出的祈愿记录均为Excel文件，但starward的导入只支持json格式，有点遗憾，希望可以增加对Excel文件的支持，这样就可以不用其他的插件了

**Comment by Scighost** [comment]
确实很遗憾，但是 Excel 不是一个适合交换数据的文件格式。比如一个单元格中的数据可能是文本，可能是数字，数字还分各种不同的格式，甚至还会丢失精度。支持 Excel 导入需要处理各种各样的问题，我选择放弃。
