### ISSUE TITLE
[Feature] 启动游戏时的区服与实际游戏不同

### ISSUE THREAD

**Issue by DreamToffee** [Scighost/Starward#896]
### Checklist

- [X] I have already read [docs/Tips.md](https://github.com/Scighost/Starward/blob/main/docs/Tips.md), but my feature is not implemented.
- [X] My suggested feature was not mentioned by others, and it is not a duplicate feature.

### Summary

游戏的实际区服，与启动器中显示的会存在不一致的情况，比如启动器显示的是Bilibili服务器，但实际运行登录的确实官方服务器。能否在启动器打开时检测一下呢

### Solution or Design

=

**Comment by DreamToffee** [comment]
不知道算不算小众的问题，遇到好几次了，手动切换可以解决，但需要先从Bilibili切换到其他服务器，再切换回去

**Comment by Eric-Joker** [comment]
预览版看起来打算重做相关逻辑，导致这部分功能bug多以至于无法使用

**Comment by Eric-Joker** [comment]
> 不知道算不算小众的问题，遇到好几次了，手动切换可以解决，但需要先从Bilibili切换到其他服务器，再切换回去

中途有用官方启动器？

**Comment by DreamToffee** [comment]
> 导致这部分功能bug多以至于无

很早就有这个问题了，不过之前我没在意，刚好看见都在说切换服务器功能没了，感觉可以顺带处理一下。使用过。最新的官方启动器会自动切换游戏为官服，所以我觉得星空也可以试试，或者检测一下，提醒使用者切换为星空记录的服务器

**Comment by Eric-Joker** [comment]
感觉，，要检测的话肯定得把国际服带上，但相关逻辑可能耗时影响体验。而且不用官启应该难以出现前提条件吧。

**Comment by DreamToffee** [comment]
> 感觉，，要检测的话肯定得把国际服带上，但相关逻辑可能耗时影响体验。而且不用官启应该难以出现前提条件吧。

头一次选择游戏区服时，也会有这个问题，不会去检测是否为选择的服务器。不过官启确实很少会有人同时使用，如何确实麻烦那就算了，我记得国际服的配置文件好像挺多的

**Comment by Eric-Joker** [comment]
> 头一次选择游戏区服时，也会有这个问题，不会去检测是否为选择的服务器。不过官启确实很少会有人同时使用，如何确实麻烦那就算了，我记得国际服的配置文件好像挺多的

之前版本中会做config.ini的检查，而且Starward积极维护该文件。应该不存在这个问题罢

**Comment by DreamToffee** [comment]
> > 头一次选择游戏区服时，也会有这个问题，不会去检测是否为选择的服务器。不过官启确实很少会有人同时使用，如何确实麻烦那就算了，我记得国际服的配置文件好像挺多的
> 
> 之前版本中会做config.ini的检查，而且Starward积极维护该文件。应该不存在这个问题罢

没，我之前启动器显示官服，启动后登录的b服，就这样玩了挺久，没检测出来选择的服务器不对，首次打开启动器会让你选择游戏的区服，就那个没检测

**Comment by Scighost** [comment]
更新后的软件不会在检查区服相关的信息，如果你在某一区服的启动页面设置了游戏文件夹，那么就会显示此游戏可用。如果游戏区服错误，请使用一键修复。
