### ISSUE TITLE
[Feature] 移除对原神【中国官服云游戏】的支持

### ISSUE THREAD

**Issue by mumingluan** [Scighost/Starward#897]
### Checklist

- [X] I have already read [docs/Tips.md](https://github.com/Scighost/Starward/blob/main/docs/Tips.md), but my feature is not implemented.
- [X] My suggested feature was not mentioned by others, and it is not a duplicate feature.

### Summary

请求原因：
1. 米哈游正在大力推广网页版云游戏（原神、崩铁，且同时支持PC与移动端）。崩铁没有PC云游戏客户端，取而代之的是完善的网页版云游戏。
2. 实际上，原神【国际服云游戏】早已发布。其官网为 https://cloudgenshin.hoyoverse.com 
3. 由 Starward 启动【中国官服云游戏】客户端时，仍需手动执行账号登录、分辨率调整、游戏启动等操作。

请求内容：
移除对”启动原神【中国官服云游戏】客户端“的支持。

### Solution or Design

移除对”启动原神【中国官服云游戏】客户端“的支持。

**Comment by Eric-Joker** [comment]
该功能加入貌似只是为了“游戏时长记录”¿

**Comment by streesobrs** [comment]
你再怎么推网页云，他桌面端的就摆在那，触非他什么时候下架

**Comment by devil233-ui** [comment]
> 1. 在大力推广网页版云游戏（原神、崩铁，且同时支持PC与移动端）。崩铁没有PC云游戏客户端，取而代之

想问下目前是不是所有游戏的计时功能都失效了……我的已经两周没动静了，当前版本最新（11.7pv）

**Comment by Yoshinoyin** [comment]
> > 该功能加入貌似只是为了“游戏时长记录”¿
> 
> 想问下目前是不是所有游戏的计时功能都失效了……我的已经两周没动静了，当前版本最新（11.7pv）

如何修改游戏计时时长？重装了系统由于把启动器文件放桌面了，只能重新下载

**Comment by Eric-Joker** [comment]
> 想问下目前是不是所有游戏的计时功能都失效了……我的已经两周没动静了，当前版本最新（11.7pv）

不知道诶，最近没咋用电脑打游戏

**Comment by Eric-Joker** [comment]
> 如何修改游戏计时时长？重装了系统由于把启动器文件放桌面了，只能重新下载

你需要学会如何更改sqlite数据库

**Comment by 111inhistory** [comment]
> 如何修改游戏计时时长？重装了系统由于把启动器文件放桌面了，只能重新下载

先打开Starward的注册URL链接协议的功能，然后在浏览器/资源管理器里按照对应的格式输入要增加的时间，回车打开Starward，理论上来说就可以同步了，胡桃工具箱也是用这个方式实现游戏时长与Starward同步的(不过它不需要通过浏览器)
最大的问题是我手头上没电脑，只能题主发挥探索精神了，文档我也忘了在哪点开了

**Comment by Yoshinoyin** [comment]
> > 如何修改游戏计时时长？重装了系统由于把启动器文件放桌面了，只能重新下载
> 
> 先打开Starward的注册URL链接协议的功能，然后在浏览器/资源管理器里按照对应的格式输入要增加的时间，回车打开Starward，理论上来说就可以同步了，胡桃工具箱也是用这个方式实现游戏时长与Starward同步的(不过它不需要通过浏览器) 最大的问题是我手头上没电脑，只能题主发挥探索精神了，文档我也忘了在哪点开了

感谢回复，目前还没有找到与URL链接协议相关的使用文档

**Comment by Scighost** [comment]
有统计时长的需求，不会移除，谢谢。

**Comment by gongfuture** [comment]
> > > 如何修改游戏计时时长？重装了系统由于把启动器文件放桌面了，只能重新下载
> > 
> > 
> > 先打开Starward的注册URL链接协议的功能，然后在浏览器/资源管理器里按照对应的格式输入要增加的时间，回车打开Starward，理论上来说就可以同步了，胡桃工具箱也是用这个方式实现游戏时长与Starward同步的(不过它不需要通过浏览器) 最大的问题是我手头上没电脑，只能题主发挥探索精神了，文档我也忘了在哪点开了
> 
> 感谢回复，目前还没有找到与URL链接协议相关的使用文档

https://github.com/Scighost/Starward/blob/main/docs/UrlProtocol.md

**Comment by Yoshinoyin** [comment]
> > > > 如何修改游戏计时时长？重装了系统由于把启动器文件放桌面了，只能重新下载
> > > 
> > > 
> > > 先打开Starward的注册URL链接协议的功能，然后在浏览器/资源管理器里按照对应的格式输入要增加的时间，回车打开Starward，理论上来说就可以同步了，胡桃工具箱也是用这个方式实现游戏时长与Starward同步的(不过它不需要通过浏览器) 最大的问题是我手头上没电脑，只能题主发挥探索精神了，文档我也忘了在哪点开了
> > 
> > 
> > 感谢回复，目前还没有找到与URL链接协议相关的使用文档
> 
> https://github.com/Scighost/Starward/blob/main/docs/UrlProtocol.md

感谢回复，已经看了文档 和时间相关的示例为 starward://playtime/{game_biz}
尝试在浏览器输入 starward://playtime/Honkai3rd 后无反应，“按照对应的格式输入要增加的时间” 目前没有找到格式相关的文档

**Comment by gongfuture** [comment]
> > > > > 如何修改游戏计时时长？重装了系统由于把启动器文件放桌面了，只能重新下载
> > > > 
> > > > 
> > > > 先打开Starward的注册URL链接协议的功能，然后在浏览器/资源管理器里按照对应的格式输入要增加的时间，回车打开Starward，理论上来说就可以同步了，胡桃工具箱也是用这个方式实现游戏时长与Starward同步的(不过它不需要通过浏览器) 最大的问题是我手头上没电脑，只能题主发挥探索精神了，文档我也忘了在哪点开了
> > > 
> > > 
> > > 感谢回复，目前还没有找到与URL链接协议相关的使用文档
> > 
> > https://github.com/Scighost/Starward/blob/main/docs/UrlProtocol.md
> 
> 感谢回复，已经看了文档 和时间相关的示例为 starward://playtime/{game_biz}
> 尝试在浏览器输入 starward://playtime/Honkai3rd 后无反应，“按照对应的格式输入要增加的时间” 目前没有找到格式相关的文档

https://github.com/Scighost/Starward/blob/main/src/Starward/Services/UrlProtocolService.cs#L103-L115
实现应该是这一段，你看一下

**Comment by yutouyes** [comment]
> 崩铁没有PC云游戏客户端
似乎是有的
![image](https://github.com/user-attachments/assets/d6fa4e7b-787e-47fb-8e06-2a35294c8aa3)
我用网页云的时候遇到的一个缺点是esc键无法退出二级界面（地图/手机等），不知道是网页限制还是我不会操作。

**Comment by yutouyes** [comment]
> > @yutouyes deleted the following comment
> > published at 2024-08-01 16:31:40 +00:00
> > updated at 2024-08-01 16:31:40 +00:00
> 
> > 崩铁没有PC云游戏客户端
> > 似乎是有的
> > ![image](https://private-user-images.githubusercontent.com/17039457/354305174-d6fa4e7b-787e-47fb-8e06-2a35294c8aa3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI1MzA2OTIsIm5iZiI6MTcyMjUzMDM5MiwicGF0aCI6Ii8xNzAzOTQ1Ny8zNTQzMDUxNzQtZDZmYTRlN2ItNzg3ZS00N2ZiLThlMDYtMmEzNTI5NGM4YWEzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODAxVDE2Mzk1MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTUzNTg3ZTZkYjA4ZjE3NjM0NmExZDAwOGMwOGQ5ZjRlODExNTgyYWM0NTExMmJiYzRlNTQ3NWU1NWI3MzZjNGImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.pkFcKeuFi3i5men9vOYcwoyB_7f68FVw5-BS96zudZk)
> > 我用网页云的时候遇到的一个缺点是esc键无法退出二级界面（地图/手机等），不知道是网页限制还是我不会操作。

搞错了抱歉，没看到敬请期待QwQ
不过客户端版云原神的esc确实和本地原神的功能是完全一样的，网页版就有点不方便
