### ISSUE TITLE
[Question] 软件打不开了

### ISSUE THREAD

**Issue by sssfjfj** [Scighost/Starward#898]
### Checklist

- [X] I have already read [docs/Tips.md](https://github.com/Scighost/Starward/blob/main/docs/Tips.md), but my question is not solved.
- [X] My question was not mentioned by others, and it is not a duplicate question.

### Description

我的软件每次打开提示更新，点击更新都没有反应，但是之后就会自动更新好。在今天的更新没有反应之后卡住之后，我像以前一样关闭软件重启软件但是软件没有响应多次尝试都没有反应

### Starward Version

最新版本

### Windows Version

22631.3593

**Comment by sssfjfj** [comment]
我现在是怕删除软件重新下载丢失之前的祈愿记录

**Comment by nd002723** [comment]
保留config目录别的直接全重下覆盖就行

**Comment by Eric-Joker** [comment]
第一次使用Starward会有引导页，让你选择数据目录，该目录保存一个数据库用于存储这些内容。在很久之前的版本数据目录默认是Starward安装目录，不是很久之前改成了C:\Users\用户名\AppData\Local\Starward
