### ISSUE TITLE
[Bug] 游戏设置中，即使将“显示游戏公告关闭”，在切换到别的界面后再切换回游戏启动器首页，还是会显示出游戏公告

### ISSUE THREAD

**Issue by ophixation** [Scighost/Starward#902]
### Checklist

- [X] My issue was not mentioned by others, and it is not a duplicate issue.

### Description

![image](https://github.com/Scighost/Starward/assets/107614970/cd2b8625-7a58-4629-a516-bf0204798df7)
关闭游戏公告显示
![image](https://github.com/Scighost/Starward/assets/107614970/48ab4ec5-e04f-4ff1-af5e-24d3603b04d4)
切换到其他界面
![image](https://github.com/Scighost/Starward/assets/107614970/fbb68a4e-d317-437a-85d9-b16e94e64c41)
再次qiehuan切换回首页发现公告回来了
![image](https://github.com/Scighost/Starward/assets/107614970/b4c44b77-4fd7-40c9-9094-d435138fe709)
打开设置发现设置没改变

![image](https://github.com/Scighost/Starward/assets/107614970/5e260fce-d12e-414c-85b6-785d7b7ff665)
启动器版本如上

### Reproduction Steps

同上

### Starward Version

0.11.4preview.4

### Windows Version

22631.3737

### Log

```shell
[22:21:36.780] [INFO] 
Welcome to Starward v0.11.7-preview.4
System: Microsoft Windows NT 10.0.22631.0
Command Line: E:\Starward\app-0.11.7-preview.4\Starward.dll playtime --biz hk4e_cn --pid 29608

[22:21:36.819] [INFO] Starward.Services.DatabaseService
Database path is 'E:\Starward'

[22:21:36.857] [INFO] Starward.Services.DatabaseService
Database version is 8, target version is 8.
```

**Comment by Eric-Joker** [comment]
#887 #886 #881 
所以打钩前你先看看字？

**Comment by ophixation** [comment]
github用的不熟练，只翻了open的issue没看到还有closed的issue
我的我的
