### ISSUE TITLE
[Feature] 关于邦布池子id和国际服公告接口

### ISSUE THREAD

**Issue by syxs233** [Scighost/Starward#906]
### Checklist

- [X] I have already read [docs/Tips.md](https://github.com/Scighost/Starward/blob/main/docs/Tips.md), but my feature is not implemented.
- [X] My suggested feature was not mentioned by others, and it is not a duplicate feature.

### Summary

--

### Solution or Design

1.邦布池子的gacha_id为ac32d8ed4032a973fd7c48a94ccd9ed065293f，我只有亚服的账号，其他区服的暂时不清楚

2.国际服游戏内游戏公告的接口为（get）https://sg-announcement-api.hoyoverse.com/common/nap_global/announcement/api/getAnnList，其中参数如图
![游戏公告](https://github.com/Scighost/Starward/assets/174759266/64121bee-17b2-4020-a754-94ac6905d037)

3.国际服游戏内活动公告的接口为（get）https://sg-announcement-static.hoyoverse.com/common/nap_global/announcement/api/getAnnContent，其中参数如图，另外，t不是必需参数
![活动公告](https://github.com/Scighost/Starward/assets/174759266/fc14dc40-77ba-4005-8f52-fd56850bf42a)

**Comment by sunfkny** [comment]
[调频概率公示一览](https://zzz.mihoyo.com/news/public) 这里可以看到部分信息

https://operation-webstatic.mihoyo.com/gacha_info/nap/prod_gf_cn/gacha/list.json
https://operation-webstatic.mihoyo.com/gacha_info/nap/prod_gf_cn/ac32d8ed4032a973fd7c48a94ccd9ed065293f/zh-cn.json
国服邦布池子的 `gacha_id` 也是 `ac32d8ed4032a973fd7c48a94ccd9ed065293f`

此外还可以看到将来的 `独家频段2` 、`音擎频段2`、`武器邦布限定池`
https://webstatic.mihoyo.com/admin/mi18n/nap_cn/m20230424hy34uw5h4w/m20230424hy34uw5h4w-zh-cn.json 
```
    "gacha_tab_1001_text": "常驻频段",
    "gacha_tab_2001_text": "独家频段",
    "gacha_tab_2002_text": "独家频段2",
    "gacha_tab_3001_text": "音擎频段",
    "gacha_tab_3002_text": "音擎频段2",
    "gacha_tab_4001_text": "邦布限定池",
    "gacha_tab_5001_text": "邦布频段",
    "gacha_tab_9001_text": "武器邦布限定池",
```

**Comment by Scighost** [comment]
感谢你们提供的信息
