### ISSUE TITLE
绝区零调频记录

### ISSUE THREAD

**Issue by fan6q6** [Scighost/Starward#910]
### Checklist

- [X] I have already read [docs/Tips.md](https://github.com/Scighost/Starward/blob/main/docs/Tips.md), but my question is not solved.
- [X] My question was not mentioned by others, and it is not a duplicate question.

### Description

邦布的记录未显示

### Starward Version

0.11.7 预览版 6

### Windows Version

22631.3737

**Comment by BaiMaollk** [comment]
加一，点了更新（全部）也没有邦布池的记录

**Comment by BaiMaollk** [comment]
> 加一，点了更新（全部）也没有邦布池的记录

版本0.11.7p6

**Comment by HyBoxwood** [comment]
提供一张图片，直接更新或者删除所有记录更新be like：
![QQ_1720242510353](https://github.com/Scighost/Starward/assets/87700780/1a368b05-67b3-4b56-aea6-c14e43c73018)

**Comment by kokoropie** [comment]
same, even the text "Bangboo Channel" got error
![1](https://github.com/Scighost/Starward/assets/37841855/40e9071a-a048-4921-b4c2-7b374d81157e)
![2](https://github.com/Scighost/Starward/assets/37841855/2f7e261e-611d-4e6b-88c6-b4d22c003f87)
![3](https://github.com/Scighost/Starward/assets/37841855/8ecb7843-65b8-4ce5-9dd0-1ed74a4c5892)

**Comment by Scighost** [comment]
改了，但没完全改完。
我还没抽邦布池，请帮忙确认一下，邦布池的 `gacha_type` 是不是 `5`

**Comment by kokoropie** [comment]
on global:
```
authkey_ver: 1
sign_type: 2
auth_appid: webview_gacha
win_mode: fullscreen
gacha_id: 
timestamp: 1719565751
init_log_gacha_type: 5001
init_log_gacha_base_type: 5
ui_layout: 
button_mode: default
plat_type: 3
authkey: 
lang: vi
region: prod_gf_jp
game_biz: nap_global
page: 1
size: 5
gacha_type: 5001
real_gacha_type: 5
```

**Comment by dase1353** [comment]
Global _Asia
```
{
    "retcode": 0,
    "message": "OK",
    "data": {
        "page": "1",
        "size": "5",
        "list": [
            {
                "uid": "1300019617",
                "gacha_id": "0",
                "gacha_type": "5",
                "item_id": "12013",
                "count": "1",
                "time": "2024-07-06 15:32:50",
                "name": "「恆等式」-本格",
                "lang": "zh-tw",
                "item_type": "音擎",
                "rank_type": "2",
                "id": "1720249200001973817"
            }
       ]
   }
}
```
