### ISSUE TITLE
[Question] 绝区零无法统计抽卡数

### ISSUE THREAD

**Issue by kaminagakouko** [Scighost/Starward#911]
### Checklist

- [X] I have already read [docs/Tips.md](https://github.com/Scighost/Starward/blob/main/docs/Tips.md), but my question is not solved.
- [X] My question was not mentioned by others, and it is not a duplicate question.

### Description

![image](https://github.com/Scighost/Starward/assets/127492305/2597a151-b891-4400-a1d3-d05f59d82728)
我的绝区零没有统计抽卡记录的按钮

### Starward Version

0.11.7-preview.4

### Windows Version

22631.3737

**Comment by kokoropie** [comment]
update to version 0.11.7-preview.6
