### ISSUE TITLE
[Feature] 关于绝区零抽卡记录图标的建议

### ISSUE THREAD

**Issue by RedTeaco** [Scighost/Starward#913]
### Checklist

- [X] I have already read [docs/Tips.md](https://github.com/Scighost/Starward/blob/main/docs/Tips.md), but my feature is not implemented.
- [X] My suggested feature was not mentioned by others, and it is not a duplicate feature.

### Summary

更新记录中提到因为养成模拟器没有上线所以没有图标，但是在米游社有官方wiki，所以通过官方wiki的api来获取图标。

### Solution or Design

抓取到的api如下：[绝区零图标api](https://api-takumi-static.mihoyo.com/common/blackboard/zzz_wiki/v1/home/content/list?app_sn=zzz_wiki&channel_id=2)
虽然格式上可能和养成模拟器获取的数据有些许差别，但是其中也是有icon链接的

**Comment by traficLucio** [comment]
可以请问一下这个API是在哪里抓取的吗，是有APP抓包工具还是APK逆向解析出来的？
另外，米游社更新了绝区零角色以及音擎的数据，这些有计划支持吗？

**Comment by Scighost** [comment]
谢谢你的建议，但是官方wiki的api中的物品id和抽卡记录api中的对应不上，所以不能够拿来用。
