### ISSUE TITLE
[Question] 邦布记录没有显示

### ISSUE THREAD

**Issue by Gpan666** [Scighost/Starward#915]
### Checklist

- [X] I have already read [docs/Tips.md](https://github.com/Scighost/Starward/blob/main/docs/Tips.md), but my question is not solved.
- [X] My question was not mentioned by others, and it is not a duplicate question.

### Description

![image](https://github.com/Scighost/Starward/assets/41224727/5ef8f2ae-2ac5-43bf-bb27-475d018ef9a6)
已经操作过更新全部也就没有，删除记录重新获取还是，目前是最新版

### Starward Version

0.11.7-preview6

### Windows Version

22631.3737

**Comment by GUODAMING3124** [comment]
https://github.com/Scighost/Starward/releases/tag/0.11.7-preview.6
因为米游社还没有类似于养成计算的功能，ZZZ 的调频记录中不会有图片。

**Comment by f59375543** [comment]
> https://github.com/Scighost/Starward/releases/tag/0.11.7-preview.6 因为米游社还没有类似于养成计算的功能，ZZZ 的调频记录中不会有图片。

点击更新(全部)后还是没有更新邦布池

**Comment by NuRest-nuuusu** [comment]
同
