### ISSUE TITLE
[Feature] 建议将双击游戏图标能返回游戏主页的功能还回来

### ISSUE THREAD

**Issue by wen20919** [Scighost/Starward#917]
### Checklist

- [X] I have already read [docs/Tips.md](https://github.com/Scighost/Starward/blob/main/docs/Tips.md), but my feature is not implemented.
- [X] My suggested feature was not mentioned by others, and it is not a duplicate feature.

### Summary

建议将双击游戏图标能返回游戏主页的功能还回来

### Solution or Design

No response

**Comment by Small-Ku** [comment]
#878 Duplicated
