### ISSUE TITLE
自己做了一个icon，分享一下

### ISSUE THREAD

**Issue by asdf3500** [Scighost/Starward#92]
https://imgse.com/i/pCwI14U
图床不支持icon，需要自己转换一下
[![logo](https://s1.ax1x.com/2023/06/29/pCwI14U.md.png)](https://imgse.com/i/pCwI14U)

**Comment by KNBLG** [comment]
我也简单搞了一个
![image](https://github.com/Scighost/Starward/assets/63439312/ff871301-7ef7-41be-9706-a51e90d25e9e)
纯白透明背景
![image](https://github.com/Scighost/Starward/assets/63439312/3f8d8c8c-31e0-4fe1-8516-782a73d296f9)

链接: https://pan.baidu.com/s/1ebpxoBFuI5L00uh80WAV_A?pwd=7yqa 提取码: 7yqa

**Comment by Psychiwave** [comment]
可以问一下如何改图标嘛。我用resource hacker更改了图标 本体确实变了，但是任务栏还是没变，请问有什么办法嘛（还是说你们都是自己打包的）

**Comment by Eric-Joker** [comment]
https://github.com/Scighost/Starward/issues/43#issuecomment-1571315753

**Comment by xinyihl** [comment]
> 

> 可以问一下如何改图标嘛。我用resource hacker更改了图标 本体确实变了，但是任务栏还是没变，请问有什么办法嘛（还是说你们都是自己打包的）

缓存问题重启一下explorer就可以了

**Comment by Condor2436** [comment]
> 可以问一下如何改图标嘛。我用resource hacker更改了图标 本体确实变了，但是任务栏还是没变，请问有什么办法嘛（还是说你们都是自己打包的）

老哥改好了吗？我也是改了图标但是任务栏没变，重启explorer也没变化

**Comment by xinyihl** [comment]
任务栏的得改这个，外面那个只是启动器
![{D130F905-691D-48b6-8238-306F403E0548}](https://github.com/Scighost/Starward/assets/75861358/03920536-b5bc-44b2-b2c8-14ec9b13b422)

**Comment by Condor2436** [comment]
> > 
> 
> > > 可以问一下如何改图标嘛。我用resource hacker更改了图标 本体确实变了，但是任务栏还是没变，请问有什么办法嘛（还是说你们都是自己打包的）
> > 
> > 
> > 老哥改好了吗？我也是改了图标但是任务栏没变，重启explorer也没变化
> 
> 任务栏的得改这个，外面那个只是启动器 ![{D130F905-691D-48b6-8238-306F403E0548}](https://user-images.githubusercontent.com/75861358/256563025-03920536-b5bc-44b2-b2c8-14ec9b13b422.png)

ok,改好了，谢谢老哥

**Comment by Condor2436** [comment]
> > 
> 
> > > 可以问一下如何改图标嘛。我用resource hacker更改了图标 本体确实变了，但是任务栏还是没变，请问有什么办法嘛（还是说你们都是自己打包的）
> > 
> > 
> > 老哥改好了吗？我也是改了图标但是任务栏没变，重启explorer也没变化
> 
> 任务栏的得改这个，外面那个只是启动器 ![{D130F905-691D-48b6-8238-306F403E0548}](https://user-images.githubusercontent.com/75861358/256563025-03920536-b5bc-44b2-b2c8-14ec9b13b422.png)

改好了，谢谢老哥

**Comment by True-ME-Elysia** [comment]
> > 
> 
> > > 可以问一下如何改图标嘛。我用resource hacker更改了图标 本体确实变了，但是任务栏还是没变，请问有什么办法嘛（还是说你们都是自己打包的）
> > 
> > 
> > 老哥改好了吗？我也是改了图标但是任务栏没变，重启explorer也没变化
> 
> 任务栏的得改这个，外面那个只是启动器 ![{D130F905-691D-48b6-8238-306F403E0548}](https://user-images.githubusercontent.com/75861358/256563025-03920536-b5bc-44b2-b2c8-14ec9b13b422.png)

老哥，可以请教一下怎么使用resource hacker更改图标吗，我打开starward.exe文件后，没有找到icon。
![0](https://github.com/Scighost/Starward/assets/119117470/8073fba9-8d3f-45ae-a0ea-534c3e6bd762)

**Comment by xinyihl** [comment]
> > > 
> > 
> > 
> > > > 可以问一下如何改图标嘛。我用resource hacker更改了图标 本体确实变了，但是任务栏还是没变，请问有什么办法嘛（还是说你们都是自己打包的）
> > > 
> > > 
> > > 老哥改好了吗？我也是改了图标但是任务栏没变，重启explorer也没变化
> > 
> > 
> > 任务栏的得改这个，外面那个只是启动器 ![{D130F905-691D-48b6-8238-306F403E0548}](https://user-images.githubusercontent.com/75861358/256563025-03920536-b5bc-44b2-b2c8-14ec9b13b422.png)
> 
> 老哥，可以请教一下怎么使用resource hacker更改图标吗，我打开starward.exe文件后，没有找到icon。 ![0](https://user-images.githubusercontent.com/119117470/256802078-8073fba9-8d3f-45ae-a0ea-534c3e6bd762.png)

1.第一种方法
![{AB4C1825-36CD-4bdb-B385-E7DEBD620A27}](https://github.com/Scighost/Starward/assets/75861358/e5ede0af-fb03-4d8e-a8da-a191216190df)
文件应该放resource hacker安装目录
![{08DF854F-8AEB-4eca-8677-3D1C44F7DA6A}](https://github.com/Scighost/Starward/assets/75861358/a7b9d256-31f2-4ee1-8f89-e6755ee87e79)
2.或者直接导入一个.ico文件应该也可以
![{ED284F60-F7FC-4aaf-BE78-28CEEEB36422}](https://github.com/Scighost/Starward/assets/75861358/32c8fccf-8246-4860-b953-613ef12352cd)

**Comment by True-ME-Elysia** [comment]
> > > > 
> > > 
> > > 
> > > > > 可以问一下如何改图标嘛。我用resource hacker更改了图标 本体确实变了，但是任务栏还是没变，请问有什么办法嘛（还是说你们都是自己打包的）
> > > > 
> > > > 
> > > > 老哥改好了吗？我也是改了图标但是任务栏没变，重启explorer也没变化
> > > 
> > > 
> > > 任务栏的得改这个，外面那个只是启动器 ![{D130F905-691D-48b6-8238-306F403E0548}](https://user-images.githubusercontent.com/75861358/256563025-03920536-b5bc-44b2-b2c8-14ec9b13b422.png)
> > 
> > 
> > 老哥，可以请教一下怎么使用resource hacker更改图标吗，我打开starward.exe文件后，没有找到icon。 ![0](https://user-images.githubusercontent.com/119117470/256802078-8073fba9-8d3f-45ae-a0ea-534c3e6bd762.png)
> 
> 1.第一种方法 ![{AB4C1825-36CD-4bdb-B385-E7DEBD620A27}](https://user-images.githubusercontent.com/75861358/256803412-e5ede0af-fb03-4d8e-a8da-a191216190df.png) 文件应该放resource hacker安装目录 ![{08DF854F-8AEB-4eca-8677-3D1C44F7DA6A}](https://user-images.githubusercontent.com/75861358/256803525-a7b9d256-31f2-4ee1-8f89-e6755ee87e79.png) 2.或者直接导入一个.ico文件应该也可以 ![{ED284F60-F7FC-4aaf-BE78-28CEEEB36422}](https://user-images.githubusercontent.com/75861358/256803888-32c8fccf-8246-4860-b953-613ef12352cd.png)

老哥，感谢你，我的超人♥
