### ISSUE TITLE
[Feature] 希望能增加一个领前瞻直播原石的页面

### ISSUE THREAD

**Issue by SilveryX** [Scighost/Starward#920]
### Checklist

- [X] I have already read [docs/Tips.md](https://github.com/Scighost/Starward/blob/main/docs/Tips.md), but my feature is not implemented.
- [X] My suggested feature was not mentioned by others, and it is not a duplicate feature.

### Summary

希望能增加一个领前瞻直播原石的页面，类似下图这样的，能搞提醒就更好了，前天忘记领原石，感觉好像错过一个亿 -_-
<img width="623" alt="image" src="https://github.com/Scighost/Starward/assets/67977075/578840de-55dd-4457-b585-f1f1629308fd">

### Solution or Design

No

**Comment by CreeperAWA** [comment]
国服没有这个东西(
不知道官方有没有前瞻兑换码的API

**Comment by Eric-Joker** [comment]
不会加入需要长期维护的功能

**Comment by Scighost** [comment]
只有国际服有这样的领取网页，中国官服没有这个东西

**Comment by Eric-Joker** [comment]
> 只有国际服有这样的领取网页，中国官服没有这个东西

https://github.com/UIGF-org/mihoyo-api-collect/issues/73 等哪天有前瞻了记得关注一手？（）

**Comment by Lyb001-Nahida** [comment]
> ### Checklist
> * [x]  I have already read [docs/Tips.md](https://github.com/Scighost/Starward/blob/main/docs/Tips.md), but my feature is not implemented.[x]  My suggested feature was not mentioned by others, and it is not a duplicate feature.
> 
> ### Summary
> 希望能增加一个领前瞻直播原石的页面，类似下图这样的，能搞提醒就更好了，前天忘记领原石，感觉好像错过一个亿 -_- <img alt="image" width="623" src="https://private-user-images.githubusercontent.com/67977075/346312461-578840de-55dd-4457-b585-f1f1629308fd.png?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NzU5ODYwNjksIm5iZiI6MTc3NTk4NTc2OSwicGF0aCI6Ii82Nzk3NzA3NS8zNDYzMTI0NjEtNTc4ODQwZGUtNTVkZC00NDU3LWI1ODUtZjFmMTYyOTMwOGZkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNjA0MTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjYwNDEyVDA5MjI0OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQ5ODZhODYxNzNiODQyMGM2MGE1ZjkwNjAzOTRiYjhlNjk5MGRiOGNlZDc4YmU5OTZiMWYxM2Y4Yzk2NGIwOGImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JnJlc3BvbnNlLWNvbnRlbnQtdHlwZT1pbWFnZSUyRnBuZyJ9.gz4X7rCpdH7GmL7tVn732RN6pxDnqF6eAopOS0VnKoc">
> 
> ### Solution or Design
> No

https://github.com/Lyb001-Nahida/miyoushe_prospect_code_get/tree/main?_wv=1
