### ISSUE TITLE
[Bug] 邦布记录不全

### ISSUE THREAD

**Issue by tiknuv** [Scighost/Starward#921]
### Checklist

- [X] My issue was not mentioned by others, and it is not a duplicate issue.

### Description

邦布的抽取记录只能读取到一部分
![image](https://github.com/Scighost/Starward/assets/101472982/97ccab73-9537-433f-b687-4bc64203ccc9)
17页，应该是81条抽取记录，但软件只能读到最新的30条记录
![image](https://github.com/Scighost/Starward/assets/101472982/8494c333-8e7e-4787-8963-ded08c996825)

### Reproduction Steps

![image](https://github.com/Scighost/Starward/assets/101472982/fd5b4e01-414d-4904-ac6f-0be4d7f1439e)

### Starward Version

0.11.7-preview.7

### Windows Version

Windows 11 22631.3737

### Log

```shell
不会
```

**Comment by Paxton-PKJ** [comment]
我一开始也是，点了更新全部记录之后就全了
![image](https://github.com/Scighost/Starward/assets/62497679/3205d5fe-3ff9-4ebc-bbc2-55d0467f5228)

**Comment by Scighost** [comment]
请重新点击 `更新(全部)` 按键
