### ISSUE TITLE
[Question] 未选择“加入预览版更新渠道“仍然提示预览版更新可用？

### ISSUE THREAD

**Issue by DGCK81LNN** [Scighost/Starward#929]
### Checklist

- [X] I have already read [docs/Tips.md](https://github.com/Scighost/Starward/blob/main/docs/Tips.md), but my question is not solved.
- [X] My question was not mentioned by others, and it is not a duplicate question.

### Description

我十分依赖 Starward 切换原神国服/国际服，目前最新的预览版似乎不支持该功能，但我从未加入预览版更新渠道，仍然在 0.11.7-preview.4 发布后收到了更新提示，这是否是预期行为？

![image](https://github.com/Scighost/Starward/assets/54282183/95e6c6e6-9805-48b1-abf1-de4defad0236)
![image](https://github.com/Scighost/Starward/assets/54282183/36478332-c299-48ec-aa04-c0ed9605eae0)

### Starward Version

0.11.6

### Windows Version

-

**Comment by Scighost** [comment]
是正常的预期行为，有时会向所有稳定版通道推送预览版的内容。

**Comment by DGCK81LNN** [comment]
感谢解答。
