### ISSUE TITLE
可以新增一个云原神的启动项吗？

### ISSUE THREAD

**Issue by ben10044** [Scighost/Starward#93]
顺便加个云原神的启动项呗，大佬~（1摩拉可以吗.jpg）

**Comment by gxmandppx** [comment]
我记得一直有啊

**Comment by Scighost** [comment]
<img width="98" alt="image" src="https://github.com/Scighost/Starward/assets/61003590/a98f2191-7353-492b-9059-65abc9285dc7">

这个是云原神
