### ISSUE TITLE
[Feature] 在全新安装一个游戏时，自动在选择的下载目录下新建一个文件夹用来存放游戏文件

### ISSUE THREAD

**Issue by Stelle22108126** [Scighost/Starward#930]
### Checklist

- [X] I have already read [docs/Tips.md](https://github.com/Scighost/Starward/blob/main/docs/Tips.md), but my feature is not implemented.
- [X] My suggested feature was not mentioned by others, and it is not a duplicate feature.

### Summary

我发现我在使用starward下载绝区零时，选择我的常用游戏存储文件夹，如果此时进行安装，会直接在该目录下写入游戏的文件，而不是新建一个文件夹来存储写入的文件。
这样可能导致全新安装其他游戏时，会覆盖原本某些名字一样的文件，同时在某些卸载软件，可能会将该目录下的其他文件一起删除
![image](https://github.com/Scighost/Starward/assets/143889343/64000b4e-db57-43b4-a602-29e6d7758f50)

### Solution or Design

在全新安装一个游戏时，自动在选择的下载目录下新建一个对应游戏名称的文件夹用来存放游戏文件

**Comment by Scighost** [comment]
安装前会提醒你选择一个空文件夹

![image](https://github.com/Scighost/Starward/assets/61003590/c92272df-9802-4f8a-8965-f151ffd41ba8)
