### ISSUE TITLE
[Question] 更新到最新版后绝区零板块依旧没有调频记录功能

### ISSUE THREAD

**Issue by kirikamizuki** [Scighost/Starward#932]
### Checklist

- [X] I have already read [docs/Tips.md](https://github.com/Scighost/Starward/blob/main/docs/Tips.md), but my question is not solved.
- [X] My question was not mentioned by others, and it is not a duplicate question.

### Description

更新到最新版后绝区零板块依旧没有调频记录功能

### Starward Version

0.11.7 Preview 7

### Windows Version

22631.3737

**Comment by kirikamizuki** [comment]
![Uploading 屏幕截图 2024-07-11 194257.png…]()

**Comment by Eric-Joker** [comment]
你甚至连个截图都不愿意传完

**Comment by ymdm2** [comment]
> 你甚至连个截图都不愿意传完
我也是这样:
![image](https://github.com/user-attachments/assets/8898d11b-dd46-4934-9af0-4b9582108ac1)
