### ISSUE TITLE
[Feature] Add Spanish Language Support

### ISSUE THREAD

**Issue by AnotherNN** [Scighost/Starward#935]
### Checklist

- [X] I have already read [docs/Tips.md](https://github.com/Scighost/Starward/blob/main/docs/Tips.md), but my feature is not implemented.
- [x] My suggested feature was not mentioned by others, and it is not a duplicate feature.

### Summary

I would like to offer my help on this, as a native Spanish speaker and translator.

### Solution or Design

Add Spanish in Crowdin options.

**Comment by Scighost** [comment]
I have added Spanish in Crowndin. Thanks for your contribution.
