### ISSUE TITLE
[Question] 如何设置开机启动

### ISSUE THREAD

**Issue by Initializist** [Scighost/Starward#938]
### Checklist

- [x] I have already read [docs/Tips.md](https://github.com/Scighost/Starward/blob/main/docs/Tips.md), but my question is not solved.
- [X] My question was not mentioned by others, and it is not a duplicate question.

### Description

我尝试按照windows教程把starward添加到shell:startup，但是开机仍然不能自启动。

### Starward Version

0.11.7

### Windows Version

19045.4651

**Comment by jhll1124** [comment]
> 可以尝试在 `C:\Users\你的用户名\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\Startup` 文件夹内创建Starward.exe的快捷方式 来开机自启

这个路径就是shell:startup

**Comment by AkatsukiZhang** [comment]
> > 可以尝试在 `C:\Users\你的用户名\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\Startup` 文件夹内创建Starward.exe的快捷方式 来开机自启
> 
> 这个路径就是shell:startup

_(:з」∠)_原来是一样的啊，老旧知识得到了更新(x

**Comment by AkatsukiZhang** [comment]
> 可以尝试在 `C:\Users\你的用户名\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\Startup` 文件夹内创建Starward.exe的快捷方式 来开机自启

我用这个方法顺利开机启动了，任务管理器里的 启动应用 页也看到自启程序里有Starward.exe了。
不是知道你是不是有什么安全软件把它禁用了。

还有一个方法就是创建计划任务
![image](https://github.com/user-attachments/assets/622b7038-f052-42d3-a224-f5734c6b2485)
但相对比较麻烦一点 :(

**Comment by Initializist** [comment]
> > 可以尝试在 `C:\Users\你的用户名\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\Startup` 文件夹内创建Starward.exe的快捷方式 来开机自启
> 
> 我用这个方法顺利开机启动了，任务管理器里的 启动应用 页也看到自启程序里有Starward.exe了。 不是知道你是不是有什么安全软件把它禁用了。
> 
> 还有一个方法就是创建计划任务 ![image](https://private-user-images.githubusercontent.com/22972499/349363338-622b7038-f052-42d3-a224-f5734c6b2485.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjExOTk3MzIsIm5iZiI6MTcyMTE5OTQzMiwicGF0aCI6Ii8yMjk3MjQ5OS8zNDkzNjMzMzgtNjIyYjcwMzgtZjA1Mi00MmQzLWEyMjQtZjU3MzRjNmIyNDg1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzE3VDA2NTcxMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTJlZTVjZDRhMDI0YjZiY2Q5NjkyODY2Yjc0MTBhZGE3MGIyYTI4NWUwZWI0OGYxZGE0MzMxNzJmNDk3OTQ5YWMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.XVyJojjIxI6f5r_MfWR7av-QZ6eF2WJwjhxX6wIq6y4) 但相对比较麻烦一点 :(

非常感谢！
