### ISSUE TITLE
【建议】在原神中增添与崩坏 星穹铁道类似的画面调整选项

### ISSUE THREAD

**Issue by MangoGong** [Scighost/Starward#94]
- 在原神中增添与崩坏 星穹铁道类似的画面调整选项。
- 帧率这一栏建议添加更多选项（如72、102、144、196等），或允许使用者自行输入帧率数值。
- 在游戏截图相册中打开图片时，默认使用系统默认图片查看器打开，或增添该功能的调整选项。
- 游戏时间每分钟自动刷新。
以上仅为本人个人意见和建议，希望可以让这个项目更加完善易用，感谢作者付出。

**Comment by Scighost** [comment]
感谢你的建议，下面逐条回复：

- 原神在注册表中存储设置的模型很复杂，[Collapse 用了2000多行代码才支持了这个功能](https://github.com/neon-nyan/Collapse/pull/183)，而且原神不存在星铁那样修改帧率后无法编辑图形设置的问题，所以这个需求不是必需的。
- 星铁的帧率只有 `30`、`60`、`120` 这三个值有效，如果设置为其他数值，进入游戏后都是60帧。
- 有一个打开文件夹按键就够了
- 记录游戏时间使用的是一个后台进程，如果有需要你可以手动刷新。
