### ISSUE TITLE
[Question] 下載速限

### ISSUE THREAD

**Issue by Jack-Chen-tw** [Scighost/Starward#942]
### Checklist

- [X] I have already read [docs/Tips.md](https://github.com/Scighost/Starward/blob/main/docs/Tips.md), but my question is not solved.
- [X] My question was not mentioned by others, and it is not a duplicate question.

### Description

有與官方啟動器一樣的下載速限設置嗎? 附圖為HoyoPlay的設定
![image](https://github.com/user-attachments/assets/10fba18d-bc74-48cc-9ec2-569b6ab7ce3b)

### Starward Version

0.11.7

### Windows Version

22631.3880

**Comment by Eric-Joker** [comment]
duplicate #739 #736 #735 #547 #417 #272 
歡迎pr
