### ISSUE TITLE
[Feature] 请求添加绝区零的自定义分辨率等功能

### ISSUE THREAD

**Issue by HyBoxwood** [Scighost/Starward#947]
### Checklist

- [X] I have already read [docs/Tips.md](https://github.com/Scighost/Starward/blob/main/docs/Tips.md), but my feature is not implemented.
- [X] My suggested feature was not mentioned by others, and it is not a duplicate feature.

### Summary

如同原神/崩铁一样的“游戏设置”一栏的功能

### Solution or Design

![QQ_1720914809679](https://github.com/user-attachments/assets/5ffaff3a-ad60-4be2-965c-5c76e7f51faa)

**Comment by gongfuture** [comment]
在`HKEY_CURRENT_USER\SOFTWARE\miHoYo\绝区零`下有看到宽高和是否全屏的当前值和默认值

**Comment by DR-lin-eng** [comment]
用处不大了，zzz已经官方支持了无限帧率

**Comment by gongfuture** [comment]
> 用处不大了，zzz已经官方支持了无限帧率

左侧的宽高调节还是有用的，至少我还在用(

**Comment by DR-lin-eng** [comment]
> > 用处不大了，zzz已经官方支持了无限帧率
> 
> 左侧的宽高调节还是有用的，至少我还在用(

该不会是特殊比例的屏幕吧，

**Comment by DR-lin-eng** [comment]
> > 用处不大了，zzz已经官方支持了无限帧率
> 
> 左侧的宽高调节还是有用的，至少我还在用(

可调分辨率的作用

**Comment by HyBoxwood** [comment]
> > @DR-lin-eng deleted the following comment
> > published at 2024-07-15 15:38:38 +00:00
> > updated at 2024-07-15 15:38:38 +00:00
> 
> > > 用处不大了，zzz已经官方支持了无限帧率
> > 
> > 
> > 左侧的宽高调节还是有用的，至少我还在用(
> 
> 该不会是特殊比例的屏幕吧，

是的，有想用宽屏的需求，我知道可用的最宽宽高比是43:18。

**Comment by gongfuture** [comment]
> 我有在尝试写这个功能，但是完全读懂代码还要一段时间 顺便哪位知道除国服，其他服务器的注册表地址的

https://github.com/gongfuture/Starward/tree/dev
按钮显示了，修改分辨率和全屏也写了逻辑，但是点击按钮不显示游戏设置界面不知道怎么解决

**Comment by gongfuture** [comment]
> > 我有在尝试写这个功能，但是完全读懂代码还要一段时间 顺便哪位知道除国服，其他服务器的注册表地址的
> 
> https://github.com/gongfuture/Starward/tree/dev 按钮显示了，修改分辨率和全屏也写了逻辑，但是点击按钮不显示游戏设置界面不知道怎么解决

写完了基础功能，就是不知道有没有bug（） #961

**Comment by LBGrandjack** [comment]
> 我有在尝试写这个功能，但是完全读懂代码还要一段时间 顺便哪位知道除国服，其他服务器的注册表地址的

\HKEY_CURRENT_USER\SOFTWARE\miHoYo\ZenlessZoneZero

**Comment by gongfuture** [comment]
> > 我有在尝试写这个功能，但是完全读懂代码还要一段时间 顺便哪位知道除国服，其他服务器的注册表地址的
> 
> 國際服的位置 国际服的位置 \HKEY_CURRENT_USER\SOFTWARE\miHoYo\ZenlessZoneZero

好的谢谢，现在好像就差b服不知道了
