### ISSUE TITLE
【建议】可否把UAC干掉？现在每次启动游戏都弹个UAC的框

### ISSUE THREAD

**Issue by lijian12345** [Scighost/Starward#95]
之前用过一个类似的工具：https://github.com/XIU2/UACWhitelistTool

**Comment by Scighost** [comment]
UAC 不可避免，这是操作系统权限管理的必要措施，但是你可以把 Starward 加入到你提到的工具的白名单中。

**Comment by lijian12345** [comment]
我看现在程序逻辑是定位到游戏文件夹，然后去查找StarRail.exe这样的程序。用白名单工具生成的只是一个快捷方式，似乎Starward没有办法直接运行某个快捷方式吧

**Comment by Scighost** [comment]
如果 Starward 有管理员权限，启动游戏的时候就不会有 UAC 弹窗。

**Comment by lijian12345** [comment]
> 如果 Starward 有管理员权限，启动游戏的时候就不会有 UAC 弹窗。

懂了，谢谢
