### ISSUE TITLE
[Question] Starward 0.11.7p7无法通过内置更新至0.12.0

### ISSUE THREAD

**Issue by MJSummer** [Scighost/Starward#953]
### Checklist

- [X] I have already read [docs/Tips.md](https://github.com/Scighost/Starward/blob/main/docs/Tips.md), but my question is not solved.
- [X] My question was not mentioned by others, and it is not a duplicate question.

### Description

如题，无论开魔法上网与否，内置更新的进度条均为0。在浏览器中能正常访问github。

### Starward Version

0.11.7 preview 7

### Windows Version

19045.3930

**Comment by nd002723** [comment]
等进度条显示出更新大小再点更新别那么急

**Comment by SSB-ARFCN** [comment]
手動將ZIP更新檔複製到遊戲安裝資料夾內可以正常更新

**Comment by MJSummer** [comment]
用手动覆盖的方式更新了 此issue结束
