### ISSUE TITLE
Made a HoyoVerse-like client icon and logo.

### ISSUE THREAD

**Issue by Vithur** [Scighost/Starward#96]
Click here to download ico：
[ICON.zip](https://github.com/Scighost/Starward/files/11911219/ICON.zip)

![Starward](https://github.com/Scighost/Starward/assets/138168095/f79e7cd9-8a6d-443d-a092-93d76661535b)

Enjoy.

**Comment by phucho0237** [comment]
look nice

**Comment by Scighost** [comment]
wow, it looks great!

**Comment by Eric-Joker** [comment]
I like it! Waiting for the successful bid. lol
