### ISSUE TITLE
[Question] 星穹铁道更改分辨率无法生效

### ISSUE THREAD

**Issue by ff2004** [Scighost/Starward#962]
### Checklist

- [X] I have already read [docs/Tips.md](https://github.com/Scighost/Starward/blob/main/docs/Tips.md), but my question is not solved.
- [X] My question was not mentioned by others, and it is not a duplicate question.

### Description

笔记本混合GPU模式下，星穹铁道只有2560x1600全屏，我使用启动器设置2560x1440窗口，启动游戏后会变成1920x1200窗口。
是游戏强制修改，还是启动器兼容性问题？
原神使用自定义分辨率是能生效的。
![QQ20240718-205249](https://github.com/user-attachments/assets/d9d464d8-ab74-4e01-a3fd-5549dfae57e3)

### Starward Version

0.12.0

### Windows Version

Windows 11 23H2 22631.3880

**Comment by gongfuture** [comment]
不能复现
我也是2560*1600的笔记本，启动器设置2560*1440可以正常窗口化打开崩铁
是使用的自定义分辨率吗？有无log文件，log存放于`C:\Users\用户名\AppData\Local\Starward\log`~应该~
![image](https://github.com/user-attachments/assets/8632f`0db-580b-4ea7-8981-32a056eeb5d5)

**Comment by gongfuture** [comment]
是使用`-screen-width 2560 -screen-height 1440 -screen-fullscreen 0`参数的时候不生效吗

**Comment by ff2004** [comment]
> 是使用参数的时候不生效吗`-screen-width 2560 -screen-height 1440 -screen-fullscreen 0`

使用启动器的分辨率设置，和使用参数，都是不生效

**Comment by Scighost** [comment]
https://github.com/Scighost/Starward/issues/489#issuecomment-1817450847
