### ISSUE TITLE
[Feature] 建议增加网络错误自动重试恢复下载功能

### ISSUE THREAD

**Issue by AnonymousUser443** [Scighost/Starward#963]
### Checklist

- [X] I have already read [docs/Tips.md](https://github.com/Scighost/Starward/blob/main/docs/Tips.md), but my feature is not implemented.
- [X] My suggested feature was not mentioned by others, and it is not a duplicate feature.

### Summary

![BTQN$DN0 1ZF_5%76(8B1KO](https://github.com/user-attachments/assets/fb16ed50-dea0-4eb6-98b7-7411079a7af5)
如图，本人笔记本电脑用户。每次电脑自动切换WiFi网络，就会打断下载，每次都要手动Retry，真的很烦。

### Solution or Design

同上。

**Comment by AnonymousUser443** [comment]
![image](https://github.com/user-attachments/assets/662fbde7-9e3f-4a6f-8136-154d41bc8482)

**Comment by Eric-Joker** [comment]
duplicate #547 #545
