### ISSUE TITLE
unityplayer.dll error ZZZ

### ISSUE THREAD

**Issue by blackreaper2131** [Scighost/Starward#965]
### Checklist

- [X] I have already read [docs/Tips.md](https://github.com/Scighost/Starward/blob/main/docs/Tips.md), but my question is not solved.
- [X] My question was not mentioned by others, and it is not a duplicate question.

### Description

![Captura de tela 2024-07-18 162840](https://github.com/user-attachments/assets/69520da0-7177-4846-a74a-781722fd5a94)

### Starward Version

0.12.0

### Windows Version

22631.2861

**Comment by HuangHB2000** [comment]
星穹铁道也遇到了类似情况

**Comment by prpjzz** [comment]
![Uploading image.png…]()
Try repair game.

**Comment by prpjzz** [comment]
Try repair game.
![image](https://github.com/user-attachments/assets/414b3243-2c16-4c5a-80ed-aae912e87617)
