### ISSUE TITLE
[Feature] 星穹铁道米游社工具箱记录活动回顾

### ISSUE THREAD

**Issue by tiyamikatto** [Scighost/Starward#970]
### Checklist

- [X] I have already read [docs/Tips.md](https://github.com/Scighost/Starward/blob/main/docs/Tips.md), but my feature is not implemented.
- [X] My suggested feature was not mentioned by others, and it is not a duplicate feature.

### Summary

米游社的工具箱里2.5版本后活动回顾功能将下线，是否可以增加一个新功能将当前的数据保存下来。
（主要是自己截图也不知道怎么存档...）

### Solution or Design

考虑到不同的活动数据类型都不同，可能需要对每一个活动单独设计存储数据的方法。
在选择刷新的时候，对目前米游社工具箱中的“战绩”部分进行截图/识别/拆包，提取信息后保存。
这样如果未来米游社只是对当期活动进行统计的话，也可以通过更新保留在本地中。

**Comment by Scighost** [comment]
这个太麻烦了，每个活动需要有相应的html页面才能展示内容，建议你在下线前截图存档。

**Comment by tiyamikatto** [comment]
> 这个太麻烦了，每个活动需要有相应的html页面才能展示内容，建议你在下线前截图存档。

感谢回复。
没想到官方往期活动内容都是独立的设计...想太简单了
