### ISSUE TITLE
[Question] 区服切换功能预计什么时候恢复呀

### ISSUE THREAD

**Issue by wjn3137823020** [Scighost/Starward#971]
### Checklist

- [X] I have already read [docs/Tips.md](https://github.com/Scighost/Starward/blob/main/docs/Tips.md), but my question is not solved.
- [X] My question was not mentioned by others, and it is not a duplicate question.

### Description

区服切换功能预计什么时候恢复呀，没这个功能用着挺难受

### Starward Version

0.12.0

### Windows Version

19045.4651

**Comment by xinyihl** [comment]
实际上现在用一键修复一样可以切换

**Comment by songzhuoru** [comment]
现在好像每次切换都要下载一下差异文件

**Comment by Scighost** [comment]
https://github.com/Scighost/Starward/releases/tag/0.12.2-preview.1
