### ISSUE TITLE
使用一键修复更换<崩坏：星穹铁道 >会导致UnityPlayer.dll丢失

### ISSUE THREAD

**Issue by ShokuhouMisaki** [Scighost/Starward#973]
### Checklist

- [X] My issue was not mentioned by others, and it is not a duplicate issue.

### Description

在切换版本后使用一键修复更换<崩坏：星穹铁道 >会导致UnityPlayer.dll丢失

### Reproduction Steps

添加其他版本
选择一键更新
下载更新途中会创建UnityPlayer.dll
校验完成后UnityPlayer.dll丢失

### Screenshots

![112](https://github.com/user-attachments/assets/b584c504-bb7a-4a5e-aa0a-90f65c5e1bea)
![113](https://github.com/user-attachments/assets/c8f25acd-639d-46c5-93e9-aadf8731e0ce)
![114](https://github.com/user-attachments/assets/92a7cb74-1bd5-4390-8d99-40e2d26effe8)
![115](https://github.com/user-attachments/assets/b4f7261c-9772-4ac8-9723-88dfd6a32155)

### Starward Version

0.12.0

### Windows Version

19045.4651

### Log

```shell
.
```

**Comment by 4545565** [comment]
不只是星穹铁道,崩三也会丢失,最麻烦的是,崩三和崩铁的UnityPlayer.dll版本不一致
