### ISSUE TITLE
[Feature] 绝区零账号储存以及切换功能

### ISSUE THREAD

**Issue by cangerjun** [Scighost/Starward#974]
### Checklist

- [X] I have already read [docs/Tips.md](https://github.com/Scighost/Starward/blob/main/docs/Tips.md), but my feature is not implemented.
- [X] My suggested feature was not mentioned by others, and it is not a duplicate feature.

### Summary

自绝区零开服以来starward一直没有账号保存的功能，虽然再次启动后账号不会掉，但是多个账号无法快速切换，只能退一个登一个。

### Solution or Design

就像原神和崩铁一样可以切换账号。

**Comment by ddjoker** [comment]
首先  zzz 的注册表地址和切换账号的KEY分别是
`HKEY_CURRENT_USER\Software\miHoYo\绝区零`
`MIHOYOSDK_ADL_PROD_CN_XXXXXX`（xxx数字随机）


命令行执行
`reg export HKEY_CURRENT_USER\Software\miHoYo\绝区零 xx.reg`

会在当前目录生成 xx.reg  

修改删除掉xx.reg中的除`MIHOYOSDK_ADL_PROD_CN_XXXXXX`的所有内容保存  

格式如下

```
Windows Registry Editor Version 5.00

[HKEY_CURRENT_USER\Software\miHoYo\绝区零]
"MIHOYOSDK_ADL_PROD_CN_xxx"=hex:xxxxxxx
```
修改xx.reg 为1.reg


同理更换账号 导出 2.reg


创建 zzz.bat 
```
@echo off

set c_p=%~dp0

echo 1、主账号

echo 2、小号 

set /p a=请输入数字登录的账号：

if %a%==1 REG IMPORT "%c_p%\1.reg"

if %a%==2 REG IMPORT "%c_p%\2.reg"

start "" {绝区零路径}\ZenlessZoneZero.exe"

```
修改  {绝区零路径} 为你的绝区零地址  如 `F:\game\miHoYo Launcher\games\ZenlessZoneZero Game\`

然后修改启动方式为 自定义启动程序，路径选择为zzz.bat就行

**Comment by ddjoker** [comment]
先用着呗 。。。 哈哈哈

**Comment by gongfuture** [comment]
> 先用着呗 。。。 哈哈哈

如果我没猜错的话，注册表部分都是一样的，国服`MIHOYOSDK_ADL_PROD_CN_h3123967166`，国际服`MIHOYOSDK_ADL_PROD_OVERSEA_h1158948810`，因为starward代码里这么写的(
这个功能我试着做下看看，但是介于我之前的pr还没被合并，我觉得期待我做出来被加进去可能性不大(

**Comment by gongfuture** [comment]
> > 先用着呗 。。。 哈哈哈
> 
> 如果我没猜错的话，注册表部分都是一样的，国服`MIHOYOSDK_ADL_PROD_CN_h3123967166`，国际服`MIHOYOSDK_ADL_PROD_OVERSEA_h1158948810`，因为starward代码里这么写的( 这个功能我试着做下看看，但是介于我之前的pr还没被合并，我觉得期待我做出来被加进去可能性不大(

Starward代码部分 https://github.com/Scighost/Starward/blob/435f978d628b61b3c5f78d0a5968b44eeee51a7f/src/Starward/Services/GameAccountService.cs#L37-L44

**Comment by ddjoker** [comment]
哦哦哦  我看有说要优化界面系统来着  说实话现在的这部分切换账号操作很各色 。。。。  可能他们在考虑优化问题

**Comment by ddjoker** [comment]
话说主要是我C++不是太会写   回头我打算也试试 看看怎么写法

**Comment by ddjoker** [comment]
> > > 先用着呗 。。。 哈哈哈
> > 
> > 
> > 如果我没猜错的话，注册表部分都是一样的，国服`MIHOYOSDK_ADL_PROD_CN_h3123967166`，国际服`MIHOYOSDK_ADL_PROD_OVERSEA_h1158948810`，因为starward代码里这么写的( 这个功能我试着做下看看，但是介于我之前的pr还没被合并，我觉得期待我做出来被加进去可能性不大(
> 
> Starward代码部分
> 
> https://github.com/Scighost/Starward/blob/435f978d628b61b3c5f78d0a5968b44eeee51a7f/src/Starward/Services/GameAccountService.cs#L37-L44



> > > 先用着呗 。。。 哈哈哈
> > 
> > 
> > 如果我没猜错的话，注册表部分都是一样的，国服`MIHOYOSDK_ADL_PROD_CN_h3123967166`，国际服`MIHOYOSDK_ADL_PROD_OVERSEA_h1158948810`，因为starward代码里这么写的( 这个功能我试着做下看看，但是介于我之前的pr还没被合并，我觉得期待我做出来被加进去可能性不大(
> 
> Starward代码部分
> 
> https://github.com/Scighost/Starward/blob/435f978d628b61b3c5f78d0a5968b44eeee51a7f/src/Starward/Services/GameAccountService.cs#L37-L44

是不是写太硬了    可以考虑改为配置试试

**Comment by cangerjun** [comment]
捞

**Comment by gongfuture** [comment]
> 捞

找不到绝区零存放登录用户的UID注册表条目

**Comment by xiaoxingruo** [comment]
完蛋……根本看不懂啊……

**Comment by cangerjun** [comment]
再次捞一下

**Comment by gongfuture** [comment]
> 再次捞一下

怎么还捞？今天推的正式版不是有了么

**Comment by cangerjun** [comment]
> > 再次捞一下
> 
> 怎么还捞？今天推的正式版不是有了么

忘记了....我star的项目有点多......
