### ISSUE TITLE
[Feature] 需要一个静默启动的快捷方式以放入计划任务当中

### ISSUE THREAD

**Issue by MJSummer** [Scighost/Starward#980]
### Checklist

- [X] I have already read [docs/Tips.md](https://github.com/Scighost/Starward/blob/main/docs/Tips.md), but my feature is not implemented.
- [X] My suggested feature was not mentioned by others, and it is not a duplicate feature.

### Summary

如题。Sw本体不支持开机启动，但有一定数量的用户习惯性通过右下角托盘菜单启动游戏，

### Solution or Design

故申请一个一个静默启动的快捷方式以放入计划任务当中，曲线实现开机启动托盘的功能

**Comment by Scighost** [comment]
`Starward.exe --hide true`

**Comment by MJSummer** [comment]
duplicate as #693.
