### ISSUE TITLE
[Feature] 在清理缓存处能否增加按钮，使日志文件不被清除

### ISSUE THREAD

**Issue by xxbhpan** [Scighost/Starward#982]
### Checklist

- [X] I have already read [docs/Tips.md](https://github.com/Scighost/Starward/blob/main/docs/Tips.md), but my feature is not implemented.
- [X] My suggested feature was not mentioned by others, and it is not a duplicate feature.

### Summary

在清理缓存处能否增加按钮，使日志文件不被清除

### Solution or Design

增加一个按钮，按钮上可写 *清除缓存(不含日志)*

**Comment by Scighost** [comment]
日志文件没什么用，不删也是纯占地方

**Comment by xxbhpan** [comment]
可以关闭该issues
