### ISSUE TITLE
[Feature] 允许用户隐藏游玩时间和账号切换按钮

### ISSUE THREAD

**Issue by harry-xi** [Scighost/Starward#984]
### Checklist

- [X] I have already read [docs/Tips.md](https://github.com/Scighost/Starward/blob/main/docs/Tips.md), but my feature is not implemented.
- [X] My suggested feature was not mentioned by others, and it is not a duplicate feature.

### Summary

现在主界面的对游玩时间的统计和账号切换功能对于部分用户并非常用功能（尤其是账号切换）。
且相较于官方启动器这些按钮对背景图有额外遮挡。
允许隐藏这些内容可允许用户拥有一个更干净的启动界面。

### Solution or Design

如标题所述

**Comment by Scighost** [comment]
![image](https://github.com/user-attachments/assets/827dc193-c674-48cd-85b4-51746a3ec71f)

设置 - 体验 - 功能

游戏时间不支持隐藏
