### ISSUE TITLE
[Question] 绝区零一键修复昨晚还有今天没了

### ISSUE THREAD

**Issue by nightplus123** [Scighost/Starward#989]
### Checklist

- [X] I have already read [docs/Tips.md](https://github.com/Scighost/Starward/blob/main/docs/Tips.md), but my question is not solved.
- [X] My question was not mentioned by others, and it is not a duplicate question.

### Description

![222222222222222222](https://github.com/user-attachments/assets/919abd58-607f-4294-b397-5f9f8a40b859)

### Starward Version

12.1

### Windows Version

19045.4651

**Comment by Scighost** [comment]
你记错了，一直没有
