### ISSUE TITLE
[Bug] 【开始游戏】按钮在启动游戏后出现文本重叠的问题

### ISSUE THREAD

**Issue by HelloWRC** [Scighost/Starward#995]
### Checklist

- [X] My issue was not mentioned by others, and it is not a duplicate issue.

### Description

如图，在游戏运行时，启动界面中的【开始游戏】按钮中“开始游戏”字样不会消失，并与文本“游戏正在运行”重叠。

### Reproduction Steps

1. 启动 Starward
2. 点击【开始游戏】按钮启动任意游戏
3. Bug 成功复现

### Expected Behavior

游戏正在运行时，【开始游戏】按钮应只显示文本“游戏正在运行”。

### Screenshots

![image](https://github.com/user-attachments/assets/2f39bcff-65f6-4759-a2d3-7f772b14f829)

### Starward Version

0.12.2-preview.1

### Windows Version

22631.3958

### Log

```shell
[19:00:14.963] [INFO] 
Welcome to Starward v0.12.2-preview.1
System: Microsoft Windows NT 10.0.22631.0
Command Line: D:\Programs\Starward\app-0.12.2-preview.1\Starward.dll

[19:00:15.013] [INFO] Starward.Services.DatabaseService
Database path is 'D:\Programs\Starward'

[19:00:15.039] [INFO] Starward.Services.DatabaseService
Database version is 9, target version is 9.

[19:00:15.136] [INFO] Starward.Pages.MainPage
Last game region is hkrpg_cn

[19:00:15.152] [INFO] Starward.Pages.MainPage
Navigate to "GameLauncherPage" with param hkrpg_cn

[19:00:15.964] [INFO] Starward.Pages.GameLauncherPage
Game install path of hkrpg_cn: "F:\Games\StarRail\Game"

[19:00:15.997] [INFO] Starward.Pages.GameLauncherPage
Acutal version and gamebiz of hkrpg_cn is "2.3.0".

[19:00:16.905] [INFO] Starward.Services.UpdateService
Start to check update (Preview: True, Arch: X64)

[19:00:17.214] [INFO] Starward.Services.UpdateService
Current version: "0.12.2-preview.1", latest version: "0.12.2-preview.1", ignore version: null

[19:01:23.645] [INFO] Starward.Services.Launcher.GameLauncherService
Start game (hkrpg_cn)
path: "F:\Games\StarRail\Game\StarRail.exe"
arg: "--platform_type CLOUD_THIRD_PARTY_MOBILE"

[19:01:24.767] [INFO] Starward.Pages.GameLauncherPage
Game started ("StarRail", 34132)

[19:01:26.779] [INFO] Starward.Services.PlayTimeService
Start to log playtime (hkrpg_cn, 34132)
```

**Comment by njpengqc** [comment]
突然发现我的也是
版本号：0.12.2-preview.1
![image](https://github.com/user-attachments/assets/2ac65f2f-552b-4b72-9dc6-588c309b197b)

**Comment by LizhiPro1145** [comment]
我的也是
![屏幕截图 2024-07-31 222335](https://github.com/user-attachments/assets/bf1507e2-19ec-422f-b659-177338895407)
并且在一段时间之后启动按钮会重置
![屏幕截图 2024-07-31 222555](https://github.com/user-attachments/assets/92ea0ec3-d4c5-4ead-993f-63f00ab9dde6)
在上图中很明显游戏已经启动，而按钮处于未启动的状态

**Comment by herta0426** [comment]
也是
![image](https://github.com/user-attachments/assets/91ecc23c-6a91-46bb-ac3f-bdd857d86e1e)

**Comment by KoakiMiku** [comment]
![image](https://github.com/user-attachments/assets/36d10ee3-3239-491f-a11c-0ccf85c2d44a)
