### ISSUE TITLE
[Feature] Is it possible to keep both download methods at the same time?

### ISSUE THREAD

**Issue by prpjzz** [Scighost/Starward#998]
### Checklist

- [X] I have already read [docs/Tips.md](https://github.com/Scighost/Starward/blob/main/docs/Tips.md), but my feature is not implemented.
- [X] My suggested feature was not mentioned by others, and it is not a duplicate feature.

### Summary

Basically, I need a .zip file for my work, such as uncompressing new audio files in the game.

So hopefully you can add traditional download functionality in parallel with Sophon, until HoyoPlay no longer supports downloading .zip files.

### Solution or Design

Still keep audio pack option, add method from setting to management download.

**Comment by Scighost** [comment]
Click the game resource button.

![image](https://github.com/user-attachments/assets/f2e2d0bf-a4cb-4edf-a488-2a765e505b06)
